### ISSUE TITLE
[Regression] Lower native framerate with default vblank

### ISSUE THREAD

**Issue by dyno0** [shadps4-emu/shadPS4#1002]
After #990, when leaving the vblank on 1, and running a game which is running 60 FPS natively, the game's FPS is capped at 57 or less, depending on the game
eg. 
![image](https://github.com/user-attachments/assets/0c47e1c0-040f-4c82-bc01-42e84eeda069)

commit before:
![image](https://github.com/user-attachments/assets/4d83ce84-b75f-4110-96e9-8ea5fe52a03b)

**Comment by birthtothunder** [comment]
Similarly happens in Dark Souls Remastered

**Comment by dyno0** [comment]
Fixed by #998
