### ISSUE TITLE
Random crash, lightning problem

### ISSUE THREAD

**Issue by Sirizis** [shadps4-emu/shadPS4#1010]
Whenever getting hit or just moving, always got a crash.
Specs:
GPU Nvidia RTX 4060
Memory 4x8 gb DDR5
CPU intel i5 13400F
OS Windows 10 x64

![изображение](https://github.com/user-attachments/assets/a8c5a310-27c9-4247-b68a-fd353c117c70)
![изображение](https://github.com/user-attachments/assets/9d094c44-c4e5-4fbc-9b32-5b5794b33a25)
[shad_log.txt](https://github.com/user-attachments/files/17085262/shad_log.txt)

**Comment by Hasster1** [comment]
Please, use discord for help requests -  https://discord.gg/bFJxfftGW6, all of these are already well-known issues
