### ISSUE TITLE
7900XTX Loading Screen Crashes

### ISSUE THREAD

**Issue by asdffdasafsd** [shadps4-emu/shadPS4#1014]
The moment that I try to load my character- or any saves in any area, it crashes. I can give the logs as well.
Another 7900xtx that I know is experiencing this.

**Comment by Mikiri7** [comment]
Try reboot the gpu (win+ctrl+shift+b)

**Comment by Johnwrnd** [comment]
> The moment that I try to load my character- or any saves in any area, it crashes. I can give the logs as well. Another 7900xtx that I know is experiencing this.

Just rename/delete the SFX folder ("asd SFX" or any name) and it should work fine. Be sure to apply the FPS Boos mod of your choice and you're good to go. Unfortunately SFX doesn't seem to work for us AMD users and while the game runs vertex explosions occur quite frequently, but at least you can enjoy the game for a couple of minutes.

UPDATE:
The latest main version seems to fix the SFX problem on my AMD hardware and I no longer need to rename or delete the SFX folder.

**Comment by Hermiten** [comment]
There is a lot of report like this, please use the search toolbar to find it
