### ISSUE TITLE
ShadPS4: Constantly freezing then closing on Winter Lantern (enemy)

### ISSUE THREAD

**Issue by Efraine-XII** [shadps4-emu/shadPS4#1027]
I've just reached Nightmare Frontier and kept crashing when i get spotted by Winter Lanterns near Amygdala (there's one patrolling entrance from poison pools and one inside second poison poll right in from of bridge to Amygdala boss).

Screenshot of enemy in question:

![image](https://github.com/user-attachments/assets/e18d9cec-7ee9-4921-ae25-88efe727d93c)

Version with constant crashes (no drawparam, no SFX, 0 mods used): shadps4-win64-qt-2024-09-22-e1d03c3

I tried downgrading to build 2 days ago (that can run BB without crashing on launch and was my previous version prior to update).
shadps4-win64-qt-2024-09-20-eaa92b5 - this build has no issues when you fight lanterns (i can get spotted by them and fight them without Emu closing).

When Emu closes itself there's nothing particular about it in console. Also didn't notice any RAM or VRAM jumps during crash.

Console freeze on crash:
![image](https://github.com/user-attachments/assets/bca8952f-174d-435e-8e81-d0f4f9e8a5ac)

**Comment by Efraine-XII** [comment]
[userdata0000.zip](https://github.com/user-attachments/files/17091038/userdata0000.zip)

Sharing my save data for those interested in testing.

Currently I tried upgrading my Emu to newest version: shadps4-win64-qt-2024-09-22-fb5bc37
No crashes spotted. I returned to Nightmare Frontier lantern and walked back trough elevator shortcut, to try approaching them again.

Going to try more with SFX and other stuff back on.

**Comment by HeinrichVonStinkenfinger** [comment]
I'll see what I can do.

**Comment by HeinrichVonStinkenfinger** [comment]
> [userdata0000.zip](https://github.com/user-attachments/files/17091038/userdata0000.zip)
> 
> Sharing my save data for those interested in testing.
> 
> Currently I tried upgrading my Emu to newest version: shadps4-win64-qt-2024-09-22-fb5bc37 No crashes spotted. I returned to Nightmare Frontier lantern and walked back trough elevator shortcut, to try approaching them again.
> 
> Going to try more with SFX and other stuff back on.

This isn't going to cut it. To help you with this I need your whole save folder zipped up.

**Comment by Efraine-XII** [comment]
> > [userdata0000.zip](https://github.com/user-attachments/files/17091038/userdata0000.zip)
> > Sharing my save data for those interested in testing.
> > Currently I tried upgrading my Emu to newest version: shadps4-win64-qt-2024-09-22-fb5bc37 No crashes spotted. I returned to Nightmare Frontier lantern and walked back trough elevator shortcut, to try approaching them again.
> > Going to try more with SFX and other stuff back on.
> 
> This isn't going to cut it. To help you with this I need your whole save folder zipped up.

God damn it, apologies, i should've dumped whole save directory...

I will keep looking after WLanterns and see if same crash happens later on (in Mensis or on NG+)
