### ISSUE TITLE
Error when starting NHL 22

### ISSUE THREAD

**Issue by Maxi060606** [shadps4-emu/shadPS4#103]
When i want to start NHL 22 the program shows the error:
[Debug] <Critical> thread_management.cpp:scePthreadMutexattrSettype:257: Unreachable code!
Invalid type: 0

**Comment by georgemoralis** [comment]
although we don't support games yet , if you can post the complete log it might be easier to figure out what is missing

**Comment by georgemoralis** [comment]
too early for this
