### ISSUE TITLE
[Feature Request] Enable Windows Game Mode

### ISSUE THREAD

**Issue by Foul-Tarnished** [shadps4-emu/shadPS4#1035]
When you open the game bar (Win+G) and go to its settings, you can see "remember as a game" is not checked.

Game mode can slightly improve framepacing and reduce latency.

(You can use SpecialK to double check if its enabled)

**Comment by Hermiten** [comment]
Can you test it and do a report if you see differences ?
We need test with differents games, with and without windows games mode.
Screen can be useful with FPS on it

If you see no difference, we can close it, if we see difference, we can maybe add this on the documentation

**Comment by Foul-Tarnished** [comment]
?

Read windows official doc on what game mode does and if it's useful.

It is in theory, and all games wants it.

**Comment by Hermiten** [comment]
As you said, it "can" improve it. "Can" does not necessarily mean that it will
As I said, test it if it's really useful. Because if there is no difference, no need to do it.

I don't need to read "Read windows official". We need to test :)

**Comment by Foul-Tarnished** [comment]
Man, you just need to whitelist the exe so windowd trigger game mode for
it, that's all.

The difference is probably minimal on beefy config so I can't really test

And I never saw any issue caused by it

Also some perf improvements are multiplicative

**Comment by Hermiten** [comment]
We can now find this information on the wiki:
https://github.com/shadps4-emu/shadPS4/wiki/V.-FAQ

Thanks you
