### ISSUE TITLE
ShadPs4: Bloodborne freezes and crashes in a certain area without error PC stat: rtx2060s i710700kf 16 ram

### ISSUE THREAD

**Issue by dontmakemelaugh** [shadps4-emu/shadPS4#1038]
https://github.com/user-attachments/assets/c28f7691-9f29-4e6e-8a90-6251aa5b461e

sorry for resolution

**Comment by lawrwajirwahjif** [comment]
What does the crash log report back? You can find it under user > log > shad_log.txt

**Comment by dontmakemelaugh** [comment]
> What does the crash log report back? You can find it under user > log > shad_log.txt

[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:391: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)

**Comment by dontmakemelaugh** [comment]
> What does the crash log report back? You can find it under user > log > shad_log.txt

[shad_log.txt](https://github.com/user-attachments/files/17114828/shad_log.txt)
