### ISSUE TITLE
2gbVRAM

### ISSUE THREAD

**Issue by AizeenAK** [shadps4-emu/shadPS4#1046]
It's just a question: the game used to run fine on the normal builds, but since I installed the betas, it always crashes. Will it work again? And yes, I know my GPU only has 2GB VRAM, and I only have 16GB RAM, but if it won't work, just let me know, and I'll forget about it.

**Comment by raphaelthegreat** [comment]
2GB of VRAM cards are not supported and their functionality will depend on the game

**Comment by AizeenAK** [comment]
It's actually running with “Downscaled Bloodborne by DimichWin10” and running perfectly!
