### ISSUE TITLE
Glibc error on Steam Deck

### ISSUE THREAD

**Issue by J0RDAA** [shadps4-emu/shadPS4#1048]
spits this out every time i run it: /tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/shadps4)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/shadps4)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libQt6Network.so.6)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libcrypto.so.3)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libQt6Gui.so.6)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libQt6Gui.so.6)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/optional/libstdc++.so.6/libstdc++.so.6)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libgssapi_krb5.so.2)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libglib-2.0.so.0)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libxkbcommon.so.0)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libicui18n.so.74)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libicui18n.so.74)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libicuuc.so.74)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libicuuc.so.74)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libkrb5.so.3)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libk5crypto.so.3)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libkrb5support.so.0)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libdbus-1.so.3)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libgomp.so.1)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libgio-2.0.so.0)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libduktape.so.207)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libduktape.so.207)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libsystemd.so.0)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libgnutls.so.30)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libldap.so.2)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/liblber.so.2)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libmount.so.1)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libselinux.so.1)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libcap.so.2)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libgcrypt.so.20)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libp11-kit.so.0)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libtasn1.so.6)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libsasl2.so.2)
/tmp/.mount_Shadpshd8dTU/usr/bin/shadps4: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Shadpshd8dTU/usr/bin/../lib/libblkid.so.1)

**Comment by ngoquang2708** [comment]
SteamOS Stable branch use old GLIBC. Switch to 3.6 Beta branch solve this issue for me.
