### ISSUE TITLE
the emu not working for me 

### ISSUE THREAD

**Issue by sidou999** [shadps4-emu/shadPS4#1058]
when i click the shadps4 icon nothing happened what's wrong     _win11 last update _

**Comment by KubokPekla** [comment]
Try the Windows-QT version, the standard Windows version doesn't have a UI.

**Comment by sidou999** [comment]
> Try the Windows-QT version, the standard Windows version doesn't have a UI.

still not working The cmd screen appears for a short time, it disappears and nothing happens, the previous version was working

**Comment by raphaelthegreat** [comment]
Not adequate information about the problem, feel free to reopen when you have a log, video or more information to help with the problem
