### ISSUE TITLE
Auto-update function disappearing after update the emulator.

### ISSUE THREAD

**Issue by Evilhelder** [shadps4-emu/shadPS4#1063]
When you update the emulator using auto-update, if the next build doesn't have the feature it is lost.

![image](https://github.com/user-attachments/assets/14f354de-cc18-4abd-b23d-711e412367a9)
![image](https://github.com/user-attachments/assets/4dd4e87f-882a-49a3-a32d-2234bc816eeb)
![image](https://github.com/user-attachments/assets/620df637-f5e6-4ea3-a401-e1831b480eb3)

**Comment by viniciuslrangel** [comment]
Isn't this expected?

**Comment by Evilhelder** [comment]
> Isn't this expected?


Yeah, but it's still a problem :T

**Comment by viniciuslrangel** [comment]
Sure it'll be fixed in the release
