### ISSUE TITLE
ShadPs4 wont launch

### ISSUE THREAD

**Issue by Hnim2910** [shadps4-emu/shadPS4#1065]
I clicked on shadps4.exe, it just a black screen terminal open up and nothing happened

**Comment by HeinrichVonStinkenfinger** [comment]
You get which version?

**Comment by boom159110** [comment]
same problem ive been looking for fixes and i downloaded the 3.0 version

**Comment by elxkot** [comment]
SDL-version comes with no graphical interface and must be launched via commandline. Try using QT-version

**Comment by Ein420** [comment]
I've been attempting windows build recently, whether it's QT or SDL, it just doesn't launch, the most it does is create 'user' folder, but that's about it

**Comment by sidou999** [comment]
same here

**Comment by ClaudioVarandas** [comment]
same problem here with multiple 0.3 builds .

intel i5 13600k
32GB DDR4
AMD 6950XT
Win 11

**Comment by minoyami** [comment]
installed Microsoft Visual C++ Redistributable Version and its start to work. https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by sidou999** [comment]
thanks broo

**Comment by sidou999** [comment]
> installed Microsoft Visual C++ Redistributable Version and its start to work. https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

thanks bro work now

**Comment by ClaudioVarandas** [comment]
> installed Microsoft Visual C++ Redistributable Version and its start to work. https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Doesn't work for me ...

**Comment by SirenBrink** [comment]
This worked for me. Steam is always installing broken vc redist files when you install a new game (pre launch setup).

Search "vc redist abbodi", that guy has saved me a lot of time

**Comment by ClaudioVarandas** [comment]
> This worked for me. Steam is always installing broken vc redist files when you install a new game (pre launch setup).
> 
> Search "vc redist abbodi", that guy has saved me a lot of time

Thanks man, https://github.com/abbodi1406/vcredist/releases/tag/v0.83.0 just works !

**Comment by MMH2-O** [comment]
> > This worked for me. Steam is always installing broken vc redist files when you install a new game (pre launch setup).
> > Search "vc redist abbodi", that guy has saved me a lot of time
> 
> Thanks man, https://github.com/abbodi1406/vcredist/releases/tag/v0.83.0 just works !

Still doesn't work for me, did I do something wrong or is there a problem with my windows?

**Comment by Hermiten** [comment]
I'm closing this one. No news from [Hnim2910](https://github.com/Hnim2910)

**Comment by AvinavGamer1611** [comment]
I am having the same problem can someone help. Even after installing vc redist again the GUI just wont open

**Comment by juliozn5** [comment]
i have the same problem , the vc redist no working for me

**Comment by AvinavGamer1611** [comment]
> i have the same problem , the vc redist no working for me

I fixed it . Download vkdiag and run it to see what you have missing . I was missing my integrated graphics drivers.  I installed then and i t started working.

**Comment by juliozn5** [comment]
> > i have the same problem , the vc redist no working for me
> 
> I fixed it . Download vkdiag and run it to see what you have missing . I was missing my integrated graphics drivers. I installed then and i t started working.

Thank you very much bro, I have a laptop with a dedicated graphics card, I always keep its drivers updated, but the integrated graphics card of the processor had never updated its driver, did it work for me

**Comment by kientarn94** [comment]
I don't know who you two are but i'm forever in your guys debt. It finally work! After one week of suffering, did every comment i've ever found, only this solution is the right key to me. Just update your onboard gpu driver with amd adrenaline or intel app, very simple but i've never noticed it before

![Image](https://github.com/user-attachments/assets/0a42c7eb-0ac9-45c2-86cd-081d16a51c61)

**Comment by roamic** [comment]
@kientarn94 do not post pirated content screenshots here or you will be banned.

**Comment by juliozn5** [comment]
> I don't know who you two are but i'm forever in your guys debt. It finally work! After one week of suffering, did every comment i've ever found, only this solution is the right key to me. Just update your onboard gpu driver with amd adrenaline or intel app, very simple but i've never noticed it before
> 
> ![Image](https://github.com/user-attachments/assets/0a42c7eb-0ac9-45c2-86cd-081d16a51c61)

It's all thanks to the brother, AvinavGamer1611, in my case it was the same, I just downloaded adrenaline for my  AMD apu and the emulator worked

**Comment by mattwalewangko** [comment]
Try searching for and deleting every instance of shadps4 from your PC with file explorer. It took a minute (more like 30) for my PC to crawl through all my files, but after I found and deleted every instance and folder of shadps4 from my PC I was able to re-run it and it started to work again.
