### ISSUE TITLE
Visual glitch on build 45e206e

### ISSUE THREAD

**Issue by edsonsilvajr** [shadps4-emu/shadPS4#1070]
reference: https://github.com/shadps4-emu/shadPS4/actions/runs/11031963503

I'm getting the following glitch on my emulator now, don't know if it's a known issue or not, here are my specs:

 - RX 7600 8GB VRAM
 - R5 5600
 - 32GB RAM

If any more info is needed just let me know! and sorry if this is already known, just wanting for the emulator to move even more forward! good job to you devs!

![image](https://github.com/user-attachments/assets/f0ebc67a-d9d6-43fe-a41d-e209a5aed9eb)

**Comment by Azther88** [comment]
can also confirm im getting this behaviour on pre release build 45e206e running on the ROG Ally X. Ive attached the log for details
[shad_log.txt](https://github.com/user-attachments/files/17133047/shad_log.txt)

**Comment by edsonsilvajr** [comment]
[shad_log.txt](https://github.com/user-attachments/files/17133183/shad_log.txt)

totally forgot about the log, here it is as well

**Comment by alekxeyuk** [comment]
[This ](https://github.com/shadps4-emu/shadPS4/actions/runs/11030492214) is the build that started the regression,
![image](https://github.com/user-attachments/assets/769bf2c0-5774-4f26-8d60-69c30d4483b1)

[previous one](https://github.com/shadps4-emu/shadPS4/actions/runs/11030108628) is without visual glitches
![image](https://github.com/user-attachments/assets/48dca0fd-3060-4dc9-935a-3c3bb3cfe754)

**Comment by StevenMiller123** [comment]
I believe that aligns with what was briefly discussed on the discord about the issue as well. I believe @psucien is looking into the issue?

**Comment by StevenMiller123** [comment]
Should be fixed by latest main.

**Comment by Azther88** [comment]
yep can confirm its fixed
