### ISSUE TITLE
Black Screen Bloodborne MacOS

### ISSUE THREAD

**Issue by Kurtjwest** [shadps4-emu/shadPS4#1077]
I am on MacOS 15, and am receiving a black screen when booting Bloodborne. Crashes when closing window.

Here is my log.
[shad_log.txt](https://github.com/user-attachments/files/17138962/shad_log.txt)

Any help would be greatly appreciated!
Keep up the great work!

**Comment by tzenus** [comment]
Same problem (MacOS 15, Mac mini m2 pro)
Log 
[shad_log.txt](https://github.com/user-attachments/files/17174886/shad_log.txt)
![Снимок экрана 2024-09-28 в 18 21 59](https://github.com/user-attachments/assets/3d37ad92-d999-49e7-9db7-3d8eca2367b8)

**Comment by darkuser89** [comment]
Complex 3D games don't work on the Mac, only smaller 2D games
