### ISSUE TITLE
SOLUTION for those (linux users) who are experiencing black screen

### ISSUE THREAD

**Issue by Ein420** [shadps4-emu/shadPS4#1078]
I'm on Arch linux and this managed to work for me

If you are experiencing no audio, these steps should also fix your issue:

1. this fixed the previous issue of it not building. (skip this, already fixed)
before compiling ShadPS4 (just after cloning),
edit your `src/video_core/texture_cache/tile_manager.cpp`
on line 298, remove `static` from `static auto [desc_layout_result, desc_layout] =`

2. then to **fix the black screen**,
add these lines to `src/core/libraries/kernel/thread_management.cpp` from this commit:
https://github.com/shadps4-emu/shadPS4/commit/481e18a245f8a19a540877778d7bc45a91672519#diff-1179139663057cf3ceb4647b8ed2cc9030d0873ccf224290152b49cf2fec2f09R1085

Make sure to use the `-DCMAKE_DISABLE_FIND_PACKAGE_SDL3=ON` flag if the SDL3 on your repo/pc is a higher version than what shadPS4 needs.

For some reason, I'm only able to get audio when compiling it myself, audio does not work at all if I'm using a pre-release/release

**Comment by ngoquang2708** [comment]
```thread_management.cpp``` patch fix black screen for me. But the emulator still crash when finishing character creation.

**Comment by Ein420** [comment]
> `thread_management.cpp` patch fix black screen for me. But the emulator still crash when finishing character creation.

try building from diegolix29's fork, you will get better results:
https://github.com/diegolix29/shadPS4

**Comment by RoastBeefer00** [comment]
> `thread_management.cpp` patch fix black screen for me. But the emulator still crash when finishing character creation.

same here :(

**Comment by Ein420** [comment]
make sure you're building the 'Full-Blood' branch of the fork I mentioned

**Comment by RoastBeefer00** [comment]
Reloading got me past character creation and now I can play the game. I had to apply this fix in the code and build from source. The fork suggested does not work me on Fedora 40 or steam deck

**Comment by Ein420** [comment]
It will take a reload to get past laggy loading screens

are u using official build?
Full-Blood/diegolix29's fork is the most performant in my case

**Comment by GryfHub** [comment]
i can't build it on my SD i get:

CMake Error at CMakeLists.txt:147 (find_package):
  Found package configuration file:

    /usr/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find required Qt component "Widgets".

  Expected Config file at "/usr/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake"
  exists



  Configuring with --debug-find-pkg=Qt6Widgets might reveal details why the
  package was not found.

**Comment by Leniptic** [comment]
Same issue as above person, but "Multimedia" instead of "Widgets". Running Mint 22 Wilma with a 3070. I've never built from source before, let alone edited someone else's code and then built it, so I 100% could've just done something wrong.

**Comment by GryfHub** [comment]
Can someone build it and link a dlwnload ?

**Comment by Ein420** [comment]
> i can't build it on my SD i get:
> CMake Error at CMakeLists.txt:147 (find_package): Found package configuration file:
> ```
> /usr/lib/cmake/Qt6/Qt6Config.cmake
> ```
> but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT FOUND. Reason given by package:

I have the latest, most bleeding edge qt6 packages installed, yet I'm not getting these issues

make sure you at least have qt6 installed

otherwise, maybe the solution to ur issues is as simple as compiling with `-DCMAKE_DISABLE_FIND_PACKAGE_QT6=ON` (something like that) e.g. ``-DCMAKE_DISABLE_FIND_PACKAGE_QT6-MULTIMEDIA=ON`

**Comment by Ein420** [comment]
Maybe the steamOS is not yet updated to Qt6/plasma 6 and still only uses plasma 5 (?) that may be ur issue

**Comment by Ein420** [comment]
> Can someone build it and link a dlwnload ?

https://www.mediafire.com/file/yygq1le5bhkqddz/shadps4/file

**Comment by Myew420** [comment]
> > Can someone build it and link a dlwnload ?
> 
> https://www.mediafire.com/file/yygq1le5bhkqddz/shadps4/file

I get this when trying to run it:
`error while loading shared libraries: libfmt.so.10: cannot open shared object file: No such file or directory`

**Comment by ngoquang2708** [comment]
> I get this when trying to run it: `error while loading shared libraries: libfmt.so.10: cannot open shared object file: No such file or directory`

Try SteamOS 3.6 Beta branch

**Comment by Skyrent** [comment]
> > I get this when trying to run it: `error while loading shared libraries: libfmt.so.10: cannot open shared object file: No such file or directory`
> 
> Try SteamOS 3.6 Beta branch

It doesn't work either on 3.6. Same error.

**Comment by RoastBeefer00** [comment]
I was able to get the game running on my steam deck using the binary from my own fork, but a lot of game textures won't load.  Also, I can no longer get past the black screen on Fedora and I don't know why

**Comment by ngoquang2708** [comment]
My advice is to wait a few months for the Linux part of the emulator to mature. Currently you can launch some games but it is just hit or miss and performance wise no where near as good as on Windows.

**Comment by RoastBeefer00** [comment]
Correction sorry it's working on Fedora again I just had to use an X11 session instead of Wayland. On my desktop I can only handle 480p so yeah waiting may be a good option.

**Comment by Ein420** [comment]
> > > I get this when trying to run it: `error while loading shared libraries: libfmt.so.10: cannot open shared object file: No such file or directory`
> > 
> > 
> > Try SteamOS 3.6 Beta branch
> 
> It doesn't work either on 3.6. Same error.

Make sure you have the 'fmt' package installed

**Comment by aaalloc** [comment]
> > `thread_management.cpp` patch fix black screen for me. But the emulator still crash when finishing character creation.
> 
> try building from diegolix29's fork, you will get better results: https://github.com/diegolix29/shadPS4

I can confirm that it worked with diegolix29 forks and thread_management fix it can launch and has no crashes when finishing character creation. (tested on Fedora 40 with AMD cpu and NVIDIA gpu)

Otherwise if it still crash after character creation, you could just restart the game and it will work.

**Comment by raphaelthegreat** [comment]
This isn't an issue but rather a discussion

**Comment by intellq** [comment]
Also, if you are getting a black screen in a Wayland session (even after applying the linux fix), call the emulator like this:

DISPLAY= ./shadps4

To force it to use wayland and not the X bridge
