### ISSUE TITLE
.

### ISSUE THREAD

**Issue by 1111111945** [shadps4-emu/shadPS4#1088]

**Comment by 1111111945** [comment]
i see black screen and  few seconds letter it crash what can i do with this ?

**Comment by StevenMiller123** [comment]
Help requests go to the shadPS4 discord server, this issue is invalid.

**Comment by Ein420** [comment]
please close this, not only did you not provide any relevant information (shad_log.txt, specs, etc). you're contributing to the spam of bloodborne specific issues that have already been opened.
