### ISSUE TITLE
Bloodborne immediately crashing on Steam Deck

### ISSUE THREAD

**Issue by spellwells** [shadps4-emu/shadPS4#1095]
Whenever I try to open Bloodborne the game crashes after a second or two without as much as even opening up a window to play the game before the crash. I'm not sure where to even begin in troubleshooting. Any sort of help would be greatly appreciated. I can provide more information but right now I'm so lost I'm not sure what information would be relative.

**Comment by StevenMiller123** [comment]
Help requests belong in the shadPS4 discord, where someone with experience can guide you through your issue.

**Comment by spellwells** [comment]
Ah sorry I did try there first but my request immediately got buried. Should I post it again in the server?

**Comment by StevenMiller123** [comment]
Yes, please repost over there instead.

**Comment by Dante1475** [comment]
you find a solution? they ban me  from discord
