### ISSUE TITLE
unknown ds3 crash issue

### ISSUE THREAD

**Issue by hgh32** [shadps4-emu/shadPS4#1098]
CUSA03387

Basically random freezes/memory leaks etc occur
There are no `<Critical>` errors in the log, but it keeps looping errors like `[Lib.Net]`
This creates a very large log file, always seems to be around 100mb

When trying to set the logFilter to Critical:
`[Debug] <Critical> address_space.cpp:operator():188: Assertion Failed!
The parameter is incorrect.`

Also setting the logType to `async` causes a noticeable performance hit

**Comment by polybiusproxy** [comment]
Please provide a log
