### ISSUE TITLE
vk_scheduler.cpp:operator() :147: Assertion Failed! Device lost during submit, error on Love Live 

### ISSUE THREAD

**Issue by obronca** [shadps4-emu/shadPS4#1099]
With the latest update, performance seems increased with the character model being able to be rendered correctly and music is played but the sound volume is too low

however, clicking on the "Play Live Show" or even "Watch Live" leads to the error

![image](https://github.com/user-attachments/assets/49681bf6-de71-4443-9ffc-288b37eb7048)

another thing to mention, the game would froze and crash at the first loading screen after clicking "Press Any Button" in the Title Screen, if "libSceRtc.sprx" is present in the sys_modules folder, moving it out from the folder allowing the game to enter the Main Menu

## With libSceRtc.sprx present
![image](https://github.com/user-attachments/assets/cbe9c38a-f8b3-49ed-80a5-9d41cd37c03d)

## Without libSceRtc.sprx
![image](https://github.com/user-attachments/assets/6c5a7eb2-9790-4eb9-a0d5-29999f867fda)

**Comment by RokkuDayo** [comment]
The game now gets into the menus just fine in the latest WIP without removing any modules but it still crashes when trying to play it, hopefully this will be dealt with soon. You can actually get into a song by using the playlist menu but the graphics are blacked out.

**Comment by RokkuDayo** [comment]
Looked into it with Renderdoc and the game does render perfectly under the hood if you do get into a live but something makes it draw a flat black rectangle over the graphics once it's finished drawing the frame. I've never seen something like this before.
![image](https://github.com/user-attachments/assets/6c664537-bd84-4249-a339-be2184643124)

**Comment by RainKikyou** [comment]
this game can ingame in 0.2.1 and 0.1.1 wip
test video: https://www.youtube.com/watch?v=AblReTT633c
![image](https://github.com/user-attachments/assets/e659b4e4-8d5c-471d-83a5-4195ce6cfe09)
It takes luck to get into the game and be able to play it for a while. Normally, it will crash immediately after entering.
![image](https://github.com/user-attachments/assets/24a06412-c243-47d5-a1fe-fb2e097cb950)
After successfully entering the game and being able to play for a period of time，then
test video: https://www.youtube.com/watch?v=Fr0esYU1Zks
![image](https://github.com/user-attachments/assets/037a74de-d91d-438c-85bd-07c19d3dc297)
this build download: https://discord.com/channels/1080089157554155590/1281178723214688279/1291265363522359389

I remember that after Bloodborn could display graphics normally， the problem of not being able to ingame appeared（Although the rendering problem of this game is also fixed）.

finally,i use intel xe card(i7 13700H own)，no this problem，this is a nvidia card regression problem
![image](https://github.com/user-attachments/assets/0eb52c1e-8ff5-4004-bf68-9266a4c3538d)

**Comment by RokkuDayo** [comment]
Game renders fine as of the latest WIP but still gets a device lost on Windows.

**Comment by Hermiten** [comment]
This is a common error, can happen on start or when you enter specific game, it depends of which game.
Thanks for the renderdoc, can you update the test on 0.4 here ? https://github.com/shadps4-emu/shadps4-game-compatibility/issues/304
I'm closing this one
