### ISSUE TITLE
game refuses to launch

### ISSUE THREAD

**Issue by SerAlanTheBold** [shadps4-emu/shadPS4#1106]
[shad_log.txt](https://github.com/user-attachments/files/17161351/shad_log.txt)

**Comment by PrimalSmite** [comment]
I have exactly same problem.
[shad_log.txt](https://github.com/user-attachments/files/17195550/shad_log.txt)

**Comment by Hermiten** [comment]
Bad report, only log, no information. I think it would be nice to do a real issue and maybe search on github if people already report this kind of issue
