### ISSUE TITLE
random crashes on ROG Ally X

### ISSUE THREAD

**Issue by Azther88** [shadps4-emu/shadPS4#1108]
Game: Bloodborne
getting random crashes when moving between areas at beginning of game and when teleporting. please see log for details

system specs:
Ryzen Z1 Extreme Processor (7840u)
24gb system ram (8gb dedicated to VRAM)
AMD adrenaline driver 24.8.1
[shad_log.txt](https://github.com/user-attachments/files/17164327/shad_log.txt)

**Comment by RyuSeisuke1992** [comment]
Maybe Help lower Resolution looking this Clip?
Higher Resolution need First time better GPU unit, especially since the emulator was first optimized for GPU standalone. APU will probably get better support over time.
https://discord.com/channels/1080089157554155590/1245616678021234768/1289292630160838708

**Comment by Azther88** [comment]
ive been using the 484p patch already and it still happens. climbing the ladder, entering the clinic and turning right at the lamp at top of the ladder seem to consistently trigger it. altho it doesnt always happen, its pretty random

**Comment by RyuSeisuke1992** [comment]
I have Solution. Thanks Dark~RyuX. 
He used this latest Build From this Fork: https://github.com/diegolix29/shadPS4/actions/runs/11075296286
And Set VRAM to 8GB. No more crashed with 1080p.
https://discord.com/channels/1080089157554155590/1245616678021234768/1289322394879787068
https://discord.com/channels/1080089157554155590/1245616678021234768/1289319572813381704

**Comment by Azther88** [comment]
same error

**Comment by RyuSeisuke1992** [comment]
Have u Setup the drawparam, sfx and Sound Files to moved Into new folder?
Follow quick guide in Discord channel

**Comment by RyuSeisuke1992** [comment]
And Install the FPS Boost Mode From Nexus mode

**Comment by Azther88** [comment]
the fps boost caused me to crash again, but dropping down to 484p patch and keeping fps boost off and just using diegolix29s merged crash fix seems to make it more stable. i tried 720p and it was crashing again

**Comment by Azther88** [comment]
nvm happened again, spoke too soon. seems to be alot less frequent tho

**Comment by Hermiten** [comment]
Already reported on another issues, it's not only because of the rog ally but also amd issue
