### ISSUE TITLE
Shadeps4 crashes on launch, sometimes opens with a black screen

### ISSUE THREAD

**Issue by IsThatLalo** [shadps4-emu/shadPS4#1113]
I’m experiencing a recurring issue where the software crashes immediately after launching. Occasionally, it does launch, but when it does, the screen is completely black. I spoke with someone on the Discord server, and they suggested that the issue might be caused by insufficient RAM. However, I have 32gb of ram installed, which should be sufficient. I was also only using about 10% of my available RAM when the crashes occurred, so I don't believe RAM is the issue, and here is the logs                                                                                                     

[Loader] <Info> emulator.cpp:Emulator:56: Starting shadps4 emulator v0.3.1 WIP 
[Loader] <Info> emulator.cpp:Emulator:57: Revision 687be5b1320382107624b36fb940a079069a82ca
[Loader] <Info> emulator.cpp:Emulator:58: Branch main
[Loader] <Info> emulator.cpp:Emulator:59: Description 687be5b
[Config] <Info> emulator.cpp:Emulator:61: General isNeo: false
[Config] <Info> emulator.cpp:Emulator:62: GPU isNullGpu: false
[Config] <Info> emulator.cpp:Emulator:63: GPU shouldDumpShaders: false
[Config] <Info> emulator.cpp:Emulator:64: GPU shouldDumpPM4: false
[Config] <Info> emulator.cpp:Emulator:65: GPU vblankDivider: 1
[Config] <Info> emulator.cpp:Emulator:66: Vulkan gpuId: -1
[Config] <Info> emulator.cpp:Emulator:67: Vulkan vkValidation: false
[Config] <Info> emulator.cpp:Emulator:68: Vulkan vkValidationSync: false
[Config] <Info> emulator.cpp:Emulator:69: Vulkan vkValidationGpu: false
[Config] <Info> emulator.cpp:Emulator:70: Vulkan rdocEnable: false
[Config] <Info> emulator.cpp:Emulator:71: Vulkan rdocMarkersEnable: false
[Config] <Info> emulator.cpp:Emulator:72: Vulkan crashDiagnostics: false
[Debug] <Critical> address_space.cpp:operator():76: Assertion Failed!
Unable to reserve virtual address space: Not enough memory resources are available to process this command.

**Comment by rafael-57** [comment]
And this is before opening a game?

**Comment by 1111111945** [comment]
i have something similar  but i cant find where i can ask about it can someone give discord link (i so stupid i cant find it by my self )

**Comment by IsThatLalo** [comment]
> And this is before opening a game?

When I click on the play button, So its after.

**Comment by mactonight37** [comment]
did anyone find a solution?

**Comment by Hermiten** [comment]
It's a common issue, it depend of the game you try to run: Please check here https://github.com/shadps4-emu/shadps4-game-compatibility/issues
