### ISSUE TITLE
[Regression] ShadPS4 crashes before running any game after #1033 on Linux

### ISSUE THREAD

**Issue by lukaszarczynski** [shadps4-emu/shadPS4#1117]
After merging #1033, emulator crashes when some game is selected (not even booted yet). It also caused linux release to be 2 times bigger.

System: Kubuntu 24.04, with wayland display server

ShadPS4 doesn't even write any logs to file, when launched from terminal it shows following errors:
[shad_crash.log](https://github.com/user-attachments/files/17169212/shad_crash.log)

**Comment by RoastBeefer00** [comment]
This happened to me as well but you can launch a game directly from the command line and that still works

**Comment by Dante1475** [comment]
> This happened to me as well but you can launch a game directly from the command line and that still works

how?

**Comment by gs-soda** [comment]
Can confirm,  manually compiled however works perfectly fine for me, so I would try that

**Comment by Dante1475** [comment]
> Can confirm, manually compiled however works perfectly fine for me, so I would try that

Do You compiled on SteamOS or in other distro?

**Comment by lukaszarczynski** [comment]
> This happened to me as well but you can launch a game directly from the command line and that still works

@RoastBeefer00 but without the ability to apply patches, right?

**Comment by RoastBeefer00** [comment]
> > This happened to me as well but you can launch a game directly from the command line and that still works
> 
> @RoastBeefer00 but without the ability to apply patches, right?

No I can apply patches, close the emulator, the launch the game from the command line

**Comment by gs-soda** [comment]
> > Can confirm, manually compiled however works perfectly fine for me, so I would try that
> 
> Do You compiled on SteamOS or in other distro?

Compiled on Arch Linux, from my knowledge the only issue on SteamOS is an outdated glibc, which is (apparently) fixed by using the beta branch. Also, AppImage seems to work now with the latest commit (62c59d1)

**Comment by lukaszarczynski** [comment]
Indeed, it was fixed today
