### ISSUE TITLE
shadps4 not working at all

### ISSUE THREAD

**Issue by bamboblam** [shadps4-emu/shadPS4#1119]
ive tried multiple versions of shad and no matter what when i try to choose a directory for games to install it just goes to the original cmd screen

**Comment by wshrZane** [comment]
me neither.i just try all vers ,only the 0.1ver works

**Comment by bamboblam** [comment]
ill try thanks

**Comment by bamboblam** [comment]
it will install bloodborne now and everything on 0.10 but it stops responding when i launch bloodborne

**Comment by twinkietwinkielittlestar** [comment]
same with me i tried it today to run Tony Hawks Pro and gives me error and the emu app vanishes 
my PC specs: 10500 CPU + 32GB RAM + rtx 3050 
Do you know where to report my errors?

**Comment by raphaelthegreat** [comment]
You have not provided any log or details about your issue, seek support on the discord instead

**Comment by wshrZane** [comment]
actually,the log file is empty&jus i click theshadPS4.exe,then choose the game file,nothing happened atlast

**Comment by wshrZane** [comment]
the qt -window never appear & there's no useful solution in the dc group,but ty
