### ISSUE TITLE
shadps4: failed to create graphics pipeline ErrorOutofDeviceMemory

### ISSUE THREAD

**Issue by ShadmanAkhter123** [shadps4-emu/shadPS4#1123]
![Screenshot 2024-09-28 130324(3)](https://github.com/user-attachments/assets/4a062aba-ab4c-443f-a62c-a19a5b594e9a)

specs
Ryzen 5 3500x
rx580 8gb
ram 16gb

**Comment by gandalfthewhite19890404** [comment]
first of all - what game
second - did you search other issue threads, what if they are same as yours
