### ISSUE TITLE
shadps4: <critical> texture_cache.cpp:operator () :224: Assertion Failed!

### ISSUE THREAD

**Issue by ShadmanAkhter123** [shadps4-emu/shadPS4#1124]
![Screenshot 2024-09-28 113959(2)](https://github.com/user-attachments/assets/d6b5d4af-48f8-4c31-aad8-975c5757b605)

specs
ryzen 5 3500x
rx580 8gb
ram 16gb

**Comment by gandalfthewhite19890404** [comment]
Close it, please, as invalid
