### ISSUE TITLE
shadps4: Failed allocating buffer with error ErrorOutofDeviceMemory

### ISSUE THREAD

**Issue by ShadmanAkhter123** [shadps4-emu/shadPS4#1125]
![Screenshot 2024-09-28 105409](https://github.com/user-attachments/assets/f3a7837b-cfed-473c-b2cb-01b9b787f5db)

specs
ryzen 5 3500x
rx580 8gb
ram 16gb

**Comment by gandalfthewhite19890404** [comment]
What the heck is going on? Where these bots came from???

**Comment by ShadmanAkhter123** [comment]
sorry???

**Comment by polybiusproxy** [comment]
This is not the place for support, please join our Discord.

**Comment by ShadmanAkhter123** [comment]
ohhhh okay...
