### ISSUE TITLE
Emu doesn't open (Windows-QT)

### ISSUE THREAD

**Issue by DogBanana** [shadps4-emu/shadPS4#1126]
When i try to open the .exe, the cmd opens for a brief moment and then closes, it also creates a user folder, but that's it, and i've seen other people getting the same problem

Edit: I've extracted the archives of the emulator on my HD and it worked properly, before i was trying to extract on my desktop

**Comment by Xphalnos** [comment]
> When i try to open the .exe, the cmd opens for a brief moment and then closes, it also creates a user folder, but that's it, and i've seen other people getting the same problem

I had this problem.
First, check that it is the Qt version
Second, check that you have Microsoft Visual C++ Redistributable 2015-2022. If you have it, update it, or else do "repair" and then restart your PC

Microsoft Visual C++ Redistributable 2015-2022: https://aka.ms/vs/17/release/vc_redist.x64.exe
