### ISSUE TITLE
P4D's Title Music breaks the new app background music thing

### ISSUE THREAD

**Issue by Da-nu** [shadps4-emu/shadPS4#1140]
It randomly just disappears, crackles, and all of the sorts.
![image](https://github.com/user-attachments/assets/94e274ea-d1ad-4bdd-aeb4-88f5df0ef35d)
I can't send a log file because shad_log.txt only covers logs after starting a game.

**Comment by SagarChandra07** [comment]
install this
https://bit.ly/47P0Nvo
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by StevenMiller123** [comment]
Oh lord, the spam is back? Needless to say, do not click that link.

**Comment by Da-nu** [comment]
lmao they have github spam scams?

**Comment by StevenMiller123** [comment]
Yup. There was a bunch of these spam messages showing up a couple weeks back, and here they are again.

**Comment by Hermiten** [comment]
Hey @tGecko do you think this is cause by this https://github.com/shadps4-emu/shadPS4/pull/1033 ?

**Comment by Hermiten** [comment]
No answer
