### ISSUE TITLE
Fullscreen CLI linux

### ISSUE THREAD

**Issue by ghost** [shadps4-emu/shadPS4#1147]
Hello, 
Is there a flag to run the SDL-Appimage as fullscreen on linux? I'm trying to create a launcher for batocera?  Or better, yet when i tried a script to the qt app image /userdata/system/pro/Shadps4-Qt-AppImage "/path/to/.eboot" it doesn't launch with that.  (Would prefer launching via qt.)

Thanks.

**Comment by qurious-pixel** [comment]
The quick way is to edit the `config.toml` in the user folder. 

```
[General]
Fullscreen = true
```

Then launch as normal `/userdata/system/pro/Shadps4-sdl-AppImage "/path/to/.eboot" `

This seems like a Feature Request that would make a good first issue for someone.

**Comment by robyn-dressler** [comment]
> This seems like a Feature Request that would make a good first issue for someone.

If no one else is working on this, I'd be happy to take a look.

**Comment by LordDaveTheKind** [comment]
If you are on Wayland, have you already considered Valve Gamescope?

**Comment by qurious-pixel** [comment]
They are using Batocera, and want a switch to open the game window fullscreen when using SDL. 
There is already a patch switch `-p` so adding an `-f/--fullscreen` can be done similiarly.

**Comment by kalaposfos13** [comment]
Can this be closed, as [my PR](https://github.com/shadps4-emu/shadPS4/pull/1356) has this implemented?

**Comment by polybiusproxy** [comment]
It can be closed once it's merged

**Comment by kalaposfos13** [comment]
Sorry, linked the wrong [PR](https://github.com/shadps4-emu/shadPS4/pull/1507)
