### ISSUE TITLE
Bloodborne  i5-12490F AMD6750xt crash

### ISSUE THREAD

**Issue by cugbbaiyun** [shadps4-emu/shadPS4#1152]
The emu crashed when the first enemy attack
![image](https://github.com/user-attachments/assets/b4ca19a0-c8e9-4ff3-b93f-2bcbb4645b29)
[shad_log.txt](https://github.com/user-attachments/files/17179630/shad_log.txt)

Besides, wrong environment light and no sound
![29813c09ac3e65a264210a79e76d6de](https://github.com/user-attachments/assets/63691cdb-70a2-4ea5-b80d-e04216e99d1f)

**Comment by cugbbaiyun** [comment]
The version of the GPU driver is 24.8.1

**Comment by StevenMiller123** [comment]
This is the expected behavior at the moment, just be patient and wait for a fix.

**Comment by Hermiten** [comment]
New commit that fix the light: https://github.com/shadps4-emu/shadPS4/pull/1146
Can you test and close if it's fixed ?
For the crash, it's already reported.

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/503

**Comment by cugbbaiyun** [comment]
![image](https://github.com/user-attachments/assets/8dc67f19-a4b4-4841-9e21-06fb51136e9e)
Currently, the light has been fixed.
