### ISSUE TITLE
No games after installation.

### ISSUE THREAD

**Issue by AikaBack** [shadps4-emu/shadPS4#1156]
![image](https://github.com/user-attachments/assets/e7266130-e439-414a-8148-cbb3d9579661)
No game list initialization, I have no vpn, no other stuff that could interfere with loading files.
user/log is empty.

**Comment by elxkot** [comment]
You should install games via .pkg files which you must obtain separately and by yourself

**Comment by Hermiten** [comment]
Better to come on discord if you need help like this. There is no game provided with shadps4, so you must dump from your console and then install on the games folder
