### ISSUE TITLE
Shadps4 doesn't open on Arch linux

### ISSUE THREAD

**Issue by igorechek90** [shadps4-emu/shadPS4#1157]
Shadps4-qt.appimage doesn't open on my steam deck after the "Choose directory" window.

**Comment by FardinHaque70** [comment]
Duplicate of this i believe #1149

**Comment by Dante1475** [comment]
Same problem 
![17277378421647378598271432899178](https://github.com/user-attachments/assets/742dcc3f-6314-4841-b8c4-317ccafb0476)

**Comment by Andrey-crazy** [comment]
Still crashes. Build [bf3e43b](https://github.com/shadps4-emu/shadPS4/releases/tag/Pre-release-shadPS4-2024-10-01-bf3e43b)
![image](https://github.com/user-attachments/assets/0dde8045-633b-4987-85fe-f2fbf1b76fe0)

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/1149
