### ISSUE TITLE
Bloodborne no sound

### ISSUE THREAD

**Issue by AikaBack** [shadps4-emu/shadPS4#1159]
Game has no sound and console spams with these things 
[Kernel] <Info> libkernel.cpp:sceKernelGetCompiledSdkVersion:258: returned system version = 0x4500000
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[shad_log.txt](https://github.com/user-attachments/files/17181424/shad_log.txt)

**Comment by akett** [comment]
I can't add anything on behalf of the emulator, but the workaround I found was to download a mod from nexus that contained all the sound files "fixed" for playback on PC. That mod seems to have nuked by Sony (can't think of any other reason the author would take it down), it used to be hosted here: https://www.nexusmods.com/bloodborne/mods/34

I'm just hoping the author of that mod shares his workflow so that we can follow the steps and fix the files ourselves, as it's not illegal to modify the game files, we just can't share them.

2024-10-02: the nexus mod is back!

**Comment by CanEHdianboi** [comment]
The sound files for BloodBorne got removed from the nexusmods, but you can get it here instead https://www.mediafire.com/file/8e377sjvn64r3d0/BB_SOUND_PACK_FULL_-_ENGLISH.zip/file

**Comment by AikaBack** [comment]
> I can't add anything on behalf of the emulator, but the workaround I found was to download a mod from nexus that contained all the sound files "fixed" for playback on PC. That mod seems to have nuked by Sony (can't think of any other reason the author would take it down), it used to be hosted here: https://www.nexusmods.com/bloodborne/mods/34
> 
> I'm just hoping the author of that mod shares his workflow so that we can follow the steps and fix the files ourselves, as it's not illegal to modify the game files, we just can't share them.

As I understand, my game has those sound files but there is still no sound?

**Comment by purgea** [comment]
> > I can't add anything on behalf of the emulator, but the workaround I found was to download a mod from nexus that contained all the sound files "fixed" for playback on PC. That mod seems to have nuked by Sony (can't think of any other reason the author would take it down), it used to be hosted here: https://www.nexusmods.com/bloodborne/mods/34
> > I'm just hoping the author of that mod shares his workflow so that we can follow the steps and fix the files ourselves, as it's not illegal to modify the game files, we just can't share them.
> 
> As I understand, my game has those sound files but there is still no sound?

The sound files in Bloodborne, as far as I am aware, are encrypted and the emulator can't read them just yet, you need to find the decrypted version of those sounds and overwrite the encrypted ones which are located in the game directory (can't really help out with this sorry, the mod got removed as mentioned before)

**Comment by Dhrazer** [comment]
> > > I can't add anything on behalf of the emulator, but the workaround I found was to download a mod from nexus that contained all the sound files "fixed" for playback on PC. That mod seems to have nuked by Sony (can't think of any other reason the author would take it down), it used to be hosted here: https://www.nexusmods.com/bloodborne/mods/34
> > > I'm just hoping the author of that mod shares his workflow so that we can follow the steps and fix the files ourselves, as it's not illegal to modify the game files, we just can't share them.
> > 
> > 
> > As I understand, my game has those sound files but there is still no sound?
> 
> The sound files in Bloodborne, as far as I am aware, are encrypted and the emulator can't read them just yet, you need to find the decrypted version of those sounds and overwrite the encrypted ones which are located in the game directory (can't really help out with this sorry, the mod got removed as mentioned before)

I think he means he already has those files, so do I, there is still no sound, none...

**Comment by purgea** [comment]
> > > > I can't add anything on behalf of the emulator, but the workaround I found was to download a mod from nexus that contained all the sound files "fixed" for playback on PC. That mod seems to have nuked by Sony (can't think of any other reason the author would take it down), it used to be hosted here: https://www.nexusmods.com/bloodborne/mods/34
> > > > I'm just hoping the author of that mod shares his workflow so that we can follow the steps and fix the files ourselves, as it's not illegal to modify the game files, we just can't share them.
> > > 
> > > 
> > > As I understand, my game has those sound files but there is still no sound?
> > 
> > 
> > The sound files in Bloodborne, as far as I am aware, are encrypted and the emulator can't read them just yet, you need to find the decrypted version of those sounds and overwrite the encrypted ones which are located in the game directory (can't really help out with this sorry, the mod got removed as mentioned before)
> 
> I think he means he already has those files, so do I, there is still no sound, none...

That's strange, I have them and they work just fine, sometimes there is a small chance that they'll fail to load, but other than that, it's perfectly fine...

**Comment by jalyasini** [comment]
I am also having this issue, sound was working in a prior build, now nothing. "sometimes there is a small chance that they'll fail to load, but other than that, it's perfectly fine..." was the case for me, but not as of the last build.

**Comment by rafael-57** [comment]
It's a known issue. The library for reading audio files (sceAJM) is not implemented yet. Some games don't use this library, which is why their audio plays

**Comment by Hermiten** [comment]
Already reported on some issue so for me it's duplicate
https://github.com/shadps4-emu/shadPS4/issues?q=is%3Aissue+is%3Aopen+sound+bloodborne

**Comment by jalyasini** [comment]
this is for windows not linux @Hermiten

**Comment by Hermiten** [comment]
SceAJM is for all platform

**Comment by isaacmoha1998** [comment]
the nexus mod link is backl

**Comment by Invalidcookie-com** [comment]
This issue is with all games, there is no way for the emulator to process those files, the Console gives you red text that says so. The files are ready to be read but the sceAJM isn't being read. Don't worry sooner or later they'll add the OPENAL or SDL2 libraries to read it. 
Great progress being made here. Bloodborne isn't the only program that opens. The complete Fnaf collection and smaler PKG open as well. I've been working my way up to testing the full size PKGs. I'll be taking a look at WWE2k23 today to see how well it renders.

**Comment by gelson-zord** [comment]
The mod is back online, it seem it got a fake claim for copyright.

**Comment by IAmBatby** [comment]
> The mod is back online, it seem it got a fake claim for copyright.

Posting piracy on this github is a little silly and not really relevant for the actual issue at hand

**Comment by gelson-zord** [comment]
> Posting piracy on this github is a little silly and not really relevant for the actual issue at hand
 
Sorry, but you had to say this to the first one who posted the link not me, I was just letting you know.
