### ISSUE TITLE
[Lovelive] [CUSA24620] In the process of checking DLC Crashes with Unreachable code

### ISSUE THREAD

**Issue by zbn297427669** [shadps4-emu/shadPS4#1163]
When the game loads to check for DLC, it will freeze and then crash.
Proof:
![photo_2024-09-30_11-16-11](https://github.com/user-attachments/assets/4d6c1d6d-f53d-405b-9d31-4feda4b75342)

Please see the attachment for the log at that time.
[shad_log.txt](https://github.com/user-attachments/files/17183340/shad_log.txt)

Let me know if you need anything else!

**Comment by Carrizo1821** [comment]
![Captura de pantalla 2024-10-01 141355](https://github.com/user-attachments/assets/37084f63-841e-412e-8dcc-c95a9d35a619)
I enter the menu but it doesn't enter the gameplay

**Comment by Hermiten** [comment]
a DLC can create new error
For you this is this one:

```
[Debug] <Critical> save_memory.cpp:WriteMemory:281: Unreachable code!
WriteMemory out of bounds
```

Maybe @viniciuslrangel is aware ?

EDIT: I pinned you but I think this is not a saving things

**Comment by viniciuslrangel** [comment]
Hello!

This is already fixed in the latest version

**Comment by Hermiten** [comment]
> Hello!
> 
> This is already fixed in the latest version

Thanks you
