### ISSUE TITLE
Black screen Bloodborne

### ISSUE THREAD

**Issue by PrimalSmite** [shadps4-emu/shadPS4#1168]
While launching Bloodborne, opens only black screen.
Logs in file:
[shad_log.txt](https://github.com/user-attachments/files/17189571/shad_log.txt)

**Comment by rafael-57** [comment]
Is the main menu a black screen too? Or only ingame? Do you have sysmodules?

**Comment by polybiusproxy** [comment]
Bloodborne doesn't run on Linux
