### ISSUE TITLE
Bloodborne no 3d rendering 

### ISSUE THREAD

**Issue by dante42lk** [shadps4-emu/shadPS4#1179]
![image](https://github.com/user-attachments/assets/ee3fd199-4de7-4b02-b551-ac7b0b622e39)
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)

Win11 22631.4169 rtx 4060, 7840hs, latest drivers, bloodborne 1.09. Same with mods/patches or without

**Comment by rafael-57** [comment]
Do you have sysmodules?

**Comment by Hermiten** [comment]
Sorry, but we only support versions of this repo.
Branch "HEAD" is not supported, ask on the right repo.
