### ISSUE TITLE
Macos Crashes on startup of game  startup (only tried sonic mania)

### ISSUE THREAD

**Issue by AwayCoast23465** [shadps4-emu/shadPS4#1180]
Here is the log;

https://docs.google.com/document/d/1IHYGu3f4xWMwub1BEAP4QhHdpCuH8aSi_SlMKP1Irv4/edit?usp=sharing

(too long for github)

**Comment by squidbus** [comment]
The emulator is only supported on Apple Silicon Macs if running macOS 15 or later.
