### ISSUE TITLE
crash affter hit enemy

### ISSUE THREAD

**Issue by Senorkashy470** [shadps4-emu/shadPS4#1182]
im going to play bloodborn and when i liiled by the wolf game crash without any error in log

**Comment by chumyshhh** [comment]
if your cpu is intel 12 - 14 generation
you probably need a mod fix for sfx

**Comment by rafael-57** [comment]
Even if there is no error in the log, please provide a log when opening an issue

**Comment by Hermiten** [comment]
Duplicate here https://github.com/shadps4-emu/shadPS4/issues/503
You can post update on the other issue
