### ISSUE TITLE
[Suggestions] Add "Minimum system requirements" on readme

### ISSUE THREAD

**Issue by Hermiten** [shadps4-emu/shadPS4#1185]
Hello,

I think it can be helpful to add a "Minimum system requirements" on the readme.
I know that this information is complicated to know but it could be interesting for people with a low configuration.

I think it's also interesting to separate Linux, Windows and Mac and thus specify the emulator's progress for each system. For example, it would be possible to say that it's normal for certain games to run better on Linux or Windows than on Mac, or even to give a sort of percentage of progress using certain games such as Bloodborne as a basis.

This could also help people who have certain errors relating to memory allocation, those looking to launch the emulator on SteamDeck or any questions about porting to Android.

But it would also make it possible to specify the difficulty of launching the emulator with or without a gpu, to have Vulkan installed in certain versions, drivers up to date, etc ...
We could also specify which GPUs are best supported for each system.

All this could fit into a table to simplify things 

Can close:
https://github.com/shadps4-emu/shadPS4/issues/725

**Comment by DanielSvoboda** [comment]
Some of this information is already in the QuickStart
for example: Vulkan 1.3 support (required)
https://github.com/shadps4-emu/shadPS4/blob/main/documents/Quickstart/Quickstart.md

**Comment by Hermiten** [comment]
Yes, that true ! I Forgot this place.
Maybe we can add further details on it like I explained

**Comment by Hermiten** [comment]
Done
