### ISSUE TITLE
Bloodborne. Rs32float error. 3d scenes not displaying (character creation screen/ingame)

### ISSUE THREAD

**Issue by dante42lk** [shadps4-emu/shadPS4#1193]
The issue **_happens on all builds_** (0.21- latest current builds. Main/head/bb hacks doesn't matter).
rtx 4060 7840hs win11 22631.4169 32gb ram. Tried with and without sys modules. The system is not out of VRAM/RAM.
![image](https://github.com/user-attachments/assets/944e8151-e9ea-439e-89f8-f7c02c021ce2)

![image](https://github.com/user-attachments/assets/6339676a-80f6-46c5-b538-e175be2a7d0c)
```
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
```

**Comment by Hermiten** [comment]
I have the same spec as you and I don't have this problem.
I'm closing it. If you do a new test and have the same problem, you can upload the new log here, I will reopen it
