### ISSUE TITLE
Why is AVX2 Necessary to Install PKG?

### ISSUE THREAD

**Issue by pikomule** [shadps4-emu/shadPS4#1202]
I have an AMD FX8350 cpu, it doesn't have AVX2. Shadps4 runs fine but fails to install PKG. If I emulate avx2 with Intel SDE, the PKG installs fine. After that I can start shadps4 normally and start the games. Thanks and great job

**Comment by Hermiten** [comment]
@georgemoralis hey, do you have an idea about that ?:)

**Comment by par274** [comment]
I am not an expert on this but they may be using some libraries of AVX2.

You can also extract it with other PKG extractor applications, there are extractors that do not require AVX2.

**Comment by pikomule** [comment]
Gracias, ¿alguna recomendación de extractor de pkg?

Al ejecutar juegos, me afectará no tener avx2? o tendré el mismo rendimiento?

**Comment by par274** [comment]
I guess AVX2 is not needed for emulation.

Sorry but I can't share this I think you can just Google it yourself.

@georgemoralis  Hey, is this considered piracy?

**Comment by red-prig** [comment]
For PS4 games AVX2 instructions are strictly required, some games of course may not use them but they can, and therefore I assume the application is compiled with support for AVX2 instructions.

**Comment by polybiusproxy** [comment]
Closing as AVX2 is required for emulation. For those people looking for alternatives anyway, I recommend PkgEditor.
