### ISSUE TITLE
Shadps4 crashing a lot near the first yharnam enemy (ryzen 9 69h00hx with intergrated graphics)

### ISSUE THREAD

**Issue by xt234** [shadps4-emu/shadPS4#1206]
So my pc has the 32 gig ram req but after killing the werewolf it crashes a lot near the first yharnam enemy and i have to remake the character again to fix the crashing.

**Comment by xt234** [comment]
Meant to add bloodborne in the title

**Comment by xt234** [comment]
[shad_log.txt](https://github.com/user-attachments/files/17234341/shad_log.txt)
here is the log file.

**Comment by Hermiten** [comment]
It's a common problem, issue already exist. Please check on issue and on discord too
