### ISSUE TITLE
Fatal Error crash on Undertale startup on the latest build.

### ISSUE THREAD

**Issue by Morphof** [shadps4-emu/shadPS4#1213]
![image](https://github.com/user-attachments/assets/87493895-2147-43b1-ad8d-32e616d1463c)
When I start up undertale, i get faced with this error message.

**Comment by Hermiten** [comment]
Only test on the main branch is allowed

**Comment by Morphof** [comment]
> Only test on the main branch is allowed

The issue still persists on the main branch. I included the wrong screenshot. 
![image](https://github.com/user-attachments/assets/ba461bd1-8e62-426b-87db-800c2d816025)

**Comment by Hermiten** [comment]
Seem's to work fine on the compatibility list
https://github.com/shadps4-emu/shadps4-game-compatibility/issues/171

**Comment by Hermiten** [comment]
Please do a fresh install of Shadps4, it's also work well for me
