### ISSUE TITLE
[Debug] <Critical> image.cpp:operator():236: Assertion Failed!

### ISSUE THREAD

**Issue by mamamoy** [shadps4-emu/shadPS4#1216]
i have some issue when try playing GOW III Remastered
log:
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:378: Compiling fs shader 0xccdebd80d1b8f55c (permutation)
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:88: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:378: Compiling vs shader 0xccdebd802401e5ac (permutation)
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:88: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:88: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:378: Compiling fs shader 0x29966d1be34790b4 
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:378: Compiling vs shader 0x29966d1b47a9adb1 
[Debug] <Critical> image.cpp:operator():236: Assertion Failed!

**Comment by Mintythos** [comment]
[Debug] <Critical> image.cpp:operator():236: Assertion Failed!
I'm having this issue also quite frequently in Bloodborne. I've tried many mods to fix it to no avail.
