### ISSUE TITLE
Update small problem: encoding problem when installing downloaded update

### ISSUE THREAD

**Issue by cvertee** [shadps4-emu/shadPS4#1217]
After downloading update shadps4 opens a new terminal for installation, after that prints something with bad encoding

Emulator & console languages installed as Russian

Dunno maybe it was already fixed, i forgor to write down commit hash on which i downloaded update

![image](https://github.com/user-attachments/assets/00427d00-9426-4431-b462-bc6d5f46c92c)

**Comment by DanielSvoboda** [comment]
I noticed this too, in my language it also happens in pt-BR "atualização".
This phrase is translated into all languages, maybe next week I'll be able to see this, or someone will fix it before
![image](https://github.com/user-attachments/assets/0e26869f-dd40-4ab3-8a53-97a4eb42dc52)

**Comment by DanielSvoboda** [comment]
The file is saved with the correct formatting.
However, it appears incorrectly in the console and, as you can see in the print I sent, there is a word below that has an accent that is part of Expand-Archive, but the text above is not correct.
I still haven't been able to identify where the problem is.

**Comment by DanielSvoboda** [comment]
I opened PR-1283, it will solve this

![image](https://github.com/user-attachments/assets/8ec4dba1-4751-43b5-aa17-e7fdde422b69)

**Comment by cvertee** [comment]
Thanks! Will test that later after getting another one update and if ok will close this issue

**Comment by cvertee** [comment]
nice :p

![image](https://github.com/user-attachments/assets/27c64fd6-4831-48c5-913d-390436baa308)
