### ISSUE TITLE
[Render.Recompiler] <Error> translate.cpp:LogMissingOpcode:455: Unknown opcode V_SUBBREV_U32 (455, category = VectorALU)

### ISSUE THREAD

**Issue by Da-nu** [shadps4-emu/shadPS4#1220]
Persona 4 Dancing with libSceVideodec.sprx forcefully loaded in gets the game further and now I've hit an unkown opcode error.
[shad_log.txt](https://github.com/user-attachments/files/17247152/shad_log.txt)

**Comment by polybiusproxy** [comment]
Move this to https://github.com/shadps4-emu/shadPS4/issues/496 please
