### ISSUE TITLE
Bloodborne (CUSA03173) blood problem on clothes

### ISSUE THREAD

**Issue by par274** [shadps4-emu/shadPS4#1224]
When Bloodborne (CUSA03173) attacks an enemy, the blood spatter deforms the clothing and an image like this appears.

Maybe it's due to AMD GPU. (RX 6700XT)

![Ekran görüntüsü 2024-10-04 000202](https://github.com/user-attachments/assets/5e486f19-f7fa-410a-9ada-c52fac7f7c19)
![resim](https://github.com/user-attachments/assets/5d0da99c-4165-419e-b953-f806764d9b7f)

**Comment by D3niPhantom** [comment]
This happens with my 3090 as well, actually.

I tried it at native res and it happens as well, my internal rendering resolution is now 1440p and still reproducible.

Specs are:
Ryzen 7800X3D
3090 FE
64GB mem @ 6000MHz
Running off of my PCIe4 NVMe.

Added an image to illustrate it from my end as well:
![Untitled](https://github.com/user-attachments/assets/2105eef8-ddc5-4ea2-adba-189b4cf21464)

**Comment by par274** [comment]
> This happens with my 3090 as well, actually.
> 
> Added an image to illustrate it from my end as well: ![Untitled](https://private-user-images.githubusercontent.com/16979144/373443135-2105eef8-ddc5-4ea2-adba-189b4cf21464.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTgyNjAsIm5iZiI6MTcyNzk5Nzk2MCwicGF0aCI6Ii8xNjk3OTE0NC8zNzM0NDMxMzUtMjEwNWVlZjgtZGRjNS00ZWEyLWFkYmEtMTg5YjRjZjIxNDY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIzMjYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyOGQ2YWRkOTYzMTc3YmJmZmY1MTdmMjVjYTdhNTkxY2Q4Y2JiYTEyNWY4MDlmYTQ0MmI0YWEzM2NkMTY3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.74H65HCNXtwet5Sw5WZw5-ju4QXF-N1ZJHeg1mbn64E)

A mod seems to fix this, but reporting it is still a good idea.

**Comment by D3niPhantom** [comment]
> > This happens with my 3090 as well, actually.
> > Added an image to illustrate it from my end as well: ![Untitled](https://private-user-images.githubusercontent.com/16979144/373443135-2105eef8-ddc5-4ea2-adba-189b4cf21464.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTgyNjAsIm5iZiI6MTcyNzk5Nzk2MCwicGF0aCI6Ii8xNjk3OTE0NC8zNzM0NDMxMzUtMjEwNWVlZjgtZGRjNS00ZWEyLWFkYmEtMTg5YjRjZjIxNDY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIzMjYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyOGQ2YWRkOTYzMTc3YmJmZmY1MTdmMjVjYTdhNTkxY2Q4Y2JiYTEyNWY4MDlmYTQ0MmI0YWEzM2NkMTY3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.74H65HCNXtwet5Sw5WZw5-ju4QXF-N1ZJHeg1mbn64E)
> 
> A mod seems to fix this, but reporting it is still a good idea.

Yep, ideal situation is to get this in a fully playable state without any mods, save for quality-of-life enhancements like greater framerates or effect removal.

**Comment by par274** [comment]
> Yep, ideal situation is to get this in a fully playable state without any mods, save for quality-of-life enhancements like greater framerates or effect removal.

Yeah, even though the mod fixes the problem, it's not as effective as the original game. For example, the mod that fixes this problem removes the blood effect on the clothes, even though it should normally be there.

**Comment by Annaya200** [comment]
> > Yep, ideal situation is to get this in a fully playable state without any mods, save for quality-of-life enhancements like greater framerates or effect removal.
> 
> Yeah, even though the mod fixes the problem, it's not as effective as the original game. For example, the mod that fixes this problem removes the blood effect on the clothes, even though it should normally be there.

What is the mod name if u dont mind? I have the same issue here, and i can live without the blood effect for a bit.

If specs help determine the cause of problem : 

4080S FE
7800x3d
32gb 5600

**Comment by par274** [comment]
> > > Yep, ideal situation is to get this in a fully playable state without any mods, save for quality-of-life enhancements like greater framerates or effect removal.
> > 
> > 
> > Yeah, even though the mod fixes the problem, it's not as effective as the original game. For example, the mod that fixes this problem removes the blood effect on the clothes, even though it should normally be there.
> 
> What is the mod name if u dont mind? I have the same issue here, and i can live without the blood effect for a bit.
> 
> If specs help determine the cause of problem :
> 
> 4080S FE 7800x3d 32gb 5600

"Rainbow-Blackness Fix" on NexusMods.

**Comment by Hermiten** [comment]
Can you please check again on the last main branch ? Some fix was made

**Comment by par274** [comment]
> Can you please check again on the last main branch ? Some fix was made

Hi, I normally use another build because it's Tess, but when I tried the last main here, I saw some improvement.

**Comment by GHU7924** [comment]
I think the issue can be closed, and in the future, in any case, someone will report the problem if a regression occurs.
