### ISSUE TITLE
Bloodborne (CUSA03173) physics engine sometimes does not render properly

### ISSUE THREAD

**Issue by par274** [shadps4-emu/shadPS4#1226]
The title may be a bit confusing, but Bloodborne (CUSA03173) physics engine sometimes gets crazy.

When this happens, everything in the game world usually starts to "shake", resulting in a 10-20 FPS drop in overall frame rate. And going to the menu and continuing again does not work, you need to close the emulator.

The problem usually occurs randomly and usually occurs on clothes, hair and plants.

Here is video:

https://github.com/user-attachments/assets/e888ea3f-a745-4c36-a3e6-625799a674db

**Comment by IAmBatby** [comment]
Just a theory not an observation but is it possible this physics problem is the result of such a harse framedrop and not the cause of it?

**Comment by par274** [comment]
> Just a theory not an observation but is it possible this physics problem is the result of such a harse framedrop and not the cause of it?

No. When this problem is not present, a constant 60 FPS is achieved, but if this problem occurs in a place where there are a lot of NPCs, for example, it drops to 20-30 FPS and is fixed by closing and reopening the emulator.

**Comment by HeinrichVonStinkenfinger** [comment]
> The title may be a bit confusing, but Bloodborne (CUSA03173) physics engine sometimes gets crazy.
> 
> When this happens, everything in the game world usually starts to "shake", resulting in a 10-20 FPS drop in overall frame rate. And going to the menu and continuing again does not work, you need to close the emulator.
> 
> The problem usually occurs randomly and usually occurs on clothes, hair and plants.
> 
> Here is video:
> 
>  2024-10-04.01-52-50_1.mp4

Do you have the 60 FPS patch on?

**Comment by par274** [comment]
> > The title may be a bit confusing, but Bloodborne (CUSA03173) physics engine sometimes gets crazy.
> 
> > 
> 
> > When this happens, everything in the game world usually starts to "shake", resulting in a 10-20 FPS drop in overall frame rate. And going to the menu and continuing again does not work, you need to close the emulator.
> 
> > 
> 
> > The problem usually occurs randomly and usually occurs on clothes, hair and plants.
> 
> > 
> 
> > Here is video:
> 
> > 
> 
> >  2024-10-04.01-52-50_1.mp4
> 
> 
> 
> Do you have the 60 FPS patch on?

Yes.

**Comment by HeinrichVonStinkenfinger** [comment]
> > > The title may be a bit confusing, but Bloodborne (CUSA03173) physics engine sometimes gets crazy.
> > 
> > 
> > > 
> > 
> > 
> > > When this happens, everything in the game world usually starts to "shake", resulting in a 10-20 FPS drop in overall frame rate. And going to the menu and continuing again does not work, you need to close the emulator.
> > 
> > 
> > > 
> > 
> > 
> > > The problem usually occurs randomly and usually occurs on clothes, hair and plants.
> > 
> > 
> > > 
> > 
> > 
> > > Here is video:
> > 
> > 
> > > 
> > 
> > 
> > > 2024-10-04.01-52-50_1.mp4
> > 
> > 
> > Do you have the 60 FPS patch on?
> 
> Yes.

Do me a favor, start a new game file and save near the Central Yharnam big bonfire, try not to kill any enemies, then quit out and load the game and move forward, see if any enemies die or blow away over buildings and have their corpses disappear. Report the findings here with pics or video if that happens.

**Comment by Hermiten** [comment]
Please tell us when you use patch. 
Test and fix can only occur on the game without any patch

**Comment by par274** [comment]
> > > > The title may be a bit confusing, but Bloodborne (CUSA03173) physics engine sometimes gets crazy.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > When this happens, everything in the game world usually starts to "shake", resulting in a 10-20 FPS drop in overall frame rate. And going to the menu and continuing again does not work, you need to close the emulator.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > The problem usually occurs randomly and usually occurs on clothes, hair and plants.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Here is video:
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 2024-10-04.01-52-50_1.mp4
> > > 
> > > 
> > > Do you have the 60 FPS patch on?
> > 
> > 
> > Yes.
> 
> Do me a favor, start a new game file and save near the Central Yharnam big bonfire, try not to kill any enemies, then quit out and load the game and move forward, see if any enemies die or blow away over buildings and have their corpses disappear. Report the findings here with pics or video if that happens.

I didn't start a new game but I killed 1-2 enemies in the area and closed the game and load save, the corpses started to fly and disappear, Broken objects remain in place but you can pass through them. When the corpses fly in the air, it affects the frame rate. However, when I remove the 60 FPS and Disable Vsync patch, it works as it should at 30 FPS and the physics engine works properly. The problem seems to be in the 60 FPS patch.

I can take a video of this if you want?

> Please tell us when you use patch. Test and fix can only occur on the game without any patch

Yeah, the problem only exists in the patched game. I definitely confirmed that. Usual suspects: Disable Vsync & 60 FPS with deltatime

**Comment by IAmBatby** [comment]
These kind of physics issues are re-producible with the 60fps patch and forcing a frame drop by capturing a frame in RenderDoc or NSight

Likely not an emulation issue and just a result of physics not correctly handling huge frame drops with Lance McDonald's patch

**Comment by par274** [comment]
> These kind of physics issues are re-producible with the 60fps patch and forcing a frame drop by capturing a frame in RenderDoc or NSight
> 
> Likely not an emulation issue and just a result of physics not correctly handling huge frame drops with Lance McDonald's patch

Yes, it certainly seems that way. Not emulation issue.

**Comment by Hermiten** [comment]
Okay thanks you. The emulator is in an early development, so for now patch can be very unstable. 
I'm closing this issue
