### ISSUE TITLE
Updator not working for AppImage build: cannot create regular file, Text file busy

### ISSUE THREAD

**Issue by KrisCris** [shadps4-emu/shadPS4#1234]
```log
Starting Update...
Archive:  /home/deck/Applications/Sony PlayStation 4/user/temp_download_update/temp_download_update.zip
  inflating: /home/deck/Applications/Sony PlayStation 4/user/temp_download_update/Shadps4-qt.AppImage  
cp: cannot create regular file '/home/deck/Applications/Sony PlayStation 4/Shadps4-qt.AppImage': Text file busy
```

**Comment by Hermiten** [comment]
Maybe something for you @DanielSvoboda ?

**Comment by DanielSvoboda** [comment]
> ```
> Starting Update...
> Archive:  /home/deck/Applications/Sony PlayStation 4/user/temp_download_update/temp_download_update.zip
>   inflating: /home/deck/Applications/Sony PlayStation 4/user/temp_download_update/Shadps4-qt.AppImage  
> cp: cannot create regular file '/home/deck/Applications/Sony PlayStation 4/Shadps4-qt.AppImage': Text file busy
> ```

What is your operating system?

**Comment by DanielSvoboda** [comment]
Please download this action and try to perform the update, to test if it solves your problem.
https://github.com/shadps4-emu/shadPS4/actions/runs/11184504826

**Comment by KrisCris** [comment]
> Please download this action and try to perform the update, to test if it solves your problem. https://github.com/shadps4-emu/shadPS4/actions/runs/11184504826

Can confirm this build fixed the issue!
