### ISSUE TITLE
Game stop and pause buttons are not working

### ISSUE THREAD

**Issue by par274** [shadps4-emu/shadPS4#1235]
When the game is open in the emulator, the stop and pause buttons on the interface do not work. When I turn off the console, the game closes, but as can be seen in the video, I cannot control the PC, that is, I cannot click anywhere. It is fixed in 3-4 seconds.

Sometimes the entire PC freezes for 5-6 seconds. This problem exists in all builds and branchs.

I think there may be other options to close the game regarding this issue.

Specs:
5800X3D
6700XT
32GB 3600 MHz RAM
ShadPS4 on M2 SSD
Win 11

https://www.youtube.com/watch?v=18kJYaw9j8M

**Comment by Hermiten** [comment]
This is how the emulator is actually build. This is planned to change this but not for now.
Thanks for the report
