### ISSUE TITLE
Bloodborne emulator cheats making game crash

### ISSUE THREAD

**Issue by Zenbeau** [shadps4-emu/shadPS4#1245]
I am guessing the crash happens because I am on the wrong game version or something like that. I'm on CUSA00900 v1.09 and the cheats that I found working for me were Blood Echoes and Infinite Stamina.
The cheats that didn't work for me were Infinite Health and One Hit Kill. for OHK, as soon as I hit enemy my game crashes.

so I made my own cheat table -> https://opencheattables.com/viewtopic.php?t=1142

I only tested it on the first level up to the point where I killed the Cleric Beast (first boss), it seems to be working fine. if anyone wants to test it more, go ahead.

**Comment by Hermiten** [comment]
Hello, thanks for the report but we don't support cheat here but only problem with the original version without mods/cheats. Use the GitHub or site in relation with the cheat
Thanks tou
