### ISSUE TITLE
black screen launching BB 1.09 steamos 3.6.12

### ISSUE THREAD

**Issue by christiancoler** [shadps4-emu/shadPS4#1246]
Currently attempting to get CUSA03173 running on steamdeck on SteamOS 3.6.17, seeing blank screen upon boot that stops responding. This seems to happen with any linux QT version I've tried.  Log is from latest action artifact. Any suggestions?
[shad_log.txt](https://github.com/user-attachments/files/17266235/shad_log.txt)

**Comment by Dante1475** [comment]
> Currently attempting to get CUSA03173 running on steamdeck on SteamOS 3.6.17, seeing blank screen upon boot that stops responding. This seems to happen with any linux QT version I've tried. Log is from latest action artifact. Any suggestions? [shad_log.txt](https://github.com/user-attachments/files/17266235/shad_log.txt)

Try these builds of ngoquang: https://github.com/ngoquang2708/shadPS4/actions

Works but with some graphic glitches.

**Comment by TheRhysWyrill** [comment]
> > Currently attempting to get CUSA03173 running on steamdeck on SteamOS 3.6.17, seeing blank screen upon boot that stops responding. This seems to happen with any linux QT version I've tried. Log is from latest action artifact. Any suggestions? [shad_log.txt](https://github.com/user-attachments/files/17266235/shad_log.txt)
> 
> Try these builds of ngoquang: https://github.com/ngoquang2708/shadPS4/actions
> 
> Works but with some graphic glitches.

Can confirm it works on my AMD iGPU where the upstream build doesn't, will what's been done to fix these issues be incorporated into upstream eventually?

**Comment by christiancoler** [comment]
> > Currently attempting to get CUSA03173 running on steamdeck on SteamOS 3.6.17, seeing blank screen upon boot that stops responding. This seems to happen with any linux QT version I've tried. Log is from latest action artifact. Any suggestions? [shad_log.txt](https://github.com/user-attachments/files/17266235/shad_log.txt)
> 
> Try these builds of ngoquang: https://github.com/ngoquang2708/shadPS4/actions
> 
> Works but with some graphic glitches.

Thanks, This build does allow me to launch, albeit with a ton of missing geometry and textures to the point where it isn't playable. I'll have to look closer to see what lets that fork launch while the main doesn't. Are you aware of anything to fix/help graphics glitches?

**Comment by SD1494** [comment]
To fix missing textures try to reload the game by going back to bloodbornes Main menu and load back in again

**Comment by Litnesslegitimate** [comment]
All of this was using https://github.com/diegolix29/shadPS4/actions
(Probably works the same on the build mentioned here, I never tried the driver switch on that)

I was able to get the game running without texture issues by using the AMDGPU-PRO drivers

With RADV I've sometimes been able to get it loading in the textures by quitting to the main menu and reloading as mentioned in the prev comment. 
RADV might have issues trying to load things in with shad. It seems to be able to display everything fine after reloading but sometimes when I move between area transitions the screen will flash gray and the textures will disappear again. Sometimes it doesn't happen, but it's been a lot more common when it's loading things for the first time

I'll grab logs for that next time I hop on linux, but it'd be nice if someone could do it for me before that

Edit: logs
What I'm pretty sure is relevant
[Shad_RADV_log.txt](https://github.com/user-attachments/files/17290234/Shad_RADV_log.txt)
The full log in case I'm wrong or missed something
[Shad_RADV_log_Full.txt](https://github.com/user-attachments/files/17290242/Shad_RADV_log_Full.txt)

OS: EndeavourOS (Arch-based)

**Comment by Saigaiii** [comment]
I was able to get into the game with this build https://github.com/diegolix29/shadPS4/actions/runs/11227878157
issue is that the geometry is missing, so while there is collision quite a few things are missing. But much closer than it has been for awhile in terms of working on linux/steam deck.

Edit: Really any of the builds after getting linux working worked on steam deck, but some have missing ui elements, and all of them have missing geometry.

**Comment by Litnesslegitimate** [comment]
> I was able to get into the game with this build https://github.com/diegolix29/shadPS4/actions/runs/11227878157 issue is that the geometry is missing, so while there is collision quite a few things are missing. But much closer than it has been for awhile in terms of working on linux/steam deck.
> 
@Saigaiii 

On my arch based system I was able to fix the missing geometry by launching the game under the AMDGPU-PRO driver (I can't see why it wouldn't work on the steam deck too)

https://wiki.archlinux.org/title/Vulkan
After installing the proprietary driver I moved it from "/usr/share/vulkan/icd.d/" to a folder I made in opt "/opt/amdgpu-stuff/" to make sure it isn't used in anything unless I call it to be (I don't think you need to do this, I'm just paranoid)

Then you can launch shadps4 with the driver using: env VK_ICD_FILENAMES=/opt/amdgpu-stuff/amd_pro_icd64.json ./Shadps4-qt.AppImage (tell VK_ICD_FILENAMES= where the driver is, mine is in opt/amdgpu-stuff)

On KDE you can make a start menu entry that auto starts with the driver, I also have it set to use mangohud
![Screenshot_20241008_145213](https://github.com/user-attachments/assets/bb8f246c-8508-418f-8c7b-e79027089542)


Footage of me booting into the game with both drivers
https://www.youtube.com/watch?v=cYJ8NdJzyTQ


EDIT: 
I just found out while trying to reinstall bloodborne that shad with the PRO driver crashes when trying to install a game. If you're adding a package just switch back to using RADV, and then back to the proprietary to play the game

**Comment by Saigaiii** [comment]
> > I was able to get into the game with this build https://github.com/diegolix29/shadPS4/actions/runs/11227878157 issue is that the geometry is missing, so while there is collision quite a few things are missing. But much closer than it has been for awhile in terms of working on linux/steam deck.
> 
> @Saigaiii
> 
> On my arch based system I was able to fix the missing geometry by launching the game under the AMDGPU-PRO driver (I can't see why it wouldn't work on the steam deck too)
> 
> https://wiki.archlinux.org/title/Vulkan After installing the proprietary driver I moved it from "/usr/share/vulkan/icd.d/" to a folder I made in opt "/opt/amdgpu-stuff/" to make sure it isn't used in anything unless I call it to be (I don't think you need to do this, I'm just paranoid)
> 
> Then you can launch shadps4 with the driver using: env VK_ICD_FILENAMES=/opt/amdgpu-stuff/amd_pro_icd64.json ./Shadps4-qt.AppImage (tell VK_ICD_FILENAMES= where the driver is, mine is in opt/amdgpu-stuff)
> 
> On KDE you can make a start menu entry that auto starts with the driver, I also have it set to use mangohud ![Screenshot_20241008_145213](https://private-user-images.githubusercontent.com/105521159/374725712-bb8f246c-8508-418f-8c7b-e79027089542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODczMTEsIm5iZiI6MTcyODQ4NzAxMSwicGF0aCI6Ii8xMDU1MjExNTkvMzc0NzI1NzEyLWJiOGYyNDZjLTg1MDgtNDE4Zi04YzdiLWU3OTAyNzA4OTU0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxNTE2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTBmNjAyMTMxYzU3YTQ3NGZjYTlhMjZmMDQxMzA0Yzk3OGE2M2MxZWI0YmFmNzJkNzdlNmVlMjRkNzFjOTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A3CTBtJ3_zrKp_N2AjszHnNksv8_NnTvPZAmd7pz1r8)
> 
> Footage of me booting into the game with both drivers https://www.youtube.com/watch?v=cYJ8NdJzyTQ
> 
> EDIT: I just found out while trying to reinstall bloodborne that shad with the PRO driver crashes when trying to install a game. If you're adding a package just switch back to using RADV, and then back to the proprietary to play the game

How did you install it? Not familiar with AUR tbh.

**Comment by Litnesslegitimate** [comment]
> How did you install it? Not familiar with AUR tbh.

@Saigaiii Sorry, I just saw this.
Personally I use yay to get things from the AUR, you kind of use it like pacman

https://itsfoss.com/install-yay-arch-linux/ (Or google "Install yay arch linux")
After that, just " yay -S vulkan-amdgpu-pro " and it'll end up in your vulkan/icd.d folder

Also might be worth checking out their github to see what it can do, I use yay quite a bit
https://github.com/Jguer/yay

**Comment by SD1494** [comment]
Highly recommend "Ram Spike Workaround" by Kyoski for playing on steam deck. You can get it on nexusmods

**Comment by Saigaiii** [comment]
Do you have issues with the ui elements not loading? What specific build version are you running on steam deck?

**Comment by SD1494** [comment]
Haha seems like we had this conversation on nexus already :D 
Like i said there i'm using ngoquang2708 fork of shadps4 right now i'm on build  35f6fc8
I'm also using boczekek's fps boost, AMD og sfx by diegolix29 and vertex Explosion fix by rainmakerv2. I haven't been messing around much with mods tho so there might be better ones for the steam deck

**Comment by Saigaiii** [comment]
> Haha seems like we had this conversation on nexus already :D Like i said there i'm using ngoquang2708 fork of shadps4 right now i'm on build [35f6fc8](https://github.com/shadps4-emu/shadPS4/commit/35f6fc80cf1bc852d4db43013b051e9126722ff2) I'm also using boczekek's fps boost, AMD og sfx by diegolix29 and vertex Explosion fix by rainmakerv2. I haven't been messing around much with mods tho so there might be better ones for the steam deck

Lol bro I been trying to see which build would stop the missing geometry and the missing ui elements. Hope that one is it

Edit: Thanks bro. It seems like ngoquang2708 forks may be the most stable linux builds right now. I can actually launch my game on his latest release.

**Comment by Saigaiii** [comment]
> Haha seems like we had this conversation on nexus already :D
> Like i said there i'm using ngoquang2708 fork of shadps4 right now i'm on build [35f6fc8](https://github.com/shadps4-emu/shadPS4/commit/35f6fc80cf1bc852d4db43013b051e9126722ff2)
> I'm also using boczekek's fps boost, AMD og sfx by diegolix29 and vertex Explosion fix by rainmakerv2. I haven't been messing around much with mods tho so there might be better ones for the steam deck

Sorry to bother you again, but are you having issues with ui elements on this build? I’m noticing blank/outline health bar and stamina, along with missing picture on the bullets and vial. 

Edit: Nevermind I think I figured it out. It’s one of mods doing it I believe.

**Comment by Skyrent** [comment]
Unfortunately, I can't get the amdgpu-pro driver to work on SteamOS. I keep getting segmentation faults or the app glitches and self-terminates almost immediately

**Comment by Missake212** [comment]
Could you try again on latest main? I believe #1683 may have fixed this issue

**Comment by christiancoler** [comment]
@Missake212 latest main appears to be working for me - tomorrow I'm going to go through and give a fresh unmodded copy of BB a try to see if that works. Closing this for now, thanks all!

**Comment by TerryNull** [comment]
In Hemwick Charnel Lane, when I approach the obelisk, a cutscene activates, and a carriage arrives, taking me to Forsaken Cainhurst Castle. Cainhurst Summons I have. A black screen appears and nothing else happens. Steam Deck on SteamOS last, Shadps4 0.9.0. I've tried with and without different patches, but nothing works
