### ISSUE TITLE
FC 24 not opening

### ISSUE THREAD

**Issue by GamingShotz** [shadps4-emu/shadPS4#1253]
Every time I try opening the emulator and the newly updated FC 24 on PS4 Package, it doesn't work, this the final code I get before it automatically closing

"[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelMapDirectMemory2 (nid: BQQniolj9tQ) called, returning zero to 0x900fe18a3"

In CMD, Shadsps4

**Comment by polybiusproxy** [comment]
Please feel free to report this on the compatibility repo.
