### ISSUE TITLE
Bloodborne assertion failed error layer not present

### ISSUE THREAD

**Issue by FattyMitchell123** [shadps4-emu/shadPS4#1262]
keep getting: [Debug] <Critical> vk_platform.cpp:operator():349: Assertion Failed!Failed to create instance: ErrorLayerNotPresent message when trying to launch bloodborne and am unsure how to fix it

**Comment by polybiusproxy** [comment]
Please provide a log.

**Comment by FattyMitchell123** [comment]
[shad_log.txt](https://github.com/user-attachments/files/17268758/shad_log.txt)

**Comment by polybiusproxy** [comment]
Disable all of the validation options

**Comment by FattyMitchell123** [comment]
thanks a lot it works now

**Comment by Pyryte** [comment]
not for me
