### ISSUE TITLE
Gravity Rush Remastered [CUSA01113] some left issues

### ISSUE THREAD

**Issue by Pikota3124** [shadps4-emu/shadPS4#1268]
Well, as previous errors were already fixed. Ill add the ones left to make game be perfect.

- Shadows are wrong, they appear and dissapear as you move.

![1022](https://github.com/user-attachments/assets/3b275401-91b5-4a23-a786-56f6584f810e)

- Game is so dull, original was brighter than this

- In last, on comic dialogues when you press to advance, usually it skip the entire dialogue, like if it presses it many times.

**Comment by ElBread3** [comment]
My theory is if the controller has no input the game thinks the controller has disconnected and pauses the game. I was looking at this issue but this will likely mean devs will have to reverse engineer what method the game uses to see if the controller is "disconnected" that the emulator doesn't provide, which is beyond my pay grade. Devs please get on this!

**Comment by SonofUgly** [comment]
>i noticed if u put your finger on the touchpad it get fixed and stop entering on pause. So looks something related to touchpad

It's not just the touchpad, if you mash any button it prevents it.

Another issue is it accepts inputs nearly every frame in menus/comic cutscenes, so you have to tap very quickly for it not to double/triple input. I'm guessing both these issues are related, like the game's input handler/polling is running insanely fast, making whatever wait threshold for inputs happen almost instantly and causing it to think the controller has disconnected somehow maybe by some desync/race condition or timeout.

**Comment by Emogop** [comment]
I fixed the text by placing these two files libSceFontFt.sprx + libSceFreeTypeOt.sprx to my installed game directory - \shadps4-win64-qt\CUSA01113\sce_module\
As for pause spamming, it manifests even when a gamepad is turned off. It also intensifies when the heroine starts climbing stairs at the starting location.

**Comment by Foul-Tarnished** [comment]
Do you guys also get #1272 ?

I don't have savefiles to test if it happens with savefile from different areas

**Comment by willywonka300** [comment]
After several minutes of play, I am not having the pause loop issue when using a wired DualShock 4 on Windows 11.

**Comment by Foul-Tarnished** [comment]
Well it happens even without a controller connected ...

Le lun. 7 oct. 2024 à 19:02, willywonka300 ***@***.***> a
écrit :

**Comment by Pikota3124** [comment]
So i updated with new things as old ones were already fixed and to not open a new post, just to make devs notice game still is not perfect.

**Comment by Hermiten** [comment]
A lot have been made, we can see progress on the compat list here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/75
I'm closing this one

**Comment by spektor8** [comment]
My problem is that there is no sound in the game and in the first scene when I knock down the apple game breaks. How to fix it?

**Comment by Kozzlick** [comment]
"comic dialogues when you press to advance, usually it skip the entire dialogue, like if it presses it many times" - I jus tested the game today on shadps4 11.0 and I still have this issue. is there any workaround? I get this behavior with gamepad, keyboard and mouse. Everything works just fine, but comic dialogues advances by several pages all the time. I had theory it has to do something with frames and input detection so I tried different presentation methods (v-sync/no v-sync), tried to connect controller via bluetooth instead of wired, tried to limit fps and still face this issue
