### ISSUE TITLE
Gravity Rush Remastered [CUSA01113] - Crash when loading savefile

### ISSUE THREAD

**Issue by Foul-Tarnished** [shadps4-emu/shadPS4#1272]
When you choose "Continue" on the main menu, then choose your savefile, the emu crash during the loading screen:

[shad_log.txt](https://github.com/user-attachments/files/17270976/shad_log.txt)
``[Debug] <Critical> texture_cache.cpp:ResolveDepthOverlap:102: Unreachable code!``

This at least happens with auto-save made from the starting area (or just after "talking" to the guy a few meters away)

edit : issue still present in 0.4.0 and 0.4.1 (f98b9f7)

**Comment by xwinwinx** [comment]
I had the same problem too. I tested the game twice, and it crashes on chapters 2 and 3, so I can't manually save it.

**Comment by azurefan01** [comment]
I've been facing this issue as well, I hope this logs help, one is of a savefile failing to load and the other one is of the same savefile succeeding to load.

Filed loading: 
[shad_log_GRR_save_load_fail.txt](https://github.com/user-attachments/files/17717245/shad_log_GRR_save_load_fail.txt)

Successful loading (It may have 2~3 failed loadings but the last one is a successful load of the savefile. In the last one I loaded the savefile opened the menu exited the game and then exited ShadPS4):
[shad_log_GRR_save_load_succeed.txt](https://github.com/user-attachments/files/17717250/shad_log_GRR_save_load_succeed.txt)
