### ISSUE TITLE
Knack CUSA00006 boots, but crash after logo

### ISSUE THREAD

**Issue by coolllman** [shadps4-emu/shadPS4#1277]
Knack boots, but crash after logo Japan Studio, on loading
KNACK CUSA00006 ver 01.00

[shad_log.txt](https://github.com/user-attachments/files/17277350/shad_log.txt)

**Comment by coolllman** [comment]
![Screenshot_20241007_160955_RVNC Viewer](https://github.com/user-attachments/assets/f95bfa67-f124-4dba-95af-10fa893352da)
![Screenshot_20241007_160948_RVNC Viewer](https://github.com/user-attachments/assets/4a5f0c3f-8626-43e8-88e9-8a1957281663)

**Comment by Hermiten** [comment]
Must be on compatibility list
