### ISSUE TITLE
Descriptions not showing in emulator settings

### ISSUE THREAD

**Issue by par274** [shadps4-emu/shadPS4#1279]
When I tried it 3-4 builds ago, when I hover over the setting with the mouse, it would write a description below, but this doesn't seem to work in recent builds.

The build I used: [main](https://github.com/shadps4-emu/shadPS4/actions/runs/11213467047)

https://github.com/user-attachments/assets/9e446c2b-207f-45f3-844e-d44e43d3a675

**Comment by TheRhysWyrill** [comment]
Noticed that too but I believe that issue should be addressed with this PR https://github.com/shadps4-emu/shadPS4/pull/1259

**Comment by Xphalnos** [comment]
Normally this was fixed by this commit **https://github.com/shadps4-emu/shadPS4/pull/1259**.

**Comment by par274** [comment]
The problem is solved, closing this
