### ISSUE TITLE
CUSA03023-Bloodborne Curse: Stuck and retreat when attacking enemies

### ISSUE THREAD

**Issue by pipiqi** [shadps4-emu/shadPS4#1281]
13600kf+7900xt+32g
[shad_log.txt](https://github.com/user-attachments/files/17281645/shad_log.txt)

**Comment by Foul-Tarnished** [comment]
Post on the game compatibility repo

**Comment by pipiqi** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！
