### ISSUE TITLE
How to remap keyboard controls?

### ISSUE THREAD

**Issue by HeinrichVonStinkenfinger** [shadps4-emu/shadPS4#1286]
I understand Touchpad Support was just added. Is there a way to remap controls on the keyboard, or at least take the buttons off the numpad? This would help laptop users out so much.

**Comment by georgemoralis** [comment]
it is in progress :D

**Comment by purgea** [comment]
> I understand Touchpad Support was just added. Is there a way to remap controls on the keyboard, or at least take the buttons off the numpad? This would help laptop users out so much.

If you are in urgent need, you can use PowerToys to remap keyboard keys and RMB for the mouse (it is designed for Ryujinx, but works perfectly fine here as well)
