### ISSUE TITLE
Uncharted The Nathan Drake Collection (CUSA02344) black screen

### ISSUE THREAD

**Issue by par274** [shadps4-emu/shadPS4#1289]
Uncharted The Nathan Drake Collection (CUSA02344) black screen, nothing crash just black screen.

[shad_log.txt](https://github.com/user-attachments/files/17293973/shad_log.txt)

**Comment by StevenMiller123** [comment]
Issues like these belong in the compatibility reports, though in this case, the compatibility report for this game already up to date. I'd also recommend testing games after dumping your firmware libraries, as you need the firmware libraries to test this game.

**Comment by par274** [comment]
> Issues like these belong in the compatibility reports, though in this case, the compatibility report for this game already up to date. I'd also recommend testing games after dumping your firmware libraries, as you need the firmware libraries to test this game.

I dont have sys_modules.

**Comment by StevenMiller123** [comment]
Dump them from your PS4 then. Either way, this issue is invalid. The shadPS4 issues page isn't for compatibility reports, we have a separate repository for those.

**Comment by par274** [comment]
> Dump them from your PS4 then. Either way, this issue is invalid. The shadPS4 issues page isn't for compatibility reports, we have a separate repository for those.

Dump my PS4? I should probably play the game on my PS4 then. I opened an issue, I know dump from PS4. We can't escape from problems like this, can we? I close this.
