### ISSUE TITLE
ShadPS4 fails emulations when Vulkan Layers are enabled

### ISSUE THREAD

**Issue by yashbudhia** [shadps4-emu/shadPS4#1291]
![image](https://github.com/user-attachments/assets/3b0afb9e-7ecd-4f43-8811-5451c87d30d5)

Bloodborne emulates fine when vulkan layers are disabled, but when Vulkan is enabled , it crashes on startup and ShadPS4 crashes. This is happening on windows 11 on ShadPS4 version 3.0  .

**Comment by DanielSvoboda** [comment]
You are using an old version 0.3.0.
Try using 0.3.1 = '[Pre-Release](https://github.com/shadps4-emu/shadPS4/releases)' 

These 2 options you mentioned are for debugging, useful for those who are developing, I do not recommend using this if you do not know what it is for, it will cause a crash.

**Comment by yashbudhia** [comment]
Yup seems about right, I think we should update 3.1 in the official website
