### ISSUE TITLE
Game installed, but not showing in the emulator itself

### ISSUE THREAD

**Issue by Halbour** [shadps4-emu/shadPS4#1293]
Here's a screenshot:
![image](https://github.com/user-attachments/assets/c9b6885f-f5df-444b-87fc-c8cef25287b2)
as you can see, it says "Games: 1" but it's empty.
It said "installed successfully" when I installed it.
Using the latest version of everything.

**Comment by DanielSvoboda** [comment]
the latest version is 0.3.1, test with [pre-release](https://github.com/shadps4-emu/shadPS4/releases)

**Comment by Halbour** [comment]
> the latest version is 0.3.1, test with [pre-release](https://github.com/shadps4-emu/shadPS4/releases)

I figured that the problem was because I have set the folder to install games to a Hebrew folder name.
Switching to English fixed it.
Thanks for the link, though, maybe that'll help me run the game...

https://github.com/user-attachments/assets/476bdf5b-6b6a-4136-b3e2-2bd5bfa2626d


---
Nope, the _real_ problem I had still isn't fixed.
Also, why is it "8 games"...??

**Comment by DanielSvoboda** [comment]
the game is stopping because of this error, it is something that has not been implemented yet, this error does not only happen to you, it will happen to anyone who tries to run this game

![image](https://github.com/user-attachments/assets/0575d0ed-ab2b-4a6c-b756-a983a1cc0895)
