### ISSUE TITLE
cheats doesnt work for me

### ISSUE THREAD

**Issue by Halarju** [shadps4-emu/shadPS4#1295]
i am using shadps4 cheats options and when i am in the game and click the square it just doesnt work, and when i close cheats/patches window and go there all options i clicked arent checked

**Comment by DanielSvoboda** [comment]
Cheats are used while the game is running, so they will not be saved in any file.
The patches you select must be clicked on 'save', so that every time you enter the game, what was selected will be applied.

What game are you testing? serial, version
and what emulator version?

**Comment by Hermiten** [comment]
No answer
