### ISSUE TITLE
Appimage updates but the new version isnt saved.

### ISSUE THREAD

**Issue by Blad3forc3** [shadps4-emu/shadPS4#1296]
When you update the appimage inside the existing appimage, the download occurs but after restart the new version doesnt show. Stays on the old version before update

**Comment by DanielSvoboda** [comment]
What version are you using? 'branch number'
Are you running it directly or through the console?
A similar issue was recently fixed, try downloading this action and updating from it to see what happens
https://github.com/shadps4-emu/shadPS4/actions/runs/11184504826

**Comment by Blad3forc3** [comment]
I am using the latest version..7ab8515.
This has been happening for a quite a while for me.
I load the appimage it pops up with a nightly update, i select update, it restarts and the new version is shown.
When i manually close the appimage and then double click it the older version loads.
If i download the appimage manually then the latest version loads fine

**Comment by DanielSvoboda** [comment]
Are you running it via command line? It may be saving the update somewhere else, try running it directly, I think that might be it

**Comment by Blad3forc3** [comment]
I am not using the command line just the mouse to open and close it

**Comment by DanielSvoboda** [comment]
The only requirement is to have unzip or 7z, but usually distros already come with unzip. Are you getting any errors? Try opening it via the command line to see if it shows more details of what is happening.

**Comment by Blad3forc3** [comment]
This is interesting.
When i run the appimage from the command line i get nothing out of the ordinary and it updates ok but when i use the mouse to double click and go through the update it updates, closes, re-opens fine then close and open with the previous appimage

**Comment by GHU7924** [comment]
Is the problem still there?

Have you downloaded new builds?
https://github.com/shadps4-emu/shadPS4/actions

Can you record a video of your actions and the result? (Maybe through the OBS Studio)

**Comment by Blad3forc3** [comment]
Hi, Ive uploaded a video
[2024-12-03 14-58-05.zip](https://github.com/user-attachments/files/17994899/2024-12-03.14-58-05.zip)

**Comment by ngoquang2708** [comment]
~~If I remember correctly, the way the updater work is by check the executable path. In this case, for appimage, the exe path is mounted at ``/tmp``, not real app path.~~

**Comment by ngoquang2708** [comment]
@Blad3forc3 Add ``Path=/path/to/you/app/image/dir/`` to your ``.desktop`` file.

**Comment by ngoquang2708** [comment]
@Blad3forc3 Also check your ``$HOME`` dir, the updated version maybe got downloaded there.

**Comment by GHU7924** [comment]
/home/user/ShadPS4test/ - my path to Shadps4-qt.AppImage

I launched shadPS4 from the folder, but I didn't have a check mark for updates, I put it on and restarted the emulator.
At the new launch, an update message appeared, the emulator was updated and restarted.
After making sure that the version was changed to the new one, I closed it, restarted it, the shadPS4 window opened (the version was new, which is updated).
Is there a problem with the app shortcut or something else?

**Comment by ngoquang2708** [comment]
My suspicion is @Blad3forc3 use a shortcut which doesn't set the working directory the same as the folder where the appimage is in.
The updater only work correctly if the current directory is the appimage directory.
I've tried update from another directory and the updated version got downloaded to the current folder, not the appimage folder.

**Comment by Blad3forc3** [comment]
Sorry for not replying straight away.
Setting the working directory has sorted the problem. I had made a custom shortcut for the menu but didnt enter the working path

**Comment by GHU7924** [comment]
That's nice. Have a good use. You can close the issue.
