### ISSUE TITLE
[CRASH] BB run but crash after the intro cinematic, caused by external audio card.

### ISSUE THREAD

**Issue by Sixmooon** [shadps4-emu/shadPS4#1297]
Hello, 

I managed to launch BloodBorne and everything works fine. 
I can adjust my settings, choose my language and start the game.
Except that in the middle of the intro cinematic, the game crashes and closes everything. 
I'm guessing a problem with the external sound cards, in this case a firewire sound card, because before the crash it disconnects/reconnects in a loop before ShadPS4 closes.

Could you give me some advice on how best to choose my audio device, or how to disable sound support altogether? 

Thanks in advance!

**Comment by StevenMiller123** [comment]
Please provide a log of your crash.

**Comment by Sixmooon** [comment]
Here the logs, we can see at the end before crashing this in loop : 

```
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.AvPlayer] <Warning> avplayer_source.cpp:GetAudioData:354: Could get audio frame. EOF reached.
[Lib.AvPlayer] <Warning> avplayer_source.cpp:GetAudioData:354: Could get audio frame. EOF reached.
[Lib.AvPlayer] <Warning> avplayer_source.cpp:GetAudioData:354: Could get audio frame. EOF reached.
[Lib.AvPlayer] <Warning> avplayer_source.cpp:GetAudioData:354: Could get audio frame. EOF reached.
[Lib.AvPlayer] <Warning> avplayer_source.cpp:GetAudioData:354: Could get audio frame. EOF reached.
[Lib.AvPlayer] <Warning> avplayer_source.cpp:GetAudioData:354: Could get audio frame. EOF reached.
[Lib.AvPlayer] <Warning> avplayer_source.cpp:GetAudioData:354: Could get audio frame. EOF reached.
[Lib.AvPlayer] <Warning> avplayer_source.cpp:GetAudioData:354: Could get audio frame. EOF reached.
[Lib.AvPlayer] <Warning> avplayer_source.cpp:GetAudioData:354: Could get audio frame. EOF reached.
[Kernel] <Info> libkernel.cpp:sceKernelGetCompiledSdkVersion:248: returned system version = 0x4500000
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.AvPlayer] <Warning> avplayer_source.cpp:GetAudioData:354: Could get audio frame. EOF reached.
[Kernel] <Info> libkernel.cpp:sceKernelGetCompiledSdkVersion:248: returned system version = 0x4500000
```

[shad_log.txt](https://github.com/user-attachments/files/17298148/shad_log.txt)

**Comment by Foul-Tarnished** [comment]
Post on the game compatibility repo

**Comment by StevenMiller123** [comment]
@Sixmooon I apologize for the late response. You're on an older build, so I can't verify if you had log type set to sync. That said, regardless of your log type, a GTX 750 Ti is not capable enough to perform PS4 emulation. Unless you can test on a newer GPU, I believe this issue is invalid. 

@Foul-Tarnished Do not suggest spamming the game compatibility repo with issues like these. Compatibility reports should only be made on v0.3.0, and by people with good enough devices to emulate PS4 games in the first place.

**Comment by Foul-Tarnished** [comment]
This issue likely also happen on 0.3.0

**Comment by StevenMiller123** [comment]
@Foul-Tarnished For the record, they were on v0.3.0, I was just restating the compatibility report requirements because you seem to be making invalid compat reports. Either way, this issue is invalid unless they can reproduce it on a device actually capable of running shadPS4.
