### ISSUE TITLE
Gravity Rush 2 - Crash at startup

### ISSUE THREAD

**Issue by Foul-Tarnished** [shadps4-emu/shadPS4#1298]
The game just crash at startup, no visible graphics

log (sync): [shad_log.txt](https://github.com/user-attachments/files/17299443/shad_log.txt)

**Comment by StevenMiller123** [comment]
Compatibility reports belong in the compatibility reports repo. Additionally, please set your log type to sync when reporting issues.

**Comment by Foul-Tarnished** [comment]
@Hermiten Maybe also close all the bloodborne related issues lol

**Comment by Hermiten** [comment]
Like you did it's a compatibility report. 
In Bloodborne ,there is some test on lot of different OS and graphic card which can be fix like vortex explosion, 3D things, etc... And these fix can apply on log of different games. 
If you look on closed issue, you can see that I closed a LOT about Bloodborne but a keep some of them open when we things it's a bug that can be fix
