### ISSUE TITLE
sonic mania runs too fast at 240fps 

### ISSUE THREAD

**Issue by takeshineale128** [shadps4-emu/shadPS4#1300]
sonic mania runs too fast at 240fps, have a option for fps limiter

**Comment by StevenMiller123** [comment]
We have a framerate cap, which can be modified through the vblank interval setting. Could you send a log?

**Comment by takeshineale128** [comment]
fixed i had it on vblank set to 4 and set it back to 1 not fast anymore

**Comment by takeshineale128** [comment]
fixed by setting vblank to 1
