### ISSUE TITLE
Settings menu always opens the "Input" tab (Instead of "General")

### ISSUE THREAD

**Issue by Foul-Tarnished** [shadps4-emu/shadPS4#1301]
Since a recent commit, opening the settings now directly go to the "Input" tab (which has not much settings) instead of going to the first tab; General.

Weird behavior

**Comment by Foul-Tarnished** [comment]
Might be related to #1266 cc @Exhigh

**Comment by Exhigh** [comment]
oou, yep, my bad

**Comment by DanielSvoboda** [comment]
I made the PR-1305 that implements 'Play Time' and I also took the opportunity to correct what you mentioned. There are still other things for the PR to be ready

**Comment by Hermiten** [comment]
This is normally fixed by PR 1305. Thanks
