### ISSUE TITLE
[Feature Request] Support multiple game directories

### ISSUE THREAD

**Issue by Foul-Tarnished** [shadps4-emu/shadPS4#1304]
Let us choose multiple folders where to look for games.

Why:
- Some users want to store some games on a HDD, while other on a SSD.
- Some users store games on a NAS, while keeping a few locally (useful for laptops, when you travel and only keep a few games when travelling, keeping your full library at home on your NAS)

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/226

**Comment by Hermiten** [comment]
You can see progress here https://github.com/shadps4-emu/shadPS4/pull/1308
