### ISSUE TITLE
[CRASH] BB run but crash after the intro cinematic, caused by external audio card.

### ISSUE THREAD

**Issue by Sixmooon** [shadps4-emu/shadPS4#1310]
Hello, 

I'm reopening this ticket because you closed the previous one without providing any solutions or giving me time to reply.

You say that my configuration is too old, but I meet more than the minimum requirements (4-core CPU, 2GB of VRAM, Vulkan 1.3, 16GB of RAM).
And according to the logs, it's mainly the audio that crashes the emulator, which I think is because I'm using an external firewire sound card with an ASIO driver.

Can you look into this a bit more?
Thanks in advance!

**Comment by StevenMiller123** [comment]
@Sixmooon Bloodborne requires more than the "minimum" specs, as it is a very intense game to emulate. With the current status of shadPS4, 2GB of VRAM is nowhere near enough to run Bloodborne. If you'd like me to look deeper, set your log type to sync, and send a new log.
