### ISSUE TITLE
[CRASH] Emulator crashes when clicking play (black screens, not responding) [Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called

### ISSUE THREAD

**Issue by ghost** [shadps4-emu/shadPS4#1311]
Hello I have an error using the GUI appimage, or nixos PR. Although it launches fine the emulator stops responding when I click play on a game. I think it crashed due to a HTTP request, but I'm not sure why the game would need the internet. Here is the error 

Full log: https://hastebin.skyra.pw/xerihalata.yaml

[Kernel.Pthread] <Error> thread_management.cpp:scePthreadAttrSetschedpolicy:284: policy=1 not supported by winpthreads
[Kernel.Pthread] <Error> thread_management.cpp:scePthreadAttrSetschedpolicy:284: policy=1 not supported by winpthreads
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCreate:1042: thread create name = DLUserPreferenceNotifyServiceIm
[Lib.UserService] <Info> userservice.cpp:sceUserServiceGetInitialUser:494: called
[Lib.UserService] <Info> userservice.cpp:sceUserServiceGetUserName:1071: called user_id = 1 ,size = 17 
[Lib.Pad] <Error> pad.cpp:scePadInit:203: (STUBBED) called
[Lib.Pad] <Info> pad.cpp:scePadOpen:248: (DUMMY) called user_id = 1 type = 0 index = 0
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/param/drawparam/empty.gparam.dcx flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:370: (PARTIAL) path = /app0/dvdroot_ps4/param/drawparam/empty.gparam.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/other/global_snow_a.tpf.dcx flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:370: (PARTIAL) path = /app0/dvdroot_ps4/other/global_snow_a.tpf.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/other/global_snow_r.tpf.dcx flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:370: (PARTIAL) path = /app0/dvdroot_ps4/other/global_snow_r.tpf.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/other/global_snow_s.tpf.dcx flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:370: (PARTIAL) path = /app0/dvdroot_ps4/other/global_snow_s.tpf.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/other/global_snow_n.tpf.dcx flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:370: (PARTIAL) path = /app0/dvdroot_ps4/other/global_snow_n.tpf.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/other/modelviewer_default_rem.tpf.dcx flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:370: (PARTIAL) path = /app0/dvdroot_ps4/other/modelviewer_default_rem.tpf.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/other/modelviewer_default_iem.tpf.dcx flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:370: (PARTIAL) path = /app0/dvdroot_ps4/other/modelviewer_default_iem.tpf.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:370: (PARTIAL) path = /app0/dvdroot_ps4/menu/black.gfx
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/menu/black.gfx flags = 0x0 mode = 0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:451: name=SceLibc_FileFD:0x7FFF8000, result=0
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:142: Closing /app0/dvdroot_ps4/menu/black.gfx
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called

**Comment by Hermiten** [comment]
This seems to be a compatibility report and a normal issue of a game not running. Please see on the game compatibility list
