### ISSUE TITLE
(Bloodborne) one tree type won't render in Forbidden Woods

### ISSUE THREAD

**Issue by LibretroAdmin** [shadps4-emu/shadPS4#1314]
In Bloodborne, there's one tree type that won't render. It seems to be mappiece 'm_009001' from map 'm27' (Forbidden Woods).

You can see it here in a Souls editor Smithbox.

![image](https://github.com/user-attachments/assets/82648bf9-0613-4cba-9d49-88f434c0a24d)

This might be a material/blending issue. 

The material MTD types are as follows in case it helps:
Material 17 - N:\SPRJ\data\Material\mtd\map\M[ARSN]_l.mtd
Material 20 - N:\SPRJ\data\Material\mtd\map\M[ARSN]_l.mtd
foliage         - N:\SPRJ\data\Material\mtd\map\m27_00\m27_tree_grass[A]_l_e.mtd
Material 25 - N:\SPRJ\data\Material\mtd\map\M[ARSN]_l_blend.mtd

How it looks like ingame - the tree is not being rendered so this little lamp is suspended in mid-air -

![tree](https://github.com/user-attachments/assets/d0e18f97-35e1-4956-b28d-0dc2ea0b5a90)

**Comment by IAmBatby** [comment]
Don't have the specific model id's but more trees after the Shadows Of Yharnam fight do not load correctly either (the trees depicted here are what are loaded on a native ps4, they are not present on emulation)

![image](https://github.com/user-attachments/assets/da22429e-8153-436f-932a-433d1d9388a3)

**Comment by LibretroAdmin** [comment]
@IAmBatby seems to be on the map Byrgenwerth (m32), mappieces 'm_000157' and ''m_00151)'.

The one common denominator I think I have seen across all these meshes so far is the material 'N:\SPRJ\data\Material\mtd\map\M[ARSN]_l_blend.mtd'. Maybe all mappieces that use that material right now just won't render? 

![image](https://github.com/user-attachments/assets/72b09b3f-7157-4f46-91c0-891fca172aff)

**Comment by AwesomeSoftware79** [comment]
This issue seems to be related with tessellation's implementation.
Using frodo's build, which implements tessellation, these trees are being rendered correctly (at least those trees after Shadows Of Yharnam`s fight):
https://github.com/baggins183/shadPS4/actions


Once frodo finishes his work and creates a PR this ticket should be retested.

**Comment by LibretroAdmin** [comment]
Yes, I can confirm these trees are rendered now w/ the tesselation branch

**Comment by Hermiten** [comment]
Tess is merged. I'm closing this one

**Comment by Foul-Tarnished** [comment]
> Tess is merged. I'm closing this one

Still opened 😅
