### ISSUE TITLE
Discord Rich Presence (RPC) does not work

### ISSUE THREAD

**Issue by par274** [shadps4-emu/shadPS4#1317]
This feature is required to type the name of the game in Discord while playing the game on ShadPS4. However, it does not work.

https://github.com/shadps4-emu/shadPS4/pull/1178

**Comment by DanielSvoboda** [comment]
I tested it here and it's working correctly. Have you checked if this option is activated in Discord, as shown in the screenshot? Is it activated in the emulator settings?
If it's still not working for you, write more details here, such as which version you're using, which game you're testing this on (serial+version), and any other details that are relevant to understanding what's happening.

![image](https://github.com/user-attachments/assets/14d5eba5-acff-4ace-a634-fa627a136811)

**Comment by par274** [comment]
> I tested it here and it's working correctly. Have you checked if this option is activated in Discord, as shown in the screenshot? Is it activated in the emulator settings? If it's still not working for you, write more details here, such as which version you're using, which game you're testing this on (serial+version), and any other details that are relevant to understanding what's happening.
> 
> ![image](https://private-user-images.githubusercontent.com/28203966/375962214-14d5eba5-acff-4ace-a634-fa627a136811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDE5MDMsIm5iZiI6MTcyODc0MTYwMywicGF0aCI6Ii8yODIwMzk2Ni8zNzU5NjIyMTQtMTRkNWViYTUtYWNmZi00YWNlLWE2MzQtZmE2MjdhMTM2ODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDE0MDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NzQ4MjlhOGIwZjA1NWJkZmFjYzk4ZjZjMmUzZWI4NmMxMDZkNWIxMjk1NGM0YTNlZGVmNjE5OTdmZjk0OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AblIpHIhcDZpme_S2-1WbaRCA52arESawMojOA5Et-w)

Hello, yes it did not work.
![resim](https://github.com/user-attachments/assets/673a2155-cf02-477d-8b34-27d42e9eab58)
![resim](https://github.com/user-attachments/assets/f6deabef-333f-4b2e-8649-240619b46d0c)

And my Discord activity:
![resim](https://github.com/user-attachments/assets/50775ffa-55e9-4461-bace-a64dc8bbdaeb)

ShadPS4 build: https://github.com/shadps4-emu/shadPS4/actions/runs/11294542553
Discord version: stable 335184 (33b5e1a) Host 1.0.9167 x64 (53601) Build Override: N/A Windows 11 64-bit (10.0.26100)
Game: Bloodborne (CUSA03173) 1.09

**Comment by Hermiten** [comment]
Any update about this ?

**Comment by par274** [comment]
> Any update about this ?

Still not working.

**Comment by Missake212** [comment]
I also have the same issue, weirdly enough, that's not the case for some
![image](https://github.com/user-attachments/assets/b42a8d92-4486-4925-952d-99f2907a77e8)
![image](https://github.com/user-attachments/assets/64b361ab-106d-47f8-878e-7ca0003e833a)

I was discussing this issue with poly on Discord, and that was his theory:
![image](https://github.com/user-attachments/assets/b36f2f61-f8ce-409b-92b4-c57d104a6aca)

I also saw a few people complaining about this issue before on the help channel on Discord. Last thing I can add is that I've tried this on both the shadPS4 install I've had since a few months ago and that I've updated through the auto updater, and also on a new install of the same build, they both didn't work, and for some reason it's not possible to change the setting, if turned off, you can't turn it on and save as it will just go back to off, and vice versa. Don't know why it behaves this way.

**Comment by polybiusproxy** [comment]
Please try commit 6f543b5

**Comment by polybiusproxy** [comment]
Issue is fixed on main now

**Comment by par274** [comment]
> Issue is fixed on main now

Please don't close this issue until we say it's fixed. Because it's not.

**Comment by Missake212** [comment]
> > Issue is fixed on main now
> 
> Please don't close this issue until we say it's fixed. Because it's not.

I just tested and it now works as intended, might be an issue on your end perhaps?

**Comment by par274** [comment]
> > > Issue is fixed on main now
> > 
> > 
> > Please don't close this issue until we say it's fixed. Because it's not.
> 
> I just tested and it now works as intended, might be an issue on your end perhaps?

What could be issue with me? Why wouldn't ShadPS4 appear when I'm playing a game or when Spotify appears there?

**Comment by Missake212** [comment]
> > > > Issue is fixed on main now
> > > 
> > > 
> > > Please don't close this issue until we say it's fixed. Because it's not.
> > 
> > 
> > I just tested and it now works as intended, might be an issue on your end perhaps?
> 
> What could be issue with me? Why wouldn't ShadPS4 appear when I'm playing a game or when Spotify appears there?

I'm telling you that the new commit has fixed the issue for me and I reported it to poly, have you tried the new commit?

**Comment by par274** [comment]
> I'm telling you that the new commit has fixed the issue for me and I reported it to poly, have you tried the new commit?

My friend, the problem may be fixed for you, but I already reported the problem and it didn't fix it either. Yes, I tried the latest main build.

**Comment by polybiusproxy** [comment]
> What could be issue with me? Why wouldn't ShadPS4 appear when I'm playing a game or when Spotify appears there?

If I recall correctly, Spotify takes priority on RPCs. Then RPCs appear in the order it was opened. If you go to your profile and click 'Activity', you should see the shadPS4 RPC along with every other application you have that is currently using RPCs.

**Comment by par274** [comment]
> If I recall correctly, Spotify takes priority on RPCs. Then RPCs appear in the order it was opened. If you go to your profile and click 'Activity', you should see the shadPS4 RPC along with every other application you have that is currently using RPCs.

Spotify isn't even open in the background. What I'm talking about there is "if there's a issue with me, why do Spotify and other games appear in Discord but ShadPS4 doesn't?"

**Comment by polybiusproxy** [comment]
Now that'd be weird. I don't have an answer to that, unfortunately. Would you be willing to do some debugging to find the cause?

**Comment by par274** [comment]
> Now that'd be weird. I don't have an answer to that, unfortunately. Would you be willing to do some debugging to find the cause?

Actually, if I knew C++, I would have a high chance of testing this. However, I should point out that this feature has not worked in any of the "main" builds since I opened this issue.

If you can tell me the methods, I would like to submit a report or log files on this issue.

**Comment by norichaomi-lgtm** [comment]
try launching shadps4 as admin, that fixed the problem for me. i was having the exact problem as you (shadps4 main, v0.10.0)

**Comment by par274** [comment]
> try launching shadps4 as admin, that fixed the problem for me. i was having the exact problem as you (shadps4 main, v0.10.0)

Bro, you are life saver. I saw your answer very late but it totally works.

<img width="357" height="157" alt="Image" src="https://github.com/user-attachments/assets/a7bea19b-8519-4551-a166-7ff5eeb6a04f" />
