### ISSUE TITLE
error while building (cmake --build build) on windows 11

### ISSUE THREAD

**Issue by FraxxDev** [shadps4-emu/shadPS4#1318]
$ cmake --build build
[25/771] Generating generated_fonts/imgui_fonts/notosansjp_regular.ttf.g.cpp
[43/771] Generating generated_fonts/imgui_fonts/proggyvector_regular.ttf.g.cpp
[638/771] Building CXX object CMakeFiles/shadps4...aries/save_data/dialog/savedatadialog_ui.cpp.obj
FAILED: CMakeFiles/shadps4.dir/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp.obj
C:\msys64\mingw64\bin\clang++.exe -DBOOST_ASIO_STANDALONE -DGLSLANG_IS_SHARED_LIBRARY=1 -DIMGUI_USER_CONFIG=\"imgui/imgui_config.h\" -DNOMINMAX -DNTDDI_VERSION=0x0A000006 -DTRACY_ENABLE -DTRACY_FIBERS -DTRACY_NO_CALLSTACK -DTRACY_NO_CODE_TRANSFER -DTRACY_NO_CONTEXT_SWITCH -DTRACY_NO_CRASH_HANDLER -DTRACY_NO_FRAME_IMAGE -DTRACY_NO_SAMPLING -DTRACY_NO_SYSTEM_TRACING -DTRACY_ONLY_LOCALHOST -DTRACY_ON_DEMAND -DWIN32_LEAN_AND_MEAN -DWINVER=0x0A00 -DZLIBNG_NATIVE_API -DZYCORE_STATIC_BUILD -DZYDIS_STATIC_BUILD -D_WIN32_WINNT=0x0A00 -IC:/msys64/home/Stefano/shadPS4/src -IC:/msys64/home/Stefano/shadPS4 -IC:/msys64/home/Stefano/shadPS4/build/src/video_core/host_shaders/include -IC:/msys64/home/Stefano/shadPS4/build/src/imgui/renderer/generated_fonts -isystem C:/msys64/home/Stefano/shadPS4/externals/magic_enum/include/magic_enum -isystem C:/msys64/home/Stefano/shadPS4/externals/fmt/include -isystem C:/msys64/home/Stefano/shadPS4/externals/toml11/include -isystem C:/msys64/home/Stefano/shadPS4/externals/robin-map/include -isystem C:/msys64/home/Stefano/shadPS4/externals/xbyak -isystem C:/msys64/home/Stefano/shadPS4/externals/tracy/public -isystem C:/msys64/home/Stefano/shadPS4/externals/./renderdoc -isystem C:/msys64/home/Stefano/shadPS4/externals/dear_imgui -isystem C:/msys64/home/Stefano/shadPS4/externals/gcn/include -isystem C:/msys64/home/Stefano/shadPS4/externals/ext-boost/libs/align/include -isystem C:/msys64/home/Stefano/shadPS4/externals/ext-boost -isystem C:/msys64/home/Stefano/shadPS4/externals/vma/include -isystem C:/msys64/home/Stefano/shadPS4/externals/sirit/src/../include -isystem C:/msys64/home/Stefano/shadPS4/externals/sirit/externals/SPIRV-Headers/include -isystem C:/msys64/home/Stefano/shadPS4/externals/vulkan-headers/include -isystem C:/msys64/home/Stefano/shadPS4/externals/xxhash -isystem C:/msys64/home/Stefano/shadPS4/externals/zydis/include -isystem C:/msys64/home/Stefano/shadPS4/build/externals/zydis -isystem C:/msys64/home/Stefano/shadPS4/externals/zydis/dependencies/zycore/include -isystem C:/msys64/home/Stefano/shadPS4/build/externals/zydis/zycore -isystem C:/msys64/home/Stefano/shadPS4/build/externals/sdl3/include -isystem C:/msys64/home/Stefano/shadPS4/externals/sdl3/include -isystem C:/msys64/home/Stefano/shadPS4/externals/pugixml/src -isystem C:/msys64/home/Stefano/shadPS4/externals/cryptopp -isystem C:/msys64/home/Stefano/shadPS4/externals -isystem C:/msys64/home/Stefano/shadPS4/build/externals/cryptopp -isystem C:/msys64/home/Stefano/shadPS4/build/externals/zlib-ng -isystem C:/msys64/home/Stefano/shadPS4/externals/zlib-ng -isystem C:/msys64/home/Stefano/shadPS4/externals/winpthreads/include -isystem C:/msys64/home/Stefano/shadPS4/externals/discord-rpc/include -O2 -march=native -O3 -DNDEBUG -std=gnu++23 -DHAVE_PTHREAD_MUTEX_TIMEDLOCK -Wno-error=unused-command-line-argument -MD -MT CMakeFiles/shadps4.dir/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp.obj -MF CMakeFiles\shadps4.dir\src\core\libraries\save_data\dialog\savedatadialog_ui.cpp.obj.d -o CMakeFiles/shadps4.dir/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp.obj -c C:/msys64/home/Stefano/shadPS4/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp
C:/msys64/home/Stefano/shadPS4/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp:102:54: error: no member named 'to_utc' in 'std::filesystem::__file_clock'
  102 |             auto utc_time = std::chrono::file_clock::to_utc(last_write);
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.
[655/771] Building CXX object CMakeFiles/shadps4.dir/src/core/libraries/videoout/driver.cpp.obj
ninja: build stopped: subcommand failed.

**Comment by DanielSvoboda** [comment]
Did you follow this step by step?
https://github.com/shadps4-emu/shadPS4/blob/main/documents/building-windows.md

I believe this part is missing:
3.Search and select `C++ Clang Compiler for Windows` and `MSBuild support for LLVM`

**Comment by GokanInferno** [comment]
Hi, I have the same problem just 5 minutes ago, and I installed both components in Visual Studio. Here is the code of MSYS2

CMake Warning (dev) at externals/pugixml/CMakeLists.txt:35 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_SHARED_LIBS'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at externals/discord-rpc/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at externals/discord-rpc/CMakeLists.txt:6 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_EXAMPLES'.
This warning is for project developers.  Use -Wno-dev to suppress it.

no rapidjson, download
-- Embedding font NotoSansJP-Regular.ttf
-- Embedding font ProggyVector-Regular.ttf
-- Configuring done (78.9s)
-- Generating done (0.4s)
-- Build files have been written to: C:/msys64/home/sebas/shadPS4/build

sebas@NucBeast11 MINGW64 ~/shadPS4
$ cmake --build build
[25/774] Generating generated_fonts/imgui_fonts/notosansjp_regular.ttf.g.cpp
[43/774] Generating generated_fonts/imgui_fonts/proggyvector_regular.ttf.g.cpp
[639/774] Building CXX object CMakeFiles/shadps4.dir/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp.obj
FAILED: CMakeFiles/shadps4.dir/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp.obj
C:\msys64\mingw64\bin\clang++.exe -DBOOST_ASIO_STANDALONE -DGLSLANG_IS_SHARED_LIBRARY=1 -DIMGUI_USER_CONFIG=\"imgui/imgui_config.h\" -DNOMINMAX -DNTDDI_VERSION=0x0A000006 -DTRACY_ENABLE -DTRACY_FIBERS -DTRACY_NO_CALLSTACK -DTRACY_NO_CODE_TRANSFER -DTRACY_NO_CONTEXT_SWITCH -DTRACY_NO_CRASH_HANDLER -DTRACY_NO_FRAME_IMAGE -DTRACY_NO_SAMPLING -DTRACY_NO_SYSTEM_TRACING -DTRACY_ONLY_LOCALHOST -DTRACY_ON_DEMAND -DWIN32_LEAN_AND_MEAN -DWINVER=0x0A00 -DZLIBNG_NATIVE_API -DZYCORE_STATIC_BUILD -DZYDIS_STATIC_BUILD -D_WIN32_WINNT=0x0A00 -IC:/msys64/home/sebas/shadPS4/src -IC:/msys64/home/sebas/shadPS4 -IC:/msys64/home/sebas/shadPS4/build/src/video_core/host_shaders/include -IC:/msys64/home/sebas/shadPS4/build/src/imgui/renderer/generated_fonts -isystem C:/msys64/home/sebas/shadPS4/externals/magic_enum/include/magic_enum -isystem C:/msys64/home/sebas/shadPS4/externals/fmt/include -isystem C:/msys64/home/sebas/shadPS4/externals/toml11/include -isystem C:/msys64/home/sebas/shadPS4/externals/robin-map/include -isystem C:/msys64/home/sebas/shadPS4/externals/xbyak -isystem C:/msys64/home/sebas/shadPS4/externals/tracy/public -isystem C:/msys64/home/sebas/shadPS4/externals/./renderdoc -isystem C:/msys64/home/sebas/shadPS4/externals/dear_imgui -isystem C:/msys64/home/sebas/shadPS4/externals/gcn/include -isystem C:/msys64/home/sebas/shadPS4/externals/ext-boost/libs/align/include -isystem C:/msys64/home/sebas/shadPS4/externals/ext-boost -isystem C:/msys64/home/sebas/shadPS4/externals/vma/include -isystem C:/msys64/home/sebas/shadPS4/externals/sirit/src/../include -isystem C:/msys64/home/sebas/shadPS4/externals/sirit/externals/SPIRV-Headers/include -isystem C:/msys64/home/sebas/shadPS4/externals/vulkan-headers/include -isystem C:/msys64/home/sebas/shadPS4/externals/xxhash -isystem C:/msys64/home/sebas/shadPS4/externals/zydis/include -isystem C:/msys64/home/sebas/shadPS4/build/externals/zydis -isystem C:/msys64/home/sebas/shadPS4/externals/zydis/dependencies/zycore/include -isystem C:/msys64/home/sebas/shadPS4/build/externals/zydis/zycore -isystem C:/msys64/home/sebas/shadPS4/build/externals/sdl3/include -isystem C:/msys64/home/sebas/shadPS4/externals/sdl3/include -isystem C:/msys64/home/sebas/shadPS4/externals/pugixml/src -isystem C:/msys64/home/sebas/shadPS4/externals/cryptopp -isystem C:/msys64/home/sebas/shadPS4/externals -isystem C:/msys64/home/sebas/shadPS4/build/externals/cryptopp -isystem C:/msys64/home/sebas/shadPS4/build/externals/zlib-ng -isystem C:/msys64/home/sebas/shadPS4/externals/zlib-ng -isystem C:/msys64/home/sebas/shadPS4/externals/winpthreads/include -isystem C:/msys64/home/sebas/shadPS4/externals/discord-rpc/include -O2 -march=native -O3 -DNDEBUG -std=gnu++23 -DHAVE_PTHREAD_MUTEX_TIMEDLOCK -Wno-error=unused-command-line-argument -MD -MT CMakeFiles/shadps4.dir/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp.obj -MF CMakeFiles\shadps4.dir\src\core\libraries\save_data\dialog\savedatadialog_ui.cpp.obj.d -o CMakeFiles/shadps4.dir/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp.obj -c C:/msys64/home/sebas/shadPS4/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp
C:/msys64/home/sebas/shadPS4/src/core/libraries/save_data/dialog/savedatadialog_ui.cpp:102:54: error: no member named 'to_utc' in 'std::filesystem::__file_clock'
  102 |             auto utc_time = std::chrono::file_clock::to_utc(last_write);
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.
[656/774] Building CXX object CMakeFiles/shadps4.dir/src/core/libraries/system/systemservice.cpp.obj
ninja: build stopped: subcommand failed.

**Comment by StevenMiller123** [comment]
@DanielSvoboda They're following option 2, the MSYS2 build guide. Your suggestion is from option 1, and does not relate to these issues.

This issue is valid, and has been brought up in the Discord before. Until a proper fix is merged, this should remain open.

**Comment by Hermiten** [comment]
This is fixed
