### ISSUE TITLE
Chromatic aberration not fixed even with patch

### ISSUE THREAD

**Issue by FraxxDev** [shadps4-emu/shadPS4#1321]
Not much to say
[shad_log.txt](https://github.com/user-attachments/files/17318829/shad_log.txt)

**Comment by DanielSvoboda** [comment]
Have you tested with version 0.3.1?
is the first 'Pre-Release': https://github.com/shadps4-emu/shadPS4/releases

**Comment by StevenMiller123** [comment]
This issue is not valid. Issues with patches belong in the patches repository, not here. https://github.com/shadps4-emu/ps4_cheats

**Comment by Hermiten** [comment]
Not much to say
