### ISSUE TITLE
Framerate suddenly drops randomly around 15 minutes in and permanently stays there

### ISSUE THREAD

**Issue by Wert5665** [shadps4-emu/shadPS4#1323]
Should mention I'm on an AMD 6650 XT 16GB of ram and a Ryzen 3700x. But I get through the beginning and when I operate the device to drop the ladder, FPS drops permanently, before I am running smoothly 50 to 60 fps, and I even tested the alternate intro where you kill the wolf with your bare hands and go to the dream on your own. When I did this, however the frame drop happened in the Hunters dream. 

Any help would be great, or if you didn't know of this issue, here ya go! Love the progress so far!

**Comment by Hermiten** [comment]
Incomplete issue. You can specify the game for example. And the emulator is in alpha stage, no games will have a constant FPS. 
Thanks for the report but I'm closing it because it has already been reported
