### ISSUE TITLE
Bug: Assertion Failed!

### ISSUE THREAD

**Issue by 9speeds** [shadps4-emu/shadPS4#1340]
Tested with the latest main build - (v0.3.0)
- Game : Bloodborne CUSA00900

**[Debug] <Critical> texture_cache.cpp:operator():224: Assertion Failed!**

This error happens randomly and very suddenly (can possibly crash the PC entirely)
is there a solution to this problem?
[shad_log.txt](https://github.com/user-attachments/files/17334630/shad_log.txt)

**Comment by Hermiten** [comment]
Please check on compatibility list and also on issues, This is a common error. 
I'm closing this one because not useful
