### ISSUE TITLE
Emulator freezes when using the fullscreen setting in Linux

### ISSUE THREAD

**Issue by robyn-dressler** [shadps4-emu/shadPS4#1348]
Environment: Linux / OpenSUSE Tumbleweed / X11 / Nvidia RTX 3080Ti

After turning on the Enable Fullscreen option in the configuration and starting the emulator, the screen completely freezes, and nothing gets drawn onto the screen. The program doesn't crash, so I had to kill the process manually. Moving windows across the screen glitches out like this:

![shadps4-fullscreen-bug](https://github.com/user-attachments/assets/fed35257-1817-4166-bb50-527b7cd06ee1)

I ran into this while trying to test a new feature for turning on fullscreen with an `-f` flag through the CLI, however this is reproducible through the normal TOML or GUI config as well.

Log:
[shad_log.txt](https://github.com/user-attachments/files/17348091/shad_log.txt)

**Comment by Hermiten** [comment]
Can you try again ? I will close this because no update since 1 month but normally this is fixed.
