### ISSUE TITLE
Empty Terminal/CMD window on launch, shadps4 does not open anymore.

### ISSUE THREAD

**Issue by Attila101** [shadps4-emu/shadPS4#1352]
shadps4 does not open at all, no matter which version, is there like some java or other dependency runtime im missing?

IT USED TO open pretty well, after a recent windows update, it did not anymore. i tried fixing, went to the extent of reinstalling windows altogether, yet nothing worked. this is a week ago problem thought maybe updates would fix, but maybe I'm missing something. I recently uninstalled a java package from my machine. maybe because of that it may have acted this way?

PLEASE Help. 

EDIT: Java app had nothing to do with this, still the same issue.

**Comment by DanielSvoboda** [comment]
Java is not used, only C++, if you are going to download something it should be this:
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by Attila101** [comment]
> Java is not used, only C++, if you are going to download something it should be this: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

I did try this, didnt fix it either.

**Comment by MMH2-O** [comment]
same problem and C++ doesn't fix it

**Comment by DanielSvoboda** [comment]
Try these steps, test one at a time

1.the link I had sent was for all versions, try installing this, which is only for the latest one
https://aka.ms/vs/17/release/vc_redist.x64.exe

2.Use the latest version of the emulator, in the link below, in pre-release,
click on the 'assets' arrow and download shadps4-win64-qt...
https://github.com/shadps4-emu/shadPS4/releases
make sure you have downloaded the QT version, it has an interface. The SDL version is command line only

3.Try running it as an administrator.

4.You can also try placing the emulator in another folder or another HD.

**Comment by Hermiten** [comment]
No answer

**Comment by abarguilas** [comment]
Did you find any solution?
