### ISSUE TITLE
Bloodborne Game drops from 60 fps (30 fps in the first video) to 12 after death (tried playing on 30 fps still the same issue)

### ISSUE THREAD

**Issue by NN3631** [shadps4-emu/shadPS4#1355]
As the title suggests, game drops from 60 fps to 12 after death. Tried removing the motion blur and chromatic patches it didn't work. Tried playing in 30 fps didn't work. Also this bug might or might not happen after death. It might happen for example while teleporting. I noticed that the bug also increases the ram usage after death (tried the mod ram spike workaround fix still doesn't work). Tried other versions of the emulator and still the same problem.
Other mods I used are Bloodborne PC SFX INTEL Fix Crashes with Effects - AMD modded SFX and vertex explosion fix
Current version I use is shadPS4 v0.3.1 WIP main b412cb4

Log for the first video:
[shad_log.txt](https://github.com/user-attachments/files/17350198/shad_log.txt)

https://github.com/user-attachments/assets/5bc7bb20-afb6-4568-af72-a7e270c2292a

another example on an older version (still the same problem, i don't have the log for it)

https://github.com/user-attachments/assets/cd446346-4542-41a8-9931-2d14215ca3bf

**Comment by NN3631** [comment]
Log for the first video: 
[shad_log.txt](https://github.com/user-attachments/files/17350196/shad_log.txt)

**Comment by par274** [comment]
This is a known issue. Bloodborne currently recommends 32GB of RAM. *Until this issue is resolved.

**Comment by NN3631** [comment]
> This is a known issue. Bloodborne currently recommends 32GB of RAM. *Until this issue is resolved.

Are you sure? Some people have 16 gb of ram and don't have this issue. Also I wanted to say that when loading in, this is what happens. FPS drops after loading in, not necessarily on death (could be when teleporting to a new area)

**Comment by par274** [comment]
> > This is a known issue. Bloodborne currently recommends 32GB of RAM. *Until this issue is resolved.
> 
> Are you sure? Some people have 16 gb of ram and don't have this issue. Also I wanted to say that when loading in, this is what happens. FPS drops after loading in, not necessarily on death (could be when teleporting to a new area)

Yes, if you enter the emulator's Discord server, many people suffer from this.

**Comment by NN3631** [comment]
> > > This is a known issue. Bloodborne currently recommends 32GB of RAM. *Until this issue is resolved.
> > 
> > 
> > Are you sure? Some people have 16 gb of ram and don't have this issue. Also I wanted to say that when loading in, this is what happens. FPS drops after loading in, not necessarily on death (could be when teleporting to a new area)
> 
> Yes, if you enter the emulator's Discord server, many people suffer from this.

Forgot to mention it happens every time I die meaning I have to restart the game every time I die. Sometimes it doesn't happen, but when it does it ruins the framerate for the entirety of the playthrough.

**Comment by purgea** [comment]
I have 16GB of RAM and this can occur during area transitions (the part where the game slows down probably due to shader compilation), but the chance of the whole game slowing down to like 12 fps permanently is quite low.

This seems to happen more often inside chalice dungeons

**Comment by par274** [comment]
> > > > This is a known issue. Bloodborne currently recommends 32GB of RAM. *Until this issue is resolved.
> > > 
> > > 
> > > Are you sure? Some people have 16 gb of ram and don't have this issue. Also I wanted to say that when loading in, this is what happens. FPS drops after loading in, not necessarily on death (could be when teleporting to a new area)
> > 
> > 
> > Yes, if you enter the emulator's Discord server, many people suffer from this.
> 
> Forgot to mention it happens every time I die meaning I have to restart the game every time I die. Sometimes it doesn't happen, but when it does it ruins the framerate for the entirety of the playthrough.

By the way, it's hard to play the game at 60 FPS right now. The emulator and physics are going crazy because it's not compatible with the patch. My advice is to play at 30 FPS.

https://github.com/shadps4-emu/shadPS4/issues/1226

**Comment by NN3631** [comment]
> > > > > This is a known issue. Bloodborne currently recommends 32GB of RAM. *Until this issue is resolved.
> > > > 
> > > > 
> > > > Are you sure? Some people have 16 gb of ram and don't have this issue. Also I wanted to say that when loading in, this is what happens. FPS drops after loading in, not necessarily on death (could be when teleporting to a new area)
> > > 
> > > 
> > > Yes, if you enter the emulator's Discord server, many people suffer from this.
> > 
> > 
> > Forgot to mention it happens every time I die meaning I have to restart the game every time I die. Sometimes it doesn't happen, but when it does it ruins the framerate for the entirety of the playthrough.
> 
> By the way, it's hard to play the game at 60 FPS right now. The emulator and physics are going crazy because it's not compatible with the patch. My advice is to play at 30 FPS.
> 
> #1226

Not like it fixes the bug (since I showed a vid in 30 fps with the same problem) but hey, might aswell play on 30 fps to not have any other bugs happen

**Comment by Hermiten** [comment]
Hello, already reported on GitHub and discord. Thanks for this. They work on it
