### ISSUE TITLE
Why is shader compiled every time?

### ISSUE THREAD

**Issue by par274** [shadps4-emu/shadPS4#1360]
I don't know how the emulator works, but why does the shader have to be compiled from scratch for each entry?

In all other emulators, the shader is saved to disk after being compiled, and nothing seen in the second entry will cause a freeze.

For example, as I showed in the video, normally you should experience momentary freezes only once, but doesn't compiling shaders every time you enter put more load on RAM than necessary?

https://www.youtube.com/watch?v=u_O1QONN3Lc

**Comment by birthtothunder** [comment]
There's no shader cache.

**Comment by par274** [comment]
> There's no shader cache.

Yes, I noticed that. I think it's a most important thing.

**Comment by cuesta4** [comment]
Sometimes shader cache will mask problems and make it difficult to see if they've been solved. It's something usually reserved for when emulators are at a more mature state, and the highest priority becomes quality of life features.  

Right now it's better to compile the shaders everytime, so we can quickly identify fixes and regressions.

**Comment by wojek07** [comment]
However, will such feature be actually needed at some point in future? If so then, it makes sense to implement this and just disable it by default.

**Comment by par274** [comment]
> Sometimes shader cache will mask problems and make it difficult to see if they've been solved. It's something usually reserved for when emulators are at a more mature state, and the highest priority becomes quality of life features.
> 
> Right now it's better to compile the shaders everytime, so we can quickly identify fixes and regressions.

There are still memory leak problems at the moment, can we say that this is the cause? If so, there may be an option to disable cache, but this feature needs to be there.

> However, will such feature be actually needed at some point in future? If so then, it makes sense to implement this and just disable it by default.

Yeah, I'm on the same point as you.

**Comment by rafael-57** [comment]
The emulator is very early in progress, the way shaders are handled changes very frequently with nightly builds. There are other things to do before implementing a shader cache

**Comment by Beworgen** [comment]
Can you make the shader compiler a option so that only people that update the games compatibility need to disable it and it will show if it is disabled or not in the log?
