### ISSUE TITLE
[Feature Request] Compile-time option to disable auto-updater

### ISSUE THREAD

**Issue by OPNA2608** [shadps4-emu/shadPS4#1368]
Having an auto-updater is a good convenience feature for users of the upstream binaries, but it should be able to disable the functionality in setups where an update is i.e. a package manager's responsibility.

![image](https://github.com/user-attachments/assets/dc84b66e-f727-4fa7-9fba-c3c43fb5a6aa)

```
Starting Update...
Archive:  /home/puna/.local/share/shadPS4/temp_download_update/temp_download_update.zip
  inflating: /home/puna/.local/share/shadPS4/temp_download_update/Shadps4-qt.AppImage  
Could not start dynamically linked executable: ./Shadps4-qt.AppImage
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

**Comment by Hermiten** [comment]
@DanielSvoboda maybe ?

**Comment by DanielSvoboda** [comment]
If the point of this issue was to disable autoUpdater in compilation, then it can already be closed, as it was implemented in this PR https://github.com/shadps4-emu/shadPS4/pull/1490
