### ISSUE TITLE
GFD Engine games enter a weird softlock state due to GPU Buffer Cache stuff

### ISSUE THREAD

**Issue by Da-nu** [shadps4-emu/shadPS4#1373]
My earlier issue (#590 ) mentioned this softlock when I first discovered it in P5D and thinking its only an issue there. As more GFD games started running, the softlock happened in all of them. ShadPS4 logs don't seem to show anything about whats causing them. 
The earlier issue was focused on P5D, but I made this new one for GFD games in general.

**Comment by polybiusproxy** [comment]
This appears to be present in all GFD Engine games.
The game gets on a loop reading the same file offset on the CriWare filesystem thread, over and over again. I suspect the cause is deep within the emulator's threading emulation.

I must also add that this issue apparently was not present in older versions, so this appears to be some sort of regression.

**Comment by Da-nu** [comment]
I would like to note the issue seems to be more common when in PS4 Pro mode.

**Comment by polybiusproxy** [comment]
I don't think PS4 Pro mode would do something, considering all it does is mostly raise the maximum of available memory to the game.
What you experienced is most likely a race condition which would check out with what there's reported already, that makes me more confident that this is a threading issue.

**Comment by Da-nu** [comment]
The cause of the issue has been found and there are 2 working workarounds. One of them is Linux only and breaks sound and the other seems to be multiplatform. Both lead to some sort of slowdown in performance. Poly is free to give a more in-depth explanation of what's happening because I am not the best at explaining how this issue works.

**Comment by Da-nu** [comment]
https://github.com/shadps4-emu/shadPS4/pull/1726 appears to have fixed this. Someone has confirmed to have P3D and P5 running. I will test P4D, P5D, and P5R later to confirm.

**Comment by Da-nu** [comment]
Can confirm it just works now. The framerate issues seem unrelated to this and P5R has some extra issues unrelated to this.
