### ISSUE TITLE
bloodborne does not start and crashes without it loading anything

### ISSUE THREAD

**Issue by KabelCZ** [shadps4-emu/shadPS4#1374]
Everytime i try to turn on bloodborne it just crashes can someone help please?
[shad_log.txt](https://github.com/user-attachments/files/17365461/shad_log.txt)

**Comment by BulkyMonkey** [comment]
Did you make sure your game Pkg and update Pkg have the same TITLE_ID and that it says (Fake) at the bottom left when viewing in PS4 package viewer. An older thread said this error is from an invalid game dump

**Comment by StevenMiller123** [comment]
Your game dump is missing important files. You need to redump your game. 

Also, support requests belong in the shadPS4 discord, not here.
