### ISSUE TITLE
Mouse activity limits camera movement when using game controller

### ISSUE THREAD

**Issue by markomaniax** [shadps4-emu/shadPS4#1377]
Hi guys,
Just updated to the newest patch and when I enter the game my right thumbstick has limited movement probably due to mouse controls enablement.  Im using xbox one controller which worked perfectly until latest update.
edit: The game in question is Bloodborne.

So please address this asap with mouse/keyboard controls toggle, either trough hotkey or option in controller settings in emulator. It is a bit frustrating you adding this option without toggle option.

**Comment by Solomonoff68** [comment]
The same problem

**Comment by kalaposfos13** [comment]
I'm guessing you talk about my pull request:
https://github.com/shadps4-emu/shadPS4/pull/1356
If that is the case, you can find its hotkeys in the comments, but I'll write it to here too:
F9: toggle mouse capture (hides mouse and confines it to the window)
F8: Reparse the keyboardInputConfig.ini file to change keybinds even ingame
F7: toggle mouse movement input (this is what you're after)

**Comment by markomaniax** [comment]
Yup, F7 solved the issue. Tnx

**Comment by Solomonoff68** [comment]
> Я предполагаю, что вы говорите о моем запросе на извлечение: #1356 Если это так, то вы можете найти горячие клавиши в комментариях, но я напишу их и здесь: F9: переключение захвата мыши (скрывает мышь и ограничивает её перемещение окном) F8: повторная обработка файла keyboardInputConfig.ini для изменения сочетаний клавиш даже в игре F7: переключение ввода с помощью мыши (это то, что вам нужно)

Tnx

**Comment by kalaposfos13** [comment]
Just a quick note: I updated my fork, so from now on, mouse movement input is off by default

**Comment by polybiusproxy** [comment]
Closing as this is an issue to an unmerged pull request.
