### ISSUE TITLE
With v0.3.1 WIP (09725bd) CUSA03806 boots

### ISSUE THREAD

**Issue by dajmodajmo** [shadps4-emu/shadPS4#1379]
Sherlock Holmes -The Devils Daughter boots and goes to "press X" but freezes there after :)

**Comment by polybiusproxy** [comment]
Please provide a log

**Comment by dajmodajmo** [comment]
[shad_log.txt](https://github.com/user-attachments/files/17381124/shad_log.txt)
log file now provided..

**Comment by StevenMiller123** [comment]
@dajmodajmo 
Firstly, your firmware libraries are encrypted. I'd suggest redumping them. 
Second, compatibility reports belong in the shadPS4 compatibility repo. If you can reproduce the game's progress on v0.3.0 with working firmware modules, then I would suggest reposting this there. If the game only works on the WIP builds, I'd suggest waiting until v0.4.0, then reporting this in the compatibility repo.
