### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "" Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LUser-12** [shadps4-emu/shadPS4#1382]
Hello So when i installed the latest linux qt main branch i get segmentation error and then i installed a older one and now i get this error
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
Segmentation fault (core dumped)
```
but before i get this error it pops up a page that asks me where my Game will be stored then i confirm and it crashes and never comes again

Software information : arch linux

**Comment by ngoquang2708** [comment]
Ignore the old build as it will not get supported. Are you running latest pre-release version? Provide more detailed info about your OS, DE, X11 or Wayland...

**Comment by Link4Electronics** [comment]
I had the same problem, I posted a temporary solution here #1361

Use `QT_QPA_PLATFORM=xcb ./Shadps4-qt.AppImage`

**Comment by ghost** [comment]
> I had the same problem, I posted a temporary solution here #1361
> 
> Use `QT_QPA_PLATFORM=xcb ./Shadps4-qt.AppImage`

Can confirm, I can launch the AppImage on GNOME/Wayland with this. Thanks @Link4Electronics

**Comment by Link4Electronics** [comment]
The current [Pre-release-shadPS4-2024-11-10-7ab8515](https://github.com/shadps4-emu/shadPS4/releases/tag/Pre-release-shadPS4-2024-11-10-7ab8515) doesn't have this problem, no need to use the `QT_QPA_PLATFORM=xcb` anymore.
