### ISSUE TITLE
The problem of playing Bloodborne on Intel A770 graphics card

### ISSUE THREAD

**Issue by ouco1986** [shadps4-emu/shadPS4#1385]
Please save the users of Intel graphics cards, big shot. Playing Bloodborne can add the comment 'assert (adjust% fmt_ride==0)', but it will cause crazy screen flickering and vertex explosion.
![38fcf704c1f74fc6057e2555d7c850f](https://github.com/user-attachments/assets/91f48590-a2e5-4475-b194-34e98836c5fc)
![211b80b4bfaccca7a200dcb9762f4bb](https://github.com/user-attachments/assets/3fe5205e-5e20-4b10-b637-e28381a48fbf)
![c6fd7c6936c3fb302b32fd75582fb17](https://github.com/user-attachments/assets/ddfc97cb-8e89-4952-9074-b6c0c2aaee30)
![1e255f535310b29ba27dedde0666c89](https://github.com/user-attachments/assets/42a976d3-1a50-47b9-bbb3-5c7f82c1b6f2)

**Comment by StevenMiller123** [comment]
This issue is known about, and will be worked on eventually. Just be patient and wait for updates.

**Comment by hgh32** [comment]
https://github.com/shadps4-emu/shadPS4/blob/8b2c151f1f381d80717386045da9db3585810b31/src/video_core/renderer_vulkan/vk_pipeline_common.cpp#L113
Or you can also let offset_aligned = offset
This will alleviate these graphics issues
Then you can use some fix mod or try to remove mtd, drawparam, sfx to make it further
