### ISSUE TITLE
BB crahes on startup win10

### ISSUE THREAD

**Issue by TRuslan3301** [shadps4-emu/shadPS4#1389]
Hey guys, i followed this guide step by step https://shadps4.org/#shadPS4-quickstart-prerequisites 
When I try to run the game emulator just closes, the log file (shad_log.txt) is empty, I managed to copy the data that were in the console before closing, its look normal to me, idk maybe im missing something. 
[log.txt](https://github.com/user-attachments/files/17383434/log.txt)

my specs: 
os - win10
cpu - R5 5600
gpu - 4070 super
ram - ddr4 32gb

I'd be happy if you could help me.

**Comment by polybiusproxy** [comment]
The linked website is \***not\*** official. Our official website is https://shadps4.net/
That said, this is not the place for support, so please feel free to join our Discord server to receive help.
