### ISSUE TITLE
user folder does not generate on linux

### ISSUE THREAD

**Issue by thethunderturner** [shadps4-emu/shadPS4#1398]
As the title suggests, the `user` folder doesn't generate when opening the appimage, or the executable built from source code. This issue appears from the last release (3.0.0) until the latest version (3.0.1). I only got a folder the first ever time I installed shadps4 on my computer. After that, future installations of shadps4 on different folders, wouldn't generate user folders inside the folder where the appimage is or inside the build folder. Am I missing something or is this a bug?

Thanks

**Comment by ngoquang2708** [comment]
It is changed to standard location ```/home/$USER/.local/share/shadPS4```.

**Comment by thethunderturner** [comment]
> It is changed to standard location `/home/$USER/.local/share/shadPS4`.

Thank you
