### ISSUE TITLE
Hey, can you fix lsd colours on AMD GPUs also please?

### ISSUE THREAD

**Issue by hopediedie** [shadps4-emu/shadPS4#1401]
Hey, can you fix lsd colours on AMD GPUs also please? Im using RX 590 series and there is the guys with new video cards with the same issue(

_Originally posted by @hopediedie in https://github.com/shadps4-emu/shadPS4/discussions/1400_

**Comment by Hermiten** [comment]
I'm closing this one. 
This is a incomplete issue, no game, no OS, no log, no screen. Nothing to know what's about

**Comment by hopediedie** [comment]
> I'm closing this one. This is a incomplete issue, no game, no OS, no log, no screen. Nothing to know what's about

Better close your extra chromosome

**Comment by Hermiten** [comment]
Stay on your negativity, I don't care I have no problem with the emulator, it's you ☺️
