### ISSUE TITLE
update killed the game opening 

### ISSUE THREAD

**Issue by examed2k** [shadps4-emu/shadPS4#1406]
before last update worked flawless 10/18/2024 latest one doesn't even open the game blood borne any more just sits on a black screen but i can go to release version works right away

**Comment by ngoquang2708** [comment]
Logs?

**Comment by Deathedit** [comment]
> Logs?

red dead also stuck on load

[shad_log.txt](https://github.com/user-attachments/files/17437110/shad_log.txt)

**Comment by ngoquang2708** [comment]
Please test this PR: https://github.com/shadps4-emu/shadPS4/pull/1408.

**Comment by ngoquang2708** [comment]
Fixed by https://github.com/shadps4-emu/shadPS4/pull/1408.
