### ISSUE TITLE
Colors everywhere 

### ISSUE THREAD

**Issue by hopediedie** [shadps4-emu/shadPS4#1411]
Any tips? 
![photo_2024-10-18_22-06-32](https://github.com/user-attachments/assets/d9cb4606-8b82-461a-b35f-a07e0021cbc0)
![photo_2024-10-18_22-09-25](https://github.com/user-attachments/assets/30233fb0-7832-4bb1-adfe-5ac452c70b2e)

Latest version of everything 
Using RX 590 GPU with 60 stable FPS 

The only thing that helps you is to delete files by route   \CUSA03173\dvdroot_ps4\param\gameparam

But it's not a solution, so as the lighting completely disappears  and the atmosphere dies... 

Help, please(

**Comment by FabioRiAmaral** [comment]
![image](https://github.com/user-attachments/assets/b993b5f4-6162-4a5e-9fcf-c1e10c4588de)

**Comment by StevenMiller123** [comment]
This is a known problem that likely isn't getting fixed anytime soon.

**Comment by hopediedie** [comment]
> This is a known problem that likely isn't getting fixed anytime soon.

Still, it's not a solution. Graphic looks awful, atmosphere is lost(

**Comment by hopediedie** [comment]
> This is a known problem that likely isn't getting fixed anytime soon.

Badly :(

**Comment by raphaelthegreat** [comment]
> > This is a known problem that likely isn't getting fixed anytime soon.
> 
> Still, it's not a solution. Graphic looks awful, atmosphere is lost(

These glitches are caused by buggy vulkan implementation on polaris GPUs, the emulator isn't responsible for that nor is it wise to spend a significant amount of time debugging and working around these at this point in time. Its probably better to play with your PS4
