### ISSUE TITLE
[Feature Request] AMD Overlay support

### ISSUE THREAD

**Issue by par274** [shadps4-emu/shadPS4#1422]
If the game being played is recognized at the driver level, we can use features such as low latency, AFMF2.

**Comment by Gentleman2292** [comment]
> If the game being played is recognized at the driver level, we can use features such as low latency, AFMF2.

you can do that yourself by manually adding shadps4 .exe file to radeon software
![image](https://github.com/user-attachments/assets/3fd4b119-d31d-4426-a11c-88e8e58b77be)

**Comment by par274** [comment]
Yes but Radeon software did not recognized game. When you do this, it sees the emulator interface, not the game, so AFMF2 cannot be turned on.
