### ISSUE TITLE
unable to open the file for writting patches

### ISSUE THREAD

**Issue by Pyryte** [shadps4-emu/shadPS4#1425]
when i wanted to save the patches it's written that and it don't work
![image](https://github.com/user-attachments/assets/ef2c1e1e-3bbb-4c1a-9133-4bef8be20be5)

**Comment by DanielSvoboda** [comment]
Which folder is your emulator in? Does it have any different characters?
Did you happen to have the patch files open?

Try again running as administrator
Are you using any antivirus? It may be preventing you from saving this file

**Comment by Pyryte** [comment]
Hi i succeed to fix it you have to launch shad ps4 as administrator
