### ISSUE TITLE
Bloodborne - Frames drop to 13 Fps

### ISSUE THREAD

**Issue by IZekyh** [shadps4-emu/shadPS4#1430]
My game just get stuck on 13 fps on map transition sometimes get a sttutering and the game just crash and to fix the lag i have to restart the game because even when i go to menu the game continues on 13 fps, this problem occurs in a few minutes after the load game...
I also notice that when this happens my player get a bug on his hitbox and enemies too, and when i broke something around they fly around my character, here are somes videos to show what actualy are happens.

https://github.com/user-attachments/assets/836f1ecc-3ffb-4594-8e38-a558efc3735f

https://github.com/user-attachments/assets/d0a09876-f9ad-4fbc-a83d-7d5a8f0e5582

My setup: Ryzen 5 2600, 16GB RAM, RX 580 8GB
I'm using some mods like SFX Restoration, and i have deleted the drawparam, because of the lsd problem on AMD Polaris and i'm using reshade to work around the problem with graphics for now, my game when there is no problem runs at 60~48 fps

**Comment by IAmBatby** [comment]
This issue will probably end up being closed as unrelated unless there's supporting evidence that this occurs without the 60fps patch

**Comment by IZekyh** [comment]
@IAmBatby Well, i've tested without the 60fps patch and i notice that the field around the character was gone, but my fps still in 13 without recording, then i decide to record one playthroug recording without the 60fps patch and that was the result:

https://github.com/user-attachments/assets/94620a84-81e6-4da0-8fc9-b31161863d2a


https://github.com/user-attachments/assets/a761325e-9997-478b-8efe-aaca63ad23f3


https://github.com/user-attachments/assets/f905d62b-3896-4cb5-9bac-db7259e84347


https://github.com/user-attachments/assets/86cd0089-4208-4a4b-8806-f0ac683fee1d

It have to be apart because of the size limit.
After that i tried again and the game was barely starting after load, then i was able to play again and another crash in less than 40 seconds

https://github.com/user-attachments/assets/6a1ede64-69a4-40f8-a6e8-d2c6a33e5f35

https://github.com/user-attachments/assets/7d5b54d1-bd13-43e5-81d3-87eee2bc9b1d

But you can see that the game runs at less than 30 fps recording and without the 60fps patch stay at 10fps recording when reach certains regions, sometimes the fps return at normal when has a trasition map but also has a sttutering and sometimes crashs :(

**Comment by Scaronz** [comment]
I have a Ryzen 5 5500 32gb of ram and an RX 5700 8gb i get this issue too

**Comment by IZekyh** [comment]
@Scaronz I've decided to just wait some more because there no way to play right now with this issue happens every single moment.

**Comment by Scaronz** [comment]
@IZekyh Yes it's unplayeble like this i think its an amd related issue we gotta wait for the fix

**Comment by Scaronz** [comment]
Any response from the devs about this ?

**Comment by IZekyh** [comment]
@Scaronz No, i just closed it due to lack of responses, but i'll reopen until a devs closes again.

**Comment by polybiusproxy** [comment]
I don't find this to be an actual issue from the emulator's side. It could be your specs, as well as the available memory, etc. If you were to ask me, I'd say your GPU is at fault here (especially considering it's an AMD GPU).

**Comment by IZekyh** [comment]
@polybiusproxy I think that is equivocate put the blame on a GPU AMD side since there only 3 of them (where intel is new at GPU market) left only 2 (AMD and Nvidia) and since my GPU isn't new, almost every game, despite the newest, runs at 50~60 fps at 1080p, i know emulation requires more of the CPU and GPU as well the RAM, but i've 16GB RAM it is problaly the minimum require to run perfectly the emulator, and on the videos i've send the ram don't pass 13GB on total and i'm not the only one with this problem
![image](https://github.com/user-attachments/assets/faee8f46-5823-469f-be18-f519662318dc)
Here a screenshot of my AMD Adrenalin where show the average fps where you can see that even newest games like Death strading runs at a average fps of 71

**Comment by polybiusproxy** [comment]
I don't think that's a good comparison. Remember we're emulating a GPU here, while PC games use things like DirectX and Vulkan for an abstraction between the game and the GPU driver.

That said, since what we're doing is GPU emulation, stability might not always be the best, especially with, as I mentioned earlier, AMD GPUs. Bloodborne has issues with AMD GPUs--this has been reported several times, for example, with lots of textures being rainbow-colored on Polaris GPUs, therefore I believe it's correct to assume your GPU is to blame in this situation.

**Comment by gnusenpai** [comment]
I'm on NVIDIA with the same set of issues. I might be running out of VRAM, but if so, it's not obvious looking at the GPU stats.

**Comment by IZekyh** [comment]
@polybiusproxy Alright this can be true, i was thinking in a upgrade on general to my setup and to a the newest GPU card, but AMD for sure, so... I hope that the experience of playing bloodborne in the future be more fluid when the time comes, but for now i can't upgrade it and give a try to my gpu anyway.

**Comment by polybiusproxy** [comment]
Emulators mature as time passes, so I think it's safe to assume these will get fixed. As of when, that's a hard question to answer.

**Comment by Jdiablo** [comment]
It's been pretty since the ticket was opened, but I made a simple trick for this issue myself: I made a custom software that just closes shadPS4.exe and restart it immediately loading Bloodborne on LS+RS xbox controller keys. I think the issue is about memory leakage and restarting the game does help.

Considering the issue occurs after death\changing location, the whole process takes about 10 seconds on my SSD and doesn't impact experience that much (I just press LS+RS immediately after death\teleportation when I see the loading screen, so the whole time for restarting the game is almost about the same as the loading screen)

I can make a github project if anyone would like to try this approach as me

**Comment by IZekyh** [comment]
@Jdiablo Since the problem was occuring i just wait some updates and today the game run at 40~60 fps depending on the scenario and have some stutters after go to a new location, but don't get stuck at 13 anymore, the only problem that happens since that day is a stuttering that sometimes all my PC stop working, and the game crashs or return to normal as nothing was happening, it is hard to capture since isn't consitent

**Comment by XRolandX** [comment]
raising padding file doesnt fix the problem. did anyone fix the issue
