### ISSUE TITLE
I can't start The Last Of Us Part II

### ISSUE THREAD

**Issue by RandomGuy35** [shadps4-emu/shadPS4#1437]
![image](https://github.com/user-attachments/assets/91f86272-3dcb-4cea-b164-ddb80c75063a)
How can I fix it?

_Originally posted by @RandomGuy35 in https://github.com/shadps4-emu/shadPS4/discussions/1435_

**Comment by polybiusproxy** [comment]
The game you're trying to open does not work at this moment.
