### ISSUE TITLE
Unable to build QT in Linux due to missing 'discord_rcp.h' even with -DENABLE_DISCORD_RPC=OFF

### ISSUE THREAD

**Issue by paljardine** [shadps4-emu/shadPS4#1443]
![image](https://github.com/user-attachments/assets/8368c087-9881-4cd3-9eb8-3d9784ecc143)

OS: Fedora Linux 40 (KDE Plasma) x86_64 
Kernel: 6.11.4-201.fc40.x86_64 

It seems like discord_rpc_handler.h is unable to find 'discord_rpc.h'. Adding ifdefs for ENABLE_DISCORD_RPC to the following files allows the build to proceed:

discord_rpc_handler.h
![image](https://github.com/user-attachments/assets/76ccf1ae-ebed-466a-912a-26f141288203)

emulator.cpp 
![image](https://github.com/user-attachments/assets/2c15da42-5823-479a-8d71-ad8b0817a84d)

main_window.cpp
![image](https://github.com/user-attachments/assets/00fb76d5-bb8f-4fed-b4a2-65af6860cca3)

settings_dialog.cpp
![image](https://github.com/user-attachments/assets/97ac2305-f20f-4b8e-838e-4d1185177117)

There should be a way to get discord_rpc_handler to properly include discord_rpc.h, but this works as quick hack.

**Comment by gandalth** [comment]
I confirm, I have the same issue.
I am building on "Debian Testing" with kernel 6.11 and I am using clang19. I also used -DENABLE_DISCORD_RPC=OFF.

When adding -DENABLE_QT_GUI=OFF I can successfully build the project.

**Comment by Hermiten** [comment]
Hey maybe for you @delledev or @abouvier ? Thanks you :)

**Comment by aaalloc** [comment]
some ifdef where missing
PR ready #1551

Edit: PR merged, issue should be closed
