### ISSUE TITLE
[NOT ACTUALLY AN ISSUE] [PACKAGING RELATED] FYI Getting this on the "AM/AppMan" PKG manager

### ISSUE THREAD

**Issue by Twig6943** [shadps4-emu/shadPS4#1455]
https://github.com/ivan-hc/AM/issues/1042

**Comment by Samueru-sama** [comment]
Btw please [don't zip AppImages](https://docs.appimage.org/packaging-guide/distribution.html#do-not-put-appimages-into-other-archives), they are already compressed and breaks delta updates with appimageupdatetool.

**Comment by Twig6943** [comment]
The pkg on am isnt zipped, is it?
