### ISSUE TITLE
Games stop loading....

### ISSUE THREAD

**Issue by jvhellraiser** [shadps4-emu/shadPS4#1464]
latest update of shadPS4 stop loading games, not sure what happen cause last night they were loading just fine
so i am a bit confuse about whats going on did something change? or is a bug anyway i have a i have a I7 with Nvidia 4060ti
16 gb of memory games try to load Gravity Rush remake stop loading,dead cells, Sonic generations etc ShadPs4 does nothing..
![Screenshot 2024-10-31 104836](https://github.com/user-attachments/assets/11df38e1-5177-476d-ab3b-fdc551962d29)

Build is ShadPs4 v0.3.1 WIP main cdae6a4

**Comment by polybiusproxy** [comment]
Fixed now, please retest.

**Comment by jvhellraiser** [comment]
> Fixed now, please retest.

They work now but i get corrupted save data on dead cells on latest main build 7b16085.
![Screenshot 2024-10-31 181932](https://github.com/user-attachments/assets/6d32bc4d-b5c3-4361-9741-550db5575007)
