### ISSUE TITLE
ShadPS4 crashes on Windows at the start of every game

### ISSUE THREAD

**Issue by MikeDeltaHH** [shadps4-emu/shadPS4#1470]
Hi there!

Up to version 0.2.0 I had no problems, I installed Sonic Mania for testing but every version after that (currently 0.4.1) causes ShadPS4 to crash completely after starting every game (deleting and reinstalling the emulator & a game did nothing) - this is also logged in the Windows Event Viewer:

-----------------------------------------------------------------------------------------------
Name of the faulty application: shadPS4.exe, version: 0.0.0.0, timestamp: 0x6724cae2
Name of the faulty module: shadPS4.exe, version: 0.0.0.0, timestamp: 0x6724cae2
Exception code: 0xc0000005
Fehleroffset: 0x00000000006ce443
ID of the faulty process: 0x0x5824
Start time of the faulty application: 0x0x1DB2C916192B933
Path of the faulty application: D:\RetroBat\emulators\shadPS4\shadPS4.exe
Path of the faulty module: D:\RetroBat\emulators\shadPS4\shadPS4.exe
Berichtskennung: 5e1a21a2-8525-4186-90a8-3ca8d0bc50ba
Full name of the faulty package: 
Application ID that is relative to the faulty package:
-----------------------------------------------------------------------------------------------

Log attached, I'm at a loss and would really appreciate some help.
Many thanks for ShadPS4!

[shad_log.txt](https://github.com/user-attachments/files/17603378/shad_log.txt)

**Comment by DanielSvoboda** [comment]
Your video card seems to be outdated, you'd better upgrade it.
What's your CPU?

**Comment by StevenMiller123** [comment]
I mean, if they had no issues on earlier shad versions, the CPU shouldn't be relevant. I wish I could provide some actually helpful information, but their log doesn't seem to show anything critical.

**Comment by MikeDeltaHH** [comment]
> Your video card seems to be outdated, you'd better upgrade it. What's your CPU?

I have a GeForce GTX 4070 Ti OC, ASUS TUF Gaming Z790-BTF Motherboard, Intel Core i5-13600KF CPU & DDR5 RAM - not exactly old but thanks for reply!

**Comment by StevenMiller123** [comment]
I think they were referring to the graphics driver

**Comment by MikeDeltaHH** [comment]
> I mean, if they had no issues on earlier shad versions, the CPU shouldn't be relevant. I wish I could provide some actually helpful information, but their log doesn't seem to show anything critical.

Yes, I have already tested everything possible - deleted everything, re-downloaded ShadPS4, redid everything in a different directory, all without success... I just don't understand it...

**Comment by MikeDeltaHH** [comment]
> I think they were referring to the graphics driver

The latest NVidia driver 566.03 is installed, which is what I first suspected...

**Comment by adikusnadi8** [comment]
me to.. how fix problem
thanks
attach : 
![Tanpa judul](https://github.com/user-attachments/assets/c3bcefe9-e482-4a1a-94a6-df7814251f50)
rtx 3070
proc i5 14600k

**Comment by DanielSvoboda** [comment]
what might help:
install this: https://aka.ms/vs/17/release/vc_redist.x64.exe
run as administrator
try running the emulator from another folder, perhaps leaving the games on the same drive

**Comment by MikeDeltaHH** [comment]
> what might help: install this: https://aka.ms/vs/17/release/vc_redist.x64.exe run as administrator try running the emulator from another folder, perhaps leaving the games on the same drive

Hey @DanielSvoboda 
Thank you very much for your support and your work on ShadPS4. I have tried all the solutions, unfortunately without success. Then downloaded version 0.2.0 again - this version runs without any problems, all subsequent versions simply close when a game is started... I'm at my wit's end...

**Comment by NextdoorPsycho** [comment]
if it means anything im also having this issue, Windows 11, 4090, 9900x, all updated to everything

**Comment by MikeDeltaHH** [comment]
> if it means anything im also having this issue, Windows 11, 4090, 9900x, all updated to everything

System and graphics card drivers are up to date, unfortunately it makes no difference.

**Comment by Crasthiff** [comment]
facing the same issue here, r5 5600, rx470 moded drivers (same issue with stock), any fix?

**Comment by Darkcranio95** [comment]
Same issue, tried 2 games, both crash on startup. Newest Nvidia driver, newest Visual CC installed, sys libraries in the proper folder.
[shad_log.txt](https://github.com/user-attachments/files/17902414/shad_log.txt)
[shad_log.txt](https://github.com/user-attachments/files/17902479/shad_log.txt)


SHAD Build: 11.25
R5 3600
RTX 2060

**Comment by Hermiten** [comment]
> Same issue, tried 2 games, both crash on startup. Newest Nvidia driver, newest Visual CC installed, sys libraries in the proper folder. [shad_log.txt](https://github.com/user-attachments/files/17902414/shad_log.txt) [shad_log.txt](https://github.com/user-attachments/files/17902479/shad_log.txt)
> 
> SHAD Build: 11.25 R5 3600 RTX 2060

It's the same game for yours 2 logs (Disney Infinity)
Some games are not working. 
You Can check every tested games here: https://github.com/shadps4-emu/shadps4-game-compatibility
And add this one on it (because not tested). This is on the issue tab

**Comment by Hermiten** [comment]
> Hi there!
> 
> Up to version 0.2.0 I had no problems, I installed Sonic Mania for testing but every version after that (currently 0.4.1) causes ShadPS4 to crash completely after starting every game (deleting and reinstalling the emulator & a game did nothing) - this is also logged in the Windows Event Viewer:
> 
> ## Name of the faulty application: shadPS4.exe, version: 0.0.0.0, timestamp: 0x6724cae2
> Name of the faulty module: shadPS4.exe, version: 0.0.0.0, timestamp: 0x6724cae2
> Exception code: 0xc0000005
> Fehleroffset: 0x00000000006ce443
> ID of the faulty process: 0x0x5824
> Start time of the faulty application: 0x0x1DB2C916192B933
> Path of the faulty application: D:\RetroBat\emulators\shadPS4\shadPS4.exe
> Path of the faulty module: D:\RetroBat\emulators\shadPS4\shadPS4.exe
> Berichtskennung: 5e1a21a2-8525-4186-90a8-3ca8d0bc50ba
> Full name of the faulty package:
> Application ID that is relative to the faulty package:
> Log attached, I'm at a loss and would really appreciate some help. Many thanks for ShadPS4!
> 
> [shad_log.txt](https://github.com/user-attachments/files/17603378/shad_log.txt)

Someone tested it with the last version and ho in-game. Can you try to update shadps4 and test again ?

It's a common problem. Your game simply cannot run on some version. You need to check here:
https://github.com/shadps4-emu/shadps4-game-compatibility

There is a regression maybe between some version but the last one seems to fix it

**Comment by Darkcranio95** [comment]
> > Same issue, tried 2 games, both crash on startup. Newest Nvidia driver, newest Visual CC installed, sys libraries in the proper folder. [shad_log.txt](https://github.com/user-attachments/files/17902414/shad_log.txt) [shad_log.txt](https://github.com/user-attachments/files/17902479/shad_log.txt)
> > SHAD Build: 11.25 R5 3600 RTX 2060
> 
> It's the same game for yours 2 logs (Disney Infinity) Some games are not working. You Can check every tested games here: https://github.com/shadps4-emu/shadps4-game-compatibility And add this one on it (because not tested). This is on the issue tab

Yes but 2 different versions of it 2.0 and 3.0, two different game.
I will add it then, but is this the type of error message we can except for every not working game? Or differs game by game? Also even if the a game doesn't work why the whole client crashes? Cause at first glance looks like a general problem not per game, no problem just good to know.

**Comment by Hermiten** [comment]
It can differ but yes it's typically what you can have.

**Comment by MikeDeltaHH** [comment]
> Someone tested it with the last version and ho in-game. Can you try to update shadps4 and test again ?
> 
> It's a common problem. Your game simply cannot run on some version. You need to check here: https://github.com/shadps4-emu/shadps4-game-compatibility
> 
> There is a regression maybe between some version but the last one seems to fix it

Hi @Hermiten With the last version it works again! Thanks a lot!!!!! :)

**Comment by MikeDeltaHH** [comment]
Update to the latest build fix it!

**Comment by kutkarshh** [comment]
**Game: God of War 3 Remastered**  
**Issue: Game crashes after studio logo**

Hello Everyone,

I'm trying to play **God of War 3 Remastered** on the ShadPS4 emulator, but the game fails to proceed past the game studio logo. It just crashes right after that. I'm attaching both the **log file** and a **video recording** as proof for further analysis.

**My system specs:**  
- Windows 11  
- 16GB RAM  
- NVIDIA RTX 3050Ti (6GB VRAM)

I've tried running the game with default settings and also tweaked a few configurations, but nothing has helped so far. Any suggestions or known fixes for this issue would be much appreciated!

Thanks in advance!

[shad_log.txt](https://github.com/user-attachments/files/19889536/shad_log.txt)

Video Link->

https://vimeo.com/1078268125?share=copy
