### ISSUE TITLE
ROG ALLY X  running Bazzite OS appimage not working

### ISSUE THREAD

**Issue by GotYahB1TCH** [shadps4-emu/shadPS4#1471]
Hey I installed the latest shadps4 version and extracted it ran the app image, at first it seemed to run fine it showed the where to install games directory file and i selected a file to install to but then after doing that it disappeared at first i though it was loading but no nothing popped up so i clicked on the app image again nothing was appearing i tried using gear lever an clicked launch but everytime it would say launching wait a few seconds the it would say launch, it wouldn't work please help I am on bazzite os

**Comment by GotYahB1TCH** [comment]
Oh yeah I should also add I have tried different version of Linux versions and shad ps4 versions

**Comment by jardon** [comment]
executing the appimage from a terminal would probably give better insight into why the process is terminating.  so in case youre not familiar just open terminal/konsole/whatever

```bash
./path/to/ShadPS4.appimage
```

**Comment by Hermiten** [comment]
I'm closing this one, no update
