### ISSUE TITLE
Application crashing when launching the game ( ex. GTA Vice City )

### ISSUE THREAD

**Issue by harshaltiwari1998** [shadps4-emu/shadPS4#1472]
I have installed all the pre-requisites for installing ShadPS4 downloaded the GTA VC game and installed the package on the application.
when I launch the game it displays a black screen and then crashes.

PFA video.

https://github.com/user-attachments/assets/7734a1d4-b0e1-496b-9ce8-f314928126a3

**Comment by MikeDeltaHH** [comment]
Trink it´s the same problem i have reported…

[#1470](https://github.com/shadps4-emu/shadPS4/issues/1470)

**Comment by DanielSvoboda** [comment]
The emulator is in the early stages of development, few games work, and it is very likely that this game will not work yet.
And this is a ps2 emulator game on ps4, they are still not working.
And it has nothing to do with @MikeDeltaHH problem.

**Comment by MikeDeltaHH** [comment]
Ah sorry, saw too late that it's about a ps2 game...

**Comment by harshaltiwari1998** [comment]
When I looked for a game I found this as a PS4 title so that's why I downloaded it.

**Comment by Hermiten** [comment]
Piracy is not allowed
