### ISSUE TITLE
bloodborne shadps4 crash

### ISSUE THREAD

**Issue by roshen139** [shadps4-emu/shadPS4#1473]
https://github.com/user-attachments/assets/6bef9d34-f2e0-472a-8e88-96814472aea7

the game just crashes, I tried to play sonic mania, and it also crashes when I try to launch it. I installed sys modules, configured the graphics according to the guides I found on YouTube. my PC configuration: gtx 1070, ryzen 5 5600, 32 gb of ram 3200 mhz, latest video card drivers installed.

**Comment by DanielSvoboda** [comment]
Install this to run c++ programs correctly.
https://aka.ms/vs/17/release/vc_redist.x64.exe
