### ISSUE TITLE
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called

### ISSUE THREAD

**Issue by SkarSSG** [shadps4-emu/shadPS4#1477]
When i run game to appear the error  [Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called.
[shad_log.txt](https://github.com/user-attachments/files/17609823/shad_log.txt)
![2024-11-03_105809](https://github.com/user-attachments/assets/9749f644-d498-45c9-8c12-6a0fc8330cf7)

**Comment by polybiusproxy** [comment]
That error is normal at this moment.

**Comment by ghost** [comment]
got the same problem, how did you fix it?
