### ISSUE TITLE
Bug: Clicking on an unpacked game on a network drive crashes the application with no message

### ISSUE THREAD

**Issue by chozandrias76** [shadps4-emu/shadPS4#1488]
# Problem
As a user with a network drive
I would like to be able to load my games from my network drive
And produce actionable messages if I cannot

# Steps
* Create and mount a network drive (Windows)
* Unpack a pkg to the network drive
* Ensure shadPS4 is set up to discover games on that new unpacked route
* Click on the name of the extracted pkg in the GUI
* Emulator crashes to desktop; no message

**Comment by Da-nu** [comment]
I tried to recreate your issue, but the emulator seemed to launch the game. Although I got a bunch of errors about not being able read the sce_sys folder. There is definitely some issue with the emulator's ability to open files from network drives.
[shad_log.txt](https://github.com/user-attachments/files/17639728/shad_log.txt)

**Comment by Hermiten** [comment]
I'm not sure if it's planned or not
