### ISSUE TITLE
(Bug) Bloodborne don't work on Ubuntu

### ISSUE THREAD

**Issue by USL3SS-DEV** [shadps4-emu/shadPS4#1492]
- CPU - AMD Ryzen 5 4500
- GPU - NVIDIA GTX 1660 Super (Galax)
- OS - Ubuntu 24.10
- Version - f98b9f7

[SHADPS4.log](https://github.com/user-attachments/files/17649262/SHADPS4.log)

**Comment by Hermiten** [comment]
Already reported, please have a look before posting a new issue
