### ISSUE TITLE
I'm trying to open The Last of Us II and I get everything red pls help is it possible to emulate a game like this?

### ISSUE THREAD

**Issue by RuHuaytaMars** [shadps4-emu/shadPS4#1497]
Adjunto Imagenes:::

![A2](https://github.com/user-attachments/assets/c97e2974-af19-4137-870f-56423cec381c)
![A1](https://github.com/user-attachments/assets/7ff963e4-1c4b-42b1-bdff-6c2d81dfa7f9)
![A2](https://github.com/user-attachments/assets/30eda9fd-d65a-4d06-a95b-8bf0d360a01c)
![A1](https://github.com/user-attachments/assets/f28b4220-7578-41c2-8efa-b5499c8ce317)

**Comment by DanielSvoboda** [comment]
No, it is not possible to run this game yet. The red lines you mentioned are functions that have not been implemented yet, so it still needs time...
