### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by username227** [shadps4-emu/shadPS4#1498]
Hi, I get a complete program crash and error message at the command prompt when trying to start Dragon Quest Heroes and Dragon Quest Heroes 2. I'm attaching one of the command output logs. The second one was similar but SOOO long that github won't take the file.

[log2.txt](https://github.com/user-attachments/files/17662894/log2.txt)

**Comment by C4ndyF1sh** [comment]
https://github.com/shadps4-emu/shadps4-game-compatibility is for questions like that
