### ISSUE TITLE
Feature request: skip GUI when launching game directly

### ISSUE THREAD

**Issue by fpiesche** [shadps4-emu/shadPS4#1499]
It'd be useful if the main Qt GUI executable didn't bother trying to read the entire game directory when it's launched directly into a game (by calling `shadps4 path/to/eboot.bin`). Some emulators just do this transparently, others (eg. RPCS3) have a command line flag to disable running the main GUI (in RPCS3's case, `--no-gui`).

This will make the emulator useful for configuring via the GUI when running it directly with no parameters, while also allowing the same executable to launch into a game directly without having to wait for the game list to build on startup first. This is a common use case with game launchers such as Steam's game mode or things like Launchbox and Playnite.

Ideally this should also launch in fullscreen mode, though doing this could also be handled by a separate command line parameter (that is, just running `shadps4 eboot.bin` will run the game in windowed mode, while running `shadps4 --fullscreen eboot.bin` will launch it in fullscreen).

**Comment by DanielSvoboda** [comment]
There is the SDL version, which is different from the QT version which has an interface

**Comment by fpiesche** [comment]
Yeah - thus in the current setup, a user would need both the SDL and the Qt version installed to be able to direct-launch games without waiting for the game list to populate first, but also have the GUI available for configuration. Making the Qt version skip the GUI, or at least the game list read, when launching an executable directly, would improve QOL for users of the Qt version.

I'll admit I haven't actually used the SDL version; does it meaningfully differ from the Qt version once it gets to actually running a game, e.g. in terms of Wayland support etc?

**Comment by DanielSvoboda** [comment]
The QT version didn't even have a command, I remember that I was the one who added the ability to run the game through the command line in the QT version, just like in SDL, I did this just to be able to create [game shortcuts](https://github.com/shadps4-emu/shadPS4/pull/246) correctly. It's a good idea to have a command to run QT headless, similar to SDL.

**Comment by Hermiten** [comment]
Can you try the last main version ?:)

**Comment by DanielSvoboda** [comment]
> Can you try the last main version ?:)

It looks like the shortcut is broken...
then I do more tests

**Comment by Nt0w** [comment]
I’m a newbie and had ai write the code.. hope it helps.. it’s for Linux and intel hope it help ✌️

#include <xf86drm.h>
#include <xf86drmMode.h>
#include <fcntl.h>
#include <unistd.h>
#include <cstring>
#include <iostream>
#include <cstdlib> // For strtol

// Function to parse CLI arguments
void parse_arguments(int argc, char *argv[], std::string &drm_device, std::string &fb_device, uint32_t &clear_color) {
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--drm-device" && i + 1 < argc) {
            drm_device = argv[++i];
        } else if (arg == "--fb-device" && i + 1 < argc) {
            fb_device = argv[++i];
        } else if (arg == "--color" && i + 1 < argc) {
            clear_color = static_cast<uint32_t>(strtol(argv[++i], nullptr, 16));
        } else {
            std::cerr << "Unknown argument: " << arg << std::endl;
        }
    }
}

// Function to open the DRM device
int open_drm_device(const char *device) {
    int fd = drmOpen(NULL, device);
    if (fd < 0) {
        std::cerr << "Error: Unable to open DRM device: " << device << std::endl;
    }
    return fd;
}

// Function to get the first connected DRM connector
drmModeConnector* get_connected_connector(int drm_fd, drmModeRes *resources) {
    for (int i = 0; i < resources->count_connectors; ++i) {
        drmModeConnector *connector = drmModeGetConnector(drm_fd, resources->connectors[i]);
        if (connector && connector->connection == DRM_MODE_CONNECTED) {
            return connector;
        }
        drmModeFreeConnector(connector);
    }
    std::cerr << "Error: No connected display found!" << std::endl;
    return nullptr;
}

// Function to open the framebuffer device
int open_framebuffer_device(const char *device) {
    int fd = open(device, O_RDWR);
    if (fd < 0) {
        std::cerr << "Error: Unable to open framebuffer device: " << device << std::endl;
    }
    return fd;
}

// Function to clear the framebuffer with a solid color
bool clear_framebuffer(int fb_fd, uint32_t width, uint32_t height, uint32_t color) {
    size_t fb_size = width * height * 4; // Assuming 32-bit color depth
    char *buffer = new char[fb_size];

    // Fill buffer with the specified color
    for (size_t i = 0; i < fb_size; i += 4) {
        std::memcpy(&buffer[i], &color, 4); // Copy color into each pixel
    }

    // Write buffer to framebuffer
    if (write(fb_fd, buffer, fb_size) < 0) {
        std::cerr << "Error: Failed to write to framebuffer!" << std::endl;
        delete[] buffer;
        return false;
    }

    delete[] buffer;
    return true;
}

int main(int argc, char *argv[]) {
    // Default values
    std::string drm_device = "/dev/dri/card0";
    std::string fb_device = "/dev/fb0";
    uint32_t clear_color = 0x00000000; // Default: Black

    // Parse command-line arguments
    parse_arguments(argc, argv, drm_device, fb_device, clear_color);

    // Open DRM device
    int drm_fd = open_drm_device(drm_device.c_str());
    if (drm_fd < 0) {
        return -1;
    }

    // Get DRM resources
    drmModeRes *resources = drmModeGetResources(drm_fd);
    if (!resources) {
        std::cerr << "Error: Failed to retrieve DRM resources!" << std::endl;
        drmClose(drm_fd);
        return -1;
    }

    // Get the first connected connector
    drmModeConnector *connector = get_connected_connector(drm_fd, resources);
    if (!connector) {
        drmModeFreeResources(resources);
        drmClose(drm_fd);
        return -1;
    }

    std::cout << "Connected to display: Connector ID " << connector->connector_id << std::endl;

    // Open framebuffer device
    int fb_fd = open_framebuffer_device(fb_device.c_str());
    if (fb_fd < 0) {
        drmModeFreeConnector(connector);
        drmModeFreeResources(resources);
        drmClose(drm_fd);
        return -1;
    }

    // Get resolution from the connector's preferred mode
    uint32_t width = 1920;  // Default width
    uint32_t height = 1080; // Default height
    if (connector->count_modes > 0) {
        width = connector->modes[0].hdisplay;
        height = connector->modes[0].vdisplay;
    } else {
        std::cerr << "Warning: No preferred mode found. Using default resolution 1920x1080." << std::endl;
    }

    std::cout << "Display resolution: " << width << "x" << height << std::endl;

    // Clear framebuffer with the specified color
    if (!clear_framebuffer(fb_fd, width, height, clear_color)) {
        std::cerr << "Error: Failed to clear framebuffer!" << std::endl;
        close(fb_fd);
        drmModeFreeConnector(connector);
        drmModeFreeResources(resources);
        drmClose(drm_fd);
        return -1;
    }

    std::cout << "Framebuffer cleared successfully with color: 0x" << std::hex << clear_color << std::dec << std::endl;

    // Cleanup
    close(fb_fd);
    drmModeFreeConnector(connector);
    drmModeFreeResources(resources);
    drmClose(drm_fd);

    return 0;
}

**Comment by Hermiten** [comment]
Fixed
