### ISSUE TITLE
[CUSA03173] Bloodborne - [Debug] Critical and more

### ISSUE THREAD

**Issue by GHU7924** [shadps4-emu/shadPS4#1509]
Build - shadPS4 v0.4.1 WIP main 75d2181

I have 2 characters. The first is the main one, the second is the test one. 

In the main menu, I chose not to continue the game, but to load the game. As soon as I selected the test character I created yesterday for the test and clicked load, for some reason the emulator crashed, but without errors. I tried again, but the result was the same.

 After some attempt, I was able to load the save. I switched between characters and loaded them several times, and I got a critical error.

I took a screenshot, but I forgot about the log file, I'm sorry.

![777](https://github.com/user-attachments/assets/bf55bbad-4877-4876-90a9-f7e88017f841)

I continued the experiment and was given another error. Here is a screenshot and a log file. 

![888](https://github.com/user-attachments/assets/b9ee0c6c-04c6-4d06-aae3-fa841e115ba7)

[shad_log.txt](https://github.com/user-attachments/files/17687991/shad_log.txt)

I started the game a few more times, and the second error was repeated. Who can test this for yourself, do you have any messages about a critical error.

There is also such a thing:

![999](https://github.com/user-attachments/assets/50472b4a-18ae-47c0-9d53-ecdaf88b0615)

![000](https://github.com/user-attachments/assets/644a6fc7-500d-4f6d-8d38-85baea19144b)

and the video version

https://github.com/user-attachments/assets/d9b1de23-bf8c-4516-8289-cc2cf468ffd3

[shad_log.txt](https://github.com/user-attachments/files/17688720/shad_log.txt)

**Comment by GHU7924** [comment]
Next, I activated 60 fps and the graphic artifacts started:

![456](https://github.com/user-attachments/assets/f18abcc3-a99f-4f24-8597-4fa42bbaddd1)
![111](https://github.com/user-attachments/assets/24287cba-f2ba-4791-ae4b-a84ea3cd408a)
![222](https://github.com/user-attachments/assets/c7e165bb-6a71-4e6d-b996-63a32d94a0c8)
![333](https://github.com/user-attachments/assets/733b4804-37df-4570-8d91-e99f94c37310)
![444](https://github.com/user-attachments/assets/e9974f4c-35f2-4a13-91f1-e59602d1a75b)
![555](https://github.com/user-attachments/assets/5dee8ef9-2f4a-46e6-95a3-f0c5224e2ae0)
![666](https://github.com/user-attachments/assets/e7e9c5b4-717d-437d-a6ff-8d356072404a)
![789](https://github.com/user-attachments/assets/d915a502-39d7-4423-adfc-d95fdc9a1081)
![4567](https://github.com/user-attachments/assets/32375ab4-3309-4c9c-94de-076e7c64c71f)
![112233](https://github.com/user-attachments/assets/47952497-7af3-41c9-9daf-27994366f36e)
![334455](https://github.com/user-attachments/assets/0e1b4c7b-bfd4-4a36-b07c-905cd2c86b31)

There were actually more artifacts, but these are enough.

**Comment by KrisCris** [comment]
https://github.com/shadps4-emu/shadPS4/issues/1232
disabling face customization workarounds the issue for now: https://www.nexusmods.com/bloodborne/mods/109

**Comment by GHU7924** [comment]
> #1232 disabling face customization workarounds the issue for now: https://www.nexusmods.com/bloodborne/mods/109

I've already finished the game on version 0.2.1, so mods are not important to me, I'm just testing builds with improvements and fixes in order to help identify problems and give feedback.

If I'm not mistaken, then in version 0.3.1 these problems seemed to have already been solved, I didn't have them, but after the release of 0.4.0 or 0.4.1 something went wrong apparently.

I upgraded to build 7ab8515

Forbidden Woods

https://github.com/user-attachments/assets/2c25a5a7-d806-4ff4-b636-132b90bcdb5e

Shadow of Yharnam

After defeating the boss, a crash occurred and the emulator closed with an error,
I had to fight a second time.

![ggg](https://github.com/user-attachments/assets/0bf90f87-3f9c-4adf-a602-b701639ce4ea)

Byrgenwerth

Maybe something is wrong with AJM, I did not understand the pattern, but some of the sounds were gone, here is an example in the video.

https://github.com/user-attachments/assets/653cd921-d8bd-4bf2-98ef-b6bef88ab2e2

Forsaken Cainhurst Castle

The cutscene with an error, restarting the emulator, the cutscene with an error, everything is fine for the third time, I got to the location.

![fgk](https://github.com/user-attachments/assets/c42359ce-a619-47e1-9e85-3f33385eedc7)

In general, after the release of 0.4.0, my performance dropped quite a lot, 2 weeks ago (on version 0.3.1) everything was fine.

**Comment by Linear524** [comment]
More effects are being discovered and emulated in latest versions, and a lot of new bug cases was discovered as well... Of course it is an early stages of PS4 emulation glory, DEVs just need more time to fix all that stuff.
I see a lot "out of memory" bugs and memory corruption issues as well. Speed is not important right now - only emulation accuracy must be with the top priority. (Speed optimization can always be done later)
Try to disable all the mods (they often breaks some native things, and sfx skipping/changing mods breaks some GPU effects, even if they solve sound/sfx freezing) and test only geometry rendering.

**Comment by GHU7924** [comment]
Recently, an issue was closed where it was said that the trophies did not appear, I decided to help, so I activated patches in an attempt to recreate the problem on my PC, but I failed to do this, everything was fine and the trophies appeared, but along with this the above problems appeared.

There was a problem with saving, it happened suddenly, I couldn't load the save because it was hanging. On the third time, the save loaded. I was able to continue the game. Then other errors started, so I created this theme.

Now I'm playing without cheats and patches and with a new save (I made a backup copy of the old save and deleted it from the emulator, so now I have a new save created by the emulator), there have been no critical errors so far, but graphical glitches and FPS is sagging (This is the first time this has happened to me.).

![bb3](https://github.com/user-attachments/assets/5ad180fb-202d-4cbf-a8be-ac86cff015de)

https://github.com/user-attachments/assets/cea47225-2975-4028-9366-a21d4d6d05c5

https://github.com/user-attachments/assets/cf4a37dd-9109-4a94-a29c-ca9af0d582fe

These videos are from Build v0.4.1 WIP main 7be35c3.
There are more videos, but they are about the same content, but the graphical errors look different.

**Comment by Hotman13** [comment]
There are a lot of errors from the very start. Bloodbourne naturally lags hard. At the moment I have 5 fps. Maybe they can be eliminated to increase FPS or wait for a later patch where everything will be fixed?  
I tried fixes and the game crashes with them
my pc:
Ryzen 7 3800X
RAM 16gb
Geforce RTX 3050 8gb
Windows 10 corp ltsc
Vulkan latest version
![23131](https://github.com/user-attachments/assets/8f8adf4f-6281-48b5-9793-7d32d345b563)

**Comment by GHU7924** [comment]
Also my experience of playing Bloodborne on Linux: 

Briefly:

>[Debug] signals.cpp:SignalHandler:76: Unreachable code!
>Unhandled access violation at code address 0x7fe30e6c880e: Read from address 0x7fdf085c5b58

>[Debug] liverpool.cpp:operator():298: Assertion Failed!
>NOP hint is missing in CB setup sequence

>[Debug] liverpool.cpp:ProcessGraphics:200: Unreachable code!
>Unsupported PM4 type 0

>[Debug] signals.cpp:SignalHandler:76: Unreachable code!
>Unhandled access violation at code address 0x9026bc1c3: Read from address 0xd2

In detail:

https://github.com/shadps4-emu/shadPS4/issues/1409#issuecomment-2484041236 and https://github.com/shadps4-emu/shadPS4/issues/1409#issuecomment-2485558522

And here's another thing:
![Снимок экрана_20241119_163416](https://github.com/user-attachments/assets/d100b50f-fcf0-4428-8c9b-156d4bd3f0e1)
![Снимок экрана_20241119_162844](https://github.com/user-attachments/assets/114c5419-7aa6-4e7c-9fc3-cbeee55dbdef)

Blackscreen...
[shad_log_main.txt](https://github.com/user-attachments/files/17815986/shad_log_main.txt)

In #1409, the situation is better with other builds, but I personally could not get further than the menu.

Edit: Update/shadps4-linux-qt-2024-11-22-8f2d71d  (Main)
![Снимок экрана_20241122_130631](https://github.com/user-attachments/assets/1d1ea391-061b-4fe9-98b7-09153219c202)

There is no black screen anymore, but the situation is still the same.
>[Debug] <Critical> signals.cpp:SignalHandler:76: Unreachable code!
>Unhandled access violation at code address 0x9026bc1c3: Read from address 0xd2

**Comment by neptuwunium** [comment]
`signals.cpp:SignalHandler:76: Unreachable code!` segfault seems to happen due to a race condition in page buffer allocation. (edit 1: suspicions seem to be confirmed by just running shadps4 over and over, occasionally it'll boot successfully but then hang at another point. edit 2: disabling the splash completely eliminates the crashes)

lldb trace:
```
Process 9101 stopped
* thread #18, name = 'shadPS4:Present', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x55c194ddef48)
    frame #0: 0x0000555556b4c6ee shadps4`VideoCore::BufferCache::ObtainViewBuffer(unsigned long, unsigned int) [inlined] VideoCore::Buffer::IsInBounds(this=<unavailable>, addr=140736607641616, size=8294400) const at buffer.h:101:24
   98  	
   99  	   /// Returns true when vaddr -> vaddr+size is fully contained in the buffer
   100 	   [[nodiscard]] bool IsInBounds(VAddr addr, u64 size) const noexcept {
-> 101 	       return addr >= cpu_addr && addr + size <= cpu_addr + SizeBytes();
   102 	   }
   103 	
   104 	   /// Returns the base CPU address of the buffer
frame #1: 0x0000555556b4c6ee shadps4`VideoCore::BufferCache::ObtainViewBuffer(this=0x00005555591f3578, gpu_addr=140736607641616, size=8294400) at buffer_cache.cpp:341:20
   338 	   const BufferId buffer_id = page_table[page];
   339 	   if (buffer_id) {
   340 	       Buffer& buffer = slot_buffers[buffer_id];
-> 341 	       if (buffer.IsInBounds(gpu_addr, size)) {
   342 	           SynchronizeBuffer(buffer, gpu_addr, size, false);
   343 	           return {&buffer, buffer.Offset(gpu_addr)};
   344 	       }
```

**Comment by GHU7924** [comment]
Since [Aggregate Issue] Bloodborne #1641 was opened, I'm closing this topic.
