### ISSUE TITLE
Windows username acute accent issues

### ISSUE THREAD

**Issue by felp1x** [shadps4-emu/shadPS4#1510]
Due to the acute accent in my Windows username, every time I start the emulator, I need to add new paths. The only solution I found for now was to place my games on another SSD that doesn't have an acute accent in its name.

the correct game directory:
![shadps4 path](https://github.com/user-attachments/assets/51ec7750-1bbe-4fba-9dd0-bd1b4e82a121)

When I try to use the emulator again after closing it: 
![shadps4 path2](https://github.com/user-attachments/assets/a5f4926f-0e08-4b3a-9e98-b8924efbf1b1)

**Comment by Osyotr** [comment]
https://github.com/shadps4-emu/shadPS4/blob/75d2181489d45dc72feba98c96ce9b2f065835a4/src/common/config.cpp#L661

Should probably be `std::ofstream file(path, std::ios::out | std::ios::binary);`

**Comment by Foul-Tarnished** [comment]
emulador
