### ISSUE TITLE
Add Winget Support

### ISSUE THREAD

**Issue by Koaxz** [shadps4-emu/shadPS4#1514]
I'm requesting the addition of support for installing the shadPS4 emulator via the Windows Package Manager (winget). This would significantly simplify the installation process for Windows users like myself.

Right now, installing shadPS4 involves manually building from source or downloading pre-built binaries. I find these methods to be a bit complex and time-consuming. Integrating with winget would greatly improve my experience, and I believe the experience of other Windows users, by providing a straightforward, standardized, and trustworthy installation method. It would also allow me to easily keep shadPS4 updated through winget's update functionality. Winget is becoming increasingly popular due to its ease of use, and I believe that adding support for shadPS4 would be a beneficial addition for the community. I would appreciate it if you would consider this request.

**Comment by Hermiten** [comment]
You only need to download once, extract it and start it Then you can update on 1 click. 
I'm not sure about using winget will be more easier. 
Also, this is a program in alpha, lot of things can change. I don't think winget is suitable for this.
