### ISSUE TITLE
Bloodborne 60FPS deltatime TROPHY CRASH

### ISSUE THREAD

**Issue by zeitar** [shadps4-emu/shadPS4#1516]
Accidentally closed last issue, trophy crashes my game when i run 60fps deltatime.

**Comment by zeitar** [comment]
@GHU7924 Same here
![Screenshot 2024-11-10 204848](https://github.com/user-attachments/assets/e176d485-43f5-4f50-be07-ef929faf3625)
BTW im testing tesselation ver. and facing same problem with 60 fps KEK. I guess it could be memory crash somehow, i have only 16gb

**Comment by zeitar** [comment]
@GHU7924 Also last log says that device lost during memory read but I may be wrong. And I keep in mind that you also reproduced my problem once, so it could be really my hardware issues because of my setup I facing this problem every time. So i guess for me personally better to play 30fps + frame gen. But I hope change my mind when I see enourmous progress of emulation/
![image](https://github.com/user-attachments/assets/c95f92aa-0e07-46fd-b7a8-bc8afc81469f)

**Comment by GHU7924** [comment]
Так как я вижу знакомые буквы, то давай на нашем)) (На английском писал, чтобы понятней было, если кто присоединится, но похоже мы вдвоём)

Значит, смотри дружище. У меня 32 Гб ОЗУ, поэтому я проверить не смогу что там при 16-ти происходит, но вполне допускаю что какое-то влияние есть. В 30 кадров игра действительно идёт лучше, актуальные же билды у меня что-то хуже работают, не знаю после каких новых изменений всё ухудшилось, но из-за этого я даже проблему открыл. В 60 кадров игра чувствует себя хуже, чем в 30, да, хотя недели две назад я проблем таких не испытывал.

Есть 3 вещи, которые стоит проверить, проверяй по одному пункту:

1) Отключи патч на своё разрешение, не меняй на другой, а просто отключи (галочку сними и сохрани). Всё что выше 900р в патчах может быть с глюками. Если 1440р поставишь, рано или поздно точно столкнёшься. К примеру, я так пошёл в чашу 5-го уровня со всеми проклятиями, последний босс был Птумерианец, так он невидимым стал, как и его локация, а там дыра посреди арены была, вот и сражайся, но хотя бы лочиться на нём можно было, но что он делает не видно, а когда патч разрешения отключил, всё вернулось в норму, и локация есть и враг видим стал.

Так что лучше без патча разрешения играй, а если и будешь применять патч, то максимум 900р. 
Я без патча на разрешение играю, но 900р тестил, было норм.
Не знаю что у тебя там есть ближайшее, чтобы получить трофей. Так что, возможно, ещё лучше вариант из пункта 2.

2) Попробуй начать новую игру и создай нового перса с другим именем, не переживай, предыдущий не затрётся, в загрузке выбрать можно будет. Попробуй быстренько с читами дойти до Церковного чудища, убедись будет ли сбой при победе и получении трофея и высветится ли вообще трофей.

3) Возможно был сбой с сохранениями. Попробуй бэкап сейвов сделать на рабочий стол, а в эмуляторе удали их. Запусти новую игру и повтори пункт 2.

Посмотрим есть ли изменения.

Итого:
1) Первый пункт покажет, оказывает ли влияние патч.
2) Второй пункт покажет, есть ли изменения на существующих сохранениях.
3) Третий пункт покажет, что будет при только что созданных сохранениях.

**Comment by zeitar** [comment]
Тоже писал на инглише чтобы другие в курсе были. В 30 игра идет максимально ровно, это факт.
1. Чисто из эстетических соображений без фикса играть не буду, ибо на моем монике другое выглядит разительно хуже. Да и я думаю что раз при анлоке игра траить начинает, то это наверняка косяк анлока или недоработок эмуля, тем самым до более стабильных версий могу и потерпеть.
2. Когда только запостил первую тему, все это сделал и что интересно: сначала все опять крашилось с анлоком, потом решил перетестить с новым персом и трофей вообще не появился. Короче странная нестабильная шляпа, которую тестить то толком не выходит.
3. Как раз второй пунк я выполнял на пустом эмуле без сейвов. Короче будь это недоработка эмуля или нехватка памяти, так или иначе проблема очень локальна чтобы в нее глубже углубляться, но конечно могут быть варианты. 

Пока реально кайфую, по крайней мере невидимых чертей в продземельях еще не было))

**Comment by GHU7924** [comment]
Просто для теста.
В настройках эмуля окно сделай 1280х720, без полноэкранного, патч отключи. Протести всё же, чтобы удостовериться.
Возможно это действительно не влияет, но проверить стоит.

В трофеях посмотри, что локед, а что анлокед. Возможно из-за краша трофея не было видно, но он засчитался (не факт).
А если он засчитался, то второй раз по идеи он мог и не высветиться, даже если босса пришлось бы второй раз проходить.
Как много Unlocked? Они были разблокированы до трофи краша или есть такие что во время?

**Comment by zeitar** [comment]
Вот с того момента как я начал гонять на новой версии с трофеями вообще какая то каша. на старых сейвах стал лутать их по второму кругу, выглядит как то так 
![image](https://github.com/user-attachments/assets/bf2d70ca-2168-4b61-9c8b-533d4ca66506)
 Что касается резпатча, выделю отдельное время на это шаманство, есть вероятность что в нем что то мешает. А ты в моем разрешении пробовал? Может быть проблема малоизвестна просто потому что ультрашироких моников у людей супер мало.

**Comment by zeitar** [comment]
Немного оффтопа: 
1)Есть ли смысл включать 30фпс фикс если я и так не анлочил фпс? Если нет то зачем он нужен?
2)Убирать ли вертикалку в моем случае? Заметил что при просадках игра с выключенной вертикалкой начинает идти выше 30 фпс и при этом ускорено.
3) Какие значения vblank в каких случаях выставлять? Я выставил 1 и меняю на 4 когда тестирую анлок фпс.
![image](https://github.com/user-attachments/assets/86146abb-65f0-49b0-89ae-9fe5b3ca349c)

**Comment by Hermiten** [comment]
We do not provide support for patches here. Please put an issue on the repository of the patch

**Comment by GHU7924** [comment]
> Вот с того момента как я начал гонять на новой версии с трофеями вообще какая то каша. на старых сейвах стал лутать их по второму кругу, выглядит как то так 

Тут просто показывает что разблокировано, а что нет.

Кстати, я вот проверил, победил Реборна и Менсиса, за них по второму кругу не дали трофеев, потому что они у меня уже были получены.

>Что касается резпатча, выделю отдельное время на это шаманство, есть вероятность что в нем что то мешает. А ты в моем разрешении пробовал? Может быть проблема малоизвестна просто потому что ультрашироких моников у людей супер мало.

Я вообще запускал в 3440х1440. Да и рано такое тестить, эмулятор до сих пор так сказать в альфе.

>Немного оффтопа:
1)Есть ли смысл включать 30фпс фикс если я и так не анлочил фпс? Если нет то зачем он нужен?
2)Убирать ли вертикалку в моем случае? Заметил что при просадках игра с выключенной вертикалкой начинает идти выше 30 фпс и при этом ускорено.
>3) Какие значения vblank в каких случаях выставлять? Я выставил 1 и меняю на 4 когда тестирую анлок фпс.

1) Это что-то вроде 30 кадров с вертикальной синхронизацией, кадры правильно расставляются и по скорости одинаковые, отсюда и плавность.

2) Bloodborne на PS4 работал в 1080р вроде и 30 фпс. Убрав галочку 30 кадров, у тебя всё-равно будет 30 кадров.
Я играю без галочки на 30, но надо бы потестить, есть ли у меня разница или просадки.

3) Я точно не уверен, но насколько я понимаю этот параметр, то это множитель фпс, типо сколько кадров в сек будет на графике фреймтайма.

Если игра залочена на 30 фпс или 60 фпс, то 1 оставляешь, потому что игра залочена, больше не получишь.
Вот Bloodborne такой вроде, ему не важно это, да и увеличение приводит к ускорению игры при патче Disable vsync.

Это что-то похожее на вертикальную синхронизацию, если ею же и не является. 
По идеи это нужно если нет лока фпс, а фпс маленький. К примеру 15 фпс, умножается на 2, получаем 30, вместо 30 будут 60 кадров вставлять, если было 60, то 120 кадров и т.д.
Но такое увеличение может наоборот ухудшить производительность.
Выставляешь значение 1 или 2, а максимум 3 или 4 - выше ставить вряд ли стоит.
