### ISSUE TITLE
CUSA00900 - Unhandled access violation at code address 0x578dfc2712a6: Read from address 0x0

### ISSUE THREAD

**Issue by thethunderturner** [shadps4-emu/shadPS4#1526]
When trying to run bloodborne on arch linux on the latest 0.4.1 version, I get this error:
```
[Common.Filesystem] <Error> io_file.cpp:Seek:385: Seeking past the end of the file
[Loader] <Critical> elf.cpp:operator():208: Failed to seek to header tables
[Debug] <Critical> signals.cpp:SignalHandler:76: Unreachable code!
Unhandled access violation at code address 0x578dfc2712a6: Read from address 0x0
```

**Comment by polybiusproxy** [comment]
From the part of the log you gave us, your game copy appears to be corrupted.

**Comment by thethunderturner** [comment]
> From the part of the log you gave us, your game copy appears to be corrupted.

I just redumped the game and I get the same error. Here is the complete log:

[log.txt](https://github.com/user-attachments/files/17907828/log.txt)

**Comment by Hermiten** [comment]
Im closing this one, there is already some issues open about this and your report is not on the main branch so we cannot help you
