### ISSUE TITLE
Gravity Rush Remake Regression

### ISSUE THREAD

**Issue by jvhellraiser** [shadps4-emu/shadPS4#1534]
Gravity Rush Remake no longer loads saves emulator crashes with error exception
![Screenshot 2024-11-14 183554](https://github.com/user-attachments/assets/eb01bf45-a305-4452-9d18-5ceccf41cd95)
 
 windows 11
 Nvidia RTX 4060 16 gb Vram
 16 gb Ram

**Comment by GHU7924** [comment]
I also get this error. But sometimes I can get into the game.
Sometimes the save cannot load and the emulator closes.

[shad_log.txt](https://github.com/user-attachments/files/17781287/shad_log.txt)

**Comment by jvhellraiser** [comment]
> I also get this error. But sometimes I can get into the game. Sometimes the save cannot load and the emulator closes.
> 
> [shad_log.txt](https://github.com/user-attachments/files/17781287/shad_log.txt)

mine wont load the save at all, i have try to loaded more than 15 times with no results just plain errors

**Comment by rainmakerv3** [comment]
i don't believe this is a regression necessarily, as people have reported these save loading issues for awhile with gravity rush. it does seem to be occurring more frequently in recent builds.

by the way, this assert (and the promotetodepth assert when fighting) when commented out have seemingly no gameplay effect on gravity rush. for those in this thread, you can play without crashes using by hacked build https://github.com/rainmakerv3/shadPS4/releases/

**Comment by GHU7924** [comment]
@jvhellraiser Have you tried the latest Main build? Everything was fixed, at least that's how it is for me. I started a new game, and after each autosave, I restarted the emulator and booted up. There were no failures when loading the save.

**Comment by jvhellraiser** [comment]
> @jvhellraiser Have you tried the latest Main build? Everything was fixed, at least that's how it is for me. I started a new game, and after each autosave, I restarted the emulator and booted up. There were no failures when loading the save.

I did actually just tested in this new release build save arfe working properly thanks....

**Comment by Foul-Tarnished** [comment]
Please close the issue then lol
