### ISSUE TITLE
CUSA03173 Bloodborne: Random fps drops

### ISSUE THREAD

**Issue by Dr-42** [shadps4-emu/shadPS4#1539]
I am running the emulator on linux.

The game suffers random fps drop to 5fps after loading the save. The problem magically disappears about 1 in 10 times.

I am also using the linux PThreadPool patch to make it work.

**Comment by Hermiten** [comment]
Thanks for the report. Bloodborn is unstable, this is a common problem. You can check on Discord and also on issue here.
I'm closing this one because not useful

**Comment by Dr-42** [comment]
Ok I guess.
