### ISSUE TITLE
crash when entering character creation screen in Bloodborne

### ISSUE THREAD

**Issue by Anuk-thotawatta** [shadps4-emu/shadPS4#1540]
in build #1331, when creating a new save the emulator crashes while giving out of memory error.
This wasn't present for me in previous builds

**Comment by Hermiten** [comment]
So for you it can be a regression ?
Can you please give more information like your specs, every version tested, etc ...
Thanks you

**Comment by Anuk-thotawatta** [comment]
I found the issue.
Its because of cloth physics.
I disabled it using the ram spike fix mod.
And everything works fine in 20-40 fps in gpu heavy areas.

Im using intel i5 8400 cpu and nvidia 1660 super gpu and 16 gb ram.

**Comment by C0rn3j** [comment]
I also seem to have issues entering the character creation screen but for me the game just freezes.

https://github.com/shadps4-emu/shadPS4/issues/1045#issuecomment-2526304983

![image](https://github.com/user-attachments/assets/0ee68100-87e4-4b49-b26a-67516c20cf6d)

I do have a bit beefier system than OP, so maybe it doesn't OOM for me for that reason.

EDIT: Nope, my issue was actually https://github.com/shadps4-emu/shadPS4/issues/1704

**Comment by Hermiten** [comment]
Can you try again on the last update @Anuk-thotawatta ? Thanks you

**Comment by Missake212** [comment]
I think we can close this, this seems like a normal issue that people used to get on character creation before #1683 was merged
