### ISSUE TITLE
"Failed to Create Graphic Pipeline"

### ISSUE THREAD

**Issue by Rob007666** [shadps4-emu/shadPS4#1545]
I was playing Bloodborne on a general use laptop with Ryzen 3 5300u, Vega 6 iGPU and 16gb of RAM, using the v.0.3.1 build by Diegolix29. The game was working fine, with a stable 480p30fps. 

But after updating to the latest v. 0.4.1 tessellation build by Diegolix29, the game crashes constantly on the loading screen with "Failed to create Graphic Pipeline". Is there any way to mitigate this problem ?

**Comment by Hermiten** [comment]
Please report this on the right place. If you use a build from an another GitHub, you may report it there. If it's from a PR here, you can also report this on the PR
