### ISSUE TITLE
[CUSA03173] Bloodborne - Cainhurst Castle - Silver Lady's skirt sometimes does not render

### ISSUE THREAD

**Issue by AwesomeSoftware79** [shadps4-emu/shadPS4#1546]
Using latest main build and CUSA03173.
It happens either with 30fps and 60fps patches.

Location: Cainhurst Castle. Sometimes [Silver Lady](https://bloodborne.wiki.fextralife.com/Silver+Lady)'s skirt does not render correctly.

Silver Lady without Skirt (incorrect):
![image](https://github.com/user-attachments/assets/cb877e85-9fcb-4b5c-9ec7-71df05c7c6d6)

Silver Lady with Skirt (correct):
![image](https://github.com/user-attachments/assets/012e554c-4490-49bb-a9b9-a7f0d2891d48)

**Comment by Hermiten** [comment]
Already reported a lot and a lot on others issues. 
Thanks for this but please have a look on other issue

**Comment by AwesomeSoftware79** [comment]
@Hermiten I am not aware of any ticket describing this issue. What ticket do you mean? Thank you
