### ISSUE TITLE
[Bloodborne] Shader fefebf9f causes 2gb buffers to be created

### ISSUE THREAD

**Issue by rafael-57** [shadps4-emu/shadPS4#1547]
This shader seems present in every area, and it can lead to single digit performance or crashes due to out of memory in the worst cases.
![image](https://github.com/user-attachments/assets/804fdd90-2c46-4811-88b9-263bfbd67af5)

For example the performance issues get particulary bad in Upper Cathedral Ward and even worse in Cainhurst:
![image](https://github.com/user-attachments/assets/b233e09c-9e04-49da-9801-294163d6e03e)

It's a simple copy shader, for some reason it gets interpreted by the emu as needing 2gb:
![image](https://github.com/user-attachments/assets/10e204db-8da7-4062-9efb-be80487faaa2)

But it's actually writing around 26KB:
![image](https://github.com/user-attachments/assets/f720524b-d146-4562-a957-eed7efe26e88)

It seems like an issue in how the emulator's texture cache interprets the shader.

Tracy profile analyses were taken with guidance of psucien (nullptr), tracy doesn't seem to work in main. 

Dumping the shader will write these two files:
cs_0x00000000fefebf9f_0.spv
cs_0x00000000fefebf9f_0.bin

Trace link:
https://drive.google.com/file/d/1wfw-5vCHwyE-X7jQVgn9L0LgSDcWqotf/view?usp=sharing

These are the workarounds used to make tracy work:
(this disables gpu work tracing, but it's the only workaround we have for now)
1. Use this client: https://github.com/wolfpld/tracy/releases/tag/v0.11.0
2. Make this bool false: https://github.com/shadps4-emu/shadPS4/blob/76f440889b28b01a32dc47b427e85a13bfb8e32d/src/video_core/renderer_vulkan/vk_instance.cpp#L263
3. In liverpool.cpp comment out all FiberEnter/FiberExit markers

**Comment by Foul-Tarnished** [comment]
What happens if we skip this shader ?
As a workaround ofc

does it cause any broken graphics or missing effects ?

**Comment by rafael-57** [comment]
> What happens if we skip this shader ? As a workaround ofc
> 
> does it cause any broken graphics or missing effects ?

I haven't tested this personally since shader skipping was kinda killed by the geoshaders PR. I've heard it's possible to do it with tess builds on some shaders.

But since this shader is used in most areas to copy things so I don't expect the game to work well without it so I haven't taken the time. Feel free to try and report though

**Comment by hgh32** [comment]
I did this a long time ago
This seems to cause most of the scenes and characters to disappear
![s](https://github.com/user-attachments/assets/1e4a2803-c007-41b5-b023-71f49520306c)

**Comment by rafael-57** [comment]
> I did this a long time ago This seems to cause most of the scenes and characters to disappear ![s](https://private-user-images.githubusercontent.com/39622638/389283432-1e4a2803-c007-41b5-b023-71f49520306c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NTI2NTYsIm5iZiI6MTczMjU1MjM1NiwicGF0aCI6Ii8zOTYyMjYzOC8zODkyODM0MzItMWU0YTI4MDMtYzAwNy00MWI1LWIwMjMtNzFmNDk1MjAzMDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE2MzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZDI2MzZhY2YzYjVlMTk0OTgxOGRhMzY2NGVkMTlkYThiODk0OGRlMTUyYWQxZmVlMTVjMWE0OWYwMTBkOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dn-FYsiDKnr2_5sdaJ6PxlLfRAYPvt8aQYoYzJsLFKg)

Thank you! Nice to see it done for confirmation. So yeah it's used a lot

**Comment by rafael-57** [comment]
![image](https://github.com/user-attachments/assets/1f812ed2-8349-4da8-82d3-8b0c08777230)
![image](https://github.com/user-attachments/assets/bc3737af-e0e3-4a20-af3e-6031411c5470)

Turtle suggested that it's not strictly an issue in how the emu interprets the game code, but that the game code is actually requesting a vsharp with 2GB.

I've asked Bloo if he can develop a game patch to lower this value to try a pissible workaround for this issue :p

Edit: Seems like it's not simple to find the value and develop a patch for this. We'll probably have to wait for future emu developements.

**Comment by BeethovenNotes** [comment]
> ![image](https://private-user-images.githubusercontent.com/13487676/389944750-1f812ed2-8349-4da8-82d3-8b0c08777230.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODcxNDUsIm5iZiI6MTczMjY4Njg0NSwicGF0aCI6Ii8xMzQ4NzY3Ni8zODk5NDQ3NTAtMWY4MTJlZDItODM0OS00ZGE4LTgyZDMtOGIwYzA4Nzc3MjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA1NTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZjNmYmQ4YTU3MzYxNGU2MDQ4ZWFhMTlkNzc4M2M5NDE1YmRjZjc1MDQ5MDQzNGRjMDI5ZTZjOWU3YTM0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ysE6emQC2s7ZDOssJqkrOAg_D4GJ-HnY90Sr-Jmptcg) ![image](https://private-user-images.githubusercontent.com/13487676/389945321-bc3737af-e0e3-4a20-af3e-6031411c5470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODcxNDUsIm5iZiI6MTczMjY4Njg0NSwicGF0aCI6Ii8xMzQ4NzY3Ni8zODk5NDUzMjEtYmMzNzM3YWYtZTBlMy00YTIwLWFmM2UtNjAzMTQxMWM1NDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA1NTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZmE5MTYwY2I1ZDlmYjlkNTUxZGRhMTdmYjc3MGNkZTBhZmRkNjhlNmE4MDcyN2RiMTFiNTQ1NDY2YTBhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Dqe-AxKOHQQ-8uq7N8RyFJrBl4kvcwtKT7rRyuYxpA8)
> 
> Turtle suggested that it's not strictly an issue in how the emu interprets the game code, but that the game code is actually requesting a vsharp with 2GB.
> 
> I've asked Bloo if he can develop a game patch to lower this value to try a pissible workaround for this issue :p
> 
> Edit: Seems like it's not simple to find the value and develop a patch for this. We'll probably have to wait for future emu developements.

Why does it not run out of mem on PS4? Is something missing?

**Comment by rafael-57** [comment]
> > ![image](https://private-user-images.githubusercontent.com/13487676/389944750-1f812ed2-8349-4da8-82d3-8b0c08777230.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODcxNDUsIm5iZiI6MTczMjY4Njg0NSwicGF0aCI6Ii8xMzQ4NzY3Ni8zODk5NDQ3NTAtMWY4MTJlZDItODM0OS00ZGE4LTgyZDMtOGIwYzA4Nzc3MjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA1NTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZjNmYmQ4YTU3MzYxNGU2MDQ4ZWFhMTlkNzc4M2M5NDE1YmRjZjc1MDQ5MDQzNGRjMDI5ZTZjOWU3YTM0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ysE6emQC2s7ZDOssJqkrOAg_D4GJ-HnY90Sr-Jmptcg) ![image](https://private-user-images.githubusercontent.com/13487676/389945321-bc3737af-e0e3-4a20-af3e-6031411c5470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODcxNDUsIm5iZiI6MTczMjY4Njg0NSwicGF0aCI6Ii8xMzQ4NzY3Ni8zODk5NDUzMjEtYmMzNzM3YWYtZTBlMy00YTIwLWFmM2UtNjAzMTQxMWM1NDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA1NTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZmE5MTYwY2I1ZDlmYjlkNTUxZGRhMTdmYjc3MGNkZTBhZmRkNjhlNmE4MDcyN2RiMTFiNTQ1NDY2YTBhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Dqe-AxKOHQQ-8uq7N8RyFJrBl4kvcwtKT7rRyuYxpA8)
> > Turtle suggested that it's not strictly an issue in how the emu interprets the game code, but that the game code is actually requesting a vsharp with 2GB.
> > I've asked Bloo if he can develop a game patch to lower this value to try a pissible workaround for this issue :p
> > Edit: Seems like it's not simple to find the value and develop a patch for this. We'll probably have to wait for future emu developements.
> 
> Why does it not run out of mem on PS4? Is something missing?

Like turtle said in the first screenshot of my previous comment, on PS4 the allocation is managed differently (I think at startup) so the game asking for this 2gb vsharp doesn't allocate any new memory on console. It basically does nothing.

On the other hand, the emu is currently reading that game code and doing what the code is asking it to do, for now.

**Comment by C0rn3j** [comment]
This should be fixed now that HLE is merged I suppose.
