### ISSUE TITLE
Shadps4 crash upon installing a game

### ISSUE THREAD

**Issue by Superyuppers** [shadps4-emu/shadPS4#1564]
So My emulator keep crashing when i try to install bloodborne am not sure why, i tried multiple bloodborne downloads and reinstalling  shadps4 no use i wonder why, anyone got any idea?

My specs 
Gigabyte aorus master
AMD ryzen 9 7950XD
36/34 ram i forgot
RTX 4070 gpu

**Comment by Hermiten** [comment]
It's absolutely forbidden to download the game. You must have to own it
