### ISSUE TITLE
ShadPS4 Game screen stretches to size of window rather than staying at 16:9

### ISSUE THREAD

**Issue by brad0demx** [shadps4-emu/shadPS4#1566]
Seems to have been introduced around commit 5054827 to main branch, not sure the exact commit but the ones from the day prior work correctly

![image](https://github.com/user-attachments/assets/a4c9ef69-89a8-4284-828f-d3a7d91b7d61)
![image](https://github.com/user-attachments/assets/8f1d2afc-58b4-4eed-836f-b1c3e252ebcd)

**Comment by AwesomeSoftware79** [comment]
The same happens with CUSA03173.
The game stretches itself when in full screen. 
I think this is only noticeable when using a non-16:9 screen, i.e. 21:9.

**Comment by psucien** [comment]
Please re-check on the latest main

**Comment by brad0demx** [comment]
![image](https://github.com/user-attachments/assets/7dd520db-e292-4227-af2d-6d8a041fb6c7)
Issue is fixed in latest main, great work👏

**Comment by willink87** [comment]
is it possible to get a stretch to window option? or can you confirm what i can modify on my end to make stretch to window originally described above?
