### ISSUE TITLE
<Critical> liverpool.cpp:ProcessGraphics:200: Unreachable code! Unsupported PM4 type 0

### ISSUE THREAD

**Issue by unk0wn-u53r** [shadps4-emu/shadPS4#1567]
Latest nightly build 0.4.1 WIP main f9ae945
Game: Bloodborne GOTY/CUSA03173

What happen: Games stucks after 30 seconds when I want loading into the gaming world.
Systeminformations: GMKtec K8 with Ryzen 7 8845HS and Radeon 780M, 32 GB DDR5 5600MHz CL40 
Latest Windows 11, all drivers up-to-date

Additional informations:
No cheats or mods used. 
Enabled patches are:
- Skip intro
- Disable chromatic abberation 
- Disable motion blur
- Disable HTTP requests
- Force enable Old Hunters DLC
- Resolution patch 900p

Tried also to disable all patches but the same critical error appears.

Crash log file 
[shad_log.txt](https://github.com/user-attachments/files/17853952/shad_log.txt)

**Comment by brosef622** [comment]
Can confirm same issue on release 58 of baggins183 build. Believe it may have something to do with AMD GPU hardware. Will add references if I can confirm.

**Comment by Crispy81** [comment]
Seen this error on a few games I've tested, I've also got an AMD GPU. Next GPU upgrade will be an Nvidia card.

**Comment by StevenMiller123** [comment]
This error is an emulation error, and has nothing to do with your GPU. If you're encountering this error in games other than Bloodborne or J-STARS Victory Vs+, please provide a log of the crash.

**Comment by Crispy81** [comment]
Next time I re-test all my games, any with that error message, I definitely will post the log in here. I'm glad it's not a GPU specific thing.

**Comment by Crispy81** [comment]
Killzone: Shadow Fall has a slightly different message: Are we interested in that or needs to be the exact same as thread title message?

![image](https://github.com/user-attachments/assets/3c1e0f6d-d0ce-489a-b4f1-b8e07a20ce0f)

**Comment by StevenMiller123** [comment]
@Crispy81 Errors like that one can be shared over in https://github.com/shadps4-emu/shadPS4/issues/496, though they're very different from the PM4 Type 0 errors mentioned here.

**Comment by Crispy81** [comment]
No problems. I found 3 more similar errors, but they had different codes.. some had compute: 664 and compute:700 so they're all for different things. I tested all 327 of my games.

**Comment by Vimvoord** [comment]
Bump. Same issue.
[shad_log.txt](https://github.com/user-attachments/files/17995378/shad_log.txt)

**Comment by kennybruhbruh** [comment]
^^
[shad_log.txt](https://github.com/user-attachments/files/18008879/shad_log.txt)

**Comment by Hermiten** [comment]
@Vimvoord @kennybruhbruh you don't use a branch from here. Please don't report this here, you will not have support

**Comment by Hermiten** [comment]
Like @StevenMiller123 , this can be report on #496 
But when you do a test, you may not use cheat nor mods. 
I'm closing this one

**Comment by NiclasNike** [comment]
@Hermiten Please stop closing this one, it does happen on main and it happens all the time (for some of us). What Steven mentioned was PM4 type 3 with an opcode, those goes into #496

**Comment by StevenMiller123** [comment]
@Hermiten I do not believe PM4 Type 0 errors belong in the opcodes aggregate issue, as PM4 Type 0 errors are completely unrelated to PM4 Type 3 opcodes.

**Comment by Vimvoord** [comment]
> @Vimvoord @kennybruhbruh you don't use a branch from here. Please don't report this here, you will not have support

It doesn't matter which branch I use. Happens on all forks including main.

**Comment by Missake212** [comment]
> > @Vimvoord @kennybruhbruh you don't use a branch from here. Please don't report this here, you will not have support
> 
> It doesn't matter which branch I use. Happens on all forks including main.

Then send a log of it happening on main instead of a fork.

**Comment by Hermiten** [comment]
> > > @Vimvoord @kennybruhbruh you don't use a branch from here. Please don't report this here, you will not have support
> > 
> > 
> > It doesn't matter which branch I use. Happens on all forks including main.
> 
> Then send a log of it happening on main instead of a fork.

Exactly

**Comment by Alekay1310** [comment]
on main release 0.4.0 still same issue 
[shad_log.txt](https://github.com/user-attachments/files/18033991/shad_log.txt)
