### ISSUE TITLE
Anyone have the correct 1.09 update patch for CUSA03014?

### ISSUE THREAD

**Issue by jzhang306** [shadps4-emu/shadPS4#1579]
The game starts with 15 fps in version 1.00 and 1.09, but it will crash if I have any patch selected. 1.00 game has firmware version 4.50, but my 1.09 update for this version has a firmware version 3.00. I used patches from GoldHen repository. Could anyone tell me if I had the wrong update patch or just something else, please?
Thank you!

**Comment by jzhang306** [comment]
[Loader] <Info> memory_patcher.cpp:OnGameLoaded:330: Patches loaded successfully
[Loader] <Error> memory_patcher.cpp:OnGameLoaded:223: No patch file found for the current serial.
So by now there is no patch for this version? This is an authentic version since it uses Japanese voice and subtitles.

**Comment by jzhang306** [comment]
Solved, but need more time to use mod to fix.

**Comment by Hermiten** [comment]
This is absolutely forbidden to share patch. You have to dump your game with your version.
