### ISSUE TITLE
Exe does not open only a blank CMD

### ISSUE THREAD

**Issue by Hallowflame** [shadps4-emu/shadPS4#1585]
Hello,
My problem is like the title, only the cmd opening, i can select where to install my games and that's it. 
What i have tried so far : Installing / reinstalling c++ 2015-2022 , i have only one drice, C, i moved it some places there, i have tried running it as an administrator, updating my GPU driver, and so on.  I have tried using their forum but my post was not approved and the forum basically has zero activity.

Specs, Ryzen 5 5600H,   3050RTX (yeah ik ik)    32GB RAM

Any ideas or solutions? It's not about the emulation alone anymore, it's about solving the issue itself too... :D 
I've seen people around having the same issue, no solutions or replies, some articles had people having thier problem solver with c++ reinstall, but some are still trying to figure out a fix.

Can someone help us with that one? Thank you!

**Comment by DanielSvoboda** [comment]
Have you tried downloading the latest version from the official website to make C++ work correctly?
try installing through this link: https://aka.ms/vs/17/release/vc_redist.x64.exe
and what is your operating system?

**Comment by Hallowflame** [comment]
> Have you tried downloading the latest version from the official website to make C++ work correctly? try installing through this link: https://aka.ms/vs/17/release/vc_redist.x64.exe and what is your operating system?

Hello!
Yes, i have tried it, restarted pc too, even know i downloaded and pressed repair and restart, doesn't seem to work.

I'm using windows 10, when i open the task manager, i can see the emu there taking around 10-11% processor usage, and 32mb of ram, non changing but i do not see the UI coming up, i'm using the qt version, and i also have a few versions in store.

**Comment by Litnesslegitimate** [comment]
It's possible that the PKG is just broken or smth, try re-dumping it or find a new one
If not and you have the extra space maybe try dualbooting with WIn11 or a fresh win10 install? (You could also just factory reset or smth if you don't care about the files you have, just make sure not to wipe the OS)

I made a windows partition not too long ago and both 10 and 11 worked fine without tinkering, so if it's not the OS your hardware might be having issues. Might also be worth looking into some 0.3.1 builds or something

**Comment by Hallowflame** [comment]
> It's possible that the PKG is just broken or smth, try re-dumping it or find a new one If not and you have the extra space maybe try dualbooting with WIn11 or a fresh win10 install? (You could also just factory reset or smth if you don't care about the files you have, just make sure not to wipe the OS)
> 
> I made a windows partition not too long ago and both 10 and 11 worked fine without tinkering, so if it's not the OS your hardware might be having issues. Might also be worth looking into some 0.3.1 builds or something

I have tried other versions too but no luck, currently i need my other files and can't do a clean reinstall on windows. Looks like i cannot solve that issue somehow, anyways, thanks.

**Comment by cropper3** [comment]
I am having the same problem.  I am running shadPS4 on windows 10.0.19045, Ryzen 7 7700, RTX 4060, 32GB RAM.  I have removed and reinstalled all of the vcredfist files using a package manager with no change:

vcredist140 14.42.34433
vcredist2005 8.0.50727.619501
vcredist2008 9.0.30729.616104
vcredist2010 10.0.40219.32503
vcredist2012 11.0.61031.20230518
vcredist2013 12.0.40660.20180427
vcredist2015 14.0.24215.20170201
vcredist2017 14.16.27052
vcredist-all 1.0.1

When starting from the command line I see no error messgaes and get no log files inside the shadps4 directory.  If I delete /user/config.toml I will see the option to select a game install directory teh next time I launch the emulator, but after that it crashes with no error message.

Windows application event log shows the following after the creash:

Log Name:      Application
Source:        Application Error
Date:          11/26/2024 12:14:17 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      TH-Gaming
Description:
Faulting application name: shadPS4.exe, version: 0.0.0.0, time stamp: 0x6741b3ba
Faulting module name: shadPS4.exe, version: 0.0.0.0, time stamp: 0x6741b3ba
Exception code: 0xc0000005
Fault offset: 0x00000000001400ed
Faulting process id: 0x2eec
Faulting application start time: 0x01db3fca6c75341a
Faulting application path: C:\Emulator\ShadPS4-Latest\shadPS4.exe
Faulting module path: C:\Emulator\ShadPS4-Latest\shadPS4.exe
Report Id: 737d62d4-6c38-40be-a0aa-7c71b99b181e
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-11-26T06:14:17.7952316Z" />
    <EventRecordID>22400</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>TH-Gaming</Computer>
    <Security />
  </System>
  <EventData>
    <Data>shadPS4.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>6741b3ba</Data>
    <Data>shadPS4.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>6741b3ba</Data>
    <Data>c0000005</Data>
    <Data>00000000001400ed</Data>
    <Data>2eec</Data>
    <Data>01db3fca6c75341a</Data>
    <Data>C:\Emulator\ShadPS4-Latest\shadPS4.exe</Data>
    <Data>C:\Emulator\ShadPS4-Latest\shadPS4.exe</Data>
    <Data>737d62d4-6c38-40be-a0aa-7c71b99b181e</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by cropper3** [comment]
I also got curious and installed and older version of ShadPS4 (0.2.0) that I happened to have archived and when running that version I get a different windows event log error that may be helpful as it does reference a different module - ucrtbase.dll.

This seems to indicate that it is not somthing in the newer versions of the emulator, but rather something has changed on my PC as this version used to work fine for me a few weeks ago, however I have not made major changes to my PC or configuration since then.  I do believe I had windows updates and component updates from my package manager recently though, so I suspect that may have something to do with these errors: 

Log Name:      Application
Source:        Application Error
Date:          11/26/2024 12:14:54 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      TH-Gaming
Description:
Faulting application name: shadPS4.exe, version: 0.0.0.0, time stamp: 0x66be344e
Faulting module name: ucrtbase.dll, version: 10.0.19041.3636, time stamp: 0x81cf5d89
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x708
Faulting application start time: 0x01db3fca82ab9dfd
Faulting application path: C:\Emulator\ShadPS4-020\shadPS4.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 3ecb16aa-f405-4236-85c2-404053ffdd05
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-11-26T06:14:54.9964922Z" />
    <EventRecordID>22402</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>TH-Gaming</Computer>
    <Security />
  </System>
  <EventData>
    <Data>shadPS4.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>66be344e</Data>
    <Data>ucrtbase.dll</Data>
    <Data>10.0.19041.3636</Data>
    <Data>81cf5d89</Data>
    <Data>c0000409</Data>
    <Data>000000000007286e</Data
    <Data>01db3fca82ab9dfd</Data>
    <Data>C:\Emulator\ShadPS4-020\shadPS4.exe</Data>
    <Data>C:\Windows\System32\ucrtbase.dll</Data>
    <Data>3ecb16aa-f405-4236-85c2-404053ffdd05</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

I would be happy to do further troubleshooting if someone can suggest some testing that would be useful.

Thanks!

**Comment by cropper3** [comment]
After looking at several other posts for similar issues this turned out to be a video card driver problem.  I installed the latest game ready driver and now I can load into the GUI.

**Comment by Hallowflame** [comment]
> After looking at several other posts for similar issues this turned out to be a video card driver problem. I installed the latest game ready driver and now I can load into the GUI.

I already have the latests, one of my first step was updating all the drivers, i have no idea what's left

**Comment by 1UPz** [comment]
> > After looking at several other posts for similar issues this turned out to be a video card driver problem. I installed the latest game ready driver and now I can load into the GUI.
> 
> I already have the latests, one of my first step was updating all the drivers, i have no idea what's left

reinstall gpu driver worked for me and i didn't used ddu.

**Comment by Hallowflame** [comment]
> > > After looking at several other posts for similar issues this turned out to be a video card driver problem. I installed the latest game ready driver and now I can load into the GUI.
> > 
> > 
> > I already have the latests, one of my first step was updating all the drivers, i have no idea what's left
> 
> reinstall gpu driver worked for me and i didn't used ddu.

I uninstalled my GPU driver, did a reinstall and still does not work. :(

**Comment by 1UPz** [comment]
> > > > After looking at several other posts for similar issues this turned out to be a video card driver problem. I installed the latest game ready driver and now I can load into the GUI.
> > > 
> > > 
> > > I already have the latests, one of my first step was updating all the drivers, i have no idea what's left
> > 
> > reinstall gpu driver worked for me and i didn't used ddu.
> 
> I uninstalled my GPU driver, did a reinstall and still does not work. :(

Did you installed the visual c++ decencies?

Here's the techpowerup link: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

And also did the emulator was working on a older version of the GPU driver?

**Comment by Hallowflame** [comment]
> > > > > After looking at several other posts for similar issues this turned out to be a video card driver problem. I installed the latest game ready driver and now I can load into the GUI.
> > > > 
> > > > 
> > > > I already have the latests, one of my first step was updating all the drivers, i have no idea what's left
> > > 
> > > 
> > > reinstall gpu driver worked for me and i didn't used ddu.
> > 
> > 
> > I uninstalled my GPU driver, did a reinstall and still does not work. :(
> 
> Did you installed the visual c++ decencies?
> 
> Here's the techpowerup link: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
> 
> And also did the emulator was working on a older version of the GPU driver?

I'm the OP of the post, i wrote it down that i already tried reinstalling c++. and other versions of the emulator with no luck so far, but thank you for the tip.

**Comment by Foul-Tarnished** [comment]
Try ``dism /online /cleanup-image /scanhealth && dism /online /cleanup-image /restorehealth && sfc /scannow`` in the command prompt (ran as admin)

Should repair any corrupted windows system files

**Comment by NDIAGLIE** [comment]
> > > > > > After looking at several other posts for similar issues this turned out to be a video card driver problem. I installed the latest game ready driver and now I can load into the GUI.
> > > > > 
> > > > > 
> > > > > I already have the latests, one of my first step was updating all the drivers, i have no idea what's left
> > > > 
> > > > 
> > > > reinstall gpu driver worked for me and i didn't used ddu.
> > > 
> > > 
> > > I uninstalled my GPU driver, did a reinstall and still does not work. :(
> > 
> > 
> > Did you installed the visual c++ decencies?
> > Here's the techpowerup link: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
> > And also did the emulator was working on a older version of the GPU driver?
> 
> I'm the OP of the post, i wrote it down that i already tried reinstalling c++. and other versions of the emulator with no luck so far, but thank you for the tip.

hey sorry  but I am having the same problem and I am desperate, if you have found a solution please let me know

**Comment by Missake212** [comment]
Is it still happening? If it still doesn't work try updating your iGPU drivers, sometimes they're the reason why the emulator crashes on startup
