### ISSUE TITLE
PKG extraction stops at 19%

### ISSUE THREAD

**Issue by sarfaraz1373** [shadps4-emu/shadPS4#1592]
My system is:
Windows 10 - Corei7 4790k - 16gb RAM - SSD

I have the same problem in both version 4 stable and preview releases.
![Uploading untitled.JPG…]()

**Comment by Randomuser8219** [comment]
What game are you trying to install?

**Comment by archonveins** [comment]
mine gets stuck at 93%
the game is quite large though (16gb) 24 when extracted via pkgeditor tool.
game is gravity rush 2

**Comment by georgemoralis** [comment]
That won't be an issue since new version doesn't have pkg extraction
