### ISSUE TITLE
CUSA03173 Bloodborne: param.sfo corrupt, losing save file

### ISSUE THREAD

**Issue by CkRnSt** [shadps4-emu/shadPS4#1596]
Build: 2024-11-24-921e66e (the "tessellation build"?) from [here](https://github.com/diegolix29/shadPS4/releases/tag/release-shadPS4-2024-11-24-921e66e)
Specs: 
```
Win 10 Pro 64-bit (10.0, Build 19045)
AMD Ryzen 7 7700X
32GB ram
RTX 3070 Ti (driver 560.94)
```

2 days ago I was playing BB fine and have a 5hr40m save file that I'd really hate to lose. When I was finished playing I exited the game to the main game menu before closing the shadPS4 window. Currently, starting BB crashes the emulator before getting to the main menu. I've narrowed the issue with the save file:

1. renaming the `user/savedata/1/CUSA03173` folder lets BB start but obviously with no save file
2. More specifically, deleting the `user/savedata/1/CUSA03173/SPRJ0005/sce_sys/param.sfo` file lets BB launch with no save. 

The editor is correctly showing my unlocked trophies in the Trophy Viewer, though I can't open the SFO Viewer for this or any other game. I've seen some SFO viewer programs online though don't know what to make of them, and have looked a bit at [what the file actually is](https://www.psdevwiki.com/ps4/Param.sfo).

I've attached my save folder and log file. Any help to get it loading is much appreciated. Thanks.

[shad_log.txt](https://github.com/user-attachments/files/17904994/shad_log.txt)
[CUSA03173.zip](https://github.com/user-attachments/files/17904999/CUSA03173.zip)

**Comment by Foul-Tarnished** [comment]
That's why you should zip your savefile after each session, worst case scenario you lose 1 day of playtime

**Comment by Hermiten** [comment]
Thanks for the report, we only support test on main branch from here. 
Sorry for this problem but it's an emulator in alpha, it's always better to do backup of save :/
