### ISSUE TITLE
Access violation happens during retrieving PFSC from decrypted pfs_image

### ISSUE THREAD

**Issue by ACGNnsj** [shadps4-emu/shadPS4#1617]
I've merged split packages via PS4 Package Viewer and tried to install the pkg file.
Access violation occured here: 
```cpp
std::memcpy(pfsc.data(), pfs_decrypted.data() + pfsc_offset, length - pfsc_offset);
```

**Comment by Hermiten** [comment]
Can you please provide more information:
OS, Which game (CUSA), wihch version of shadps4, etc ?

Thanks you
