### ISSUE TITLE
Error while building 

### ISSUE THREAD

**Issue by Tentacle-Monster** [shadps4-emu/shadPS4#1618]
Please specify which version of clang is supposed to be used. 
When building with 18 and above there is an unknown error for the [cryptopp-cmake](https://github.com/abdes/cryptopp-cmake) library
`[ 32%] Linking CXX static library libcryptopp.a
[ 32%] Built target cryptopp
gmake: *** [Makefile:156: all] Error 2
`
And on versions 17 and below compiller can't process cpp20
`/src/core/linker.h:104:30: error: no member named 'contains' in namespace 'std::ranges'
  104 |             if (std::ranges::contains(imports, m->name, &ModuleInfo::name)) {
`
Am i supposed to generate *.a files separately in an earlier clang version?
Cmake version 3.25.1, operation system debian 12 bookworm.

**Comment by GHU7924** [comment]
https://github.com/shadps4-emu/shadPS4/pull/1549
