### ISSUE TITLE
Emulator version and github hash, title name, title code, title version, FPS counter

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#162]
Hello!
please, add emulator version (i.e. `shadps4-win64-v0.0.3` for stable or `shadps4-win64-nightly-github_hash` for currently developed but not released in GH Releases), title name, title code, title version, FPS counter in window titlebar.

**Comment by Xphalnos** [comment]
All the features you mentioned have been implemented. This feature request can be marked as completed.
