### ISSUE TITLE
shadps4 using 100% of CPU while Project DIVA X 1.02 update (CUSA04518) is booting 

### ISSUE THREAD

**Issue by PDAFTS** [shadps4-emu/shadPS4#1623]
When starting the game Project DIVA X (CUSA04518) in version 1.02, the emulator consumes all of my CPU, making it impossible to open the game

build used: [shadps4-win64-qt-2024-11-30-284b084](https://github.com/shadps4-emu/shadPS4/actions/runs/12092673666/artifacts/2255838684)

![Captura de tela 2024-11-29 231958](https://github.com/user-attachments/assets/941b824c-d55b-41a1-83e6-363a4c655b43)

specs:
AMD Ryzen 5 3500X
8GB ram
GeForce GTX 1050Ti

log:
[shad_log.txt](https://github.com/user-attachments/files/17963981/shad_log.txt)

**Comment by squidbus** [comment]
I believe this is fixed by <https://github.com/shadps4-emu/shadPS4/pull/1615> if you want to try downloading from the actions artifacts.

**Comment by PDAFTS** [comment]
didn't work for me, still using 100% CPU :(

**Comment by Hermiten** [comment]
Diva X can only boot for now and have problem with intro. You can try sometimes if there is a progress.
I'm closing this one because it's a know problem
