### ISSUE TITLE
Build 666b060 is asking for install directory every time.

### ISSUE THREAD

**Issue by Crispy81** [shadps4-emu/shadPS4#1625]
Just as an fyi - the latest nightly build is prompting for the install directory, even though it's already set in the emulator settings, every time it is launched.

![image](https://github.com/user-attachments/assets/239b37c5-b5fd-4ec1-ac30-0d3e415adac7)

![image](https://github.com/user-attachments/assets/dd8cc3a2-a4e1-4de9-af79-18a597f1cde9)

**Comment by Missake212** [comment]
Should be fixed once squidbus:fix-config is merged

**Comment by Missake212** [comment]
Should be fixed once #1626 is merged

**Comment by Crispy81** [comment]
Good shitake.

**Comment by Missake212** [comment]
It's merged now, can close this issue.
