### ISSUE TITLE
Blank CMD upon launch

### ISSUE THREAD

**Issue by tLots0213** [shadps4-emu/shadPS4#1634]
I've already tried reinstalling Visual C++ and I am on the QT version.

While messing with my drivers, I managed to get the GUI open ONLY when my NVIDIA drivers are being reinstalled; Specifically when the old driver has been removed and the new driver hasn't finished installing. When it worked, I tried running Bloodborne v1.09 but it showed a black screen and crashed. I'm using v11.00 sysmodules. It somehow runs correctly (although very laggy) when I disable either one of my GPU's through device manager.

My system:
Ryzen 7 5800H
RTX3070 Laptop GPU
32GB DDR4 3200
Windows 11 23H2

**Comment by 1UPz** [comment]
reinstall gpu driver worked for me and i didn't used ddu.
but have you tried ddu?
downgrade your nvdia driver?

**Comment by tLots0213** [comment]
I have not but it was not working before I updated so is there a specific version I should downgrade to?

**Comment by 1UPz** [comment]
try 560.xx

**Comment by tLots0213** [comment]
Ok, so it does work when I downgrade to 512.74 but it doesn't work even on a fresh install of the latest version 566.14. I'm gonna try reinstalling drivers for the iGPU.

**Comment by 1UPz** [comment]
Ok

**Comment by tLots0213** [comment]
Alright, it works now after reinstalling everything. It also works now with the latest NVIDIA driver.

**Comment by NDIAGLIE** [comment]
> I've already tried reinstalling Visual C++ and I am on the QT version.
> 
> While messing with my drivers, I managed to get the GUI open ONLY when my NVIDIA drivers are being reinstalled; Specifically when the old driver has been removed and the new driver hasn't finished installing. When it worked, I tried running Bloodborne v1.09 but it showed a black screen and crashed. I'm using v11.00 sysmodules. It somehow runs correctly (although very laggy) when I disable either one of my GPU's through device manager.
> 
> My system: Ryzen 7 5800H RTX3070 Laptop GPU 32GB DDR4 3200 Windows 11 23H2

dude I have been looking for a fucking solution for literal days on end...thank you so very much

**Comment by tLots0213** [comment]
You are very welcome good hunter.
