### ISSUE TITLE
Shadps4 crashing when i click any button on my controller in BB

### ISSUE THREAD

**Issue by PerryIdol** [shadps4-emu/shadPS4#1642]
The game starts up and i can chose between play online or offline but when i try to press anything on my controller it freezes and crashes the whole shadps4. The terminal shows errors that i have a file dvdroot_ps4/menu/.gfx missing:
[Kernel.Pthread] <Error> file_system.cpp:posix_stat:403: posix_stat: error = -2147352574
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/menu/.gfx flags = 0x0 mode = 0
[Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=D:/shad/shadps4-win64-qt-2024-11-30-68bd22bfc10b6430ecde6e57eb249d9169ad04d6/Games/CUSA00900\dvdroot_ps4/menu/.gfx, error_message=no such file or directory
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:370: (PARTIAL) path = /app0/dvdroot_ps4/menu/.gfx
[Kernel.Pthread] <Error> file_system.cpp:posix_stat:403: posix_stat: error = -2147352574
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/menu/.gfx flags = 0x0 mode = 0
[Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=D:/shad/shadps4-win64-qt-2024-11-30-68bd22bfc10b6430ecde6e57eb249d9169ad04d6/Games/CUSA00900\dvdroot_ps4/menu/.gfx, error_message=no such file or directory
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:370: (PARTIAL) path = /app0/dvdroot_ps4/menu/.gfx
[Kernel.Pthread] <Error> file_system.cpp:posix_stat:403: posix_stat: error = -2147352574
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/menu/.gfx flags = 0x0 mode = 0
[Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=D:/shad/shadps4-win64-qt-2024-11-30-68bd22bfc10b6430ecde6e57eb249d9169ad04d6/Games/CUSA00900\dvdroot_ps4/menu/.gfx, error_message=no such file or directory

And there is some other errors that i have no clue what they mean:

[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type Interpreter Path
[Core.Linker] <Info> module.cpp:LoadModuleToMemory:196: TLS virtual address = 0x9050d8040
[Core.Linker] <Info> module.cpp:LoadModuleToMemory:197: TLS image size      = 1872
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type SCE Comment
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type SCE Library Version
[Core.Linker] <Info> module.cpp:LoadModuleToMemory:224: program entry addr ..........: 0x00000008ffffc0a0
[Loader] <Error> memory_patcher.cpp:OnGameLoaded:199: Unable to open files.json for reading.

[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type SCE Module Parameters
[Core.Linker] <Info> module.cpp:LoadModuleToMemory:196: TLS virtual address = 0x9100b4018
[Core.Linker] <Info> module.cpp:LoadModuleToMemory:197: TLS image size      = 1184
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type SCE Comment
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type SCE Library Version

[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type SCE Module Parameters
[Core.Linker] <Info> module.cpp:LoadModuleToMemory:196: TLS virtual address = 0x91fffc000
[Core.Linker] <Info> module.cpp:LoadModuleToMemory:197: TLS image size      = 0
[Core.Linker] <Error> module.cpp:LoadModuleToMemory:219: Unimplemented type SCE Library Version

[Core] <Error> stubs.cpp:CommonStub:42: Stub: scePthreadSetaffinity (nid: bt3CTBKmGyI) called, returning zero to 0x901e3b1c4
[Core] <Error> stubs.cpp:CommonStub:42: Stub: scePthreadSetaffinity (nid: bt3CTBKmGyI) called, returning zero to 0x902637473
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:56: (DUMMY) called module = ORBIS_SYSMODULE_NP_TROPHY
[Lib.SysModule] <Error> sysmodule.cpp:sceSysmoduleLoadModule:56: (DUMMY) called module = ORBIS_SYSMODULE_PLAYGO

**Comment by rainmakerv3** [comment]
Are you using a fork? If not, what specific build are you using? Also might help to post the entire log, I think I may know what this is

**Comment by PerryIdol** [comment]
I am sorry i'm new to this and i don't really know the diffrence between a fork and build, I just followed a YT tutorial. I downloaded shadps4 from diegolix29(Dmugetsu) github page and it says it's forked from shadps4-emu/shadPS4 so i think it's a fork.

And here is the whole log
[shad log.txt](https://github.com/user-attachments/files/17975806/shad.log.txt)

**Comment by rainmakerv3** [comment]
This is an issue with that particular fork but you may be able to fix it by updating. Either way, forks are not supported here so we cannot continue this converstion and maybe you ask on the discord instead

**Comment by PerryIdol** [comment]
Ok, thanks for help.

**Comment by enderbroo** [comment]
has this problem been solved yet? I just ran into the same problem, but I still haven't figured out the solution. Help please.
