### ISSUE TITLE
i don't know what happened, but i can't play Bloodborne anymore

### ISSUE THREAD

**Issue by DogBanana** [shadps4-emu/shadPS4#1647]
After i finished the game, i started a new game+, it went very well until... it didn't. When i try to open my save, this debug critical error appears on cmd and freezes my pc, just to close after it. Also, it seems, the game opens normally after i rename the sfx folder, but, of course, without the visual effects. Anyone knows what happened here and how can i fix it?

if it is important, here's my specs:
Ryzen 5 5500
RX 6600 8gb
2x8gb ddr4 3200mhz

![issue-image](https://github.com/user-attachments/assets/91afa29a-5edd-4a83-b96d-2027fe14f4e8)

**Comment by Foul-Tarnished** [comment]
Give your full (sync) log...

Does it work with a new save ?

**Comment by DogBanana** [comment]
> Give your full (sync) log...
> 
> Does it work with a new save ?
![imagem_2024-12-02_050202518](https://github.com/user-attachments/assets/3b06a60c-5ed7-4163-bcbd-8b22f680eb7f)

[sync-log.txt](https://github.com/user-attachments/files/17974723/sync-log.txt)

i tried to get the sync log, but it crashed before the debug critical

and doesn't works with new saves

also i tried to reinstall the emulator and the game in another disk, but the same issue happened

**Comment by Missake212** [comment]
Could you try to install the main fork? You're on mainBB

**Comment by DogBanana** [comment]
> Could you try to install the main fork? You're on mainBB

probably, but as i said, it was working properly until it don't works anymore, but i can try later

**Comment by Missake212** [comment]
The thing is mainBB is a fork, the one able to help you is the the owner of that fork, the devs and collaborators don't have anything to do with that fork so an issue shouldn't be opened here in the first place, you should ask Diegolix

**Comment by Hermiten** [comment]
We don't support fork branch. Please ask on their GitHub and not here.

**Comment by DogBanana** [comment]
> We don't support fork branch. Please ask on their GitHub and not here.



> The thing is mainBB is a fork, the one able to help you is the the owner of that fork, the devs and collaborators don't have anything to do with that fork so an issue shouldn't be opened here in the first place, you should ask Diegolix

oh, okay, sorry, their github doesn't have an issues section, so i tried here

**Comment by Foul-Tarnished** [comment]
Don't use shitty broken builds :)
