### ISSUE TITLE
BB crashes directly to windows after new update - Failed to create graphics pipeline: ErrorUnknown

### ISSUE THREAD

**Issue by markomaniax** [shadps4-emu/shadPS4#1651]
Hi,

As described in title, the game (Bloodborne) crashes after the newest update (0.4.1 WIP mainBB **fe9a257**.
It is tess shader build, and it worked flawlessly yesterday.

This is the part from the log that might give you some clues:
`[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:459: Compiling fs shader 0x71c96598
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:459: Compiling ls shader 0x4cd21a0f
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:459: Compiling hs shader 0x8453cd1c
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:459: Compiling vs shader 0x7f03e945
[Debug] <Critical> vk_graphics_pipeline.cpp:operator():341: Assertion Failed!
Failed to create graphics pipeline: ErrorUnknown`

Any workaround or should I just wait for upcoming update?

Tip - if possible, please implement something like undo patch option.

**Comment by roamic** [comment]
We do not provide support for issues in forks. Please contact fork owner for this issue.
