### ISSUE TITLE
CUSA03173 Bloodborne - Dark&Light Flickerings glitches

### ISSUE THREAD

**Issue by EmulaNoob** [shadps4-emu/shadPS4#1654]
Since the shad had alot of progress this issue always happening with my experience, tried ask to people on community but nobody answers, knows, solve or explain why that issue happening. Is there anyway to analysis and fix this flickerings? Hope someone look for this issue.

https://github.com/user-attachments/assets/d03ff525-e3e5-4dae-84e3-86b432792f32

Here's the log too from the currently build:
[shad_log.txt](https://github.com/user-attachments/files/17986049/shad_log.txt)

**Comment by Missake212** [comment]
You're on a fork, discuss this issue with the owner of the fork not here

**Comment by roamic** [comment]
We do not provide support for issues in forks. Please contact the fork owner regarding this issue. You can re-open this issue if it is reproduced on shadPS4 main branch.
