### ISSUE TITLE
The Witch and the Hundred Knight 2 does not start with AMD

### ISSUE THREAD

**Issue by ChronoRPG** [shadps4-emu/shadPS4#1666]
Greetings

When I start the game The Witch and the Hundred Knight 2 on the ShadPS4, it closes instantly. I’m sharing my log file. I enabled Vulkan validation options in the debugger.

I hope it helps to identify the issue.

[shad_log.txt](https://github.com/user-attachments/files/18014862/shad_log.txt)

**Comment by Hermiten** [comment]
Ok, thanks you, you can report it here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/25
But please on the version 0.4 (not 0.4.1)
