### ISSUE TITLE
Critical error on emulation

### ISSUE THREAD

**Issue by masinov** [shadps4-emu/shadPS4#1678]
I'm getting this error running the latest builds:

[Debug] <Critical> signals.cpp:SignalHandler:85: Unreachable code!
Unhandled access violation in thread 'FMOD mixer thre' at code address 0x715fcd9261fd: Read from address 0x0

A more complete part of the log that may be related to the error:
[Lib.AudioOut] <Info> audioout.cpp:sceAudioOutOpen:283: AudioOutOpen id = 255 port_type = MAIN index = 0 lenght= 256 sample_rate = 48000 param_type = FLOAT_8CH attr = NONE
[Lib.AudioOut] <Info> audioout.cpp:sceAudioOutOpen:283: AudioOutOpen id = 255 port_type = BGM index = 0 lenght= 256 sample_rate = 48000 param_type = FLOAT_8CH attr = NONE
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_mixer.fev flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multimix.mix
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multimix.mix
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_multimix.mix flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multimix.mix
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/dvdroot_ps4/sound/sprj_multimix.mix
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multich.mch
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multich.mch
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_multich.mch flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multich.mch
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multich.mch
[Debug] <Critical> signals.cpp:SignalHandler:85: Unreachable code!
Unhandled access violation in thread 'FMOD mixer thre' at code address 0x7e91343261fd: Read from address 0x0

I'm using the qt interface and running it on Arch Linux. 

I'm trying to run Bloodborne. It happens when launching the game. No image loads, the critical error is returned and emulation stops.

Tell me if you need any more information for debugging.

**Comment by masinov** [comment]
Located the exact point/action where this starts happening:
[f43c6de](https://github.com/shadps4-emu/shadPS4/actions/runs/12165041578/artifacts/2274888049)

**Comment by Missake212** [comment]
Would be useful to know on what game this happens

**Comment by enfal-r** [comment]
I'm having exact same issue with Bloodborne.

**Comment by masinov** [comment]
> Would be useful to know on what game this happens

Updated main post. Happens in Bloodborne.

**Comment by AdityaHebballe** [comment]
This only seems to happen with the qt version, anyone managed to fix it?

**Comment by teenkamael** [comment]
I have the same message but with another code (I just downloaded last version from main):
```
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_mixer.fev flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multimix.mix
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multimix.mix
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_multimix.mix flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multimix.mix
 [Debug] <Critical> signals.cpp:SignalHandler:85: Unreachable code!
Unhandled access violation in thread 'FMOD mixer thre' at code address 0x716b4ff2725d: Read from address 0x0
```
I don't know if it is somewhat related to user's hardware or it could be related to several access that can be related between codes.
I am on ubuntu in my case.

**Comment by kalaposfos13** [comment]
@teenkamael This is already reported by me at https://github.com/shadps4-emu/shadPS4/issues/1704
It is a problem with userfaultfd

**Comment by teenkamael** [comment]
Guys with the new build without the userfaultd, the code address is 0x7998d3a98d61:
```
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_mixer.fev flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Debug] <Critical> signals.cpp:SignalHandler:85: Unreachable code!
Unhandled access violation in thread 'FMOD mixer thre' at code address 0x7998d3a98d61: Read from address 0x0
Violación de segmento ('core' generado) - translation: segmentation fault (core dumped) [I think, I didn't found any literal message alike]
```
At least it is not the same error

**UPDATE:** After last update the error now is:
```
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/dvdroot_ps4/sound/sprj_mixer.fev
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/dvdroot_ps4/sound/sprj_multirpc.rpc
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multimix.mix
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multimix.mix
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_multimix.mix flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multimix.mix
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/dvdroot_ps4/sound/sprj_multimix.mix
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multich.mch
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multich.mch
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/dvdroot_ps4/sound/sprj_multich.mch flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:460: (PARTIAL) path = /app0/dvdroot_ps4/sound/sprj_multich.mch
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/dvdroot_ps4/sound/sprj_multich.mch
[Core] <Error> stubs.cpp:CommonStub:42: Stub: scePthreadSetaffinity (nid: bt3CTBKmGyI) called, returning zero to 0x902637473
[Kernel.Vmm] <Warning> memory.cpp:sceKernelGetDirectMemorySize:22: called
[Kernel.Vmm] <Info> memory.cpp:sceKernelAllocateDirectMemory:54: searchStart = 0x0, searchEnd = 0x120000000, len = 0x20000, alignment = 0x10000, memoryType = 0x3, physAddrOut = 0x11ed00000
[Kernel.Vmm] <Info> memory.cpp:sceKernelMapDirectMemory:183: called, redirected to sceKernelMapNamedDirectMemory
[Kernel.Vmm] <Info> memory.cpp:operator():173: in_addr = 0xff0000000, out_addr = 0xff0000000, len = 0x20000, prot = 0x33, flags = 0x0, directMemoryStart = 0x11ed00000, alignment = 0x10000
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmMapComputeQueue:1273: ASC pipe 0 queue 0 mapped to vqueue 1
[Debug] <Critical> signals.cpp:SignalHandler:85: Unreachable code!
Unhandled access violation in thread 'FMOD mixer thre' at code address 0x7dda8f298d61: Read from address 0x0
Violación de segmento (`core' generado)
```

**Comment by Hermiten** [comment]
This issue is older than this one: https://github.com/shadps4-emu/shadPS4/issues/1704 but the last one have more information.
I'm closing this one as duplicate
