### ISSUE TITLE
Crash when looting a blood gem

### ISSUE THREAD

**Issue by Rheckar** [shadps4-emu/shadPS4#1682]
Happens in Mergo's Loft when looting the bloodgem on the corpse near the the two pigs

Happens in Defiled Cursed Chalice Dungeon Watchdog boss fight. When it dies and an item was supposed to be added it crashes. Also specific enemies if they drop a blood gem it cannot be looted and crashes.

Happens in Isz Dungeon Brainsucker boss fight. Also specific enemies if they drop a blood gem it cannot be looted and crashes.

Build:Shadps4 0.4.1 941a668

**Comment by Hermiten** [comment]
Hello, better to put it here:
https://github.com/shadps4-emu/shadPS4/issues/1641
There is to much issue, we cannot open an issue for each item or each mob that make crash

**Comment by Missake212** [comment]
> Hello, better to put it here: #1641 There is to much issue, we cannot open an issue for each item or each mob that make crash

I believe this is actually related to a regression caused by the way to Unity part 1, seems like beating any boss make the game close.
