### ISSUE TITLE
Auto Updater - Expand-Archive : A parameter cannot be found that matches parameter name 'DestinationPath'.

### ISSUE THREAD

**Issue by blackstar0** [shadps4-emu/shadPS4#1686]
Whenever I try to use the auto-updater, it gives me this error
```
Starting Update...
Expand-Archive : A parameter cannot be found that matches parameter name 'DestinationPath'.
At C:\Users\hblac\Downloads\shadps4-win64-qt-2024-12-06-8eacb88\user\temp_download_update\update.ps1:9 char:136
+ ... mp_download_update\temp_download_update.zip' -DestinationPath 'C:\Use ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Pscx.Commands.IO.Compression.ExpandArchiveCommand
```

I'm on 8eacb88 and I am trying to update 941a668.  I also am not sure how to expand the output if it would be helpful.

Edit: Just tried to update Pscx and it doesn't seem to have helped unless I am doing something wrong.

**Comment by DanielSvoboda** [comment]
Which Windows are you using?

Try running as administrator

**Comment by blackstar0** [comment]
I'm on Windows 10 and running as admin didn't work

**Comment by DanielSvoboda** [comment]
C:\Users\hblac\Downloads\shadps4-win64-qt-2024-12-06-8eacb88\user\temp_download_update\update.ps1
If you have this file in this path, open it as text and send it here to see where it was registered, as it apparently cannot locate the destination location that the emulator saved.

**Comment by blackstar0** [comment]
```
Set-ExecutionPolicy Bypass -Scope Process -Force
$binaryStartingUpdate = '000000000101001100000000011101000000000001100001000000000111001000000000011101000000000001101001000000000110111000000000011001110000000000100000000000000101010100000000011100000000000001100100000000000110000100000000011101000000000001100101000000000010111000000000001011100000000000101110'
$chars = @()
for ($i = 0; $i -lt $binaryStartingUpdate.Length; $i += 16) {
    $chars += [char]([convert]::ToInt32($binaryStartingUpdate.Substring($i, 16), 2))
}
$startingUpdate = -join $chars
Write-Output $startingUpdate
Expand-Archive -Path 'C:\Users\hblac\Downloads\shadps4-win64-qt-2024-12-06-8eacb88\user/temp_download_update\temp_download_update.zip' -DestinationPath 'C:\Users\hblac\Downloads\shadps4-win64-qt-2024-12-06-8eacb88\user/temp_download_update' -Force
Start-Sleep -Seconds 3
Copy-Item -Recurse -Force 'C:\Users\hblac\Downloads\shadps4-win64-qt-2024-12-06-8eacb88\user/temp_download_update\*' 'C:\Users\hblac\Downloads\shadps4-win64-qt-2024-12-06-8eacb88\'
Start-Sleep -Seconds 2
Remove-Item -Force 'C:\Users\hblac\Downloads\shadps4-win64-qt-2024-12-06-8eacb88\update.ps1'
Remove-Item -Force 'C:\Users\hblac\Downloads\shadps4-win64-qt-2024-12-06-8eacb88\temp_download_update.zip'
Start-Process 'C:\Users\hblac\Downloads\shadps4-win64-qt-2024-12-06-8eacb88\shadps4.exe'
Remove-Item -Recurse -Force 'C:\Users\hblac\Downloads\shadps4-win64-qt-2024-12-06-8eacb88\user/temp_download_update'
```

It and the folder itself are removed after the update, which seems like what its supposed to be doing, but without performing the update.

**Comment by DanielSvoboda** [comment]
The code is being generated correctly.
The only requirement would be powershell 5.1, but all Windows 10 already comes with it.
I really don't know what could have caused this, try updating using Windows Update...

**Comment by blackstar0** [comment]
I just tried to run the script by specifying Microsoft.PowerShell.Archive for Expand-Archive and it seemed to work as intended, so I guess it's trying to use Pscx and its not supposed to?

Edit: i just ended up uninstalling PSCX and its working fine now, I don't know if it was important but it's quite old at this point and most of it has been implemented.  I don't know if it is worthwhile to account for it in the install script or not

**Comment by Hermiten** [comment]
@blackstar0 You've opened it up again, is it still relevant?

**Comment by blackstar0** [comment]
Didn’t mean to
