### ISSUE TITLE
Bloodborne launches a black screen, before promptly crashing ShadPS4.

### ISSUE THREAD

**Issue by HammersAre4Killing** [shadps4-emu/shadPS4#1687]
After following installation and setup instructions, launching Bloodborne 1.09 through ShadPS4 causes the game to launch a black screen, which it sits on for around 10-15 seconds before closing all windows of ShadPS4, along with the terminal window.
![image](https://github.com/user-attachments/assets/42bdcbbf-2e1c-4cac-9aaf-fc7d51989173)

Specs:
AMD Ryzen 7 5800H
16 GB ram
RTX 3050 TI

Log:
[shad_log.txt](https://github.com/user-attachments/files/18049343/shad_log.txt)

**Comment by Hermiten** [comment]
You follow an unofficial guide and we don't support other branch than here. You can open a issue on the GitHub concerned. 
Thanks you
