### ISSUE TITLE
game crashes at "prey slaughtererd" screen

### ISSUE THREAD

**Issue by ephraimt09** [shadps4-emu/shadPS4#1695]
[shad_log.txt](https://github.com/user-attachments/files/18050849/shad_log.txt)

i play on GPD win 4 2024.  i just updated and now at every boss "prey slaughtered" screen the games crashes.  it didn't happen before the update.  ive tried beating vicar amelia and witch of hemwick many times but everytime i reach "prey slaughtered" the game crashes and starts me over right at the fog wall.  i have the usual patches and mods for performance and various bug fixes.  i also tried just 30 fps. and it still wont work.  i attached my log.

thanks!
[shad_log.txt](https://github.com/user-attachments/files/18050857/shad_log.txt)

**Comment by Hermiten** [comment]
Bloodborne is unstable and lot of work is made.
Please come here to have more information:
https://github.com/shadps4-emu/shadPS4/issues/1641

You can also try last version, they put lots of fixes
