### ISSUE TITLE
ERROR: Failed to open sce_discmap_patch.plt

### ISSUE THREAD

**Issue by C0rn3j** [shadps4-emu/shadPS4#1698]
~~I've been trying to run Bloodborne on the latest git master with no success, and~~ one of the things I noticed in https://github.com/shadps4-emu/shadPS4/issues/1045#issuecomment-2525340259 with CUSA03173 1.00 is the error in the title.

[shad_log.txt](https://github.com/user-attachments/files/18051640/shad_log.txt)

![image](https://github.com/user-attachments/assets/8c228155-844c-4bb6-b910-7b8e1b4df8c4)

My rip did end up with the discmap file but not the discmap_patch file, is this expected and the error is just mostly cosmetic, or is it actually a problem?

~~Also trying to add this directory as an ELF folder to shad just closes the file dialog with no errors or stdout logs whatsoever.~~ reported separately under #1703

**Comment by polybiusproxy** [comment]
The error is normal and nothing to worry about.

**Comment by C0rn3j** [comment]
It should then be dropped down to debug/info/warning at worst then, if it's not an actual error

**Comment by polybiusproxy** [comment]
We don't control that, since the file is loaded by an external library. Lowering down file open errors would hide actual errors.
