### ISSUE TITLE
Repo About was not updated along with the README

### ISSUE THREAD

**Issue by C0rn3j** [shadps4-emu/shadPS4#1699]
`PS4 emulator for Windows,Linux,MacOS`  
vs  
`PlayStation 4 emulator for Windows, Linux and macOS written in C++`

If nothing else, spaces should be added and "MacOS" capitalized as macOS:  
`PS4 emulator for Windows, Linux, macOS`

**Comment by Foul-Tarnished** [comment]
🤓 ☝️

**Comment by Hermiten** [comment]
Done !
