### ISSUE TITLE
Proposal for shadPS4 0.0.4

### ISSUE THREAD

**Issue by Xphalnos** [shadps4-emu/shadPS4#170]
I think it would be a good idea to upgrade to 0.0.4 because the development since the last version has been huge and we were able to launch our first game. Additionally on Github we are at 360 stars and almost 3000 downloads!

**Comment by raphaelthegreat** [comment]
For next release, I think we have everything in place and the only thing left is completing texture detiling support. So sometime this or next week

**Comment by Xphalnos** [comment]
Do you think that for the next version it would be good to upgrade to Clang 18 to take advantage of the latest patches?

**Comment by georgemoralis** [comment]
there isn't available clang-ci 18 for vstudio yet

**Comment by Xphalnos** [comment]
Fixed ! 😊
