### ISSUE TITLE
Emulator detects hard copied games with a different naming convention fine, but refuses to apply patches for them

### ISSUE THREAD

**Issue by C0rn3j** [shadps4-emu/shadPS4#1700]
I copied a BR dump of CUSA03173 with my own naming convention to the install directory - it loaded fine - ![image](https://github.com/user-attachments/assets/3e442c4d-e520-4f94-a22e-0e1a47edc5c0)

However, trying to install a patch for it failed to find it. I had to rename the dir to just `CUSA03173`, after which the patch installation detects the game.

If the emulator is capable of reading the game and its ID with a custom name, it should be able to associate such ID to the custom name and install there.

Mildly related to https://github.com/shadps4-emu/shadPS4/issues/1646 as it is about name handling also.

**Comment by Xphalnos** [comment]
I think it's not up to the emulator to guess which patch will go on which game. It must respect the CUSA to the letter because it could cause bugs for example if we have Bloodborne CUSA03173 and CUSA00900 twice, on which one will it install the patch?

**Comment by C0rn3j** [comment]
> for example if we have Bloodborne CUSA03173 and CUSA00900 twice, on which one will it install the patch

The CUSA it's made for, according to the detected serial?

Not sure what your hypothethical has to do with my issue of using path as a serial. Named or misnamed path, the hypothetical issue remains the same there - though I don't see what the problem is.

There is no guessing, it already detected the serial, I would appreciate if you could reopen the issue.

EDIT: Oh, twice. I missed that.   
A choice box that shows you the paths in that case, if a person has multiple versions of the same (not different) game installed.
