### ISSUE TITLE
Linux regression due to userfaultfd change

### ISSUE THREAD

**Issue by kalaposfos13** [shadps4-emu/shadPS4#1704]
https://github.com/shadps4-emu/shadPS4/pull/1640 has introduced enabling userfaultfd by default (and [this commit](https://github.com/shadps4-emu/shadPS4/commit/8ee672fe32702b232728ae193abf57d9468b5de1) added the ability to run it in user mode), which breaks basically my entire library of games on Linux Mint (games I tested that were previously working: Bloodborne, Minecraft, Gravity Rush Remastered, NieR: Automata and TLG (from splash screen to nothing)) , causing them to hang either indefinitely or just "only" so much that I didn't have the patience to wait it out (meaning more than 1 minute). Bloodborne sometimes also crashes here: `[Debug] <Critical> signals.cpp:SignalHandler:85: Unreachable code! Unhandled access violation in thread 'FMOD mixer thre' at code address 0x7f14c952725d: Read from address 0x0`
Commenting [this line]( https://github.com/shadps4-emu/shadPS4/blob/4fb2247196d4626bab8f2c28710b0c34cad053fe/CMakeLists.txt#L886) out to disable the change solves all related problems from happening.

**Comment by setepenre** [comment]
Can confirm, have to comment out said line before compiling to load in game bloodborne ; am running arch linux on intel cpu + nvidia gpu desktop.
I guess it would be great if userfaultfd could be enabled or disable with a flag when first calling cmake.
EDIT:
something like
```
if (${CMAKE_SYSTEM_NAME} STREQUAL "Linux" AND ENABLE_USERFAULTFD)
    target_compile_definitions(shadps4 PRIVATE ENABLE_USERFAULTFD)
endif()
```
with `cmake ... -DENABLE_USERFAULTFS=ON/OFF ...` seems to work on my end

EDIT after https://github.com/shadps4-emu/shadPS4/issues/1704#issuecomment-2529377695:
My desktop manager uses X11, unset $DISPLAY disallow sdl to open a windows ending up in an exception

**Comment by C0rn3j** [comment]
@setepenre ~~no such issues here with Arch + Nvidia with [AUR/shadps4-git](https://aur.archlinux.org/packages/shadps4-git) on https://github.com/shadps4-emu/shadPS4/commit/4fb2247196d4626bab8f2c28710b0c34cad053fe, odd.~~

Both GOTY and non-GOTY BB launches ~~fine~~ as long as $DISPLAY is unset.

![image](https://github.com/user-attachments/assets/5a163cfc-5709-437a-98f4-05c057de5729)

~~EDIT: Latest master works fine too (https://github.com/shadps4-emu/shadPS4/commit/fea2593ab4be8638426e4f608ebbe2314d83d9f6)~~


EDIT2: While the game LAUNCHES, it freezes in character creator

EDIT3: This seems to make an existing freezing issue more prominent but is not necessarily the cause of it.

**Comment by 7oxicshadow** [comment]
Can confirm that this build flag breaks Bloodborne for me.
![image](https://github.com/user-attachments/assets/6b757478-e236-419e-9907-09456a5cd4c9)

**Comment by ikmjssc** [comment]
x11 having this issue too

**Comment by knewman23** [comment]
Following for updates, same issue on steam deck

**Comment by Shoegzer** [comment]
Confirmed here too, Linux Mint 22 and X11.

Unfortunately, commenting out [this line](https://github.com/shadps4-emu/shadPS4/blob/4fb2247196d4626bab8f2c28710b0c34cad053fe/CMakeLists.txt#L886) as suggested above does not fix this issue.

Update: Fully resolved with #1777.

**Comment by zt64** [comment]
On Nvidia proprietary driver 565.77 on Wayland what worked for me was `env -u DISPLAY shadps4`

**Comment by ikmjssc** [comment]
commenting out that line worked for me on X11, but wayland still need to unset the DISPLAY variable. 
btw beware if (kde)screen scale is larger than 1.00x every fullscreen app will be smaller than the actual screen size by default

**Comment by C0rn3j** [comment]
The PR that makes userfaultfd opt-in has been merged, but for those that userfaultfd was causing crashes and not freezes, it would be nice if you posted a stack trace in here.

One can enable userfaultfd support during compile time via `-DENABLE_USERFAULTFD=ON` now.

**Comment by kavika13** [comment]
I am getting the freeze as well. It isn't Wayland specific. But I am also using KDE.

![image](https://github.com/user-attachments/assets/10517e28-e383-4b1c-af0b-566cbcb1bd2a)

nVidia driver is 565.77.

If I `CTRL + Z` on the console to put the process in the background, then `fg` to activate the process again, it gets unstuck.

This seems like a pretty useful thing to solve. I am getting MUCH better performance in the beginning of the Bloodborne DLC with userfaultfd enabled (notably the area with the worst performance in the game, as far as I've seen).

Edit: Here's a dump of the current threads, mixed with the GDB session log, and the emulator log (`gdb shadps4` -> `run` -> load my saved game that usually hangs, and it hangs this time -> wait for a bit to see if it unhangs, which it doesn't -> see some `[Thread 0x7fffa1ffb6c0 (LWP 254988) exited]` type messages -> hit `CTRL + C`, type `thread apply all bt`):

[gdb_log.txt](https://github.com/user-attachments/files/18220759/gdb_log.txt)

**Comment by kalaposfos13** [comment]
https://github.com/shadps4-emu/shadPS4/pull/1777 disabled this, so this problem is now temporarily solved, but ideally the devs will figure out the issue with the implementation and userfaultfd will be reintruduced without the current problem.
