### ISSUE TITLE
Unicorn Overlord - Crashed when entering the battle

### ISSUE THREAD

**Issue by substarX** [shadps4-emu/shadPS4#1709]
First of all, I've to say sorry for my poor English. I will detail the problems I encountered to the best of my ability.
I've tried to use the latest build (2024/12/08) to play the title mentioned game.
Everytime I tried to use my unit to fight with the enemy, the log always shows the following error.
Then the program crashed.

[Debug] <Critical> texture_cache.cpp:operator():213: Assertion Failed!

For details, please find the log file that I've uploaded.

[shad_log.txt](https://github.com/user-attachments/files/18053873/shad_log.txt)

By the way, when I use the earlier build (e.g. 2024/11/08 build) to play the game, the issue will not be happened.

**Comment by Hermiten** [comment]
Hello,
What happen on other build ?
It seem's that your game cannot run for now and it's a common error.
You can also check your game here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/998

**Comment by substarX** [comment]
Hi Hermiten,

According to the information you provided, the game cannot be run by the emulator.
However, the game could normally worked (I remembered there are some error in the console, however it still worked) on the 2024/11/08 build that I was mentioned in my first post.

The log file below is saved when I use 2024/11/08 build to shortly play the game (include playing battle scene). 
Everything worked fine, and there is no error like I mentioned in my first post.

[shad_log.txt](https://github.com/user-attachments/files/18054697/shad_log.txt)

In fact, I have use the 2024/11/08 build to play Unicorn Overlord for 2 more stages.

**Comment by Hermiten** [comment]
I understand, lot of things have be done this week and you can test again. 
Please come on discord for this regression, and also you can report it on the https://github.com/shadps4-emu/shadps4-game-compatibility/issues/998.
