### ISSUE TITLE
[CUSA00900](Intel+Nvidia)Bloodborne Effects disappear when Sys_Modules are added

### ISSUE THREAD

**Issue by burn1cycle** [shadps4-emu/shadPS4#1714]
(RTX 3060, i5 12500, 32GB RAM)
 Special effects like fogs, item glows, and fire disappear when Sys Modules are added to the ShadPS4>User>Sys Module directory.

**Comment by gandalfthewhite19890404** [comment]
> (RTX 3060, i5 12500, 32GB RAM) Special effects like fogs, item glows, and fire disappear when Sys Modules are added to the ShadPS4>User>Sys Module directory.

Which exact module? You can add them one after one to find out.

**Comment by burn1cycle** [comment]
> > (RTX 3060, i5 12500, 32GB RAM) Special effects like fogs, item glows, and fire disappear when Sys Modules are added to the ShadPS4>User>Sys Module directory.
> 
> Which exact module? You can add them one after one to find out.

I apologize. I have not done that testing I'll try to have it done by the end of the day.

**Comment by morten71** [comment]
I have this exact problem too. For example Old Yharnam looks like this, without all the fire and smoke effects. But I have not added anything to the sys_modules folder.

I use an RTX 3080 Ti, i9-9900K, 32 GB, and I compile shadPS4 from source on linux. The nvidia driver version is 565.77.

![20241209-220747_shadPS4v0 4 1WIPmainv 0 4 0-150-gf1b23c61-dirty|CUSA03173-Bloodborne™-01 09-_001](https://github.com/user-attachments/assets/6cc60ac8-666e-4cb9-b8a3-f56302d5d70d)

**Comment by burn1cycle** [comment]
I've found dropping only the recommend Sys_Modules in the directory:
libSceDiscMap.sprx
libSceFiber.sprx
libSceJpegEnc.sprx
libSceJson.sprx
libSceJson2.sprx
libSceLibcInternal.sprx
libSceNgs2.sprx
libSceRtc.sprx
libSceUlt.sprx

prevents the problem where previously I was dumping all 436 modules into the directory.

**Comment by burn1cycle** [comment]
> I have this exact problem too. For example Old Yharnam looks like this, without all the fire and smoke effects. But I have not added anything to the sys_modules folder.
> 
> I use an RTX 3080 Ti, i9-9900K, 32 GB, and I compile shadPS4 from source on linux. The nvidia driver version is 565.77.
> 
Please make sure you're using a [TESS version of ShadPS4](https://github.com/baggins183/shadPS4/actions/runs/12109939200)

**Comment by morten71** [comment]
> > I have this exact problem too. For example Old Yharnam looks like this, without all the fire and smoke effects. But I have not added anything to the sys_modules folder.
> > I use an RTX 3080 Ti, i9-9900K, 32 GB, and I compile shadPS4 from source on linux. The nvidia driver version is 565.77.
> 
> Please make sure you're using a [TESS version of ShadPS4](https://github.com/baggins183/shadPS4/actions/runs/12109939200)

Thanks! That does fix all those effects.
It looks like this is something I should have known about, but I didn't. Sorry about that :-)

**Comment by Hermiten** [comment]
Im closing it because we do not support officialy the usage of sys_module and also another branch.
Thanks for the report, you can also come on discord for more help
