### ISSUE TITLE
[CUSA00900](Intel+Nvidia)Bloodborne Looting blood gems causes crashing

### ISSUE THREAD

**Issue by burn1cycle** [shadps4-emu/shadPS4#1715]
(RTX 3060, i5 12500, 32GB RAM)
A recent update to ShadPS4 has caused problems with blood gem looting which causes the emulator to crash. Another user mentions these crashes [on Reddit here](https://www.reddit.com/r/shadps4/comments/1h7y3i9/did_this_issues_happen_only_to_me_or_did_you_guys/) in the comment section which sound the same as the ones I experienced.

**Comment by Hermiten** [comment]
Thanks you.
For this maybe will be more helpful here:
https://github.com/shadps4-emu/shadPS4/issues/1641

I'm closing this one
