### ISSUE TITLE
Lego Dimensions (CUSA00935)

### ISSUE THREAD

**Issue by youtubeeicarlos** [shadps4-emu/shadPS4#1719]
The Lego Dimensions game does not start and closes the emulator brutally, I must warn you that the LEGO engine is really terrible, many emulators have problems with it, but I wish good luck to your team. By the way, Godzilla for PS4 It's entering the loading screen and closing, but I congratulate you because this is already a big step, shadps4 will certainly be more accurate than RPCS3 thanks to your efforts, congratulations! 🤩

**Comment by Hermiten** [comment]
Please check on the compatibility list, this is the place to report every game :)
Thanks you

**Comment by youtubeeicarlos** [comment]
> Please check on the compatibility list, this is the place to report every game :) Thanks you

Okay, I'll move this over there, you can delete it here and I'm sorry for the inconvenience.

**Comment by Hermiten** [comment]
No worries
