### ISSUE TITLE
Deleting a game does not immediately remove it from the list

### ISSUE THREAD

**Issue by C0rn3j** [shadps4-emu/shadPS4#1721]
Arch Linux, Plasma, Wayland, Nvidia, built from AUR/shadps4-git on https://github.com/shadps4-emu/shadPS4/commit/0b59ebb22fd64bd4c60d2fe409966900b617428e.

Random log unrelated to this issue, with more system info: [shad_log.txt](https://github.com/user-attachments/files/18051640/shad_log.txt)

---

If I try to remove patched `Peggle 2 1.00 -> 1.01 (CUSA00743)`, (or presumably any other game), it seems to get removed, but the game list does not refresh.

Nothing is logged in STDOUT/STDERR.

Repeatedly removing seems to still do nothing (shouldn't it at least throw an error about a missing directory now?).

Restarting the emulator loads the game list without the deleted game fine.

**Comment by Hermiten** [comment]
Fixed #1730
