### ISSUE TITLE
CUSA03173 Bloodborne: Brightness/Contrast issue

### ISSUE THREAD

**Issue by Missake212** [shadps4-emu/shadPS4#1725]
Since a little while now, Bloodborne brightness/contrast (not sure which, could even be gamma not sure what is the correct term to employ) has been impacted by a merged PR. Not sure what is the exact PR that created this issue, and not sure if this issue affects other games as well, but I noticed, among other people, the game being brighter, weirdly enough no one opened an issue about it and so no fix was made, it kinda got forgotten.

Here's how the menu looks like currently on nightly (f1b23c6)
![Capture d'écran 2024-12-10 115728](https://github.com/user-attachments/assets/d68a94c1-0ac3-4d3a-aa3d-ec5d6e15fcac)

And here's how it looked like on 0.4.0
![Capture d'écran 2024-12-10 115919](https://github.com/user-attachments/assets/9895c978-5025-4a6f-a479-b964bf14e0bb)

For comparison, here's how it looks like on real hardware (PS5 in this case, don't think that matters but I could try to get a screenshot on PS4 instead if needed, thanks to @theishikawarin on Discord for the screenshots !)
![IMG_7685](https://github.com/user-attachments/assets/c1e60981-bb30-4652-83a9-177568a659e0)

Here's how it looks like in game on nightly vs stable
![image](https://github.com/user-attachments/assets/fea8b2fd-a2fd-44c4-bc4b-adca89cee083)

![image](https://github.com/user-attachments/assets/340699af-6c87-41a1-b39e-ccfab9c55366)

And last two screenshots showing nightly vs PS5 (Rin's screenshots)
Nightly:
![11109416906707173376_20241210112254_1](https://github.com/user-attachments/assets/e050eb26-0dc1-4266-ae02-dfdcc1f40ff4)

PS5:
![IMG_7686](https://github.com/user-attachments/assets/72c76282-c570-492e-835b-01368b4d3265)

While we're not sure what caused this regression, we speculate it was PR #1559 that might've cause it, I didn't try to test builds prior to the merge of this PR (I didn't even check if they would still be available honestly) but I'd be glad to do it if more info is needed.

**Comment by setepenre** [comment]
https://github.com/shadps4-emu/shadPS4/commit/3d04765a3fa3425481036bb1fd5be0e99b1a42e6:
![3d04765_bb_main_menu](https://github.com/user-attachments/assets/c29f9ffb-2497-4348-9eff-30d3e548a417)
and the previous commit https://github.com/shadps4-emu/shadPS4/commit/e98fab4b58504713896ad16db5f279015f55740f:
![e98fab4_bb_main_menu](https://github.com/user-attachments/assets/43ca5dfa-01e6-4354-97ff-f321b1d40d9d)

**Comment by setepenre** [comment]
the following patch (don't mind the format applied to frag shader) applied to current main will result in tone matching what it was before the PR:
```diff
diff --git a/src/video_core/host_shaders/post_process.frag b/src/video_core/host_shaders/post_process.frag
index fcced323..65064985 100644
--- a/src/video_core/host_shaders/post_process.frag
+++ b/src/video_core/host_shaders/post_process.frag
@@ -3,10 +3,10 @@
 
 #version 450
 
-layout (location = 0) in vec2 uv;
-layout (location = 0) out vec4 color;
+layout(location = 0) in vec2 uv;
+layout(location = 0) out vec4 color;
 
-layout (binding = 0) uniform sampler2D texSampler;
+layout(binding = 0) uniform sampler2D texSampler;
 
 layout(push_constant) uniform settings {
     float gamma;
@@ -15,5 +15,5 @@ layout(push_constant) uniform settings {
 void main()
 {
     vec4 color_linear = texture(texSampler, uv);
-    color = pow(color_linear, vec4(1.0/(2.2 + 1.0 - pp.gamma)));
+    color = color_linear;
 }
diff --git a/src/video_core/renderer_vulkan/vk_presenter.cpp b/src/video_core/renderer_vulkan/vk_presenter.cpp
index b7d82931..96661a27 100644
--- a/src/video_core/renderer_vulkan/vk_presenter.cpp
+++ b/src/video_core/renderer_vulkan/vk_presenter.cpp
@@ -325,8 +325,7 @@ Presenter::Presenter(Frontend::WindowSDL& window_, AmdGpu::Liverpool* liverpool_
     CreatePostProcessPipeline();
 
     // Setup ImGui
-    ImGui::Core::Initialize(instance, window, num_images,
-                            FormatToUnorm(swapchain.GetSurfaceFormat().format));
+    ImGui::Core::Initialize(instance, window, num_images, swapchain.GetSurfaceFormat().format);
     ImGui::Layer::AddLayer(Common::Singleton<Core::Devtools::Layer>::Instance());
 }
 
@@ -388,7 +387,7 @@ void Presenter::RecreateFrame(Frame* frame, u32 width, u32 height) {
     const vk::ImageViewCreateInfo view_info = {
         .image = frame->image,
         .viewType = vk::ImageViewType::e2D,
-        .format = FormatToUnorm(format),
+        .format = format,
         .subresourceRange{
             .aspectMask = vk::ImageAspectFlagBits::eColor,
             .baseMipLevel = 0,
```
to my understanding this diff means disabling the gamma correction implemented in https://github.com/shadps4-emu/shadPS4/commit/3d04765a3fa3425481036bb1fd5be0e99b1a42e6 ; so I don't think this is what we would want, but it means there's work to be done so that the post processing matches the darker tone.

**Comment by Missake212** [comment]
That's nice for people who want to play the game right now tbh, good suggestion, I'll try and let people know about this on the Discord if they just want to play the game.

**Comment by rainmakerv3** [comment]
I feel this just needs to be adjusted:

color = pow(color_linear, vec4(1.0/(2.2 + 1.0 - pp.gamma))); 

For example, with that setting (what it is now) the title screen looks like this:

![image](https://github.com/user-attachments/assets/62c856ce-598a-4182-8283-e13b057c1949)

Whereas if I set it to color = pow(color_linear, vec4(1.0/(2.2 + 0.5 - pp.gamma))); it seems to be a lot closer to the original:

![image](https://github.com/user-attachments/assets/7f939377-8b6e-4f77-96e9-95530f48a9af)

Both images are using the same ingame brightness settings.

**Comment by hgh32** [comment]
> Both images are using the same ingame brightness settings.

Wait, the brightness setting also applies to the title menu?

**Comment by rainmakerv3** [comment]
> > Both images are using the same ingame brightness settings.
> 
> Wait, the brightness setting also applies to the title menu?

Good point, I haven't tested it. The idea behind my post is the same either way though

**Comment by setepenre** [comment]
```patch
diff --git a/src/video_core/host_shaders/post_process.frag b/src/video_core/host_shaders/post_process.frag
index fcced323..6a13ca58 100644
--- a/src/video_core/host_shaders/post_process.frag
+++ b/src/video_core/host_shaders/post_process.frag
@@ -3,17 +3,22 @@
 
 #version 450
 
-layout (location = 0) in vec2 uv;
-layout (location = 0) out vec4 color;
+layout(location = 0) in vec2 uv;
+layout(location = 0) out vec4 color;
 
-layout (binding = 0) uniform sampler2D texSampler;
+layout(binding = 0) uniform sampler2D texSampler;
 
 layout(push_constant) uniform settings {
     float gamma;
 } pp;
 
+const float cutoff = 0.0031308, a = 1.055, b = 0.055, g = 2.4, d = 12.92;
+vec3 linear_to_srgb(vec3 rgb) {
+    return mix(a * pow(rgb, vec3(1.0 / (g + 1.0 - pp.gamma))) - b, d * rgb, step(rgb, vec3(cutoff)));
+}
+
 void main()
 {
     vec4 color_linear = texture(texSampler, uv);
-    color = pow(color_linear, vec4(1.0/(2.2 + 1.0 - pp.gamma)));
+    color = vec4(linear_to_srgb(color_linear.rgb), color_linear.a);
 }
```
something like this seems to restore dynamic range and gets closer to v.0.4.0, ps4 and ps5 brightness and contrast while still allowing to adjust brightness thru devtools

EDIT forgor to put images:
![image](https://github.com/user-attachments/assets/34d9016e-0dbf-4140-9d9b-2f8a32be93b3)
![image](https://github.com/user-attachments/assets/840831eb-5ab7-4a16-964a-30716c74d317)
![image](https://github.com/user-attachments/assets/f8114809-c865-4df4-86f1-ccf9874622ce)

EDIT edited patch so that it only impacts fragment shader

**Comment by Missake212** [comment]
Let's start fresh, got some PS4 screenshots, it's better to use those than PS5 ones to be sure of the accuracy. Here's Brightness set to 0
![Brightness0](https://github.com/user-attachments/assets/4840244c-3593-4dcd-9bda-cb3002bb25a3)
![Menu0](https://github.com/user-attachments/assets/c64c1b00-e299-4eb0-907b-fd4d0b79396e)

Brightness set to 5
![Brightness5](https://github.com/user-attachments/assets/a1d79be1-3007-4859-ae8a-02158f734a28)
![Menu5](https://github.com/user-attachments/assets/c7550204-0f55-418b-a242-aabdacfac273)

Brightness set to 10
![Brightness10](https://github.com/user-attachments/assets/9dd568d6-be9e-4eb0-b6c1-976b50411716)
![Menu10](https://github.com/user-attachments/assets/52a59b7d-4587-4f76-8777-937d9d1b51ca)
