### ISSUE TITLE
Crash when trying to install packages of Bloodborne

### ISSUE THREAD

**Issue by fgurma** [shadps4-emu/shadPS4#1727]
After choosing a .pkg file shadps4 crashes. After restart I see Bloodborne only 11 mb weight. Also I can install patch and update it to 1.09 but i can not launch the games because of absent Eboot.bin .
![Снимок экрана 2024-12-08 235514](https://github.com/user-attachments/assets/c91f3b75-93a2-437a-90ad-d2ef501cd407)

**Comment by polybiusproxy** [comment]
A crash when installing packages usually means broken dump and/or unsupported CPU.

**Comment by Tasosgemah** [comment]
Had the same issue trying to upgrade Bloodborne to 1.09. Fixed it by using the diegolix build instead.
