### ISSUE TITLE
Don't start

### ISSUE THREAD

**Issue by Mikiri7** [shadps4-emu/shadPS4#1732]
![image](https://github.com/user-attachments/assets/77235c6a-2d05-440f-b031-80479adad70c)

Emulator crash after this

**Comment by DanielSvoboda** [comment]
install this for c++ to work properly, then try again
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Mikiri7** [comment]
update c++, playing again, thank you!

**Comment by Mikiri7** [comment]
Thanks! that solve the issue

________________________________
