### ISSUE TITLE
The Witch and the Hundred Knight 2 does not start with AMD

### ISSUE THREAD

**Issue by ChronoRPG** [shadps4-emu/shadPS4#1734]
Greetings

The game throws the following error in version 0.4.0. I am attaching the log of this version with Vulkan validations enabled.

[shad_log.txt](https://github.com/user-attachments/files/18086829/shad_log.txt)

Now, one of the staff members told me the following:

works fine just need to skip IMAGE_STORE_MIP and log is filled with 

And they told me to compile the emulator myself and to place the IMAGE_STORE_MIP jump in this area:

https://github.com/shadps4-emu/shadPS4/blob/main/src%2Fshader_recompiler%2Ffrontend%2Fstructured_control_flow.cpp#L%D9%A8%D9%A3%D9%A5

I tried, but it gives me an error... If someone could help me by adding the jump and providing the version, I would really appreciate it.

Thank you very much in advance.

**Comment by Hermiten** [comment]
PLease come on Discord for this kind of "hack" to start a specific game.
We don't officialy support this on Github, only what they published
