### ISSUE TITLE
star ocean 5 crashing after 5sec

### ISSUE THREAD

**Issue by takeshineale128** [shadps4-emu/shadPS4#1743]
STAR OCEAN: Integrity and Faithlessness
CUSA03219

issue Cashes when launching the game but works with null gpu only hear the audio

[Debug] <Critical> liverpool_to_vk.cpp:operator():650: Assertion Failed!
Unknown data_format=10 and num_format=10

log file 
[shad_log.txt](https://github.com/user-attachments/files/18102304/shad_log.txt)

**Comment by Hermiten** [comment]
Can you please update your post here ?
https://github.com/shadps4-emu/shadps4-game-compatibility/issues/328
And if there is some regression, you can tell us on it or on Discord :)

Thanks you
