### ISSUE TITLE
Regression: CUSA12380 Persona 5 Dancing crash after title screen

### ISSUE THREAD

**Issue by smiRaphi** [shadps4-emu/shadPS4#1745]
Haven't tested this game in a while so I only noticed it just now, before it was able to get to the first loading screen after the intro talk (after the title screen on first start) but now it crashes at the title screen:
```log
[Debug] <Critical> texture_cache.cpp:operator():216: Assertion Failed!
```
[shad_log.txt](https://github.com/user-attachments/files/18104193/shad_log.txt)

**Comment by Hermiten** [comment]
Can you try again on the last main? They've made a lot of changes in recent weeks and some have produced changes in the Persona games

**Comment by smiRaphi** [comment]
Just tried it and it's still the exact same

**Comment by Hermiten** [comment]
Do you enable PS4 Pro mode ?
Please check that this is deactivated and test again. This is a typical error

**Comment by smiRaphi** [comment]
ah, yup that was the problem, sorry

**Comment by smiRaphi** [comment]
you can actually play thru songs now :D
