### ISSUE TITLE
The audio is too quiet

### ISSUE THREAD

**Issue by SlimDread** [shadps4-emu/shadPS4#1751]
The emulator's audio is too quiet and a way to adjust it would be nice.

**Comment by DanielSvoboda** [comment]
I've never seen this. In which game did this happen? And if possible, send the log so we can identify possible causes.

**Comment by smiRaphi** [comment]
Oh I expected this to be just a known issue, I've had this always with every game

**Comment by Foul-Tarnished** [comment]
Are you sure ShadPS4 is at 100% in the audio mixer ?

As a workaround, you could use EqualizerAPO to boost the volume of all apps for a specific audio output
(need a pc restart after app configuration iirc)

**Comment by smiRaphi** [comment]
Yes I've checked everything (audio mixer, windows game bar audio mixer, device volume, voicemeeter stuff, physical device volume)

**Comment by Hermiten** [comment]
Can you try the latest main ? They did something with audio

**Comment by smiRaphi** [comment]
seems to be mostly fine now, would still be nice to have a volume slider from like 0-200% but definitely playable now without having to turn on some kind of volume booster

**Comment by Hermiten** [comment]
You can maybe open a suggestion for this
