### ISSUE TITLE
Bloodborne Textures Deload

### ISSUE THREAD

**Issue by sam20112011** [shadps4-emu/shadPS4#1752]
Since the merging of the two HLE [e5e1aba](https://github.com/shadps4-emu/shadPS4/commit/e5e1aba24172b4cf41e1c4ea56adf0b0984b815b) brunches and the double-delete [41fd1c8](https://github.com/shadps4-emu/shadPS4/commit/41fd1c84cf51fbb8b3784e038c72d4bb37b8f406), the game has seen an increase in texture deloading. Since July, on my system I have not encountered this once on shadps4 (on ps4 pro encountered), but after the latest version of HLE merged into the main build, it happens all the time in different parts of any location. Most noticeable at the very beginning of the game, if you don't go to the hunter's dream and make your way down the main street:
![image](https://github.com/user-attachments/assets/ad00902b-38e0-43fa-8ad3-e9c7103aeba2)
Also a signal of such a problem is the presence of a vertex explosion in the player character from a "cold start" of the emulator at the beginning of a new game.

**Comment by rainmakerv3** [comment]
Per testing, seems to be specially from this commit: https://github.com/shadps4-emu/shadPS4/commit/363c6c1b7babf10babeac7d0996d222829e79d7d

**Comment by sam20112011** [comment]
Commit [1e3d034](https://github.com/shadps4-emu/shadPS4/commit/1e3d034f9682956e5737126ef8b97d54cdf08d2a) after merging into the main one, the problem is still present.

**Comment by dcealopez** [comment]
Could you test if [1757](https://github.com/shadps4-emu/shadPS4/pull/1757) fixes this?

**Comment by sam20112011** [comment]
> Could you test if [1757](https://github.com/shadps4-emu/shadPS4/pull/1757) fixes this?

Well, based on my testing method, despite the returned error "unsupported pm4 type 0", the deload problem is solved. Need fideback from more players. But it's promising).

**Comment by rainmakerv3** [comment]
PM4 type 0 errors have always happened in Bloodborne (more common on some systems than others for some reason) and are unrelated, so this is indeed promising!

**Comment by sam20112011** [comment]
> PM4 type 0 errors have always happened in Bloodborne (more common on some systems than others for some reason) and are unrelated, so this is indeed promising!

Interestingly enough, when the deload occurred, the pm4 problem did not affect me. could it be related?
