### ISSUE TITLE
Bloodborne crash on startup

### ISSUE THREAD

**Issue by Y0r5** [shadps4-emu/shadPS4#1759]
I've downloaded bloodborne, applied patches, tweaked the settings, but, I crash on startup, I have pretty old specs, but they have no issues with other games I've played in the past, I dont see why it would have an issue here. All I get is warnings about Render.vulkan then the crash with a pop up about unable to read memory.*

Specs are (very fucking mid):
GTX 660 
Ryzen 3 3200G
16gb ram

**Comment by raphaelthegreat** [comment]
Piracy is not supported in this emulator
