### ISSUE TITLE
Enable Separate Game Folder option doesn't work on Linux

### ISSUE THREAD

**Issue by kalaposfos13** [shadps4-emu/shadPS4#1765]
Exactly what the title says. To troubleshoot sound issues in GR2, I decided to backup my current dump and dump it again to start from scratch. I then decided to enable separate update folders, as I haven't used it yet, and the premise of easily being able to go back to 01.00 versions for testing sounded good. Everything was fine and the game and the update folder correctly generated, and the launcher displayed that I do in fact have an update to the game, but when I tried launching it, I got to after loading the libraries, then immediately crashed, I think at the moment it was trying to execute code from the eboot. (This is the error code, but I don't think it's relevant: `[Debug] <Critical> signals.cpp:SignalHandler:85: Unreachable code! Unhandled access violation in thread 'GAME_MainThread' at code address 0x90011bb06: Read from address 0xc`) I tried some other troubleshooting before trying to add the update folder's contents to the main folder and removing the update folder (after backing those up, too, of course), effectively disabling the separate update folder after which the game launched fine again (still no sound tho). I then repeated this experiment with Beach Buggy Racing, as it is a small game that has an update too. I observed the same results there, so it's very likely that something that should use the update version uses the 01.00 instead Recently there was a problem where config.toml was saved as Config.toml, also breaking Linux, maybe this is similar?

**Comment by Hermiten** [comment]
Maybe for you @ElBread3 ?

**Comment by kalaposfos13** [comment]
Since https://github.com/shadps4-emu/shadPS4/pull/1487 got merged, the problem is fixed
