### ISSUE TITLE
Crashing when Trying to use the "install packages (pkg)"

### ISSUE THREAD

**Issue by ulisesrreyes12** [shadps4-emu/shadPS4#1774]
shadps4 crashes when i use that option to install bloodborne on the emulator, so it only instals 11mb out of the 30gb and crashes.
Basically meaning i can't play

**Comment by Hermiten** [comment]
Where did you find it ?

**Comment by ulisesrreyes12** [comment]
On a reddit. Do you think the problem is the pkg?

**Comment by Hermiten** [comment]
Yes it's absolutely forbidden sorry

**Comment by ulisesrreyes12** [comment]
So What do i do? I got another copy But it's divided on 4 files so i don't know how to check if it works

**Comment by raphaelthegreat** [comment]
Piracy is not supported by this project
