### ISSUE TITLE
Critical error when booting any games. Homebrew builds included on nightly build 

### ISSUE THREAD

**Issue by Peacefuldwarf** [shadps4-emu/shadPS4#1794]
I've run into a problem after updating to the latest nightly build regarding a critical error whenever I try to boot any and all games. I've done a bit of trouble shooting with Moderator: Poly on the discord, sadly to no avail.
The current things we've tried is running as Administrator and disabling Windows Defender Protection in Local Group Policy Editor/Regedit, and the program itself

The following error appears whenever I boot a game based on a PKG file
```
[Debug] <Critical> pthread.cpp:operator():293: Assertion Failed!
Failed to create thread with error -1073741790
```

And this error occurs when trying to boot homebrew games based on eboot (Breakout_eboot and such)
`[Debug] <Critical> memory.cpp:operator():284: Assertion Failed!`

The error doesn't appear when using the main release branch

I don't know if this is needed, but I'll include my specs just in case.

Intel Core i7-13700KF
DDR5 6600 32GB
Nvidia GeForce RTX 4080
Windows 11 Pro

Here is my latest [shad_log.txt](https://github.com/user-attachments/files/18138103/shad_log.txt) for PKG games
And this one from launching eboot games 
[shad_log.txt](https://github.com/user-attachments/files/18140521/shad_log.txt)

EDIT: Error persists in newer nightly builds

**Comment by HMPoweredMan** [comment]
I'm also having this issue with the nightly builds.
AMD 5950x
RTX 3070
Windows 11

Lastest game ready driver
Troubleshooting steps updated to latest BIOS
Running as admin

One thing unique about my setup is the games do load from a network location. I haven't tried running them locally but it hasn't been an issue on the main stable branch.
