### ISSUE TITLE
Strobing and Negative Color issues

### ISSUE THREAD

**Issue by StupidasSloth** [shadps4-emu/shadPS4#1808]
Since updating Shadps4 today and loading up Bloodborne. I had an error occur where the text and screen would be strobing/flickering. I tried removing all mods and patches to no success, I have also loaded into the game which is in like a negative esc coloring.

**Comment by roamic** [comment]
Please provide all relevant information like which exact build you are using and your specs. Also, please attach a log from `shadPS4/user/log`

**Comment by JuanB0609** [comment]
I have the same issue, when I open the game it looks like flickering in the main screen, in game the colors are all messed up, like negative colors.

GPU: Nvidia RTX 3080 Ti
CPU: AMD R9 5900X
RAM 32GB @3200 Mhz
Build v0.4.1 WIP PgoBB b972ce4

[shad_log.txt](https://github.com/user-attachments/files/18175322/shad_log.txt)

If you need any other information please let me know

**Comment by roamic** [comment]
> I have the same issue, when I open the game it looks like flickering in the main screen, in game the colors are all messed up, like negative colors.
> 
> GPU: Nvidia RTX 3080 Ti CPU: AMD R9 5900X RAM 32GB @3200 Mhz Build v0.4.1 WIP PgoBB [b972ce4](https://github.com/shadps4-emu/shadPS4/commit/b972ce4af56b559577ca7b32d9de5bbfb03c9e8c)
> 
> [shad_log.txt](https://github.com/user-attachments/files/18175322/shad_log.txt)
> 
> If you need any other information please let me know

You are using an unofficial build. We do not provide support for those. If you have any issues with it you have to take them directly to the person who made it.

**Comment by Hermiten** [comment]
Please have a look here: https://github.com/shadps4-emu/shadPS4/issues/1641
And if you don't find any useful infornation, you can open a new issue with complete information.
Please make sure you don't use an unofficial build.

**Comment by StupidasSloth** [comment]
Hey I reinstalled the launcher and made sure the updates were set to “release” instead of nightly. 0.4.0 works for Bloodborne fine.
