### ISSUE TITLE
Bloodborne zone transitions not rendering

### ISSUE THREAD

**Issue by TequilaSunsetIRL** [shadps4-emu/shadPS4#1814]
Testing [release-shadPS4-2024-12-17-f79a619](https://github.com/diegolix29/shadPS4/releases/tag/release-shadPS4-2024-12-17-f79a619) with Bloodborne CUSA03173. Game zones that are set to only render when you approach them such as Hemwick Charnel Lane (from Oedon Chapel) are not rendering. 

![shadPS4 2024-12-17 14-54-01](https://github.com/user-attachments/assets/4a51a616-dcb1-45bb-9f7f-01dbee4e7ae2)
![shadPS4 2024-12-17 15-17-07](https://github.com/user-attachments/assets/bbb5ecbb-e462-4a03-bba3-fda9fcac8e99)

Reloading the game from within the affected area causes it to render and the previous one to derender. Tested going to and from Cathedral Ward.
System specs:
Processor	AMD Ryzen 7 5800X 8-Core Processor                3.80 GHz
Installed RAM	32,0 GB
System type	64-bit operating system, x64-based processor
Nvidia GeForce GTX Titan X
Driver Version 566.14
CUDA cores: 3072
Graphics Clock: 1152
Memory Rate 6.61 gb
Mem Bandwidth 317.28 gb/s
Total Available graphics memory 28634 mb
Dedicated video memory 12288 mb
Shared system memory 16346
[shad_log.txt](https://github.com/user-attachments/files/18170829/shad_log.txt)

Using the following mods
[Fromsoftserve Bloodborne remaster project](https://www.nexusmods.com/bloodborne/mods/45)
[Fromsoftserve visual tweaks](https://www.nexusmods.com/bloodborne/mods/27)
[Vertex explosion fix](https://www.nexusmods.com/bloodborne/mods/109)
[Bright objects flash fix](https://www.nexusmods.com/bloodborne/mods/110)

**Comment by rainmakerv3** [comment]
The remaster project mod is known is cause issues such as this. a good practice before reporting issues is to try without mods and patches first, as mods and patches are not officially supported

**Comment by TequilaSunsetIRL** [comment]
Noted. I'll go back to unmodded before reporting anything going forward

**Comment by GHU7924** [comment]
Branch Full-BB, Main-BB and others = Close issue.

Builds downloaded from the link are taken into account https://github.com/shadps4-emu/shadPS4/actions

No mods and no patches.

**Comment by fedyyyyy** [comment]
who tf are you GHU7924 are you a mod or an author or something ? shameless behaviour

**Comment by roamic** [comment]
We do not provide support for issues in unofficial builds. Mods and patches have no official support in this repository either. Feel free to re-open this issue if you encounter it in the official build without any patches or mods.
