### ISSUE TITLE
when i click check for updates on the setting and when I click download patches nothing happens

### ISSUE THREAD

**Issue by jiimmmy02** [shadps4-emu/shadPS4#1816]
it just say nothing anyone know wt the solution is 

![image](https://github.com/user-attachments/assets/e3808c0b-fca8-488b-985d-8ecc45e95072)

**Comment by Hermiten** [comment]
This work fine for me on fresh install with the last main.
Can you test again, and give more information like which version you did use, how did you install bloodborne, etc.. ?

**Comment by DanielSvoboda** [comment]
Which operating system?
try again with the latest emulator version [0.4.1 (Pre-release)](https://github.com/shadps4-emu/shadPS4/releases)
