### ISSUE TITLE
[Linux] Nvidia RTX 3060 Doesnt work 

### ISSUE THREAD

**Issue by Fuoxden** [shadps4-emu/shadPS4#1817]
https://github.com/user-attachments/assets/f0bd1912-08be-46a4-b311-d0e0987623c2

Seems like my RTX 3060 Doesnt work, While the livmpipe works just fine, Also, Anytime you try to close the window, the emulator doesnt respond, Meaning it Basically crashes

**Comment by Hermiten** [comment]
This is normal that the emulator does not respond when the game crash but I we need the log to understand, can you please upload it ?
I'm not sure that the emulator work well on virtual machine

**Comment by C0rn3j** [comment]
Seems like a dupe of https://github.com/shadps4-emu/shadPS4/issues/1720

**Comment by GHU7924** [comment]
@Hermiten This has been a problem with Nvidia for a long time, but I don't remember if the emulator continues to work. Perhaps this is due to the "DISPLAY" problem.

It is also necessary to review the code, because the emulator do not work well on Linux. #882

**Comment by Fuoxden** [comment]
> This is normal that the emulator does not respond when the game crash but I we need the log to understand, can you please upload it ? I'm not sure that the emulator work well on virtual machine

OH Right! Im sorry i didnt give you the log, Here you go, Pretty sure thats the log, Hope that helps! 

[shad_log.txt](https://github.com/user-attachments/files/18204397/shad_log.txt)

**Comment by ngoquang2708** [comment]
@Fuoxden Can you try this https://github.com/shadps4-emu/shadPS4/pull/1830.

**Comment by Fuoxden** [comment]
> @Fuoxden Can you try this https://github.com/shadps4-emu/shadPS4/pull/1830.

I will try it after my shower, and I update, hope it works and if it does, then thank you!

**Comment by ngoquang2708** [comment]
@Fuoxden Don't forget to report the result there. Thanks.

**Comment by Fuoxden** [comment]
https://github.com/user-attachments/assets/c97b9184-8c6d-4ccb-894e-d741811abde4

It Seems like it's still broken, Here's The new log:
[shad_log.txt](https://github.com/user-attachments/files/18225415/shad_log.txt)

**Comment by ngoquang2708** [comment]
@Fuoxden You ~~only test~~ tested build from main branch. Download the qt artifact from this https://github.com/shadps4-emu/shadPS4/actions/runs/12425736865?pr=1830.

**Comment by Fuoxden** [comment]
Alright, My card looks like its working! I will make sure to use the main branch from now on

https://github.com/user-attachments/assets/6d6b204d-28e5-4219-b2b7-fb8744e3e6d3

The "ShadPS4 is not responding" message is still here, But i am still happy the card seems to be working, Thank you!

**Comment by ngoquang2708** [comment]
@Fuoxden Sorry if I got you confused in the previous comment. I mean that you tested on main which doesn't have the fix. The link I gave you is my change to make it work, it is not in main branch yet.
Now that my fix works for you so please report it here https://github.com/shadps4-emu/shadPS4/pull/1830 to help it gains visibility.

**Comment by Fuoxden** [comment]
Ah, Okay! I will just report that it works on that post, Do i need to close this report? Or keep it open until the fix get's rolled out?

**Comment by ngoquang2708** [comment]
I think just wait until that PR got merged.

**Comment by Fuoxden** [comment]
Ah, Got it! I will go to #1830 and report that it works for me! Thank you for the fix! It's very cool how fast ps4 emulation is Developing! Hope someday we can all play ps4 games on PC
