### ISSUE TITLE
Detecting Update Even After Updating to latest Version

### ISSUE THREAD

**Issue by King-Of-The-Coding-World** [shadps4-emu/shadPS4#1818]
Version: 0.4.0

I updated the emulator to latest version and configured the setting to check for updates on startup. When I reran the emulator, it was still detecting the update and on clicking on update button it was downloading it too. That's all about what I observed. I hope it will help.

Thanks

**Comment by DanielSvoboda** [comment]
Thanks for reporting, but this problem has already been fixed in PR1465, but the fix will only take effect in the next release, I recommend changing the update channel to 'Nightly'
![image](https://github.com/user-attachments/assets/7cc077e9-5192-43b6-9156-25f44b75276f)
