### ISSUE TITLE
Crash on bloodborne

### ISSUE THREAD

**Issue by doscua** [shadps4-emu/shadPS4#1831]
When im playing the game does random crashes. It doesnt happend with a specifical situation. It just happends. This is what the console shows. 

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcGetCurrentClockLocalTime (nid: ZPD1YOKI+Kw) called, returning zero to 0x9015653f3
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcGetTick (nid: 8w-H19ip48I) called, returning zero to 0x90156541b
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcSetTick (nid: ueega6v3GUw) called, returning zero to 0x9020ea232
[Render.Vulkan] <Critical> liverpool.cpp:ProcessGraphics:617: DmaData Memory 0x22b0f21e8 -> Gds 0x20, 4 bytes
[Render.Vulkan] <Critical> liverpool.cpp:ProcessGraphics:610: DmaData Data (0) -> Gds 0x24, 4 bytes
[Render.Vulkan] <Critical> liverpool.cpp:ProcessGraphics:631: DmaData Gds 0x20 -> Memory 0x22b0f21e8, 4 bytes
[Render.Vulkan] <Critical> liverpool.cpp:ProcessGraphics:631: DmaData Gds 0x24 -> Memory 0x22b0e79d8, 4 bytes
[Render.Vulkan] <Critical> liverpool.cpp:ProcessGraphics:638: DmaData Memory 0x22b0e79d8 -> Memory 0x216bf2bf0, 4 bytes
[Render.Vulkan] <Critical> liverpool.cpp:ProcessGraphics:638: DmaData Memory 0x22b0e79d8 -> Memory 0x216a54ff0, 4 bytes (this is the last msg and its when the games freezes)

After that the game can come back like nothing happends or it can crash

**Comment by doscua** [comment]
Update: A new msg appears when the game is going to crash, it says: 
[Debug] <Critical> vk_presenter.cpp:operator():768: Assertion Failed!
Device lost during waiting for a frame

**Comment by roamic** [comment]
You are using an unofficial build which has no support in this repository. You can take this issue directly to the build author. Feel free to re-open this issue if it is reproduced in the official build without any mods or patches.
