### ISSUE TITLE
Same issue.  CRASH WHILE PLAYING BLOODBORNE

### ISSUE THREAD

**Issue by doscua** [shadps4-emu/shadPS4#1833]
im getting the same issue as before but not that frequently as before.  Reinstalled shadps4 from the shadps4 page and installed the build named: shadps4-win64-qt-2024-12-19-cbb854a

stubs.cpp:CommonStub:42: Stub: sceRtcGetTick (nid: 8w-H19ip48I) called, returning zero to 0x90156541b
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcSetTick (nid: ueega6v3GUw) called, returning zero to 0x9020ea232
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcSetTick (nid: ueega6v3GUw) called, returning zero to 0x9020ea232
[Debug] <Critical> vk_presenter.cpp:operator():768: Assertion Failed!
Device lost during waiting for a frame (after this the game crash)

![imagen_2024-12-20_162842705](https://github.com/user-attachments/assets/8c8c6db8-9623-412c-b096-cca29b03eb95)

**Comment by raphaelthegreat** [comment]
Github is not a support to debug your issues, also this is a duplicate issue
