### ISSUE TITLE
Having a game missing compatibility tags causes shad to crash while loading games list. 

### ISSUE THREAD

**Issue by brad0demx** [shadps4-emu/shadPS4#1843]
### **on 0.4.0** 
![image](https://github.com/user-attachments/assets/df071317-d695-4c72-b0c8-d84268a3c68a)

### **and on latest main as of today 22/12/2024**
![image](https://github.com/user-attachments/assets/fab4a343-3ab9-4fcb-b803-3a2e4e5df427)

This issue is mentioned in the [compatibility report ](https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1402) for this region of the game. 

I also want to add, that going in the param.sfo and changing the Serial (referred to as TITLE_ID) the game shows up normally with the newer builds.

Originally I was having this issue with EU version of Dark Souls Remastered, but I found after making a [new issue ](https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1412) now presents the same issue while having that game in my directory too.

**Comment by f8ith** [comment]
I forgot to add `status-unknown` to `LabelToCompatStatus`, so .at causes a crash at `CompatibilityInfoClass::GetCompatibilityInfo()`

**Comment by Hermiten** [comment]
Can you try again ?

**Comment by brad0demx** [comment]
Using latest main WIP commit 8abc43a shad now loads correctly with both of my affected games
