### ISSUE TITLE
Bloodborne freezes on character screen on Linux

### ISSUE THREAD

**Issue by Faugus** [shadps4-emu/shadPS4#1844]
Ryzen 7 5700X3D / Radeon RX 7900XT

Tested on Arch Linux and Fedora.
Tested with RADV and AMDVLK.

Logs: [shadps4-bloodborne.txt](https://github.com/user-attachments/files/18220563/shadps4-bloodborne.txt)

**Comment by kavika13** [comment]
Might be a dupe of https://github.com/shadps4-emu/shadPS4/issues/1704, which just had a work-around merged to main very recently.

Try the very latest shad build if you're not running it already. Also try `CTRL + Z` and `fg` when the game freezes, to see if that gets the game unstuck.

Edit: I checked your log, and you're on the commit RIGHT before the work-around got merged back into main. So, update and you probably won't see this issue.

**Comment by Faugus** [comment]
It works now, thank you!
