### ISSUE TITLE
Emulator crashes when trying to run Bloodborne

### ISSUE THREAD

**Issue by alicepachecoo** [shadps4-emu/shadPS4#1845]
Trying to run the Bloodborne CUSA00900 (version 1.09) game results in the emulator completely crashing.

**Reproduction steps:**

1. Download and configure the emulator
2. Install Bloodborne 1.0 retail .pkg
3. Update the game to the 1.09 version
4. Click twice on the game icon to execute it
5. Notice the error messages in the terminal and the immediate crash of the application.

**Platform:**
Windows

**Emulator version:**
Pre-release-shadPS4-2024-12-22-fb2c035

**Game version:**
CUSA00900

**Game cheats/patches:**
No cheats or patches were installed.

**Observation:**
A possible workaround for this issue it's to play the 1.0 version of the game with the ram spike workaround mod.

[shad_log.txt](https://github.com/user-attachments/files/18220734/shad_log.txt)

**Comment by Hermiten** [comment]
Can you also send your computer specs ? Thanks you

**Comment by Rimurudemon** [comment]
I have followed the same procedure and the same crash happens to me .
I have: intel i712700h, nvidia 4060, asus tuf f15 2023, 16 gb ram, 1tb ssd

**Comment by C0rn3j** [comment]
Works fine for me with https://github.com/shadps4-emu/shadPS4/commit/43fd8fa44a4ea7e8bdfba86106e72e57d7e678d5 on Arch Linux + Plasma (Wayland) + Nvidia.

Maybe try a newer build from today to see if it hasn't resolved?

![image](https://github.com/user-attachments/assets/958e787c-17be-40bc-96f1-a2f766a706fb)

**Comment by Rimurudemon** [comment]
Can you recommend one for windows?

**Comment by C0rn3j** [comment]
> Can you recommend one for windows?

You can test the exact commit that works for me, it has Windows builds available in the CI, just go for the green checkmark icon to find them.

**Comment by Rimurudemon** [comment]
![IMG_20241223_172029.jpg](https://github.com/user-attachments/assets/de50e90b-1b6f-4377-a08b-2a9b734d418e)

This is the error I get on the terminal every time I try to access the game

**Comment by alicepachecoo** [comment]
> Can you also send your computer specs ? Thanks you

Yes, here are my specs:
OS: Windows 11 24H2 IoT Enterprise LTSC (Build 26100.2605)
CPU: Ryzen 7 5700X
GPU: Geforce RTX 3600 12GB
Memory: 32GB

**Comment by Missake212** [comment]
If the game works without the update but crashes with it, it's most likely a bad dump of the update imo

**Comment by pycoder08** [comment]
I'm getting the same error messages. When I disable all shadps4 patches (the texture patches and such) it will play the first cutscene, then crashes. When I use patches, it never starts, and gives the "returning to zero" messages. 

Specs: 
OS: Microsoft Windows 11 Home, Version 10.0.22631
GPU: Nvidia RTX 3080 10 GB
CPU: 11th Gen Intel(R) Core(TM) i7-1 1700F @ 2.50GHz
Memory: 64 GB

My game is updated to 1.09, and Shadps4 is up to date.

Full error message:

 <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x97003b3dc

Update: It seems the '30 fps fix' patch is what causes the issue. When it is disabled, the command line gives an infinite stream of errors like so:

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcGetTick (nid: 8w-H19ip48I) called, returning zero to 0x90156563b
[Lib.Net] <Error> net.cpp:sceNetSetsockopt:954: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetGetsockopt:689: (STUBBED) called
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcSetTick (nid: ueega6v3GUw) called, returning zero to 0x9020eb622

Despite these errors, it plays the first cutscene, then crashes. When the '30 fps fix' patch is enabled, it doesn't give these errors, and instead gives the "returning zero to 0x97003b3dc" error and crashes before it can get to the home screen. This behavior is consistent across the 1.00 and the 1.09 versions. Adding sys modules doesn't fix the issue.

**Comment by AzslayZ** [comment]
same has been happening to me since the dec 11 build

**Comment by pycoder08** [comment]
Update now: skipping the first cutscene fixes the issue, and I've managed to play though the opening sequence and got past the hunter's dream. However, even though the "skip intro" patch is enabled, the intro still plays. The 30fps fix patch still breaks the game, though. 

Update x2: it seems enabling the 'remove chromatic aberration' and 'remove motion blur' patches causes the emulator to crash after trying to load my save. seems like every patch I try ends up breaking something. The resolution patch I tried caused all the textures to start glitching red. The 60fps patch causes the same issue as the 30fps one. The disable vsync patch does likewise.

Update x3: the December 25th build hasn't fixed these issues. All the resolution patches keep crashing my game at the same spot after the second checkpoint (when an enemy jumps out from behind boxes to attack you, although it only crashes when I lock on to the enemy). Any patch 1440p or higher causes textures to glitch out. Chromatic Abberation/motion blur still crash the game, and any fps patches still stop the game from launching.

Update x4: I uninstalled the emulator, re-installed it, and re-extracted the game file, everything works perfectly now... not sure what that was about.

**Comment by Hermiten** [comment]
Please follow everything on this issue:
https://github.com/shadps4-emu/shadPS4/issues/1641

You will find more information
We do not support patches and cheats here, and only with a clean build from here. Thanks you !

About your update 4: Because you did a fresh install !
