### ISSUE TITLE
Bloodborne 5.1 Surround Sound Audio has broken effects

### ISSUE THREAD

**Issue by burn1cycle** [shadps4-emu/shadPS4#1861]
Starting off, I don't expect 5.1 or other surround formats to be implemented any time soon given all the other hard work being put into other areas of the emulator this is just for documentation purposes for later.

 I'm using Creative Sound Blaster Audigy PCIe RX 7.1 to get a 5.1 output unfortunately ShadPS4 isn't designed to do this yet(I don't think) and at least in Bloodborne trying to do so will produce working sound however in indoor areas that are programmed to echo the echo effect seems broken. What it sounds like is as if the echo never decays it just stays at the same volume until the end of the audio clip. 
(Win10, RTX 3060 Ti, i5 12500, 32GB RAM)

**Comment by Xphalnos** [comment]
This issue can't be considered valid because, as you said, surround has not been implemented. And then I think that if the problem came from shadPS4, all the sounds would be bugged and not just the reverb.
