### ISSUE TITLE
Game crash after start

### ISSUE THREAD

**Issue by alwerg123** [shadps4-emu/shadPS4#1862]
qtode = 0
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:469: (PARTIAL) path = /app0/art/cache/msn_vor.sprig.xpps
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = 1 rgb = 255 255 255
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = 1 rgb = 255 255 255
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = 1 rgb = 255 255 255
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = 1 rgb = 255 255 255
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/art/cache/msn_vor.sprig.xpps
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = 1 rgb = 255 255 255
[Kernel.Event] <Info> event_flag.cpp:sceKernelCreateEventFlag:186: called name = AkEvent attr = 0x20 initPattern = 0x0
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = 1 rgb = 255 255 255
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:61: path = /app0/art/cache/skydome_sunbreak.sprig.xpps flags = 0x0 mode = 0
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:469: (PARTIAL) path = /app0/art/cache/skydome_sunbreak.sprig.xpps
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = 1 rgb = 255 255 255
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = 1 rgb = 255 255 255
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = 1 rgb = 255 255 255
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Lib.DiscMap] <Error> disc_map.cpp:Func_7C980FFB0AA27E7A:23: (STUBBED) called
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:478: Compiling cs shader 0x58652d72
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:478: Compiling cs shader 0x2c6b674a
[Lib.Pad] <Info> pad.cpp:scePadSetLightBar:464: scePadSetLightBar called handle = 1 rgb = 255 255 255
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:478: Compiling fs shader 0xfa2ea78e
[Lib.DiscMap] <Warning> disc_map.cpp:sceDiscMapIsRequestOnHDD:18: (DUMMY) called
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:188: Closing /app0/art/cache/skydome_sunbreak.sprig.xpps
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:478: Compiling vs shader 0xfd2a358b
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:478: Compiling fs shader 0xfa2ea78e (permutation)
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:478: Compiling cs shader 0x64ad2129
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:478: Compiling cs shader 0xc6e8de8c
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:478: Compiling fs shader 0x9215a6e8
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:478: Compiling vs shader 0xc9640a36
[Debug] <Critical> liverpool_to_vk.h:PromoteFormatToDepth:116: Unreachable code!
Infamous:Second Son crash after start
I've tried different versions of the emulator and different repacks of the game, nothing changes.

**Comment by polybiusproxy** [comment]
Piracy is strictly prohibited and we won't support it.
