### ISSUE TITLE
CUSA04480_NIER_AUTOMATA - Infinite Loading

### ISSUE THREAD

**Issue by InfiniteT8** [shadps4-emu/shadPS4#1874]
![image](https://github.com/user-attachments/assets/f72a7e50-b283-4591-8334-293a05705cf8)
Playable up until the first loading screen. I haven't managed to get in-game play just yet.

**Comment by polybiusproxy** [comment]
Game compatibility reports go to https://github.com/shadps4-emu/shadps4-game-compatibility, not here.
(note that only reports for released versions will be accepted, reports using WIP versions will be closed.)
