### ISSUE TITLE
Emulator defaults to Xwayland despite having Wayland support

### ISSUE THREAD

**Issue by C0rn3j** [shadps4-emu/shadPS4#1878]
Is this intended?

unsetting DISPLAY makes it run under native Wayland, which is preferable, unless there are some major issues, but it seems to work fine on my machine™.

Keeping the possibility to override it to Xwayland would of course make sense.

**Comment by ngoquang2708** [comment]
It because of this https://github.com/libsdl-org/SDL/pull/9383.

**Comment by ngoquang2708** [comment]
I made a PR to force Wayland https://github.com/shadps4-emu/shadPS4/pull/1827 but decided that just wait for DEs to implement required protocols.

**Comment by C0rn3j** [comment]
One of the needed protocols was just pushed a release behind for kwin which I use... https://invent.kde.org/plasma/kwin/-/merge_requests/6474

But I suppose this is then resolved on shad's side, as it will eventually default to Wayland on its own.

It is worth to mention that messing with DISPLAY is the wrong way to do this based on reading that thread, and `export SDL_VIDEO_DRIVER=wayland; shadps4` is actually the way to go.
