### ISSUE TITLE
AppImage - Can't launch games from CLI with -g

### ISSUE THREAD

**Issue by dragoonDorise** [shadps4-emu/shadPS4#1881]
Hi there, Trying to launch games like this:

Shadps4-qt.AppImage -g CUSAXXXXX

or like this:

Shadps4-qt.AppImage -g gamespath/CUSAXXXXX/eboot.bin

crashes shadPS4, here's the log when trying to launch a game on a Steam Deck:

`
[Loader] <Info> emulator.cpp:Emulator:61: Starting shadps4 emulator v0.4.1 WIP 
[Loader] <Info> emulator.cpp:Emulator:62: Revision 3ab118837aba313bb1d2d53b50347cf5c4e67727
[Loader] <Info> emulator.cpp:Emulator:63: Branch main
[Loader] <Info> emulator.cpp:Emulator:64: Description 3ab1188
[Config] <Info> emulator.cpp:Emulator:66: General Logtype: async
[Config] <Info> emulator.cpp:Emulator:67: General isNeo: false
[Config] <Info> emulator.cpp:Emulator:68: GPU isNullGpu: false
[Config] <Info> emulator.cpp:Emulator:69: GPU shouldDumpShaders: false
[Config] <Info> emulator.cpp:Emulator:70: GPU vblankDivider: 1
[Config] <Info> emulator.cpp:Emulator:71: Vulkan gpuId: -1
[Config] <Info> emulator.cpp:Emulator:72: Vulkan vkValidation: false
[Config] <Info> emulator.cpp:Emulator:73: Vulkan vkValidationSync: false
[Config] <Info> emulator.cpp:Emulator:74: Vulkan vkValidationGpu: false
[Config] <Info> emulator.cpp:Emulator:75: Vulkan rdocEnable: false
[Config] <Info> emulator.cpp:Emulator:76: Vulkan rdocMarkersEnable: false
[Config] <Info> emulator.cpp:Emulator:77: Vulkan crashDiagnostics: false
[Kernel.Vmm] <Info> address_space.cpp:Impl:423: System managed virtual memory region: 0x400000 - 0x7ffffbfff
[Kernel.Vmm] <Info> address_space.cpp:Impl:426: System reserved virtual memory region: 0x7ffffc000 - 0xfffffffff
[Kernel.Vmm] <Info> address_space.cpp:Impl:428: User virtual memory region: 0x1000000000 - 0x10fffffffff
[Kernel.Vmm] <Info> memory.cpp:SetupMemoryRegions:53: Configured memory regions: flexible size = 0x1c000000, direct size = 0x120000000
[Kernel.Vmm] <Info> memory.cpp:MemoryManager:36: Usable memory address space: 1087_GB
[Loader] <Info> emulator.cpp:Run:161: Game id: CUSA07010 Title: Sonic Mania
[Loader] <Info> emulator.cpp:Run:164: Fw: 0x4700000 App Version: 01.00
[Lib.Kernel] <Info> libs.cpp:InitHLELibs:53: Initializing HLE libraries
[Lib.GnmDriver] <Info> gnmdriver.cpp:RegisterlibSceGnmDriver:2769: Initializing presenter
[Render.Vulkan] <Info> vk_platform.cpp:CreateInstance:229: Creating vulkan instance
[Render.Vulkan] <Info> vk_platform.cpp:CreateInstance:271: Enabled instance extensions: VK_KHR_xlib_surface, VK_KHR_surface, VK_EXT_debug_utils
[Render.Vulkan] <Info> vk_platform.cpp:CreateInstance:272: Enabled instance layers: 
[Render.Vulkan] <Info> vk_instance.cpp:Instance:107: Found 1 physical devices
[Render.Vulkan] <Info> vk_instance.cpp:CollectDeviceParameters:544: GPU_Vendor: radv
[Render.Vulkan] <Info> vk_instance.cpp:CollectDeviceParameters:545: GPU_Model: AMD Custom GPU 0405 (RADV VANGOGH)
[Render.Vulkan] <Info> vk_instance.cpp:CollectDeviceParameters:546: GPU_Vulkan_Driver: radv 24.0.99
[Render.Vulkan] <Info> vk_instance.cpp:CollectDeviceParameters:547: GPU_Vulkan_Version: 1.3.278
[Render.Vulkan] <Info> vk_instance.cpp:CollectDeviceParameters:548: GPU_Vulkan_Extensions: VK_KHR_8bit_storage, VK_KHR_16bit_storage, VK_KHR_acceleration_structure, VK_KHR_bind_memory2, VK_KHR_buffer_device_address, VK_KHR_calibrated_timestamps, VK_KHR_copy_commands2, VK_KHR_create_renderpass2, VK_KHR_dedicated_allocation, VK_KHR_deferred_host_operations, VK_KHR_depth_stencil_resolve, VK_KHR_descriptor_update_template, VK_KHR_device_group, VK_KHR_draw_indirect_count, VK_KHR_driver_properties, VK_KHR_dynamic_rendering, VK_KHR_external_fence, VK_KHR_external_fence_fd, VK_KHR_external_memory, VK_KHR_external_memory_fd, VK_KHR_external_semaphore, VK_KHR_external_semaphore_fd, VK_KHR_format_feature_flags2, VK_KHR_fragment_shader_barycentric, VK_KHR_fragment_shading_rate, VK_KHR_get_memory_requirements2, VK_KHR_global_priority, VK_KHR_image_format_list, VK_KHR_imageless_framebuffer, VK_KHR_incremental_present, VK_KHR_index_type_uint8, VK_KHR_line_rasterization, VK_KHR_load_store_op_none, VK_KHR_maintenance1, VK_KHR_maintenance2, VK_KHR_maintenance3, VK_KHR_maintenance4, VK_KHR_maintenance5, VK_KHR_maintenance6, VK_KHR_map_memory2, VK_KHR_multiview, VK_KHR_performance_query, VK_KHR_pipeline_executable_properties, VK_KHR_pipeline_library, VK_KHR_present_id, VK_KHR_present_wait, VK_KHR_push_descriptor, VK_KHR_ray_query, VK_KHR_ray_tracing_maintenance1, VK_KHR_ray_tracing_pipeline, VK_KHR_ray_tracing_position_fetch, VK_KHR_relaxed_block_layout, VK_KHR_sampler_mirror_clamp_to_edge, VK_KHR_sampler_ycbcr_conversion, VK_KHR_separate_depth_stencil_layouts, VK_KHR_shader_atomic_int64, VK_KHR_shader_clock, VK_KHR_shader_draw_parameters, VK_KHR_shader_expect_assume, VK_KHR_shader_float16_int8, VK_KHR_shader_float_controls, VK_KHR_shader_integer_dot_product, VK_KHR_shader_maximal_reconvergence, VK_KHR_shader_non_semantic_info, VK_KHR_shader_quad_control, VK_KHR_shader_subgroup_extended_types, VK_KHR_shader_subgroup_rotate, VK_KHR_shader_subgroup_uniform_control_flow, VK_KHR_shader_terminate_invocation, VK_KHR_spirv_1_4, VK_KHR_storage_buffer_storage_class, VK_KHR_swapchain, VK_KHR_swapchain_mutable_format, VK_KHR_synchronization2, VK_KHR_timeline_semaphore, VK_KHR_uniform_buffer_standard_layout, VK_KHR_variable_pointers, VK_KHR_vertex_attribute_divisor, VK_KHR_vulkan_memory_model, VK_KHR_workgroup_memory_explicit_layout, VK_KHR_zero_initialize_workgroup_memory, VK_EXT_4444_formats, VK_EXT_attachment_feedback_loop_dynamic_state, VK_EXT_attachment_feedback_loop_layout, VK_EXT_border_color_swizzle, VK_EXT_buffer_device_address, VK_EXT_calibrated_timestamps, VK_EXT_color_write_enable, VK_EXT_conditional_rendering, VK_EXT_conservative_rasterization, VK_EXT_custom_border_color, VK_EXT_depth_bias_control, VK_EXT_depth_clamp_zero_one, VK_EXT_depth_clip_control, VK_EXT_depth_clip_enable, VK_EXT_depth_range_unrestricted, VK_EXT_descriptor_buffer, VK_EXT_descriptor_indexing, VK_EXT_device_address_binding_report, VK_EXT_device_fault, VK_EXT_discard_rectangles, VK_EXT_display_control, VK_EXT_dynamic_rendering_unused_attachments, VK_EXT_extended_dynamic_state, VK_EXT_extended_dynamic_state2, VK_EXT_extended_dynamic_state3, VK_EXT_external_memory_acquire_unmodified, VK_EXT_external_memory_dma_buf, VK_EXT_external_memory_host, VK_EXT_fragment_shader_interlock, VK_EXT_global_priority, VK_EXT_global_priority_query, VK_EXT_graphics_pipeline_library, VK_EXT_host_query_reset, VK_EXT_image_2d_view_of_3d, VK_EXT_image_compression_control, VK_EXT_image_drm_format_modifier, VK_EXT_image_robustness, VK_EXT_image_sliced_view_of_3d, VK_EXT_image_view_min_lod, VK_EXT_index_type_uint8, VK_EXT_inline_uniform_block, VK_EXT_line_rasterization, VK_EXT_load_store_op_none, VK_EXT_map_memory_placed, VK_EXT_memory_budget, VK_EXT_memory_priority, VK_EXT_mesh_shader, VK_EXT_multi_draw, VK_EXT_mutable_descriptor_type, VK_EXT_non_seamless_cube_map, VK_EXT_pci_bus_info, VK_EXT_physical_device_drm, VK_EXT_pipeline_creation_cache_control, VK_EXT_pipeline_creation_feedback, VK_EXT_pipeline_library_group_handles, VK_EXT_pipeline_robustness, VK_EXT_post_depth_coverage, VK_EXT_primitive_topology_list_restart, VK_EXT_primitives_generated_query, VK_EXT_private_data, VK_EXT_provoking_vertex, VK_EXT_queue_family_foreign, VK_EXT_robustness2, VK_EXT_sampler_filter_minmax, VK_EXT_scalar_block_layout, VK_EXT_separate_stencil_usage, VK_EXT_shader_atomic_float, VK_EXT_shader_atomic_float2, VK_EXT_shader_demote_to_helper_invocation, VK_EXT_shader_image_atomic_int64, VK_EXT_shader_module_identifier, VK_EXT_shader_object, VK_EXT_shader_stencil_export, VK_EXT_shader_subgroup_ballot, VK_EXT_shader_subgroup_vote, VK_EXT_shader_viewport_index_layer, VK_EXT_subgroup_size_control, VK_EXT_swapchain_maintenance1, VK_EXT_texel_buffer_alignment, VK_EXT_tooling_info, VK_EXT_transform_feedback, VK_EXT_vertex_attribute_divisor, VK_EXT_vertex_input_dynamic_state, VK_EXT_ycbcr_image_arrays, VK_AMD_buffer_marker, VK_AMD_device_coherent_memory, VK_AMD_draw_indirect_count, VK_AMD_gcn_shader, VK_AMD_gpu_shader_half_float, VK_AMD_gpu_shader_int16, VK_AMD_memory_overallocation_behavior, VK_AMD_mixed_attachment_samples, VK_AMD_shader_ballot, VK_AMD_shader_core_properties, VK_AMD_shader_core_properties2, VK_AMD_shader_early_and_late_fragment_tests, VK_AMD_shader_explicit_vertex_parameter, VK_AMD_shader_fragment_mask, VK_AMD_shader_image_load_store_lod, VK_AMD_shader_trinary_minmax, VK_AMD_texture_gather_bias_lod, VK_GOOGLE_decorate_string, VK_GOOGLE_hlsl_functionality1, VK_GOOGLE_user_type, VK_INTEL_shader_integer_functions2, VK_NV_compute_shader_derivatives, VK_VALVE_mutable_descriptor_type
[Render.Vulkan] <Info> vk_instance.cpp:CreateDevice:226: Physical device subgroup size 64
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_KHR_swapchain
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_shader_stencil_export
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_external_memory_host
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_custom_border_color
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_KHR_push_descriptor
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_depth_clip_control
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_depth_range_unrestricted
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_KHR_workgroup_memory_explicit_layout
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_vertex_input_dynamic_state
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_KHR_fragment_shader_barycentric
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_color_write_enable
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_extended_dynamic_state3
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_robustness2
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_primitive_topology_list_restart
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_KHR_maintenance5
[Render.Vulkan] <Warning> vk_instance.cpp:operator():246: Extension VK_EXT_legacy_vertex_attributes unavailable.
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_AMD_shader_image_load_store_lod
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_KHR_maintenance4
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_KHR_format_feature_flags2
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_KHR_dynamic_rendering
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_shader_demote_to_helper_invocation
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_KHR_synchronization2
[Render.Vulkan] <Info> vk_instance.cpp:operator():241: Enabling extension: VK_EXT_extended_dynamic_state
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=1, number_format=2 is not fully supported (vk_format=R8Uscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=1, number_format=3 is not fully supported (vk_format=R8Sscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=2, number_format=2 is not fully supported (vk_format=R16Uscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=2, number_format=3 is not fully supported (vk_format=R16Sscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=3, number_format=2 is not fully supported (vk_format=R8G8Uscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=3, number_format=3 is not fully supported (vk_format=R8G8Sscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=5, number_format=2 is not fully supported (vk_format=R16G16Uscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=5, number_format=3 is not fully supported (vk_format=R16G16Sscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=9, number_format=1 is not fully supported (vk_format=A2B10G10R10SnormPack32, missing features={ SampledImage | StorageImage | UniformTexelBuffer | StorageTexelBuffer | ColorAttachment | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=9, number_format=2 is not fully supported (vk_format=A2B10G10R10UscaledPack32, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=9, number_format=3 is not fully supported (vk_format=A2B10G10R10SscaledPack32, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=9, number_format=5 is not fully supported (vk_format=A2B10G10R10SintPack32, missing features={ SampledImage | StorageImage | UniformTexelBuffer | StorageTexelBuffer | ColorAttachment | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=10, number_format=2 is not fully supported (vk_format=R8G8B8A8Uscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=10, number_format=3 is not fully supported (vk_format=R8G8B8A8Sscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=12, number_format=2 is not fully supported (vk_format=R16G16B16A16Uscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=12, number_format=3 is not fully supported (vk_format=R16G16B16A16Sscaled, missing features={ SampledImage | UniformTexelBuffer | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=13, number_format=4 is not fully supported (vk_format=R32G32B32Uint, missing features={ SampledImage | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=13, number_format=5 is not fully supported (vk_format=R32G32B32Sint, missing features={ SampledImage | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=13, number_format=7 is not fully supported (vk_format=R32G32B32Sfloat, missing features={ SampledImage | TransferSrc | TransferDst })
[Render.Vulkan] <Warning> vk_instance.cpp:Instance:170: Surface format data_format=13, number_format=7 is not fully supported (vk_format=R32G32B32Sfloat, missing features={ SampledImage | TransferSrc | TransferDst })
[Debug] <Critical> signals.cpp:SignalHandler:85: Unreachable code!
Unhandled access violation in thread 'shadPS4:Present' at code address 0x55a3e9d98a1e: Read from address 0x55a3fe10f5f0
Trace/breakpoint trap (core dumped)
`

**Comment by ngoquang2708** [comment]
Work fine on mine. Can you change the log type to ``sync`` in settings, test again, if it still crash, attach (don't paste) your ``/home/deck/.local/share/shadPS4/log/shad_log.txt`` here.

**Comment by dragoonDorise** [comment]
Works on 0.5.0, it wasn't on 0.4.0...  thanks!
