### ISSUE TITLE
[Bloodborne] [Regression] Character hair is missing after 0.4

### ISSUE THREAD

**Issue by rafael-57** [shadps4-emu/shadPS4#1883]
This is a picture of hair currently with latest main (baldie):
<img width="797" alt="hair_0 5" src="https://github.com/user-attachments/assets/5e80938c-380c-44ed-aa57-33ae6527f013" />

This has been present for a while in 0.4.1W IP but I've only double-checked with 0.4 now. If needed just let me know and I will fix my visual studio and try to find the guilty commit.

<img width="917" alt="hair_0 4" src="https://github.com/user-attachments/assets/6bc72a4e-c925-497f-82d8-73a3db5530e8" />

I can also share a savefile to quickly reproduce the issue. Let me know for any questions

Just in case, this is AMD CPU + Nvidia GPU. Not posting logs since I'm not sure they would help with anything.

**Comment by Missake212** [comment]
Duplicate of #1858

**Comment by rafael-57** [comment]
Can confirm, it's a duplicate.
