### ISSUE TITLE
AppImage - Fullscreen = Freeze

### ISSUE THREAD

**Issue by ghost** [shadps4-emu/shadPS4#1888]
Hey, the Linux Build works perfetctly fine, but using the AppImage with Fullscreen enabled results in a blackscreen.
Starting in windowed mode works, but pressing F11 for fullscreen results in a freeze.

**Comment by ngoquang2708** [comment]
Can you try if this works https://github.com/shadps4-emu/shadPS4/pull/1860. If it is please report there.
Link to builds https://github.com/shadps4-emu/shadPS4/actions/runs/12489138276.

**Comment by ghost** [comment]
Thank you!! All of the 3 things work now! <3
>Launching with fullscreen enabled
>Launching windowed, fullscreening with F11.
>Resizing window.

No crashes, freezes or blackscreens.

**Comment by ngoquang2708** [comment]
Much appreciate if you could report this to #1860.
