### ISSUE TITLE
Some translation entries are not working

### ISSUE THREAD

**Issue by DemoJameson** [shadps4-emu/shadPS4#1891]
The translation entries for both success and failure of creating shortcuts do not work, don't know if there are any other
https://github.com/shadps4-emu/shadPS4/blob/0939082aca4e289a6e9804987949ea732eb923b9/src/qt_gui/translations/zh_CN.ts#L186
![image](https://github.com/user-attachments/assets/ebd84e72-ee60-4265-ac5d-207cad345689)

**Comment by DanielSvoboda** [comment]
Thanks for reporting this, in all languages ​​this didn't work, I hadn't noticed that before. I've fixed it in PR1897
