### ISSUE TITLE
Timer class does not properly count up outside of Windows

### ISSUE THREAD

**Issue by wheremyfoodat** [shadps4-emu/shadPS4#19]
The timer class compiles but does not count up. You might be interested in using https://linux.die.net/man/2/clock_gettime on Unix.

**Comment by georgemoralis** [comment]
i am not into linux , you can probably fix it with a pull request :D

**Comment by wheremyfoodat** [comment]
what is a pull request

**Comment by VelocityRa** [comment]
what is linux

**Comment by wheremyfoodat** [comment]
I don't know but it sounds very sexy

**Comment by georgemoralis** [comment]
μισω το linux , καταραμενο linux

**Comment by georgemoralis** [comment]
there isn't a timer class anymore , problem solved!
