### ISSUE TITLE
Bloodborne black screen on windows.

### ISSUE THREAD

**Issue by 22casual** [shadps4-emu/shadPS4#1902]
Hey so I am not experienced at all with emulation but I would like some help with this cuz I don`t get what I am doing wrong since I followed tutorials. Any help would be nice here's the logs.

[LOg.txt](https://github.com/user-attachments/files/18253924/LOg.txt)

**Comment by mailwl** [comment]
log not from start.

**Comment by 22casual** [comment]
> log not from start.

I already figured out my problem. The param folder was empty

**Comment by Missake212** [comment]
Could you close the issue

**Comment by 22casual** [comment]
> Could you close the issue
