### ISSUE TITLE
Bloodborne Point lights not working

### ISSUE THREAD

**Issue by moazcheese** [shadps4-emu/shadPS4#1913]
This issue was encountered on ShadPS4 0.5.1 WIP but it also happens on the stable release

![Screenshot (56)](https://github.com/user-attachments/assets/f442b67f-9f2b-4d6b-9578-4e5ced74fde5)
![Screenshot (57)](https://github.com/user-attachments/assets/a6368403-2693-44d1-80a8-267952194dd9)
![Screenshot (58)](https://github.com/user-attachments/assets/ccda21df-f7b8-4b97-9367-2c074cc94d09)

As seen in the images, there are no point lights in places where there clearly should be, I can't seem to find this issue anywhere on the internet

As for my system specs, my GPU is a gtx 1060 and the CPU is i5-7400

**Comment by Missake212** [comment]
Do you have any mods installed ?

**Comment by moazcheese** [comment]
> Do you have any mods installed ?

Sorry, i forgot to mention it in the issue but yes I do, BloodBorne visual tweaks and visual FX restoration namely

**Comment by Missake212** [comment]
Try a fresh install with no mods to see if that fixes it

**Comment by moazcheese** [comment]
> Try a fresh install with no mods to see if that fixes it

I have, the issue remains

**Comment by Missake212** [comment]
Try to redump your game then, might be a bad dump

**Comment by moazcheese** [comment]
> Try to redump your game then, might be a bad dump

I'll try and get back to you, thanks

**Comment by moazcheese** [comment]
I cant find the original pkg file anywhere actually i think i might've gotten the game pre-dumped, so any other suggestions are appreciated, if not, i'll just download the pkg

**Comment by polybiusproxy** [comment]
Piracy is strictly prohibited.
