### ISSUE TITLE
my game keeps crashing on the new builds

### ISSUE THREAD

**Issue by AzslayZ** [shadps4-emu/shadPS4#1915]
[shad_log.txt](https://github.com/user-attachments/files/18255693/shad_log.txt)

**Comment by mailwl** [comment]
useless issue. Suggest to close.
TS, create issue in https://github.com/shadps4-emu/shadps4-game-compatibility with all rules

**Comment by rainmakerv3** [comment]
Also, this is not an official build, please discuss this on the fork creator's github page instead
