### ISSUE TITLE
Hopefully, you can add something like FSR  bilinear filtering

### ISSUE THREAD

**Issue by ycb678** [shadps4-emu/shadPS4#1919]
Hopefully, you can add something like FSR  bilinear filtering

**Comment by ycb678** [comment]
Using an external FSR will allow the game to perform better at 1080p 
Hopefully built into the emulator

**Comment by Foul-Tarnished** [comment]
afaik they could only add FSR1 and not FSR2/3

duplicate of #1864
related to #1303

**Comment by roamic** [comment]
Closed as duplicate.
