### ISSUE TITLE
DLC Love Live SIF Issue

### ISSUE THREAD

**Issue by Gabrielfsn** [shadps4-emu/shadPS4#1921]
I installed all the DLCs on Shadps4 0.5.0 (Release) for the game Love Live! School Idol Festival after school ACTIVITY Wai-Wai!Home Meeting!!, but the game only unlocks the costumes, not the songs. What could be the problem?

**Comment by roamic** [comment]
This is not a place for such questions. You can join our discord and ask there. GitHub issues is strictly for technical and development topics.
