### ISSUE TITLE
" vk_presenterer.cpp:operator():772:assertation failed " casue crash while loading

### ISSUE THREAD

**Issue by r3inforcer** [shadps4-emu/shadPS4#1923]
![immagine](https://github.com/user-attachments/assets/916e3ccd-45e7-4c74-852d-acc426cd4efe)
while loading, for whatever reason, bc I'm died or bc I've tp my-self somewhere game freeze screens go black and then the emulator crash

**Comment by raphaelthegreat** [comment]
Github isn't for support requests, please seek helper elsewhere
