### ISSUE TITLE
[Feature Request] add a self decryption util

### ISSUE THREAD

**Issue by switchuwu** [shadps4-emu/shadPS4#1926]
title. rpcs3 has the same thing. shadps4 already runs encrypted eboots so it should work

**Comment by Nenkai** [comment]
Retail packages (and by definition eboots) cannot be decrypted as is without a console.
shadPS4 does not run encrypted eboots. FPKGs contain eboots that are already decrypted.

**Comment by kalaposfos13** [comment]
shadPS4 can technically run encrypted eboots, if you ignore the fact that it will handle it as if it's unencrypted and will crash immediately due to garbage data. This is because a lot of things in this project don't have any form of error checking, so you can even open any random file with it, if you want to, but that will also just crash.

**Comment by StevenMiller123** [comment]
This is both not feasible, and not planned. Just dump your games through the proper methods and you shouldn't have any issues.

**Comment by mailwl** [comment]
AFAIR, ps3 and ps vita private keys for decryption was right on console itself as usual file.
in ps4 private keys somewhere in hardware and cannot be extracted. so, there is 2 way to get decrypted games - decrypt by youself using jailbroken ps4, or download already decrypted. i think, both ways illegal, you don't "own" software (and hardware, ps4), even if you buy it.

**Comment by switchuwu** [comment]
maybe i misunderstood something.
selfs are encrypted, even in an fpkg.
decrypting them turns them into elfs (in which the decryption key is always the same for fpkgs), which allows for binary editing in something like ida for example.

**Comment by switchuwu** [comment]
a tool like this already exists
https://github.com/SocraticBliss/ps4_unfself

**Comment by mailwl** [comment]
> selfs are encrypted, even in an fpkg.

encrypted with key, which looks like: 0000000000000000000
