### ISSUE TITLE
pvs studio static analizer

### ISSUE THREAD

**Issue by mailwl** [shadps4-emu/shadPS4#1934]
i am trying to analize code with PVS Studio, it found some bad code, like this:
https://github.com/shadps4-emu/shadPS4/blob/3218c36b22335e69d558a724627f9876ac70f7b7/src/core/libraries/save_data/savedata.cpp#L1259
V522 Dereferencing of the null pointer 'mount' might take place. savedata.cpp 1259

this convert to: if (mount == nullptr && `nullptr`->dirName != nullptr)

how do you think, it should be fixed? create new PR with fixes?

**Comment by georgemoralis** [comment]
yah that would be great

**Comment by Hermiten** [comment]
Hello, I'm closing this one. Better to come on Discord to have more information how to debug everything !
You can also open PR as draft to ask devs to helps you solving some bad code :)

Thanks you for your help

**Comment by mailwl** [comment]
Discord was banned in Russia :)
i will create PR, later
