### ISSUE TITLE
[macOS] [BB] Crash in first Chalice Dungeon - CUSA03173

### ISSUE THREAD

**Issue by shinra-electric** [shadps4-emu/shadPS4#1938]
I encountered a reproducible crash in the first chalice dungeon in CUSA03173 1.09. 

The location is the very first dungeon. In order to access it you need to have defeated the blood-starved beast, so here is a save:
[SPRJ0005.zip](https://github.com/user-attachments/files/18264182/SPRJ0005.zip)

**Logs**
[shad_log.txt](https://github.com/user-attachments/files/18264186/shad_log.txt)
[Terminal Saved Output.txt](https://github.com/user-attachments/files/18264190/Terminal.Saved.Output.txt)

**Location**
<img width="1392" alt="Screenshot 2024-12-27 at 22 36 36" src="https://github.com/user-attachments/assets/b68e5165-c5a0-4374-98de-e2bda733efa4" />

https://github.com/user-attachments/assets/e69302b6-63e5-4fc3-bebf-c918e04f8a28

**System**
M1 Pro
Sequoia 15.2

**Comment by squidbus** [comment]
Seems to be another instance of:
```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Vertex shader requires output buffer, but there is no free slot to pass it.
```

So a tessellation issue same as https://github.com/shadps4-emu/shadPS4/issues/1820. You may want to consolidate this issue into that one.

**Comment by shinra-electric** [comment]
Moved to the other open PR as advised.
