### ISSUE TITLE
ShadPS4 closes when attempting to launch Bloodborne

### ISSUE THREAD

**Issue by RandomizedHuman** [shadps4-emu/shadPS4#1940]
I tried to launch Bloodborne using ShadPS4, but it closed without launching the game. There is seemingly no relevant error message.

https://github.com/user-attachments/assets/617564e4-bc9e-43af-a68f-062bdd90aee3

My specs are: a Intel Core i7 12700K,  a NVIDIA GeForce RTX 3070 Ti, 32GB of DDR5 RAM, an Asus PRIME Z790-A WIFI, and a Samsung SSD 980 PRO 1TB. I'm also running Windows 11.

Any help would be appreciated.

**Comment by bolt1c** [comment]
I am also experiencing the same problem. We both have very similar hardware aswell. When i launch Bloodborne, it also crashes but the cmd prompt goes away too?

**Comment by RandomizedHuman** [comment]
> I am also experiencing the same problem. We both have very similar hardware aswell. When i launch Bloodborne, it also crashes but the cmd prompt goes away too?

I turned on a Windows setting which stopped it from closing, but it didn't change anything.

**Comment by bolt1c** [comment]
> > I am also experiencing the same problem. We both have very similar hardware aswell. When i launch Bloodborne, it also crashes but the cmd prompt goes away too?
> 
> I turned on a Windows setting which stopped it from closing, but it didn't change anything.

can you see your logs? i cant.

**Comment by mailwl** [comment]
logs saves to `user\log\shad_log.txt`
the folder `user` in same folder as `shadps4.exe` executable

**Comment by Hermiten** [comment]
Do you have Microsoft Visual C++ 2022 installed ?
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by RandomizedHuman** [comment]
> Do you have Microsoft Visual C++ 2022 installed ? https://aka.ms/vs/17/release/vc_redist.x64.exe

This worked, thank you for your help.
