### ISSUE TITLE
CUSA10053 render issue

### ISSUE THREAD

**Issue by Duer03** [shadps4-emu/shadPS4#1943]
I got a render issue happening when playing FTON lost paradise Chinese version（CUSA10053）
![9B04A80F4301AC8075BC49756A6B2E3E](https://github.com/user-attachments/assets/d94b2db4-5d1c-4198-9783-d3fcc33a2411)

**Comment by Xphalnos** [comment]
Can you send a log? Because otherwise it won't be very convenient for us.

**Comment by polybiusproxy** [comment]
This issue is known and to be fixed with PR https://github.com/shadps4-emu/shadPS4/pull/1906.

**Comment by Duer03** [comment]
> This issue is known and to be fixed with PR #1906.

I found that someone plays well with the English version, I wonder why

**Comment by Hermiten** [comment]
There is no report of this game, lot of things can happens on an emulator in alpha stage.
Thanks for the report, you can see the progress here: #1906
You can alos open a test for this game here: https://github.com/shadps4-emu/shadps4-game-compatibility/
