### ISSUE TITLE
ShadPS4 not starting after selecting folders

### ISSUE THREAD

**Issue by RaymonMX** [shadps4-emu/shadPS4#1954]
I try to open the .exe and I select the folders, but after that the emulator doesn't open. I've tried to install the correct Visual C++ stuff, and I tried many of them, but it simply doesn't work.

I also tried to move the folder to my C:/ but the same issue happens.

https://github.com/user-attachments/assets/36e22274-57aa-4ab6-9969-a4b63cc004e4

**Comment by Missake212** [comment]
Are your drivers up to date? Also what CPU and GPU do you have ?

**Comment by RaymonMX** [comment]
They are.

Processor | AMD Ryzen 5 4600H with Radeon Graphics
Video Card | AMD Radeon(TM) Graphics
Video Card #2 | NVIDIA GeForce GTX 1650
Operating System | Windows 11
RAM | 16 GB

https://github.com/user-attachments/assets/688dbb8b-93e6-4316-bb3f-097106c6d275

**Comment by Missake212** [comment]
I wouldn't trust Windows built in driver updater, you should look directly at the AMD iGPU drivers webpage and download them from here

**Comment by RaymonMX** [comment]
Problem solved! Thank you so much

The problem really was the AMD drivers. I was focused on my NVIDIA GPU and totally forgot the AMD.

Thanks again!
