### ISSUE TITLE
ShadPS4 Crash

### ISSUE THREAD

**Issue by k-koehler** [shadps4-emu/shadPS4#1955]
Shadps4 info:
- shadps4 v0.5.0
- firmware 4.50

Specs:

- i7-13700k
- 4080 super
- 32gb ram
- windows 11

Game:

CUSA03173, Bloodborne 1.09

Patches (shadps4 repo):

- Disable HTTP Request
- 60 FPS (With Deltatime)
- Disable Vsync
- Resolution Patch (2560x1440)

Relevant Log:

```
[Debug] <Critical> liverpool_to_vk.h:PromoteFormatToDepth:88: Unreachable code!
```

**Comment by roamic** [comment]
This repository only accepts issues with clean runs (no mods, no patches, no forks). Can you disable all patches and see if it's gone? If it's not, attach the whole log and describe in detail how to reproduce it.
If you are having troubles with patches you should submit an issue [here](https://github.com/shadps4-emu/ps4_cheats).

**Comment by Hermiten** [comment]
Did you install Microsoft Visual C++ https://aka.ms/vs/17/release/vc_redist.x64.exe ?

**Comment by nx555555555** [comment]
> Did you install Microsoft Visual C++ https://aka.ms/vs/17/release/vc_redist.x64.exe ?

I installed it when I saw your reply, but it still crashes.
Using blood vials or taking enemy damage will cause a crash.

Windows 10 Home 64-bit
i7-12700KF
32gb RAM
MAG Z690 TORPEDO
NVIDIA GeForce RTX 3080 Ti

shadps4 v0.5.0
No patches, no cheats
Base emulator settings
CUSA03173, Bloodborne 1.09

**Comment by Hermiten** [comment]
Ok, but now you can start it. It's a new problem. 
For this new one, we already talk about it here: https://github.com/shadps4-emu/shadPS4/issues/1641
You will find all information needed. 
I'm closing this one
