### ISSUE TITLE
Bloodborne crashing on launch with error attached 

### ISSUE THREAD

**Issue by Spangle232** [shadps4-emu/shadPS4#1961]
Redacted

**Comment by mailwl** [comment]
i think, maintainers should create a template for issues, which contains mandatory fields with OS, shadPS4 version, log file and so on.
telepaths on vacation

**Comment by Hermiten** [comment]
You can come here and see what to do:
https://github.com/shadps4-emu/shadPS4/issues/1641

**Comment by Hermiten** [comment]
> i think, maintainers should create a template for issues, which contains mandatory fields with OS, shadPS4 version, log file and so on. telepaths on vacation

For sure ! I don't have access for it but I will be happy to create a template

**Comment by ngoquang2708** [comment]
@Hermiten You can make PR to create the template for issues.

**Comment by Hermiten** [comment]
Wonderful
