### ISSUE TITLE
How do i manually update my bloodborne copy?

### ISSUE THREAD

**Issue by david100awesome** [shadps4-emu/shadPS4#1964]
I legally (wow, shocker) ripped bloodborne off of my jailbroken ps4, and i got the direct files, not the .pkgs. Ive got bloodborne version 1.00 working, but i cant seem to figure out how to update it to the 1.09 version. yes, i also ripped the 1.09 patch off of my ps4 as well. Now how do i update the 1.00 game to the 1.09 using these files
![image](https://github.com/user-attachments/assets/6b43b38f-1f59-4966-bbad-ec80465c0e9e)

**Comment by kalaposfos13** [comment]
Either rename the patch folder to CUSA00900-UPDATE and turn on Enable Separate Update Folder, or take the patch folder contents and add it to the main folder, overwriting some of the files.

**Comment by kalaposfos13** [comment]
This info should be added to the Quickstart as well, so people who dump their games in this way aren't confused on what to do.

**Comment by mailwl** [comment]
are all files can be replaced? i think, `sce_sys` may contains files, which tells it's update, not main game
(atm shadPS4 does not rely on this files, but who knows)

**Comment by david100awesome** [comment]
I renamed the patch folder, and it worked!
