### ISSUE TITLE
[APP BUG]: The emulator just dosen't start

### ISSUE THREAD

**Issue by Thanas124** [shadps4-emu/shadPS4#1977]
### Checklist

- [X] I have searched for a similar issue in this repository and did not find one.
- [X] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.

### Describe the Bug

![Screenshot 2024-12-30 010506](https://github.com/user-attachments/assets/cb28393d-e9f9-4ffb-8491-32167a05adbb)
When i open for the first time after i set the path for game file and DLC file

### Reproduction Steps

![2](https://github.com/user-attachments/assets/dfeb4519-ebfc-488c-8bb0-f51f9b63eb05)
When i open for the second time.

### Specify OS Version

windows 11

**Comment by roamic** [comment]
This is a support request.
Also, if you've really searched for an issue you'd have found plenty that have the same problem. Closing as a low effort support request.

**Comment by Thanas124** [comment]
> This is a support request. Also, if you've really searched for an issue you'd have found plenty that have the same problem. Closing as a low effort support request.

Where can i write for support than ?  Because i can't find the solution no matter how much i search.

**Comment by roamic** [comment]
![Screenshot_2024-12-31-09-05-56-095_org mozilla firefox-edit](https://github.com/user-attachments/assets/27cd9641-a5ad-415b-83ef-294a2f0b7153)
