### ISSUE TITLE
Bloodborne CUSA03173 is not booting up on shadps4

### ISSUE THREAD

**Issue by PreySlaughtered** [shadps4-emu/shadPS4#1979]
### Checklist

- [ ] I have searched for a similar issue in this repository and did not find one.
- [X] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.
- [ ] I have re-dumped the game and performed a clean install without mods.
- [x] I have disabled all patches and cheats.
- [ ] I have all the required [system modules](https://github.com/shadps4-emu/shadps4-game-compatibility?tab=readme-ov-file#informations) installed.

### Describe the Bug

okay this is my first time discussing an issue on github
i recently downloaded the bloodborne cusa03173 eu goty edition and then the latest nightly pre-release of shadps4 
but now the issue is i can not seem to be able to boot up the game for some reason i don't know and i was wondering if the great minds of github might be able to help

### Reproduction Steps

the game won't boot up and the shadps4 closes as soon as i hit play game icon in it
i saw tutorial on YT but in their case the version and everything is same as mine and the emulator seems to be running some codes in the terminal window in the background but in my case the terminal is just empty nothing gets noted in it and the emulator closes without running the game

### Specify OS Version

windows 11

### CPU

intel core i5 11400H

### GPU

nVidia RTX 3050 Laptop GPU

### Amount of RAM in GB

16 GB

### Amount of VRAM in GB

4 GB

### Logs

heeeelllppppppppppppppppppp

**Comment by Hermiten** [comment]
Unfortunately this is forbidden to download a game. We only support people that dump the game 
Sorry
