### ISSUE TITLE
[Feature Request]: Esdras Tarsis GOW3 HACKS on Main

### ISSUE THREAD

**Issue by SixSeven-off** [shadps4-emu/shadPS4#1983]
### Checklist

- [X] I have searched for a similar issue in this repository and did not find one.

### Description

https://github.com/esdrastarsis/shadPS4/actions/runs/12549969357
Check this one, and port it to main gow3 hacks that is booting up GOW3, not beautiful graphic but is some

### Reason

I want this, because GoW3 deserves to be ported and to be playable by everyone whoever want to test it

### Examples

It has potential, even for future games

**Comment by roamic** [comment]
1. This person can create a pull request themselves if they decide that it is worthy to include
2. We do NOT include hacks in mainline builds

**Comment by polybiusproxy** [comment]
To further explain things, these are called 'hacks' for a reason—they're quick patches done just to see how far the game gets on the emulator, to further help development, and they're not actual fixes for the problems the game has. That said, given the nature of hacks, they can't simply be included on the emulator, but rather the proper solution here is to fix the problems these third-party forks skip.
