### ISSUE TITLE
[DYSMANTLE] Blocks on startup

### ISSUE THREAD

**Issue by Xphalnos** [shadps4-emu/shadPS4#204]
# Description of issue:
When I try to launch Dysmantle, the game gets stuck on the loading screen.
I'm using shadPS4 from commit #203.

Screenshot:
![Capture d'écran 2024-06-17 205350](https://github.com/shadps4-emu/shadPS4/assets/164882787/ec13ab69-3201-4789-95d8-b9cb73771424)

LOG:
[shad_log.txt](https://github.com/user-attachments/files/15875809/shad_log.txt)

Specs:
CPU: Intel Pentium Gold 8505
GPU: Intel UHD Graphics (with latest drivers)
OS: Windows 11 23H2
RAM: 16GB DDR4
Game version 01.08

**Comment by raphaelthegreat** [comment]
The log doesn't show anything interesting. Try enabling vulkan debugging in config.toml and installing the vulkan sdk + opening vulkan configurator (which should enable validation layers in the app).

**Comment by Xphalnos** [comment]
> The log doesn't show anything interesting. Try enabling vulkan debugging in config.toml and installing the vulkan sdk + opening vulkan configurator (which should enable validation layers in the app).

The problem is that I cannot install the Vulkan SDK because of a known error. https://vulkan.lunarg.com/issue/view/6579c9dd5df1125b58afb5d7

**Comment by Xphalnos** [comment]
Here is the debug dump for Dysmantle.
[DebugDump.zip](https://github.com/user-attachments/files/15891878/DebugDump.zip)

**Comment by Xphalnos** [comment]
I close it because there is shadps4-game-compatibility for that
