### ISSUE TITLE
Building fails in Linux

### ISSUE THREAD

**Issue by Shoegzer** [shadps4-emu/shadPS4#205]
From the build log: 

```
/home/testing/Desktop/shadPS4/src/common/logging/backend.cpp: In member function ‘void Common::Log::{anonymous}::Impl::PushEntry(Common::Log::Class, Common::Log::Level, const char*, unsigned int, const char*, std::string)’:
/home/testing/Desktop/shadPS4/src/common/logging/backend.cpp:173:40: error: ‘format’ is not a member of ‘std’; did you mean ‘fmt::v10::format’?
  173 |             const auto& msg_str = std::format("[{}] {}", GetLogClassName(log_class), message);
      |                                        ^~~~~~
In file included from /home/testing/Desktop/shadPS4/src/common/logging/backend.cpp:8:
/home/testing/Desktop/shadPS4/externals/fmt/include/fmt/format.h:4365:13: note: ‘fmt::v10::format’ declared here
 4365 | inline auto format(const Locale& loc, format_string<T...> fmt, T&&... args)
      |             ^~~~~~
```
* OS: Linux Mint 21.3 / kernel 6.5
* CPU: Intel i7-10870h
* Compiler: gcc-12.3.0
* Commit tested: d9f2758850a36f2fd05e2c3d7baf39eca168f9bb
* Full build log: [build.log](https://github.com/user-attachments/files/15893539/build.log)

**Comment by raphaelthegreat** [comment]
Try replacing std::format with fmt::format

**Comment by Shoegzer** [comment]
Thanks, that seems to clear that particular issue but then more errors of various types appear, such as:
```
/home/testing/Desktop/shadPS4/src/core/linker.h:45:30: error: ‘contains’ is not a member of ‘std::ranges’
   45 |             if (std::ranges::contains(imports, m->name, &ModuleInfo::name)) {
      |                              ^~~~~~~~
```
To me this seems to be part of a larger build issue.

**Comment by raphaelthegreat** [comment]
It seems to me like your compiler/libstdc++ version is too old. We use C++23 features and std::ranges::contains was added in GCC 13

**Comment by Shoegzer** [comment]
You nailed it, thanks.  Updating to gcc-13 indeed fixes this as expected.  Closing.

**Comment by deadmeu** [comment]
Would be good to update https://github.com/shadps4-emu/shadPS4/blob/main/documents/building-linux.md to include gcc-13.

**Comment by Kineforce** [comment]
> Would be good to update https://github.com/shadps4-emu/shadPS4/blob/main/documents/building-linux.md to include gcc-13.

+1, it happened to me using Debian Bookworm (by default comes with gcc 12)
