### ISSUE TITLE
[DYSMANTLE] No sound, not accepting input to load past menu

### ISSUE THREAD

**Issue by Shoegzer** [shadps4-emu/shadPS4#209]
As the title indicates, no menu sounds play and it does not accept input to load any main menu option such as "Play" or "Credits".  I'm not sure what keys are mapped to the "X" or "Start" controller buttons, but every key on the keyboard was tested. This contrasts with the video shown [here](https://www.youtube.com/watch?v=b9xzhLBdESE), which does not exhibit these issues. Note that keys to navigate the menu itself (up, down, left, right) do work.  

Test info:

* OS: Linux Mint 21.3 / kernel 6.5
* CPU: Intel i7-10870h
* GPU: Nvidia GTX 3070 / driver 545.29
* Build tested: cb6b21de1f57642e265dcde57fdd26ff3327157c
* Log: [shad_log.txt](https://github.com/user-attachments/files/15948835/shad_log.txt)

**Comment by Shoegzer** [comment]
Update: Tested #210 with gamepad support (using PS5 DualSense pad).  This works - it is possible to go ingame with the pad now.  However, keyboard remains not working on the test system due to a lack of an "accept" key mapped (X button in this case), and there is no sound.

Perhaps this issue is due to differences in OS since the video posted above was from a Windows test system.

**Comment by raphaelthegreat** [comment]
For the sound you need to dump PS4 firmware and place libSceNgs2.prx in sys_modules folder

**Comment by Shoegzer** [comment]
Thanks much. I'll take your word for it that this works until I have time to find docs and dump the firmware to test. In any event I'll plan to keep this issue open at least until keymapping supports the full control suite.

**Comment by EmulationPsycho** [comment]
> Update: Tested #210 with gamepad support (using PS5 DualSense pad). This works - it is possible to go ingame with the pad now. However, keyboard remains not working on the test system due to a lack of an "accept" key mapped (X button in this case), and there is no sound.
> 
> Perhaps this issue is due to differences in OS since the video posted above was from a Windows test system.

Try button 2 friend of keyboard to confirm, and button 6 to exit, button 4 also works for me! :)

**Comment by Shoegzer** [comment]
Interesting. That doesn't work here. What OS are you using?

**Comment by EmulationPsycho** [comment]
> Interesting. That doesn't work here. What OS are you using?

Windows 11 bro

**Comment by Shoegzer** [comment]
Per the keyboard mappings noted in #228, it seems the face buttons are only mapped to numpad keys.  Given that this test system lacks a numpad, the face buttons are of course unusable.  A custom remapping feature would be nice, but at least this issue is known now.  Note that users without a numpad can still use a gamepad if they compile with #210 (not sure why that one was closed though, it works well here at least, but apparently it will be reopened at some point).

Regardless, I'm closing this to avoid needlessly cluttering up the issue log.
