### ISSUE TITLE
Folder scanning for games

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#226]
Please, add possibility to add folders for scanning of games/apps.

**Comment by Tarfist** [comment]
Not the most important feature, but I guess you'll have to wait until the main emulator becomes stable for the devs to start working on additional features like the one you mentioned.

**Comment by notgonnaleo** [comment]
Ok so currently shadPS4 have a option to refresh the current directory to show any new game added into the selected folder, the option itself is this one 
![image](https://github.com/user-attachments/assets/c53ddc65-88c2-40df-a30d-29b099a8a016)

Whenever you click this option after adding the new game in the folder it will reload the list (as expected)
So, could you specify more what exactly you want on this issue? or even if this is something that's already implemented.

**Comment by gandalfthewhite19890404** [comment]
> So, could you specify more what exactly you want on this issue? or even if this is something that's already implemented.

Multiple folders to scan games or elfs. Not only one.
Or I can choose root folder(i.e. whole HDD) and scan it?

**Comment by notgonnaleo** [comment]
Oh i see, I like the first option, it reminds me how FL Studio (DAW Software) works on reading folders, I will take a look on that option, let me know if there's anything else you think that would be worth to add :)

**Comment by kiwidoggie** [comment]
One thing I have noticed is, shadPS4 does not recognize games that do not have the param.sfo (probably for good reason), but it would be nice to have the option to create "dummy" games based on the folder name if no param.sfo is found.

I could probably add support for that if this is okay with the developers intentions.

**Comment by Hermiten** [comment]
Hey @kiwidoggie any news about this ? :)

**Comment by kiwidoggie** [comment]
> Hey @kiwidoggie any news about this ? :)

@Hermiten, I've been waiting for someone on the shadPS4 team to give me feedback.

**Comment by ElBread3** [comment]
Can this be closed now that I've implemented this feature?

**Comment by ares1768** [comment]
![image](https://github.com/user-attachments/assets/9877c0aa-2b6e-4aae-90f4-147c058b9897) 
I installed bloodborne on my external hard drive. does anyone know how can I get it back in the game list in shadps4? refreshing does not work. (I know I can boot it still from the files)

**Comment by Hermiten** [comment]
![image](https://github.com/user-attachments/assets/5e28b9f8-0737-43eb-9b4c-dc6c2c4236a2)

**Comment by ares1768** [comment]
Yep, thank you I just changed them.
