### ISSUE TITLE
shadePS4 for macOS is planned?

### ISSUE THREAD

**Issue by muhammadbahaa2001** [shadps4-emu/shadPS4#240]
I know this project for the fun and whenever you have free time although you have free limited time. I'm not rushing you, but I was just curious if it will support macOS in the distant future.

**Comment by d9j** [comment]
lol. this project yet to get run properly a single game.

**Comment by ryzendew** [comment]
> lol. this project yet to get run properly a single game.

not true at all it runs a few dead cells is very playable and one piece something or other a 3d game is beyond full speed and also playable and dig world works and a few more i can't remember

**Comment by d9j** [comment]
it's unlikely will be worth effort  to support mac  due to few exclusives on ps4

**Comment by georgemoralis** [comment]
#294 pr has initial support for mac , will be soon on master i believe ;)

**Comment by d9j** [comment]
> #294 pr has initial support for mac , will be soon on master i believe ;)

too optimistic. non of devs have macs as they mentioned. so maintain support will be relied on random contributors. which means there will be no good support

**Comment by VasylBaran** [comment]
@d9j @georgemoralis I'm waiting for it to get merged (I have both M1 and Intel Mac). If it works reliably I plan to use it as the main OS for development

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/c554a826-4971-4703-b2bc-c8d1b173da0c">

**Comment by VasylBaran** [comment]
> it's unlikely will be worth effort to support mac due to few exclusives on ps4

I'm not sure I understand what you mean, the list of PS4 exclusives is the same whether you're emulating on macOS, Linux or Windows.

**Comment by d9j** [comment]
> > it's unlikely will be worth effort to support mac due to few exclusives on ps4
> 
> I'm not sure I understand what you mean, the list of PS4 exclusives is the same whether you're emulating on macOS, Linux or Windows.

my point is the game may run properly on windows / linux.. but not mac because of   architecture and drivers support. therefore the development of this can be quite burden unless there is huge push to support these platforms

**Comment by VasylBaran** [comment]
> > > it's unlikely will be worth effort to support mac due to few exclusives on ps4
> > 
> > 
> > I'm not sure I understand what you mean, the list of PS4 exclusives is the same whether you're emulating on macOS, Linux or Windows.
> 
> my point is the game may run properly on windows / linux.. but not mac because of architecture and drivers support. therefore the development of this can be quite burden unless there is huge push to support these platforms

I agree.

**Comment by atsetilam** [comment]
First support PR was merged 4 days ago: https://github.com/shadps4-emu/shadPS4/pull/294

I am looking forward to testing the emulator on my 2019 MacBook Pro 16".

**Comment by VasylBaran** [comment]
@atsetilam yeap 😎

![Screenshot 2024-07-25 at 18 15 17](https://github.com/user-attachments/assets/2817315c-4cc9-4f22-be93-756c960dbba9)
