### ISSUE TITLE
Linux not running the AppImage on Steam Deck

### ISSUE THREAD

**Issue by obscurerev** [shadps4-emu/shadPS4#251]
I am receiving an error which doesn't allow the program to run on Steam Deck. I've read a forum online saying it's due to the libraries the appimage is being built on to be a later version. Is there a fix, or is it not possible to run ShadPS4 on a Steam Deck right now?
![image](https://github.com/shadps4-emu/shadPS4/assets/77601184/3546c9fc-6f93-40d4-bbc7-642220243bf6)

**Comment by qurious-pixel** [comment]
This is due to the build using the latest GLIBC version for the artifacts. Using an earlier version `Ubuntu 22.04`, would fix this error, but there is another error curently blocking that tries to create a read-write folder in a read-only section of the package.

**Comment by anatoliiohorodnyk** [comment]
Update Steam Deck to latest 20240702 firmware, and try. I managed to run the linux-qt version from the test branch where the read-only problem is fixed

**Comment by prototype5885** [comment]
same issue on debian 12

**Comment by MorrisBA** [comment]
I have the same issue on PopOS! on Wayland. I have tried with the latest linux-qt build. I have followed the steps to build using cmake, outlined in Linux Build Instructions. When installing the requirements I receive the below.
`E: Unable to locate package libvulkan-memory-allocator-dev
E: Unable to locate package libmagicenum-dev`

**Comment by veryrealwildcat** [comment]
Just tested, the bb-hacks branch is not working on latest stable SteamOS. Just refuses to open in both desktop and game mode.

**Comment by Hermiten** [comment]
Can you test again ?
Maybe this can fix the problem https://github.com/shadps4-emu/shadPS4/pull/1187

**Comment by qurious-pixel** [comment]
> Just tested, the bb-hacks branch is not working on latest stable SteamOS. Just refuses to open in both desktop and game mode.

You need SteamOS Beta branch. It is up-to-date with the builds from Github.
