### ISSUE TITLE
unresolved! -QgqOT5u2Vk lib[libc_v1]mod[libc_v1.1]  from videoout_basic.elf (debug version probably)

### ISSUE THREAD

**Issue by georgemoralis** [shadps4-emu/shadPS4#26]
unresolved! -QgqOT5u2Vk lib[libc_v1]mod[libc_v1.1]
R_X86_64_64-R_X86_64_JUMP_SLOT sym_type 2 bind STB_GLOBAL symbol : 0x00000039
function not patched! Unresolved!!!

**Comment by red-prig** [comment]
-QgqOT5u2Vk = _Assert
