### ISSUE TITLE
MSVC doens't support SYS_V_ABI

### ISSUE THREAD

**Issue by georgemoralis** [shadps4-emu/shadPS4#28]
so calling conversions are wrong and the callling functions are also wrong . 

Solution is to go to CLANG 

γαμω την microsoft γαμω

**Comment by wheremyfoodat** [comment]
Ο επαναμεταγλωττιστης του @skmp θα μπορούσε να φτιάξει αυτό το πρόβλημα με φορητό τροπο, ή η χρηση εικονοποίησης, η απλά πολύς κώδικας για να κάνεις ένα συσβ-ον-μσ στρώμα συμβατότητας.

**Comment by georgemoralis** [comment]
clang ,cmake has issue with vstudio  2022 (17.6.5)

https://developercommunity.visualstudio.com/t/cmake-generates-bad-dependencies-for-rc/10398924?q=cmake+dependencies

Let's try vstudio 2022 17.7 preview 4....

**Comment by georgemoralis** [comment]
switched to clang to support SYS_V_ABI
