### ISSUE TITLE
Fix ShadPs4 on Fedora and Arch distros, and in Wayland sessions.

### ISSUE THREAD

**Issue by DanixUwU** [shadps4-emu/shadPS4#301]
The title explains everything.
I am using Nobara Linux (a Fedora distro with Wayland session) and i was trying to test and experiment the emulator on a HP Pavilion Laptop 15-cs3xxx, but the emulator doesnt work at all, i tried everything i installed dependencies, i tried the Apimage version with qt and without qt, i tried X11 session, i tried the WIP and the 0.1.0 versions, and i even tried to build the emulator my self, still noting.
I also heard from some people on the offical discord server that Arch distros doesnt work at all, and its all very sad, because:
1º- I am dualbooting Windows and Linux on the same computer, and on Windows the emulator is working perfectly fine, without the same errors that i am having on Linux;
2º- I need to use Wayland, because is the only way that i can use my monitor properly, my monitor doesnt work on Windows, it doesnt work on X11, it only works with Wayland;
3º- I dont daily drive Windows, and i am experimenting with new distros, so i dont wanna be forced to use a OS that i dont like and i dont care, just because one emulator doesnt work properly on linux (emulator that HAS support for linux).
So with all this problems and reasons, please, pleaseeeeeeee fix Shadps4 to work properly on Fedora/Arch distros, and on Wayland sessions (even if it's just work on xWayland), seriously i am begging for all of you.
[Video Proving.zip](https://github.com/user-attachments/files/16276228/Video.Proving.zip)

**Comment by ryzendew** [comment]
#271 is already a thing can you add it their

**Comment by DanixUwU** [comment]
ok i ill put my comment in their.

> #271 is already a thing can you add it their
