### ISSUE TITLE
Errors when launching Gravity Rush 2

### ISSUE THREAD

**Issue by GingerBobRoss** [shadps4-emu/shadPS4#313]
OS:Endeavor OS
Build: ShadPS4 0.1.0 / ShadPS4-QT

When trying to launch Gravity Rush 2, the log reports:
`[Debug] <Critical> texture_cache.cpp:GuestFaultSignalHandler:43: Unreachable `code!``

I tried using the linux QT build as well, but after launching the Appimage, nothing happens and i am not able to locate any script to actually run ShadPS4 withing the `User` folder it creates.

[shad_log.txt](https://github.com/user-attachments/files/16325969/shad_log.txt)

**Comment by georgemoralis** [comment]
Game is not currently supported you can find some games and their status in compatibility list https://github.com/shadps4-emu/shadps4-game-compatibility
