### ISSUE TITLE
Updates close games on my PC

### ISSUE THREAD

**Issue by ghost** [shadps4-emu/shadPS4#315]
As versões mais recentes (Actions) não conseguem rodar no meu PC, somente as versões antigas (0.1.0). Tem como corrigir no meu caso?

Intel Xeon E3 1225 V3
RX 580 2048SP 8GB GDDR5
16GB DDR3 1600MHz

**Comment by viniciuslrangel** [comment]
Use inglês, por gentileza

**Comment by Lopes93** [comment]
Sorry.Em 21 de jul. de 2024 20:29, Vinicius Rangel ***@***.***> escreveu:
Use inglês, por gentileza

**Comment by ghost** [comment]
The latest versions (Actions) do not run on my PC, only the old versions (0.1.0). Can you agree in my case?

Intel Xeon E3 1225 V3
RX 580 2048SP 8 GB GDDR5
16 GB DDR3 1600 MHz

**Comment by yaya54840** [comment]
Hello yes me too
Some updates do not start on my system
So I'm waiting for the next one
this one works https://github.com/shadps4-emu/shadPS4/actions/runs/10031322981
I noticed that the updates do not accumulate
I think we have to wait for the next release.
correct me if im wrong.

**Comment by Haroldo777** [comment]
I have the same problem with a similar configuration

**Comment by Lopes93** [comment]
The emulator is still in development phase, WIP updates are a little different than the official release ones. When the emulator is well optimized I believe they will fix several bugs.
