### ISSUE TITLE
Crash in Shader::Gcn::CFG::EmitBlocks(), out of bounds list access

### ISSUE THREAD

**Issue by xezrunner** [shadps4-emu/shadPS4#321]
https://github.com/shadps4-emu/shadPS4/blob/1d6a42c39a9c96bdebc5984482199ed1c9167477/src/shader_recompiler/frontend/control_flow_graph.cpp#L105-L108

On **line 107**, the `end_index` for accessing `inst_list` goes beyond (/is equal) to the size of `inst_list` during the startup procedure of Amplitude as it's attempting to start a scene in the engine (Forge Engine game, could be the same case for Rock Band 4,  Fuser and other Harmonix titles on the PS4).

It appears to be processing label 61 out of 63 total. The code mentions the last label being special, but I'm not sure how or why that would be the case.

![image](https://github.com/user-attachments/assets/f2adf4d5-0466-43d4-9492-19fb1cf33a97)

I wasn't able to work around this or figure out how to troubleshoot this further.

**Comment by Sailanarmo** [comment]
This entire for block has a bug in it. The reason is because you call for `std::next`. Once you’ve reached the end of your container `std::next` isn’t going to be able to grab anything other than junk.  

If the last spot in the container is special, either copy all the elements - 1 and iterate over that or keep a count that if the index is the size - 1 to return. I’m currently on mobile or I would suggest a better fix. If I have time tonight I’ll hop on and make a suggestion.

**Comment by xezrunner** [comment]
Currently, Amplitude no longer crashes at this point, but it could also be something else having been broken earlier in the boot process.

> This entire for block has a bug in it. The reason is because you call for std::next. Once you’ve reached the end of your container std::next isn’t going to be able to grab anything other than junk.

I'll leave this issue open then, in case this is something that requires attention regardless of game boot status.

**Comment by xezrunner** [comment]
The root issue causing this should be fixed with https://github.com/shadps4-emu/shadPS4/pull/497, definitely for Amplitude (2016) `CUSA02480`.

Leaving this open in case the above comment related to the for loop having a bug in it still applies.

**Comment by Hermiten** [comment]
Can I have an update on this one ? Is it still revelant ?

**Comment by xezrunner** [comment]
> Can I have an update on this one ? Is it still revelant ?

I believe this isn't relevant anymore. The root issue was fixed elsewhere, this part of the function now behaves fine.

The `for` loop issue mentioned above is probably an intentional choice, as I have noticed during debugging that many iterators use a special "end" element that denotes the end of iteration.  
I could be wrong though. @Sailanarmo do you have any additional input on it?

**Comment by Sailanarmo** [comment]
@xezrunner I would go ahead and close this.
