### ISSUE TITLE
Crash (SIGFPE) in MemoryManager::SearchFree()

### ISSUE THREAD

**Issue by tkoecker** [shadps4-emu/shadPS4#337]
I've encountered a crash in `MemoryManager::SearchFree()` where the function was called with the default value of `alignment` (which is `0`). The crash happens inside the 
```
virtual_addr = Common::AlignUp(vma.base, alignment);
```
where the `value % size` with `size` of `0` triggers a `SIGFPE`.

I guess this can be fixed by calling `Common::AlignUp` the same way as in the other calls in this class:
```
virtual_addr = alignment > 0 ? Common::AlignUp(vma.base, alignment) : vma.base;
```
(or maybe by defaulting alignment to `1` instead - not sure what the semantic of aligning to `0` bytes should be)

**Comment by georgemoralis** [comment]
can you test https://github.com/shadps4-emu/shadPS4/pull/338 . Should fix the issue

**Comment by tkoecker** [comment]
Thx. Yes this fixes the issue. The execution progresses further now.

**Comment by georgemoralis** [comment]
ok fine :)
