### ISSUE TITLE
Breaks Shadps4 Windows 11 24H2

### ISSUE THREAD

**Issue by EmulationChannel** [shadps4-emu/shadPS4#345]
Friends, this emulator doesn't even open here, it simply breaks as soon as I select any game, my help here URGENT
https://streamable.com/src8fi

**Comment by Lopes93** [comment]
In my case it's like that too. We need to wait for the next official emulator update to fix this bug.

**Comment by DanielSvoboda** [comment]
I think the problem is with the "config.toml" file in the "user" folder, it is not being created, if you create a file with the same name it works, test if this works for you

**Comment by EmulationChannel** [comment]
> I think the problem is with the "config.toml" file in the "user" folder, it is not being created, if you create a file with the same name it works, test if this works for you

my case file created even so emulator breaks

**Comment by EmulationChannel** [comment]
> I think the problem is with the "config.toml" file in the "user" folder, it is not being created, if you create a file with the same name it works, test if this works for you

Oky fixed Install Visual Studio 2022 clossing
