### ISSUE TITLE
Assertion Failed! Unsupported component swap mode 3 (Yakuza 6 Blue Jacket Demo)

### ISSUE THREAD

**Issue by shiiironyanpan** [shadps4-emu/shadPS4#349]
Figured that I should make a new issue on Github so that it's easier to keep the track on the progress.

Currently using PR #347, tested on Yakuza 6 Blue Jacket Demo and it finally has consistent crashes that was unable to be logged consistently on previous versions.

Happens with modules and without modules

```
[Debug] <Critical> liverpool_to_vk.cpp:operator():552: Assertion Failed!
Unsupported component swap mode 3
```

log: [shad_log.txt](https://github.com/user-attachments/files/16437980/shad_log.txt)

**Comment by Hermiten** [comment]
I put it on the other issue, I close this one
