### ISSUE TITLE
Doesn't play anything

### ISSUE THREAD

**Issue by OFFTKP** [shadps4-emu/shadPS4#35]
This emulator says it's 10% done but doesn't play anything. Please fix I need to play bloodborne.

**Comment by wheremyfoodat** [comment]
Ελληνικά δεν σου έμαθε η μάνα σου ρε μαλακα και γράφεις στα εγγλέζικα

**Comment by OFFTKP** [comment]
Εκπροσωπώ την γενιά Ζ. (Είμαστε λουλουδέλληνες)

**Comment by wheremyfoodat** [comment]
Ον γκοντ φρ φρ

**Comment by georgemoralis** [comment]
παρηηηη που εισαι παρηηη

**Comment by georgemoralis** [comment]
σε εβαλα και στο ριντμε τι αλλο να κανω

**Comment by OFFTKP** [comment]
aaa egina aderfi?

**Comment by OFFTKP** [comment]
na se kanw kai sena aderfi tote ama einai

**Comment by georgemoralis** [comment]
Ο ροδάκινο γιατί δεν είναι αδερφή στο χαιδντρά?

**Comment by OFFTKP** [comment]
rodakine tha gineis aderfi?

**Comment by wheremyfoodat** [comment]
@OFFTKP Για εσένα μόνο θα γινόμουν

**Comment by wheremyfoodat** [comment]
@OFFTKP https://github.com/wheremyfoodat/Panda3DS/pull/193
Κοιτα σε εκανα αδερφή

**Comment by OFFTKP** [comment]
mpravo mikro mou panda

**Comment by georgemoralis** [comment]
fixed it plays at least 1 demo :D
