### ISSUE TITLE
[Feature request] Controller support

### ISSUE THREAD

**Issue by greggameplayer** [shadps4-emu/shadPS4#357]
Hello, is it possible to allow all kinds of controllers to work instead of only the keyboard including the xbox controllers and the dualshock 4 with proper support of all it's functionnalities ?

**Comment by dima-xd** [comment]
The work is in progress. https://github.com/shadps4-emu/shadPS4/tree/controllers_1 here is a branch with a current progress

**Comment by greggameplayer** [comment]
@dima-xd okay nice, at least this issue will serve to follow the progress of the implementation

**Comment by Shoegzer** [comment]
This can be closed thanks to #407.
