### ISSUE TITLE
[Feature Request] Change SFO Viewer to Properties

### ISSUE THREAD

**Issue by Xphalnos** [shadps4-emu/shadPS4#372]
I suggest replacing the SFO Viewer with Property to display the game specifications.
It could also be used to select patches or cheats. I think that to do this you would need a great mastery of Qt.
I recreated what it might look like

![shadPS4 properties (2)](https://github.com/user-attachments/assets/e02daf6b-8e15-43b8-b922-076b9f3328b0)

**Comment by DanielSvoboda** [comment]
Excellent visual idea for the interface, based on that I made PR 493, it is already functional, but I am still making some adjustments, thanks for sharing the idea.

**Comment by Xphalnos** [comment]
> Excellent visual idea for the interface, based on that I made PR 493, it is already functional, but I am still making some adjustments, thanks for sharing the idea.

Thank you very much! It means a lot to me!

**Comment by Hermiten** [comment]
Do we need to update the SFO viewer ? For me can be close because we can see everything needed with the SFO viewer + we have a good GUI for Patches/Cheats were we can see interesting things too.
