### ISSUE TITLE
Shadow of the colossus crashing before boot screen so far.

### ISSUE THREAD

**Issue by m4iccc** [shadps4-emu/shadPS4#398]
Here's my log file after trying to run Shadow Of the colossus on 0.1.1 WIP today's release of Windows QT, just to further help improve this emulator, keep up the good work :)

[shad_log.txt](https://github.com/user-attachments/files/16573432/shad_log.txt)

**Comment by lzardy** [comment]
The crash posted by the OP is related to #394. Using this will get you slightly farther, but will still crash on a separate error.
