### ISSUE TITLE
[macOS] Regression after #373 causing most working games no longer boot.

### ISSUE THREAD

**Issue by mavethee** [shadps4-emu/shadPS4#401]
# Quick summary
After #373, macOS build is crashing after attempt to run any game.

## Details
After #373, macOS build is crashing after attempt to run any game.
Downgrading to #366 resolves the issue.

There's also weird issue with Qt locking up the window trying to quit the emulator when game is running.

Can attach more log files if needed.

## Log files
- [Another_World_159b2c_WORKING.txt](https://github.com/user-attachments/files/16575755/Another_World_159b2c_WORKING.txt)
- [Another_World_381ba8c_CRASH.txt](https://github.com/user-attachments/files/16575758/Another_World_381ba8c_CRASH.txt)

## System configuration
- **Operating System**: macOS 15.1.0
- **SoC**: Apple M1
- **RAM**: 16 GB

**Comment by squidbus** [comment]
Same issue as https://github.com/shadps4-emu/shadPS4/issues/418, see comments

**Comment by mavethee** [comment]
...and which was opened earlier? 🤨 
But as it's merged, closing :P

**Comment by squidbus** [comment]
> ...and which was opened earlier? 🤨

Yeah just linking it here for reference since there ended up being discussion there.
