### ISSUE TITLE
The Legend of Heroes: Trails through Daybreak crashing before boot screen so far

### ISSUE THREAD

**Issue by chienthan91** [shadps4-emu/shadPS4#403]
Here's my log file after trying to run CUSA45506 - The Legend of Heroes: Trails through Daybreak on 0.1.1 WIP today's release of Windows QT, just to further help improve this emulator, keep up the good work :)
[shad_log.txt](https://github.com/user-attachments/files/16578326/shad_log.txt)

**Comment by Hermiten** [comment]
Is it usefull to have this here rather than on game compatibility list ?
