### ISSUE TITLE
Question about functionality time management functions

### ISSUE THREAD

**Issue by GermanAizek** [shadps4-emu/shadPS4#405]
@georgemoralis, what is actually the difference between `sceKernelGetTscFrequency()` and `sceKernelGetProcessTimeCounterFrequency()` functions?

https://github.com/shadps4-emu/shadPS4/blob/834e3a500e62d58f1fe94fb509dff0eaefd06b27/src/core/libraries/kernel/time_management.cpp#L28-L46

**Comment by red-prig** [comment]
On PS4 it's the same thing
