### ISSUE TITLE
Newest Main will not compile 

### ISSUE THREAD

**Issue by ryzendew** [shadps4-emu/shadPS4#416]
[shadps4.txt](https://github.com/user-attachments/files/16590105/shadps4.txt)
the log

Arch Linux

**Comment by StevenMiller123** [comment]
I have this issue when trying to compile on Ubuntu 24.04.

**Comment by setepenre** [comment]
i have managed to compile latest main (3d0fdf1) on linux by switching from gcc to clang with `cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++` (found looking at the github build actions)

**Comment by psucien** [comment]
Please check if [2ba3221](https://github.com/shadps4-emu/shadPS4/commit/2ba3221fc94df83d79103b957fd8888296c4f305) fixes this

**Comment by ryzendew** [comment]
> i have managed to compile latest main ([3d0fdf1](https://github.com/shadps4-emu/shadPS4/commit/3d0fdf11f0781ac8b84f5e501d8837137a45e387)) on linux by switching from gcc to clang with `cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++` (found looking at the github build actions)

that worked

**Comment by StevenMiller123** [comment]
https://github.com/shadps4-emu/shadPS4/commit/2ba3221fc94df83d79103b957fd8888296c4f305 fixes it on my end.
