### ISSUE TITLE
Error when attempting to build on ARM64 Linux

### ISSUE THREAD

**Issue by lacamar** [shadps4-emu/shadPS4#417]
I followed the build instructions for Linux but it ended in errors before the build could complete.
Here is the log of the build process: 
[error-log.txt](https://github.com/user-attachments/files/16590979/error-log.txt)

This is my output from `uname -a`
`Linux hostname 6.9.12-401.asahi.fc40.aarch64+16k #1 SMP PREEMPT_DYNAMIC Sat Aug  3 22:26:24 UTC 2024 aarch64 GNU/Linux`

**Comment by squidbus** [comment]
There's no support for ARM64 builds, only x86_64. You would need to build for x86_64 and run under a translation layer.

**Comment by lacamar** [comment]
Okay. Is this from a fundamental constraint of how the emulator is designed or just not supported for now?

**Comment by squidbus** [comment]
Currently the emulator runs the x86_64 PS4 code directly, to run on ARM there would need to be a CPU recompiler.

**Comment by lacamar** [comment]
Okay, sounds like running it under FEXemu or some other fast x86 emulator would be the most practical solution rather than making a CPU recompiler for this.
