### ISSUE TITLE
Exited with code 3221225477 (0xc0000005)

### ISSUE THREAD

**Issue by Redstone626** [shadps4-emu/shadPS4#421]
I got this error and am not sure what to do now

[Exited with code 3221225477 (0xc0000005)]

It happens every time i try to load a game and the app crashes too and closes

**Comment by lzardy** [comment]
You'll need to provide some more details, including the log file, your computer specifications, operating system, and whether you've installed possible prerequisites.

**Comment by Redstone626** [comment]
I checked the log file and it's 0kb and empty

specs are this (if u need more than this i can give more):

i3 12100f
rtx 3060 ti
16gb 4800 ddr5

What prerequisites?

**Comment by millionsofplayers** [comment]
getting this error too when i try to install game updates

**Comment by Hermiten** [comment]
Maybe can be close because it was not followed up and there was little information to help us understand the problem.
