### ISSUE TITLE
[SOLVED] Regression: VkImage crashes on main branch

### ISSUE THREAD

**Issue by shiiironyanpan** [shadps4-emu/shadPS4#422]
Tested with Megadimension Neptunia VII (this game wasn't launching until surface_works3 launched it) , here's the log with validation enabled

![image-15](https://github.com/user-attachments/assets/a624755e-3f23-4973-b885-56332b6607f4)

[Neptunia shad_log.txt](https://github.com/user-attachments/files/16596650/shad_log.txt)

Also crashed on Red Dead Redemption which launched before (not my log)

`[Render.Vulkan] <Error> vk_platform.cpp:DebugUtilsCallback:59: VUID-vkCmdDraw-None-06479: Validation Error: [ VUID-vkCmdDraw-None-06479 ] Object 0: handle = 0xf582f600000001d8, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4b9d1597 | vkCmdDraw():  the descriptor VkDescriptorSet 0x0[] [Set 0, Binding 6, Index 0, variable "fs_img12_08"] has VkImageView 0xf582f600000001d8[] with format of VK_FORMAT_R32_SFLOAT which doesn't support VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT in.
i(supported features: VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_BIT|VK_FORMAT_FEATURE_2_STORAGE_IMAGE_BIT|VK_FORMAT_FEATURE_2_STORAGE_IMAGE_ATOMIC_BIT|VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BIT|VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BLEND_BIT|VK_FORMAT_FEATURE_2_BLIT_SRC_BIT|VK_FORMAT_FEATURE_2_BLIT_DST_BIT|VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_LINEAR_BIT|VK_FORMAT_FEATURE_2_TRANSFER_SRC_BIT|VK_FORMAT_FEATURE_2_TRANSFER_DST_BIT|VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_MINMAX_BIT|VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT|VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT|VK_FORMAT_FEATURE_2_HOST_IMAGE_TRANSFER_BIT_EXT). The Vulkan spec states: If a VkImageView is sampled with depth comparison, the image view's format features must contain VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDraw-None-06479)
`

[RDR shad_log.txt](https://github.com/user-attachments/files/16596687/shad_log.txt)

**Comment by shiiironyanpan** [comment]
Looking for confirmation from more people. If anyone wants to confirm this crash on RDR1, you need to install Vulkan SDK first then enable validation (NOT validation sync)

**Comment by bigol83** [comment]
It seems that PR https://github.com/shadps4-emu/shadPS4/pull/431 fixes the crash issue in Red Dead Redemption for me.

**Comment by shiiironyanpan** [comment]
Unfortunately Megadimension Neptunia VII still isn't fixed, however, there is different error printed
[shad_log.txt](https://github.com/user-attachments/files/16621717/shad_log.txt)

**Comment by Hermiten** [comment]
So maybe can be close ? because it's a new issue

**Comment by shiiironyanpan** [comment]
> So maybe can be close ? because it's a new issue

I completely forgot about this lol, closing as this is solved
