### ISSUE TITLE
[Linux] Screen not visible upon launch when fullscreen mode is enabled 

### ISSUE THREAD

**Issue by Shoegzer** [shadps4-emu/shadPS4#425]
When turning on fullscreen mode via Settings > General > Enable Fullscreen, and then launching a game, the main game screen does not enter fullscreen mode and does not render anything visually (you can hear audio though).

Update: This issue sometimes doesn't occur - on testing it seems to go into fullscreen mode roughly one in five launches, though it's currently unknown why this happens.  It was initially thought to occur only when the underlying shadps4 window is "snapped" to an edge, but that's not always the case either.
 
* OS: Linux Mint 22 / kernel 6.8
* CPU: Intel i7-10870h
* GPU: Nvidia GTX 3070 / driver 535.183
* Commit: d8b9d82ffaa2e0931b154a646d1573e535bc951f
* Log: [shad_log.txt](https://github.com/user-attachments/files/16604218/shad_log.txt)

**Comment by Hermiten** [comment]
Can you test again @Shoegzer ? 
Some commit maybe fix that

**Comment by Shoegzer** [comment]
Actually yes, it does seem to have been fixed, likely from a recent PR merge.  Thanks for bringing it to my attention, closing.
