### ISSUE TITLE
Could you enable search for games in subfolders? 

### ISSUE THREAD

**Issue by youtubeeicarlos** [shadps4-emu/shadPS4#437]
Well first of all I would like you to see if it is possible to use .zar compression in games in the future, it is the best format for reading disks and is used in emulators such as Xenia, before the games there only worked by extraction, like your process, until this was changed. (.zar does not interfere with the reading process, being more practical than .chd, for example.

But if it is not possible, at least being able to read subfolders would be useful, being able to use folders named after the game to differentiate it from others would help with organization.

Game won't open: 

Godzilla VS

[shad_log_055656.txt](https://github.com/user-attachments/files/16620828/shad_log_055656.txt)

**Comment by youtubeeicarlos** [comment]
Is the emulator already using the latest version of visual c++? There are some emulators still stuck on 14.38, I hope that is not your case

**Comment by SamuelFontes** [comment]
Hi Carlos,

I can investgate what would be the effort to support compressed games.
Related to reading subfolders I belive there another issue related to that feature open: https://github.com/shadps4-emu/shadPS4/issues/226
For game compatibilty please create an issue on https://github.com/shadps4-emu/shadps4-game-compatibility/issues.
As for the visual c++ version, I don't understand why this would be relevant.

**Comment by georgemoralis** [comment]
That can slowdown loading a lot

**Comment by youtubeeicarlos** [comment]
> That can slowdown loading a lot

Well, Xenia had no problems with performance, it's not something that requires work to read as it would be in the case of the .chd that compressed the iso, the .zar would just compress what shadps4 installed from the .pkg. But if you say the emulator can't do it, that's fine...
