### ISSUE TITLE
[BlazBlue Cross Tag Battle] The game creates 1980x1088 image for 1980x1080 video

### ISSUE THREAD

**Issue by roamic** [shadps4-emu/shadPS4#450]
This can be observed after #400 is merged. There is a line at the bottom of the video and the chrominance channel is shifted because of that.

**Comment by roamic** [comment]
From the RE: the game does not even read the `width`/`height` values returned by the AvPlayer library: neither from the `sceAvPlayerGetStreamInfo` nor from the `sceAvPlayerGetVideoDataEx`. So it is currently unclear how it calculates them.

**Comment by Emulator-Team-2** [comment]
Fixed by #560.

**Comment by roamic** [comment]
Fixed by #560.
