### ISSUE TITLE
[Bloodborne] [CUSA03173] DLC area Crashes with Unknown opcode BUFFER_ATOMIC_ADD

### ISSUE THREAD

**Issue by rafael-57** [shadps4-emu/shadPS4#457]
Since I have my save-file in an advanced DLC area (The research hall) I figured I would try loading into it, and the error is new to me:

[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondInit:656: name=NoName, result=0
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:301: (PARTIAL) path = /app0/dvdroot_ps4/event/common.emeld.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelOpen:28: path = /app0/dvdroot_ps4/event/common.emevd.dcx flags = 0x0 mode = 365
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:301: (PARTIAL) path = /app0/dvdroot_ps4/event/common.emevd.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:140: Closing /app0/dvdroot_ps4/event/common.emeld.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:140: Closing /app0/dvdroot_ps4/event/common.emedf.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:140: Closing /app0/dvdroot_ps4/event/common.emevd.dcx
[Render.Recompiler] <Error> translate.cpp:LogMissingOpcode:449: Unknown opcode BUFFER_ATOMIC_ADD (1330, category = VectorMemory)
[Debug] <Critical> translate.cpp:GetSrc:159: Unreachable code!

Proof:
![savefile](https://github.com/user-attachments/assets/bda524da-dfa2-417f-a542-da55bbc8a68e)

I've attached logs for loading in the reserch hall and for when you just create a new character so that you can compare if needed

[bloodborne_research_hall_shad_log_async.txt](https://github.com/user-attachments/files/16644650/bloodborne_research_hall_shad_log_async.txt)
[bloodborne_new_character_shad_log_aync.txt](https://github.com/user-attachments/files/16644652/bloodborne_new_character_shad_log_aync.txt)

Let me know if you need anything else!

**Comment by rafael-57** [comment]
Just for info, I've tried multiple times and it always fails with the same error:
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondInit:656: name=NoName, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondInit:656: name=NoName, result=0
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Render.Recompiler] <Error> translate.cpp:LogMissingOpcode:449: Unknown opcode BUFFER_ATOMIC_ADD (1330, category = VectorMemory)
[Debug] <Critical> translate.cpp:GetSrc:159: Unreachable code!

It crashes very fast too. Not even 5 seconds into loading

**Comment by esdrastarsis** [comment]
I think https://github.com/shadps4-emu/shadPS4/pull/428 will fix this.

**Comment by rafael-57** [comment]
> I think #428 will fix this.

Indeed, I checked the latest PR (#428) from his branch and the log crashes with a different error

[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateComputePipeline:325: Compiling cs shader 0xa509af23
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.VideoOut] <Info> video_out.cpp:sceVideoOutGetFlipStatus:195: count = 938, processTime = 76593750, tsc = 32218951800002, submitTsc = 32218949709054, flipArg = 937, gcQueueNum = 0, flipPendingNum = 0, currentBuffer = 1
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:140: Closing /app0/dvdroot_ps4/event/common.emeld.dcx
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitAndFlipCommandBuffers:2039: called [buf = 2]
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitDone:2139: called
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:140: Closing /app0/dvdroot_ps4/event/common.emedf.dcx
[Kernel.Fs] <Info> file_system.cpp:sceKernelClose:140: Closing /app0/dvdroot_ps4/event/common.emevd.dcx
[Debug] <Critical> translate.cpp:GetSrc:159: Unreachable code!

[shad_log.txt](https://github.com/user-attachments/files/16645664/shad_log.txt)

**Comment by rafael-57** [comment]
I'll retest once it's merged into main to be safe.

**Comment by lzardy** [comment]
The changes have been pushed, please test this once again to reconfirm.

**Comment by rafael-57** [comment]
Thank you, I can confirm the error is gone. Now It ends with this:

[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitAndFlipCommandBuffers:2039: called [buf = 0]
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitDone:2139: called
[Debug] <Critical> translate.cpp:GetSrc:159: Unreachable code!

[shad_log.txt](https://github.com/user-attachments/files/16648039/shad_log.txt)

**Comment by soykhaler** [comment]
im having same error at startup with [http](http.cpp:sceHttpWaitRequest:585: (STUBBED) called)

**Comment by BigLoaf94** [comment]
> im having same error at startup with [http](http.cpp:sceHttpWaitRequest:585: (STUBBED) called)

Did you ever figure this out? I'm having the same issue

**Comment by unk0wn-u53r** [comment]
Same issue since 3 months now
