### ISSUE TITLE
[AvPlayer] - Sporadic behaviour [CUSA03173] [Bloodborne]

### ISSUE THREAD

**Issue by rafael-57** [shadps4-emu/shadPS4#462]
Hi,

when creating a new character in BB and seeing the cinematic play with AvPlayer, I saw 3 possible behaviours:
1. (Most common) Video plays just fine
2. Green artifact all over the screen, video continued playing (I don't have a screenshot sadly, trying to reproduce but it happened quite a few times)
3. Video just stops playing with some audio errors and crashes after a while

I have attached logs for all 3 occurrences. Let me know if you need anything else.

[shad_log_player_green_artifact.txt](https://github.com/user-attachments/files/16648234/shad_log_player_green_artifact.txt)
[shad_log_avplayer_random_crash.txt](https://github.com/user-attachments/files/16648237/shad_log_avplayer_random_crash.txt)
[shad_log_avplayer_ok.txt](https://github.com/user-attachments/files/16648292/shad_log_avplayer_ok.txt)

**Comment by rafael-57** [comment]
![image](https://github.com/user-attachments/assets/d7db4efe-f4da-41e0-a2b6-6f8c3765aeaf)
Screenshot of the green artifact taken from Discord, posted by another user. Looks just the same as when I get it. Haven't found a way to replicate it so far.

**Comment by purgea** [comment]
I managed to reproduce it once by tinkering with the game settings and then firing up new game!

**Comment by 0xsegf4ult** [comment]
Also reproducible by having more than 10 profiles and going into new game having the game prompt you to overwrite one. This process always compiles a few shaders which might be borking some gpu state but thats just a wild guess.
This is on main branch commit c79b10e

**Comment by rafael-57** [comment]
Haven't been able to reproduce or see this for a long while now, must have been fixed.
