### ISSUE TITLE
Bloodborne with amd gpu crashing (CUSA03173)

### ISSUE THREAD

**Issue by ChronoRPG** [shadps4-emu/shadPS4#467]
crash on bloodbrone when i starting the game, after of chose the character

[shad_log.txt](https://github.com/user-attachments/files/16652906/shad_log.txt)

My pc specification 

CPU: Ryzen 9 5900X
Ram: 32Gb 3200Mhz
GPU AMD RX 6700 XT

**Comment by TarnishedX** [comment]
Seems alot of us with AMD have issues ..

**Comment by Bedmar** [comment]
Agreed, my 5700 XT doesn't want to run Bloodborne at all

**Comment by yaya54840** [comment]
Hi
I add my case
log de Bloodborne with patch 60fps


[shad_log.zip](https://github.com/user-attachments/files/16656220/shad_log.zip)
and my config

![Capture d'écran 2024-08-19 074207](https://github.com/user-attachments/assets/9e9b5748-e6d5-478c-b277-1bfb68e0bb10)


![Capture d'écran 2024-08-19 074232](https://github.com/user-attachments/assets/f1deb046-476b-40b8-9650-3e59366eb998)

Vulkan Development Status:
- Vulkan Layers Controlled by Vulkan Applications
- Environment variables:
    - VULKAN_SDK: C:\VulkanSDK\1.3.290.0
    - VK_LOCAL: C:\Users\yaya7\VulkanSDK
- Vulkan Loader version: 1.3.261
    - VK_LOADER_DEBUG=error,warn,info,debug,layer,implem
- User-Defined Layers locations:
    - VK_LAYER_PATH variable: None
    - Per-configuration paths: None
    - VK_ADD_LAYER_PATH variable: None
- `vk_layer_settings.txt` uses the default platform path:
    C:\Users\yaya7\AppData\Local\LunarG\vkconfig\override
- Available Layers:
    - VK_LAYER_AMD_switchable_graphics
    - VK_LAYER_VALVE_steam_overlay
    - VK_LAYER_VALVE_steam_fossilize
    - VK_LAYER_LUNARG_api_dump
    - VK_LAYER_LUNARG_gfxreconstruct
    - VK_LAYER_KHRONOS_synchronization2
    - VK_LAYER_KHRONOS_validation
    - VK_LAYER_LUNARG_monitor
    - VK_LAYER_LUNARG_screenshot
    - VK_LAYER_KHRONOS_profiles
    - VK_LAYER_KHRONOS_shader_object
    - VK_LAYER_LUNARG_crash_diagnostic (ALPHA)
- Physical Devices:
    - AMD Radeon RX 7800 XT with Vulkan 1.3.280
        - deviceUUID: 00000000110000000000000000000000
        - driverUUID: 414D442D57494E2D4452560000000000

**Comment by ChronoRPG** [comment]
https://cdn.discordapp.com/attachments/1274870927636824064/1275078820147494922/2024-08-19_14-06-48.mp4?ex=66c49530&is=66c343b0&hm=1b6e09fa4a80397009980e5781097b49951b3b2b7be29a252c4c431a3480b18b&

**Comment by HermitsA** [comment]
I would like to add to this, exact same errors as seen above.

GPU:RX 6700xt, VK 1.3.280
CPU: ryzen 5 7600
RAM: 32 Gb 6000mhz

**Comment by vookhan** [comment]
I get a driver timeout upon loading completion.

![image](https://github.com/user-attachments/assets/6869cf41-85bf-4395-8d6e-345e8c3e2dc5)

[shad_log.txt](https://github.com/user-attachments/files/16665536/shad_log.txt)

CPU: 7800X3D
GPU: 7900 XT
RAM: 32 Gb 6000 Mhz

**Comment by Ex0312** [comment]
Crashing after the first cinematic intro after the character creation.
![image](https://github.com/user-attachments/assets/21c23a7d-1f13-41ab-bc72-30d856c7d650)


[shad_log.txt](https://github.com/user-attachments/files/16678272/shad_log.txt)

CPU: ryzen 5 5500
GPU: RX 6600
RAM: 32GB 3200Mhz

**Comment by cowhour** [comment]
+1, crashing after character creation. 

GPU: 7900xtx
RAM: 32gig 
CPU: 7800 X3D

**Comment by HermitsA** [comment]
I have found a somewhat working fix, credits to @Conker on the Discord for leading me there.

It seems that using the AFMF 2 drivers from the Amd.com website lets you enter into a new save file and load iosefkas clinic, altough you are invulnerable and cannot enter hunters dream.

This is the driver i and Conker used. You can see screenshots in #showcase-bloodborne on the discord.

https://www.amd.com/en/resources/support-articles/release-notes/RN-RAD-WIN-AFMF2-TECH-Preview.html

**Comment by srcamarda** [comment]
> I have found a somewhat working fix, credits to @conker on the Discord for leading me there.
> 
> It seems that using the AFMF 2 drivers from the Amd.com website lets you enter into a new save file and load iosefkas clinic, altough you are invulnerable and cannot enter hunters dream.
> 
> This is the driver i and Conker used. You can see screenshots in #showcase-bloodborne on the discord.
> 
> https://www.amd.com/en/resources/support-articles/release-notes/RN-RAD-WIN-AFMF2-TECH-Preview.html

Just tried this but with no luck. I have a RX7800 XT. With this driver, CUSA00900 stopped booting and CUSA03173 (GOTY) crashes on the same spot.

Which build of shadPS4 are you using? bb-hacks branch?

**Comment by HermitsA** [comment]
> Which build of shadPS4 are you using? bb-hacks branch?

Bb-hacks repo latest action on windows-qt build

**Comment by BorjaLJ** [comment]
Hello, I've been trying to get it to work for days, and I have achieved this success, thanks to the mention of the AFMF2 drivers, which have managed to start the game. 

In addition to the drivers themselves, I also used the latest version of bb-hacks, loaded the game that I downloaded from new game plus (do not click continue) and entered the game.
I also followed a guide, which I saw in a post for a GTX 1080, to "downgrade" the game, except for the firmware, which is not necessary for the game to work, in addition to the "Bloodborne FPS Boost" mod that you can find in nexus mods I leave you a screenshot and link, good luck!
https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit  (guide)

![image](https://github.com/user-attachments/assets/70b812bd-c2a8-4883-87cd-673274e50aca)


 GPU: RX6600
CPU:3600
RAM:32GB
Drivers: (AFMF2) 24.20.01.02

https://github.com/user-attachments/assets/235092e6-33a2-4eed-8a9e-d1e40e2955a3

**Comment by Etaash-mathamsetty** [comment]
bit of a meme suggestion but maybe compile the RADV driver, I saw a mesa MR for it to work on windows the other day.
edit: seems like through WSL, but better than nothing if you want to get a decent vulkan driver (AMD's one is shit), or just install linux...

**Comment by R1chterScale** [comment]
> bit of a meme suggestion but maybe compile the RADV driver, I saw a mesa MR for it to work on windows the other day. edit: seems like through WSL, but better than nothing if you want to get a decent vulkan driver (AMD's one is shit), or just install linux...

RADV gets past char creation without crashing but has major rendering issues. If you want to actually render you use RADV to get in game (or just copy over a save) and then close and reopen with AMD's proprietary drivers or AMDVLK once a save has been made for actual rendering

**Comment by voguelike** [comment]
> RADV gets past char creation without crashing but has major rendering issues. If you want to actually render you use RADV to get in game (or just copy over a save) and then close and reopen with AMD's proprietary drivers or AMDVLK once a save has been made for actual rendering

describe in more detail what do you entirely mean by "major rendering issues"? gray/black screen, no access to depth buffer, the base rendering issues present in the emulator for most people, or was it something entirely unique to the behaviour you obseved when using the RADV driver?

**Comment by R1chterScale** [comment]
> > RADV gets past char creation without crashing but has major rendering issues. If you want to actually render you use RADV to get in game (or just copy over a save) and then close and reopen with AMD's proprietary drivers or AMDVLK once a save has been made for actual rendering
> 
> describe in more detail what do you entirely mean by "major rendering issues"? gray/black screen, no access to depth buffer, the base rendering issues present in the emulator for most people, or was it something entirely unique to the behaviour you obseved when using the RADV driver?

As seen in this showcase post by another, a substantial amount of geometry simply does not render:

https://discord.com/channels/1080089157554155590/1245616678021234768/1274911951495102585

**Comment by R1chterScale** [comment]
If there's some level of debug/dump I can provide that would be properly useful, do let me know

**Comment by HermitsA** [comment]
> > bit of a meme suggestion but maybe compile the RADV driver, I saw a mesa MR for it to work on windows the other day. edit: seems like through WSL, but better than nothing if you want to get a decent vulkan driver (AMD's one is shit), or just install linux...
> 
> 
> 
> RADV gets past char creation without crashing but has major rendering issues. If you want to actually render you use RADV to get in game (or just copy over a save) and then close and reopen with AMD's proprietary drivers or AMDVLK once a save has been made for actual rendering

Im gonna try switching to amdvlk to see how much better it runs, i'd much wrather prefer that over booting windows

**Comment by Etaash-mathamsetty** [comment]
> > > RADV gets past char creation without crashing but has major rendering issues. If you want to actually render you use RADV to get in game (or just copy over a save) and then close and reopen with AMD's proprietary drivers or AMDVLK once a save has been made for actual rendering
> > 
> > 
> > describe in more detail what do you entirely mean by "major rendering issues"? gray/black screen, no access to depth buffer, the base rendering issues present in the emulator for most people, or was it something entirely unique to the behaviour you obseved when using the RADV driver?
> 
> As seen in this showcase post by another, a substantial amount of geometry simply does not render:
> 
> [discord.com/channels/1080089157554155590/1245616678021234768/1274911951495102585](https://discord.com/channels/1080089157554155590/1245616678021234768/1274911951495102585)

try RADV_DEBUG=zerovram and some other radv envs to see if it helps

**Comment by R1chterScale** [comment]
> try RADV_DEBUG=zerovram and some other radv envs to see if it helps

Tried multiple RADV_DEBUG options, including llvm, nobinning, nocache, nocompute, nofastclears, nogpl, nohiz, syncshaders, and zerovram, no improvement, with a few causing crashing. Also tried all of the wave32 RADV_PERFTEST options to no progress there either.

**Comment by HermitsA** [comment]
Can confirm that switching AMDVLK fixes Bloodborne rendering on linux. It does not constantly "grey screen" and de-render half the assets anymore. 

sys-specs:
Nixos-unstable 24.11
Rx 6700XT
Ryzen 5 7600
32gb DDR5 6000Mhz

**Comment by noelmiller** [comment]
I'll cross post this here: https://github.com/shadps4-emu/shadPS4/issues/1641#issuecomment-2519154427

**Comment by Hermiten** [comment]
I'm closing this one. Lot have benn made and nobody update it since 2 months.
There is some new problem but this one seem's to be almost gone
