### ISSUE TITLE
Bloodborne 5600x GTX 1080 crash

### ISSUE THREAD

**Issue by srjghseruikg** [shadps4-emu/shadPS4#470]
![vk scheduler ACK](https://github.com/user-attachments/assets/7987b6a9-85c0-4202-8476-ba140680a3fc)

CPU: Ryzen 5 5600x
GPU:NVIDIA GTX 1080
Build: (I dont see a version number anywhere but here's where i got it) https://github.com/shadps4-emu/shadPS4/actions/runs/10443249835

**Comment by lzardy** [comment]
Post your vulkan version displayed when first launching the game as well. The recommended version is `1.3.280`, if you are lower than this, please update your graphics drivers.

**Comment by srjghseruikg** [comment]
> Post your vulkan version displayed when first launching the game as well. The recommended version is `1.3.280`, if you are lower than this, please update your graphics drivers.

![vulkan](https://github.com/user-attachments/assets/2dc63a8d-ade8-4db3-9210-d8ae14975b4c)
here you go, 1.3.280

**Comment by Julioevm** [comment]
Same here, using latest build winfows qt of bb_hacks branch: https://github.com/shadps4-emu/shadPS4/actions/runs/10448528983

Crashes as soon as it would load the first in-game section. After character creation.

CPU: Ryzen 7 7800X3D
GPU: RX 6650 XT

```[Loader] <Info> emulator.cpp:Emulator:52: Starting shadps4 emulator v0.2.1 WIP
[Loader] <Info> emulator.cpp:Emulator:53: Revision de92009a24f1b7b7dca48066fad7d0d3c93c5f84
[Loader] <Info> emulator.cpp:Emulator:54: Branch HEAD
[Loader] <Info> emulator.cpp:Emulator:55: Description de92009
[Kernel.Vmm] <Info> address_space.cpp:Impl:84: System managed virtual memory region: 0x141c90000 - 0x7c188bfff
[Kernel.Vmm] <Info> address_space.cpp:Impl:87: System reserved virtual memory region: 0x7ffffc000 - 0xfffffffff
[Kernel.Vmm] <Info> address_space.cpp:Impl:89: User virtual memory region: 0x1000000000 - 0x10fffffffff
[Kernel.Vmm] <Info> memory.cpp:MemoryManager:33: Usable memory address space: 1081_GB
[Loader] <Info> emulator.cpp:Run:88: Game id: CUSA03173 Title: BloodborneÔäó
[Loader] <Info> emulator.cpp:Run:91: Fw: 0x4500000 App Version: 01.09
[Lib.Kernel] <Info> libs.cpp:InitHLELibs:45: Initializing HLE libraries
[Lib.GnmDriver] <Info> gnmdriver.cpp:RegisterlibSceGnmDriver:2642: Initializing renderer
[Render.Vulkan] <Info> vk_platform.cpp:CreateInstance:191: Creating vulkan instance
[Render.Vulkan] <Info> vk_instance.cpp:Instance:63: Found 2 physical devices
[Render.Vulkan] <Info> vk_instance.cpp:CollectDeviceParameters:445: GPU_Vendor: AMD proprietary driver
[Render.Vulkan] <Info> vk_instance.cpp:CollectDeviceParameters:446: GPU_Model: AMD Radeon RX 6650 XT
[Render.Vulkan] <Info> vk_instance.cpp:CollectDeviceParameters:447: GPU_Vulkan_Driver: AMD proprietary driver 2.0.302
[Render.Vulkan] <Info> vk_instance.cpp:CollectDeviceParameters:448: GPU_Vulkan_Version: 1.3.280```

**Comment by dunestorm333** [comment]
I get the same thing on my system.

GPU: AMD 6800XT (Driver v24.6.1)
CPU: AMD 5900X
RAM: 32GB DDR4 (3000MHz)
OS: Windows 11 Pro

```
[Render.Recompiler] <Warning> export.cpp:EmitExport:11: An ambiguous export appeared in translation
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling fs shader 0xe80526cc
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling vs shader 0x7e956bc3
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling fs shader 0xff902740
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling fs shader 0x474f0123
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling vs shader 0xd7407513
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling fs shader 0x2112931
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling vs shader 0x7d668276
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling fs shader 0x290a042b
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling vs shader 0xd3ca03f3
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Info> renderer_vulkan.cpp:GetRenderFrame:357: Got render frame, remaining 1
[Debug] <Critical> vk_scheduler.cpp:SubmitExecution:195: Unreachable code!
Device lost during submit: vk::Queue::submit: ErrorDeviceLost
```

![image](https://github.com/user-attachments/assets/ddbb8a2f-ad70-4641-8f25-0da906fdd56a)

The second time I tried, I got an entirely different set of errors before the crash.

```
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.VideoOut] <Info> video_out.cpp:sceVideoOutGetFlipStatus:195: count = 782, processTime = 67734375, tsc = 317167648088648, submitTsc = 317167613408406, flipArg = 781, gcQueueNum = 0, flipPendingNum = 0, currentBuffer = 1
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitAndFlipCommandBuffers:2039: called [buf = 2]
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitDone:2139: called
[Tty] <Info> libkernel.cpp:ps4__write:210: == Stall during rendering at flush 171
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:83: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:83: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling fs shader 0xff841760
[Render.Recompiler] <Warning> export.cpp:EmitExport:11: An ambiguous export appeared in translation
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling vs shader 0x965e549a
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
```

**Comment by efigr** [comment]
Same issue here.

GPU: GTX 1080ti
CPU: Ryzen 9 7900X
RAM: 32GB (DDR5) @ 5600MHz
OS: Windows 11

No matter what settings, no background apps, re-dumping, nothing changes.

```
[Render.Vulkan] <Warning> vk_compute_pipeline.cpp:BindResources:177: Metadata update skipped
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:83: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Warning> vk_compute_pipeline.cpp:BindResources:177: Metadata update skipped
[Render.Vulkan] <Warning> vk_compute_pipeline.cpp:BindResources:177: Metadata update skipped
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CreateGraphicsPipeline:318: Compiling fs shader 0x389c34c
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Info> renderer_vulkan.cpp:GetRenderFrame:357: Got render frame, remaining 1
[Debug] <Critical> liverpool.h:unhandled_exception:1094: Unreachable code!
Unhandled exception: vk::Device::waitForFences: ErrorDeviceLost
```

[shad_log.txt](https://github.com/user-attachments/files/16666443/shad_log.txt)

**Comment by makanm** [comment]
Same issue here with bb hacks on 1.09.
Crashig right at the end of the loading after creating the character.

GPU: GTX 1080ti
CPU: Intel i7 8700K
RAM: 32GB (DDR4) @ 3200MHz
OS: Windows 11

[shad_log.txt](https://github.com/user-attachments/files/16674614/shad_log.txt)

**Comment by kleinermob** [comment]
This is how far i get with a save game 

![grafik](https://github.com/user-attachments/assets/9f3df1a0-c254-40a7-8dc3-dac001a851f6)
[shad_log.txt](https://github.com/user-attachments/files/16690378/shad_log.txt)
exactly the same on linux also

https://www.nexusmods.com/bloodborne/mods/26?tab=files&file_id=190

**Comment by kleinermob** [comment]
After doing: 
```
Essential fixes/troubleshooting
No picture when loading into the game:
Move all shader filesin ShadPS4/games/CUSAXXXXX/dvdroot_ps4/param/drawparam to a separate folder except these:
default.gparam.dcx
default_drawparam.gparambnd.dcx
empty.gparam.dcx
m_template.gparam.dcx
Try:
removing ShadPS4/user/sys_modules/libSceDiskMap.sprx.
enabling the “Is PS4 Pro” option in ShadPS4 settings (pretty sure this is placebo).
```

from https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit
it actually works now on GTX 1080 Ti
![grafik](https://github.com/user-attachments/assets/67a05cea-2974-4f05-86c9-c602f1c39b5e)

**Comment by efigr** [comment]
> After doing:
> 
> ```
> Essential fixes/troubleshooting
> No picture when loading into the game:
> Move all shader filesin ShadPS4/games/CUSAXXXXX/dvdroot_ps4/param/drawparam to a separate folder except these:
> default.gparam.dcx
> default_drawparam.gparambnd.dcx
> empty.gparam.dcx
> m_template.gparam.dcx
> Try:
> removing ShadPS4/user/sys_modules/libSceDiskMap.sprx.
> enabling the “Is PS4 Pro” option in ShadPS4 settings (pretty sure this is placebo).
> ```
> 
> from https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit it actually works now on GTX 1080 Ti ![grafik](https://private-user-images.githubusercontent.com/42699035/359866086-67a05cea-2974-4f05-86c9-c602f1c39b5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTM5NTIsIm5iZiI6MTcyNDI1MzY1MiwicGF0aCI6Ii80MjY5OTAzNS8zNTk4NjYwODYtNjdhMDVjZWEtMjk3NC00ZjA1LTg2YzktYzYwMmYxYzM5YjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE1MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGU0ZTQ3NDZhMTljNjE0MGQ2NmU0M2YwOGM2NWZlODk2ODU5ZWEzODVkOGNkMGE3YmViMGE2NjJlMTcyYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yIEiBNxv0F5Kfq0P_yiEVGoagt7G3OjfrHYy0vYN2JU)


Can confirm, removing the sounds and sfx folders has allowed me too boot into game, no longer getting:

```
[Debug] <Critical> vk_scheduler.cpp:SubmitExecution:195: Unreachable code!
Device lost during submit: vk::Queue::submit: ErrorDeviceLost
```

**Comment by kleinermob** [comment]
empty.gparam.dcx and m_template.gparam.dcx arent even necessary, apparently it has been edited in the guide also

**Comment by makanm** [comment]
These workarounds doesn't work for me :(

**Comment by Julioevm** [comment]
Removing the sfx and audio folders lets me get to the ingame part. But it crashes within seconds...

**Comment by dunestorm333** [comment]
> Removing the sfx and audio folders lets me get to the ingame part. But it crashes within seconds...

In exactly the same boat, I don’t understand how people are getting the game running. I followed the instructions exactly and no matter what, I crash after the loading screen after character creation.

**Comment by efigr** [comment]
If removing the sfx and sound files has gotten you past the loading screen, but you crash a few seconds into the game, try [Fromsoftserve's Bloodborne FPS Boost mod on NexusMods.](https://www.nexusmods.com/bloodborne/mods/27?)
I had the same issue, but applying the mod fixed it.

**Comment by Julioevm** [comment]
> If removing the sfx and sound files has gotten you past the loading screen, but you crash a few seconds into the game, try [Fromsoftserve's Bloodborne FPS Boost mod on NexusMods.](https://www.nexusmods.com/bloodborne/mods/27?) I had the same issue, but applying the mod fixed it.

Neat, it works!

**Comment by makanm** [comment]
> > Removing the sfx and audio folders lets me get to the ingame part. But it crashes within seconds...
> 
> In exactly the same boat, I don’t understand how people are getting the game running. I followed the instructions exactly and no matter what, I crash after the loading screen after character creation.

Me too.
No matter what  i do game will crash after the loading.

I tried everyhing , patches , mods , removing sfx/audio folders and...
Nothing works.

Could my old cpu be the culprit?

GPU: GTX 1080ti
CPU: Intel i7 8700K
RAM: 32GB (DDR4) @ 3200MHz
OS: Windows 11

**Comment by makanm** [comment]
Ok i found what was my problem.
I didn't download bbhacks version !
If anyoone has this problem just download this last version:
https://github.com/shadps4-emu/shadPS4/actions/runs/10526470367

And follow the above guide on googledocs.
=====
I can run the game on 1440p and 60 fps :))

**Comment by DanielPerovi** [comment]
> Ok i found what was my problem. I didn't download bbhacks version ! If anyoone has this problem just download this last version: https://github.com/shadps4-emu/shadPS4/actions/runs/10526470367
> 
> # And follow the above guide on googledocs.
> I can run the game on 1440p and 60 fps :))

can't download this version as it has expired, anyone provide a download link that works?

**Comment by srjghseruikg** [comment]
even with the latest bbhacks and redumping my game for the second time i still get this same error lol just wanted to update after ive tested several other games and played them just fine.

**Comment by gwyinbleidd** [comment]
> > After doing:
> > ```
> > Essential fixes/troubleshooting
> > No picture when loading into the game:
> > Move all shader filesin ShadPS4/games/CUSAXXXXX/dvdroot_ps4/param/drawparam to a separate folder except these:
> > default.gparam.dcx
> > default_drawparam.gparambnd.dcx
> > empty.gparam.dcx
> > m_template.gparam.dcx
> > Try:
> > removing ShadPS4/user/sys_modules/libSceDiskMap.sprx.
> > enabling the “Is PS4 Pro” option in ShadPS4 settings (pretty sure this is placebo).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > from https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit it actually works now on GTX 1080 Ti ![grafik](https://private-user-images.githubusercontent.com/42699035/359866086-67a05cea-2974-4f05-86c9-c602f1c39b5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTM5NTIsIm5iZiI6MTcyNDI1MzY1MiwicGF0aCI6Ii80MjY5OTAzNS8zNTk4NjYwODYtNjdhMDVjZWEtMjk3NC00ZjA1LTg2YzktYzYwMmYxYzM5YjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE1MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGU0ZTQ3NDZhMTljNjE0MGQ2NmU0M2YwOGM2NWZlODk2ODU5ZWEzODVkOGNkMGE3YmViMGE2NjJlMTcyYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yIEiBNxv0F5Kfq0P_yiEVGoagt7G3OjfrHYy0vYN2JU)
> 
> Can confirm, removing the sounds and sfx folders has allowed me too boot into game, no longer getting:
> 
> ```
> [Debug] <Critical> vk_scheduler.cpp:SubmitExecution:195: Unreachable code!
> Device lost during submit: vk::Queue::submit: ErrorDeviceLost
> ```

I did  remove the sfx and sound folder now im ingame

**Comment by srjghseruikg** [comment]
> > > After doing:
> > > ```
> > > Essential fixes/troubleshooting
> > > No picture when loading into the game:
> > > Move all shader filesin ShadPS4/games/CUSAXXXXX/dvdroot_ps4/param/drawparam to a separate folder except these:
> > > default.gparam.dcx
> > > default_drawparam.gparambnd.dcx
> > > empty.gparam.dcx
> > > m_template.gparam.dcx
> > > Try:
> > > removing ShadPS4/user/sys_modules/libSceDiskMap.sprx.
> > > enabling the “Is PS4 Pro” option in ShadPS4 settings (pretty sure this is placebo).
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > from https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit it actually works now on GTX 1080 Ti ![grafik](https://private-user-images.githubusercontent.com/42699035/359866086-67a05cea-2974-4f05-86c9-c602f1c39b5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTM5NTIsIm5iZiI6MTcyNDI1MzY1MiwicGF0aCI6Ii80MjY5OTAzNS8zNTk4NjYwODYtNjdhMDVjZWEtMjk3NC00ZjA1LTg2YzktYzYwMmYxYzM5YjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE1MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGU0ZTQ3NDZhMTljNjE0MGQ2NmU0M2YwOGM2NWZlODk2ODU5ZWEzODVkOGNkMGE3YmViMGE2NjJlMTcyYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yIEiBNxv0F5Kfq0P_yiEVGoagt7G3OjfrHYy0vYN2JU)
> > 
> > 
> > Can confirm, removing the sounds and sfx folders has allowed me too boot into game, no longer getting:
> > ```
> > [Debug] <Critical> vk_scheduler.cpp:SubmitExecution:195: Unreachable code!
> > Device lost during submit: vk::Queue::submit: ErrorDeviceLost
> > ```
> 
> I did remove the sfx and sound folder now im ingame

for me i'm just waiting for when we dont have to do that anymore lol.

**Comment by srjghseruikg** [comment]
As of this build i just grabbed https://github.com/shadps4-emu/shadPS4/actions/runs/10828119257
Bloodborne now goes fully ingame. (Character is completely white in the character creator screen though, new bug.), got a crash when i got close to the wolf enemy.
Should i, technically, close this issue if it's resolved? lol

**Comment by ArrowKnee410** [comment]
> As of this build i just grabbed https://github.com/shadps4-emu/shadPS4/actions/runs/10828119257 Bloodborne now goes fully ingame. (Character is completely white in the character creator screen though, new bug.), got a crash when i got close to the wolf enemy. Should i, technically, close this issue if it's resolved? lol

Same problem here, crash as soon as hitbox collision with enemies.
