### ISSUE TITLE
[Steam deck] bloodborne black screen 

### ISSUE THREAD

**Issue by nEmo-iv** [shadps4-emu/shadPS4#478]
Linux-Qt

CUSA03173

build version: Actions 19.08.2024
[Add messages to asserts (#476)](https://github.com/shadps4-emu/shadPS4/actions/runs/10453358528)
Linux-Qt #1538: Commit [1f41613](https://github.com/shadps4-emu/shadPS4/commit/1f416134e7f2d23d90dcb9713661c58dd0bfb0d9) pushed by [georgemoralis](https://github.com/georgemoralis)

[shad_log-v.game-1.0.txt](https://github.com/user-attachments/files/16661667/shad_log-v.game-1.0.txt)
[shad_log-v.game-1.0.9.txt](https://github.com/user-attachments/files/16661672/shad_log-v.game-1.0.9.txt)

**Comment by nEmo-iv** [comment]
In desktop mode, give write permissions to the directory where the executable appimage is located and all folders located in it, otherwise the log file will not be written.

**Comment by dunestorm333** [comment]
The Steam Deck is noway near powerful enough to emulate PS4 games.

**Comment by TorutheRedFox** [comment]
> The Steam Deck is noway near powerful enough to emulate PS4 games.

high-level PS4 emulation on an x86-based system has nowhere near as much overhead as emulating a system with a different CPU architecture or doing a low-level emulation of the system

with enough optimization of the emulator, it should run perfectly fine on a system more powerful than a PS4, such as a Steam Deck, especially when the Deck runs at 720p, and a PS4 usually runs at 1080p

**Comment by rynnyr-maomao** [comment]
> > The Steam Deck is noway near powerful enough to emulate PS4 games.
> 
> high-level PS4 emulation on an x86-based system has nowhere near as much overhead as emulating a system with a different CPU architecture or doing a low-level emulation of the system
> 
> with enough optimization of the emulator, it should run perfectly fine on a system more powerful than a PS4, such as a Steam Deck, especially when the Deck runs at 720p, and a PS4 usually runs at 1080p

Actually, Steam Deck is about the same or less powerful than PS4.

**Comment by Lun3th** [comment]
> The Steam Deck is noway near powerful enough to emulate PS4 games.

I can play the game from Windows(Steam Deck) but if I run in linux shadps4 I have black screen only... nothing happens when I'm trying to run a game... not even the fans spins up... just black screen.
If I run shad from the terminal:
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""

Same under X11 without the console message.

**Comment by RyuSeisuke1992** [comment]
Bloodborne Run with 30fps on the Steam Deck
https://youtu.be/LafZSOtbTsI?si=vN7nLRyeEsri8INh

**Comment by Superredstone** [comment]
I'm having the same issue on my laptop

OS: Arch Linux (6.10.6 mainline)
GPU: Nvidia RTX 4060
CPU: 13th Gen Intel® Core™ i7-13620H

EDIT: I've just tried with some hombrew games and I get black screen too

**Comment by QushyQushy** [comment]
Same here on BazziteOS with the QT AppImage.

**Comment by GalecO1987** [comment]
Same issue here.

OS: Arch Linux (6.10.6-arch1-1)
GPU: AMD Radeon RX 7700 XT
CPU: AMD Ryzen 5 3600 (12) @ 3.60 GHz
