### ISSUE TITLE
Bloodborne 1.00 creating much more errors than 1.09 [CUSA03173 & CUSA00207]

### ISSUE THREAD

**Issue by Cjraven07** [shadps4-emu/shadPS4#482]
I rececntly dumped my bloodborne and it's patch separately and have a 1.00 and a patched 1.09 copy on my pc for testing in the emulator. Will be testing the experimental releases in actions soon, i have the newest main, bb hack and less shaders version i want to try but i won't write about them unless i'm asked.
 
When running 1.00 it took a long time to get to the main menu, i stopped the emulator as soon as "checking save data..." dissapeared after clicking play offline and it made a 67MB log compared to getting to the same point on 1.09 which creates a 1.25MB log.

1.00 log: [shad_log.zip](https://github.com/user-attachments/files/16664618/shad_log.zip)
1.09 log: [shad_log-1.09.zip](https://github.com/user-attachments/files/16664679/shad_log-1.09.zip)
The differences in the logs start at around line 741
the 1.00 log gets filled with "(STUBBED) called" and "(DUMMY) name = ResolveDomainName size = 4096 flags = 0"
the 1.09 log gets an error every few lines inbetween \<Info> logs, and the 1.00 log is almost all errors from that point on.

I am running the Windows-Qt version of the emulator

**Comment by Uncasted** [comment]
Seems like that's also the case for the 1.00 alpha demo for me, I get the same kind of errors when I try to run the demo on the latest build of the bb-hacks branch, it also runs very slowly.

Logs: [shad_log.zip](https://github.com/user-attachments/files/16665528/shad_log.zip)

**Comment by Cjraven07** [comment]
yeah i tested that earlier as well and 1.00 still has the same problem on bb-hack.

**Comment by Cjraven07** [comment]
just dumped my old copy of bloodborne to see if it was any different because i know GOTY has different stuff to the old game even outside of the built-in dlc. Goes basically the same with 1.00 and 1.09 on the GOTY edition.

**Comment by Cjraven07** [comment]
not really related to the topic, but the less-shaders version of the emulator actually manages to get some kind of a silhouette of a character in the character creator screen, which is something that even the bb-hack version doesn't manage.

Also do we know what causes all the STUBBED and DUMMY errors, is that a common thing that happens with games currently or is it just a bloodborne related issue? i'll try dumping one of my other games and have a look after work to see if it's a common thing.

**Comment by bigol83** [comment]
> not really related to the topic, but the less-shaders version of the emulator actually manages to get some kind of a silhouette of a character in the character creator screen, which is something that even the bb-hack version doesn't manage.
> 
> Also do we know what causes all the STUBBED and DUMMY errors, is that a common thing that happens with games currently or is it just a bloodborne related issue? i'll try dumping one of my other games and have a look after work to see if it's a common thing.

Those are not errors, but unimplemented stuff.

**Comment by Cjraven07** [comment]
yeah that makes sense, it's just making calls to some libsce that aren't emulated yet i guess?

**Comment by Hermiten** [comment]
Lot of news things on bloodborne and no update on this issue. It can be close and maybe open a new one if you find something new
