### ISSUE TITLE
Documentation for intentional exceptions meant for debugging purposes

### ISSUE THREAD

**Issue by xezrunner** [shadps4-emu/shadPS4#483]
This stems from https://github.com/shadps4-emu/shadPS4/issues/460#issuecomment-2297329915

There are intentional access violation exceptions thrown on memory writes in relation to game data that can be safely skipped during debugging.

Documentation should probably explain / add guidance on excluding intentional exceptions and perhaps even on using them, to avoid confusion during debugging.

**Comment by xezrunner** [comment]
https://github.com/shadps4-emu/shadPS4/pull/513 would have this covered.

**Comment by georgemoralis** [comment]
merged :)
