### ISSUE TITLE
Guys help i littraly cant run bloodborne no matter how hard i try 

### ISSUE THREAD

**Issue by devilnouria** [shadps4-emu/shadPS4#489]
![2024-08-20 13_53_07-E__Bloodborne Game of the Year Edition v1 09 by MorpheusGames_shadPS4 exe](https://github.com/user-attachments/assets/bcdb53db-b50e-4f92-b9a1-601b1281fd75)

**Comment by devilnouria** [comment]
it just reaches to this in the cmd and crashes afterwards like as in the entire emulator

**Comment by rafael-57** [comment]
Github issues exist to report specific problems with the emu, please ask for help on the shadps4 Discord inside #help before opening an issue
