### ISSUE TITLE
Crash after first cutscene (the paleblood transfusion) into the character creator screen

### ISSUE THREAD

**Issue by Jaswanth-Vardireddy** [shadps4-emu/shadPS4#498]
![image](https://github.com/user-attachments/assets/91e6bc34-9f2c-4926-86af-c766f38b397c)

Is the issue solely because of gpu?

**Comment by Ex0312** [comment]
If you are using an AMD GPU it might be, An issue regarding crashing on the amd gpus was already opened

**Comment by Jaswanth-Vardireddy** [comment]
I'm trying an intel gpu 
![image](https://github.com/user-attachments/assets/1cc4cdc6-6392-41c9-b980-68d84df4afa1)
this is the one

**Comment by Jaswanth-Vardireddy** [comment]
This is the gpu I'm using right now
![image](https://github.com/user-attachments/assets/17532408-b9f3-4622-a24e-164b2cbfc3e0)

**Comment by Jaswanth-Vardireddy** [comment]
And this is the GPU performance when it crashes. 
![image](https://github.com/user-attachments/assets/4564fc1f-2969-4b66-9051-ef01d338843c)
 Is there a way to fix this?

**Comment by Foul-Tarnished** [comment]
> This is the gpu I'm using right now ![image](https://private-user-images.githubusercontent.com/71151981/359651195-17532408-b9f3-4622-a24e-164b2cbfc3e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjYzNTYsIm5iZiI6MTcyNDIyNjA1NiwicGF0aCI6Ii83MTE1MTk4MS8zNTk2NTExOTUtMTc1MzI0MDgtYjlmMy00NjIyLWEyNGUtMTY0YjJjYmZjM2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA3NDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1M2NlNzIxZjJkMGQ2ZTU0NjM1ZTQxMTI3MGY2Zjk3YzZjOGU4OGQzZDUxOTk3YzFhMWEwOWM3MGJhYzExYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ILzxib70WDF6rCq2DalIzxRXjKeVOC3EDKJDIJhL0hU)

That's a CPU, not a GPU
Also, post the full log file, not just a screenshot

**Comment by Rayen-Heni** [comment]
I had this same problem fixed it by downloading this save game : https://supporter-files.nexus-cdn.com/2708/26/Bloodborne%20NG%20Plus%20Save%20(Encrypted%20and%20Decrypted)-26-1-1724160220.rar?md5=crIXiD05mnTUFzcKP5dj1A&expires=1724253937&user_id=179510439
go to : shadps4\user\savedata\1\CUSA03173\SPRJ0005 
delete everything there and place the new files there , then when starting the game load the save file it should work

**Comment by SolidnyWonsz** [comment]
It literally says "out of device memory". Your GPU ran out of memory. 8 GB of VRAM isn't enough for now since the emulator leaks a lot of memory

**Comment by lolleri200** [comment]
I have the same issue, but with Nvidia RTX 3070 GPU. Could someone help?
