### ISSUE TITLE
BSB arena crash

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadPS4#505]
if you look behind the player near the BSB arena or even walk a bit too far from the arena it has a shader issue,

how to replicate:
load in, move the camera an inch, crash

video: 
https://youtu.be/qETmJgB5mUk
dump:
[shad_log.txt](https://github.com/user-attachments/files/16687506/shad_log.txt)
save file at the entrance (EU/CUSA03173): 
[CUSA00207-00000004.zip](https://github.com/user-attachments/files/16687509/CUSA00207-00000004.zip)

**Comment by Cyclizar** [comment]
two other save files that immediately give the same result 
(5 is outside of vicar amelias boss room, bottom of the stairs but outside down the stairs, and even inside after killing her at the lamp both result in the same thing)
(6 is outside of the darkbeast paarl boss arena)

[CUSA00207-00000005.zip](https://github.com/user-attachments/files/16687558/CUSA00207-00000005.zip)
[CUSA00207-00000006.zip](https://github.com/user-attachments/files/16687556/CUSA00207-00000006.zip)

**Comment by Hermiten** [comment]
Can you test again please ? Some commit fix light and also memory leak. Maybe can fix your problem
