### ISSUE TITLE
Bloodborne crash 

### ISSUE THREAD

**Issue by Phazdelta** [shadps4-emu/shadPS4#508]
hello i have AMD 6900XT + Ryzen 5600X Bloodborne crash at start of the game,, the main menu work great 

![untitled](https://github.com/user-attachments/assets/75332fe4-cdb8-4d0d-abaf-40264feb6ef7)

**Comment by kleinermob** [comment]
can you try it with following save game? https://supporter-files.nexus-cdn.com/2708/26/Bloodborne%20NG%20Plus%20Save%20(Encrypted%20and%20Decrypted)-26-1-1724160220.rar?md5=crIXiD05mnTUFzcKP5dj1A&expires=1724253937&user_id=179510439

**Comment by Phazdelta** [comment]
> can you try it with following save game? https://supporter-files.nexus-cdn.com/2708/26/Bloodborne%20NG%20Plus%20Save%20(Encrypted%20and%20Decrypted)-26-1-1724160220.rar?md5=crIXiD05mnTUFzcKP5dj1A&expires=1724253937&user_id=179510439

where to put those file ?

**Comment by Phazdelta** [comment]
found it still crash ..........

**Comment by rynnyr-maomao** [comment]
Follow steps in https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit (it's from shadPS4 discord server)

**Comment by georgemoralis** [comment]
Sharing save files public not permited

**Comment by GermanAizek** [comment]
> Follow steps in https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit (it's from shadPS4 discord server)

Many thanks. I need single demanding image for testing.

**Comment by Hermiten** [comment]
Can be close I think
