### ISSUE TITLE
[macOS] Feature Request: Place user folder in Application Support

### ISSUE THREAD

**Issue by shinra-electric** [shadps4-emu/shadPS4#509]
Currently the `user` folder is created in the same directory as the app bundle. 

The preferred place for it would be:
`~/Library/Application Support/shadPS4/user`

Because some users might not know how to access their user library (it’s hidden by default), a menu option in the UI that opens the user folder directly would also be useful.

**Comment by squidbus** [comment]
I actually prefer to have it next to the app so this should be an option, probably all platforms should have portable and non-portable options.

**Comment by mavethee** [comment]
> I actually prefer to have it next to the app so this should be an option, probably all platforms should have portable and non-portable options.

Maybe something as Vita3K does during first time setup
`~/Library/Application Support/shadPS4/user` as default and allow user to change it any time?

**Comment by shinra-electric** [comment]
I'd say the best option is for the default location to be Application Support, but the app searches for the presence of the user folder in both locations, prioritising the portable one over the App Support one. 

This way it's invisible to people who don't care about the location, but if someone is using portable mode it will be used instead.

**Comment by mavethee** [comment]
With introduction of Qt translations, this would be extra needed.
