### ISSUE TITLE
Sonic Mania Crash on macOS

### ISSUE THREAD

**Issue by aptonline** [shadps4-emu/shadPS4#510]
Testing with a known playable game, Sonic Mania, and I receive the following crash on launching the game.

ShadPS4 v0.2.0

macOS 14.6.1

[shad_log.txt](https://github.com/user-attachments/files/16690905/shad_log.txt)

[shadPS4_mac_crash_logs.txt](https://github.com/user-attachments/files/16690926/shadPS4_mac_crash_logs.txt)

Edited: Clarified that crashes on launching game not app.

**Comment by shinra-electric** [comment]
#506 fixed a crash when trying to run it from the Downloads folder.

If you were trying to run it from there, either move to /Applications (or a sub-folder in there) or download the latest main branch build from GitHub Actions…

Edit: I saw from the log you have it in /Applications, so my suggestion is not relevant. Sorry…

**Comment by squidbus** [comment]
macOS 15 or above is required for Apple Silicon Macs.

**Comment by aptonline** [comment]
> macOS 15 or above is required for Apple Silicon Macs.

Where does it state this? macOS Sequoia (15) isn’t released to the public yet. I’m running the latest public version of the os.

**Comment by squidbus** [comment]
> Where does it state this? macOS Sequoia (15) isn’t released to the public yet. I’m running the latest public version of the os.

I'm not sure if it's properly stated anywhere but it was in the original PR: https://github.com/shadps4-emu/shadPS4/pull/294

macOS 15 adds support to Rosetta 2 for newer instruction sets like AVX, which are needed for most if not all games.

**Comment by aptonline** [comment]
Many thanks for the link, I’ll close this issue and retest once Sequoia is out 👍.
