### ISSUE TITLE
Is it possible to combine this project with Box64?

### ISSUE THREAD

**Issue by pppaa08** [shadps4-emu/shadPS4#515]
Since the Box64 is a powerful ARM-x86 emulator, can we take advantage of it to emulate the cpu part? Thus we can run this project on ARM-based devices such as Android handhelds?

**Comment by georgemoralis** [comment]
If someone want to work on a arm64 recompiled why not it is not team's priority atm

**Comment by Hermiten** [comment]
No one want to work on it ?It's not planned for now, I'm closing it
