### ISSUE TITLE
Proxmox Windows11 Guest Workaround

### ISSUE THREAD

**Issue by deathbybandaid** [shadps4-emu/shadPS4#516]
For those of you trying to run shadPS4 in a Proxmox Virtual Machine

Create a `.ps1` file names something like `pve-launch.ps1` and give it the contents:

`$Env:TRACY_NO_INVARIANT_CHECK=1 ; .\shadPS4.exe`

This will add an environment variable that will allow the application to open.

In my instance, I was seeing the app flash a black cmd window briefly, then nothing.
I opened terminal to see the output directly and got

````
Tracy Profiler initialization failure: CPU doesn't support invariant TSC.
Define TRACY_NO_INVARIANT_CHECK=1 to ignore this error, *if you know what you are doing*.
Alternatively you may rebuild the application with the TRACY_TIMER_QPC or TRACY_TIMER_FALLBACK define to use lower resolution timer.
````

The host machine is a 2nd gen threadripper and resides on my network rack.
The guest machine is set to `host` with some clever stuff to fool anti-cheat.
The Guest has pcie passthrough of a RTX3050 and I use sunshine/moonlight to stream games old/new to other devices around my house.

This is my first time testing shadPS4, and came here from the youtube channel MrSujano. If there is any additional information I can provide, let me know. I did a search first, and felt this was information worth sharing.

**Comment by GlCap** [comment]
Thank you, had the same problem with a guest win11 vm in using libvirt
