### ISSUE TITLE
AMD GPU issue

### ISSUE THREAD

**Issue by dogoawesomeness256** [shadps4-emu/shadPS4#519]
i have video footage of the issue but basically i can boot into the title screen and get into game but after 4 -5 inputs the game crashes also the game does not display cutscenes and only shows the subtitles 

here is a link to the footage: https://drive.google.com/file/d/1SRESb267JyfDX-z5fai6sevym0uWqzyz/view?usp=drive_link

**Comment by Phazdelta** [comment]
mine can't go to in-game

**Comment by dogoawesomeness256** [comment]
turn off async and turn on sync its in the settings bloodborne only works with sync

**Comment by dogoawesomeness256** [comment]
nvm make sure your using bbhacks build

**Comment by Hermiten** [comment]
This issue can be close
