### ISSUE TITLE
old yharnam instacrash. is consistent even with map edits. 

### ISSUE THREAD

**Issue by ogju** [shadps4-emu/shadPS4#520]
old yharnam consistently crashes even if theres 0 map pieces or objects or even enemies in the level. ive tested it all at this point. i disabled all shadow casting on every object and map piece, disabled lights, deleted literally 90% of the level while doing it and it still consistently crashes at this point in each of my attempts:

https://github.com/user-attachments/assets/9af07970-63a9-401a-9dab-dd907f56130a

https://github.com/user-attachments/assets/678d29fd-3613-4950-99d3-bf9c3d99e0b6

when u try to load into the lamp of old yharnam, it loads when theres no map pieces but doesnt make it far. crashed about a minute after recording this, think it was from the npc on the tower in the level. 
edit: if u dont edit the map it instacrashes. 

https://github.com/user-attachments/assets/92a78511-3fc8-4e85-8c70-841feb4c6fd8

**Comment by Hermiten** [comment]
Lot of work are made on bloodbordne. This issue is old and not followed. I close it
Thanks for the report, you can try lastest version it will be really better !
