### ISSUE TITLE
Newer Version (Since ver. 0.2.0) Won't Open On My System (Windows 10)

### ISSUE THREAD

**Issue by wahpedal** [shadps4-emu/shadPS4#524]
hello, as the title says I can't run it on my system. it opens until the game directory window, after selecting the games folder it just disappears. and when I try to launch it, only command window opens for a second and then disappears or force close? I don't know.
or do I need a specific library to open newer version Shadps4 ? Thanks.

ver 0.1.0 works like a charm.

https://github.com/user-attachments/assets/9aa5130d-9997-41fc-9258-f02f7507782e

**Comment by SolidnyWonsz** [comment]
Show logs

**Comment by wahpedal** [comment]
I just googled how to see logs on windows, I thought the logs will be inside "ShadPS4\user\log". sorry, my bad.
lmk if this not the logs.

ERROR
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="" /> 
  <EventRecordID>71799</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>shadPS4.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>66c7024a</Data> 
  <Data>ucrtbase.dll</Data> 
  <Data>10.0.19041.3636</Data> 
  <Data>81cf5d89</Data> 
  <Data>c0000409</Data> 
  <Data>000000000007286e</Data> 
  <Data>1e8c</Data> 
  <Data>01daf4812ebdda05</Data> 
  <Data>I:\PS4\Emu\shadps4-win64-qt\shadPS4.exe</Data> 
  <Data>C:\WINDOWS\System32\ucrtbase.dll</Data> 
  <Data>5849ddaf-3e1c-475c-9a0a-8af0b6752fea</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

INFORMATION A
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="" /> 
  <EventRecordID>71800</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data /> 
  <Data>0</Data> 
  <Data>BEX64</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>shadPS4.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>66c7024a</Data> 
  <Data>ucrtbase.dll</Data> 
  <Data>10.0.19041.3636</Data> 
  <Data>81cf5d89</Data> 
  <Data>000000000007286e</Data> 
  <Data>c0000409</Data> 
  <Data>0000000000000007</Data> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA1E5.tmp.mdmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA263.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2A3.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2A1.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2C1.tmp.txt \\?\C:\Users\UserName\AppData\Local\Temp\WERA2D4.tmp.appcompat.txt</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_shadPS4.exe_2146c1a76c6fdbecc111e85364f1a4e86338775_be7959d3_cab_9ccaec63-9468-487e-a184-e9d48091ede9</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>5849ddaf-3e1c-475c-9a0a-8af0b6752fea</Data> 
  <Data>4</Data> 
  <Data /> 
  <Data>0</Data> 
  </EventData>
  </Event>
```

INFORMATION B
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="" /> 
  <EventRecordID>71801</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>2140805896590049764</Data> 
  <Data>5</Data> 
  <Data>BEX64</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>shadPS4.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>66c7024a</Data> 
  <Data>ucrtbase.dll</Data> 
  <Data>10.0.19041.3636</Data> 
  <Data>81cf5d89</Data> 
  <Data>000000000007286e</Data> 
  <Data>c0000409</Data> 
  <Data>0000000000000007</Data> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA1E5.tmp.mdmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA263.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2A3.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2A1.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2C1.tmp.txt \\?\C:\Users\UserName\AppData\Local\Temp\WERA2D4.tmp.appcompat.txt</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_shadPS4.exe_2146c1a76c6fdbecc111e85364f1a4e86338775_be7959d3_9ccaec63-9468-487e-a184-e9d48091ede9</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>5849ddaf-3e1c-475c-9a0a-8af0b6752fea</Data> 
  <Data>268435456</Data> 
  <Data>cc5a1e5f3c8e4ca29db5ab9ed74fc1e4</Data> 
  <Data>0</Data> 
  </EventData>
  </Event>
```

**Comment by ArjixWasTaken** [comment]
I don't think they are asking for windows logs, but program logs.

If you open cmd at the same folder as the executable, and invoke the executable using cmd, the console should stay open even after it crashes, are there any logs in the console?

**Comment by ArjixWasTaken** [comment]
I am not fully sure, but it looks like logs come out when you use the `--help` argument.

![image](https://github.com/user-attachments/assets/6fa709d3-460c-4585-b3af-cc8e08437bc0)

I made a video showing how you can replicate my screenshot:


https://github.com/user-attachments/assets/866d1fe4-85b5-4ac0-9c4d-33acfa146f08


--

##### Kinda weird ngl, I'd expect to see a help message with the available program arguments, so that behaviour sounds weird.

**Comment by ArjixWasTaken** [comment]
Ok, the reason I see logs when I have `--help` is because the code assumes that any argument given is a game?
So it tries to launch a game with the name `--help`?

https://github.com/shadps4-emu/shadPS4/blob/main/src/qt_gui/main.cpp#L40-L44

PS: I am the one that marked my messages as outdated, since they didn't bring any value to the issue.

**Comment by wahpedal** [comment]
> I don't think they are asking for windows logs, but program logs.

Yeah, tbh it would makes sense if the logs are from inside the folder. but in my case there are no logs being generated. this really confuses me, without the logs we won't be able to diagnose the problem.

> If you open cmd at the same folder as the executable, and invoke the executable using cmd, the console should stay open even after it crashes, are there any logs in the console?

no, it has the same behavior as before (auto close). I tried to run windows in safe mode, still the same.


https://github.com/user-attachments/assets/9158d4da-2d47-4324-9047-e5d3790b8f95

**Comment by ArjixWasTaken** [comment]
That is really really weird, it didn't even try to load a game.

**Comment by ArjixWasTaken** [comment]
Can you redo what you did in the video, but after that run `echo %errorlevel%` to get the exit code of shadPS4?

**Comment by n12y0** [comment]
go Windows Event Viewer, Windows Logs -> Application, send the event log

**Comment by ArjixWasTaken** [comment]
> go Windows Event Viewer, Windows Logs -> Application, send the event log

I believe they already sent the event logs

https://github.com/shadps4-emu/shadPS4/issues/524#issuecomment-2304382699

**Comment by hikikomero** [comment]
Try moving the shadps4 folder to another drive, fixed it for me. Weird, I know.

**Comment by wahpedal** [comment]
> Can you redo what you did in the video, but after that run `echo %errorlevel%` to get the exit code of shadPS4?

tried it 2 runs just to make sure, it gives me `-1073740791`

> Try moving the shadps4 folder to another drive, fixed it for me. Weird, I know.

yeah, I've tried this also and still won't launch. it happened to me back then with Unreal Engine, it won't launch when I installed on drive C (windows installed drive).

**Comment by ItsMuffins** [comment]
Yeah, this version won't open for me either. Same issue, it just shuts down before even opening the client

**Comment by Sukkunnaa** [comment]
same problem here, any fixes guys?

**Comment by yumlevi** [comment]
same here, launching from cmd line it just prints Usage: path\shadPS4.exe <elf or eboot.bin path>, installed not on C drive

**Comment by Sakmael** [comment]
same here

**Comment by lecosilva** [comment]
@yumlevi @Sakmael @Sukkunnaa @ItsMuffins @wahpedal It needs to be on the same drive Windows is installed.

**Comment by jrgf** [comment]
Same problem here this is the log seems to be a problem with visual studio 2015 redistributable : 


Faulting application name: shadPS4.exe, version: 0.0.0.0, time stamp: 0x66f64d8c
Faulting module name: MSVCP140.dll, version: 14.29.30133.0, time stamp: 0x60ff28cc
Exception code: 0xc0000005
Fault offset: 0x0000000000013020
Faulting process id: 0x0x7090
Faulting application start time: 0x0x1DB10EA25F1442A
Faulting application path: D:\shadps4-win64-qt-2024-09-27-75166ec\shadPS4.exe
Faulting module path: C:\Windows\SYSTEM32\MSVCP140.dll
Report Id: ef4045be-5df0-484b-b07e-920bf6a9b211
Faulting package full name: 
Faulting package-relative application ID:

**Comment by jrgf** [comment]
Yes fixed! just reinstall de Visual C++ redistributable 2015-2022 here the links:
https://aka.ms/vs/17/release/vc_redist.x86.exe
https://aka.ms/vs/17/release/vc_redist.x64.exe
![image](https://github.com/user-attachments/assets/956bc474-0a44-495f-82cd-d302503f4ebb)
