### ISSUE TITLE
console language

### ISSUE THREAD

**Issue by su322** [shadps4-emu/shadPS4#529]
Settings->General->Console Language 
When I try to change language, there's no thing happened. Isn't it referring to the language of the user interface? : )
(Windows10 Qt)

**Comment by Xphalnos** [comment]
It depends on the language you have chosen, some languages ​​are not available for certain games.

**Comment by DanielSvoboda** [comment]
This changes the language of the console and not the emulator interface.
Currently the emulator is only available in English and there is no option to change the interface to Chinese, for example.
