### ISSUE TITLE
[Aggregate issue] Invalid texture type Color2DMsaa

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#532]
Hit by CUSA04548 - World of Final Fantasy

**Comment by Amini-ab** [comment]
#include<iostream>
using namespace std;

**Comment by kvicken** [comment]
same error in CUSA01623 - God of War III Remastered
![godrshad](https://github.com/user-attachments/assets/70f7f023-5882-499d-91e6-c589d0a00b1a)

**Comment by georgemoralis** [comment]
Known unimplemented stuff

**Comment by gandalfthewhite19890404** [comment]
СUSA02172 - Journey Collectors Edition

**Comment by dima-xd** [comment]
Also Wipeout

**Comment by gandalfthewhite19890404** [comment]
CUSA00046 - Doki-Doki Universe

**Comment by gandalfthewhite19890404** [comment]
CUSA08076 - Sine Mora EX

**Comment by georgemoralis** [comment]
If possible try to post the url of compatibility  list if game exists there so it create a link there. So when the is implemented we should know  which game to test in the list

**Comment by ElBread3** [comment]
CUSA03562 - Kyoei Toshi, while compiling during bootup, 1.00

**Comment by ElBread3** [comment]
Figured out this boots on stable so I can make an linked issue! https://github.com/shadps4-emu/shadps4-game-compatibility/issues/570

**Comment by Hermiten** [comment]
I think this is outdated and this https://github.com/shadps4-emu/shadPS4/pull/1013 maybe fix it
