### ISSUE TITLE
Translations in qt interface

### ISSUE THREAD

**Issue by georgemoralis** [shadps4-emu/shadPS4#540]
Implemented translate interface for supporting different languages in qt

**Comment by Winvoker** [comment]
I can help for Turkish language

**Comment by RamonJales** [comment]
I can help for Portuguese language

**Comment by dima-xd** [comment]
I can do that. But I think it would be better to use transifex instead of PRs

**Comment by georgemoralis** [comment]
dima implement the qt part and we will see

**Comment by mavethee** [comment]
> I can do that. But I think it would be better to use transifex instead of PRs

What about Crowdin instead?

**Comment by georgemoralis** [comment]
Interface added

**Comment by LeDragoX** [comment]
> I can help for Portuguese language

Hey @RamonJales, do you still want to translate it to Portuguese? This PR is already merged, are you working on it already?
I'm interested in doing it as well, maybe you wanna join their discord server to exchange ideas 😉.

Edit: I've already done it.
