### ISSUE TITLE
Regression in linux concerning latest bb-hacks 

### ISSUE THREAD

**Issue by HermitsA** [shadps4-emu/shadPS4#545]
OS: Nixos unstable (24.11)
GPU: RX 6700xt
CPU: Ryzen 5 7600
RAM: 32GB DDR5 6000 Mhz 

It seems that the latest appimages for bb-hacks linux-qt has had a few regressions making the game unable to get to the menu.

It worked on the appimage from 4 days ago as of writing:
https://github.com/shadps4-emu/shadPS4/actions/runs/10458195832

Regressed at: https://github.com/shadps4-emu/shadPS4/actions/runs/10524940281
Also seen in: https://github.com/shadps4-emu/shadPS4/actions/runs/10526470363

[shad_log.txt](https://github.com/user-attachments/files/16730860/shad_log.txt)
![issues](https://github.com/user-attachments/assets/57478af3-d7aa-4571-8f6e-10fbb4056f1a)

I have also followed the troubleshooting steps inside the google doc provided in the discord, however this did not give any results, neither is a completely fresh install.

**Comment by EatedPantsu** [comment]
Can confirm

**Comment by mavethee** [comment]
And why it supposed to be a separate issue when it's related to [PR's branch](https://github.com/shadps4-emu/shadPS4/pull/465)?
![explain](https://media1.tenor.com/m/SIGH_uFUqdAAAAAC/confused-the-office.gif)

**Comment by HermitsA** [comment]
forgot it existed.

no idea how to open an issue for a specific branch.

**Comment by mavethee** [comment]
Comment about the issue on that PR?
Assuming it's hacks it will not get merged any time soon if even.
Plus would be more eye-catching for PR maintainer.

**Comment by HermitsA** [comment]
alright, will do

**Comment by Hermiten** [comment]
Can be close, this branch doesn't exist anymore
