### ISSUE TITLE
Crash after first cutscene

### ISSUE THREAD

**Issue by dmitryloshakov** [shadps4-emu/shadPS4#552]
![Снимок экрана 2024-08-24 073347](https://github.com/user-attachments/assets/68a7f6c7-14dd-4c0c-b351-c2f567547eb4)
Crash after first cutscene rtx 3080 i5-14600K

**Comment by mscolari** [comment]
Similar crash after first cutscene. RTX 3080 5800X
<img width="1714" alt="image" src="https://github.com/user-attachments/assets/9a31be0c-3903-4194-aa3a-18eb41095398">

**Comment by gandalfthewhite19890404** [comment]
Without game, cusa. Just - crash. Nice issue, really.

**Comment by mscolari** [comment]
Bloodborne - CUSA03173

**Comment by dmitryloshakov** [comment]
> Bloodborne - CUSA03173

yes it is

**Comment by wahpedal** [comment]
I have the same error code.

**Comment by wahpedal** [comment]
Quick update.

I found out removing `libSceDiscMap.sprx` when using sys_modules caused ```
 [Debug] <Critical> structured_control_flow.cpp:operator():832: Assertion Failed!
Shader translation has failed ```

it didn't give an error when I'm not using the sys_modules.

so you have 2 options either not using sys_modules at all or include `libSceDiscMap.sprx` inside sys modules folder.

**Comment by dmitryloshakov** [comment]
thats didnt help mi or i doing something wrong anyway thanks

**Comment by wahpedal** [comment]
just to make sure, did you use the bb-hacks branch build? because other releases can't go in game.

**Comment by dmitryloshakov** [comment]
i try it now but now another ptoblem i think simular with @mscolari 
![Снимок экрана 2024-08-25 111809](https://github.com/user-attachments/assets/276b8f8b-ed20-4cdc-95c2-58f60d752c4a)

**Comment by RE4L1** [comment]
Same issue. Critical liverpool.cpp
PC just freezes for about 20 seconds. RTX 3060

**Comment by mscolari** [comment]
> Quick update.
> 
> I found out removing `libSceDiscMap.sprx` when using sys_modules caused `[Debug] <Critical> structured_control_flow.cpp:operator():832: Assertion Failed! Shader translation has failed`
> 
> it didn't give an error when I'm not using the sys_modules.
> 
> so you have 2 options either not using sys_modules at all or include `libSceDiscMap.sprx` inside sys modules folder.

Just tried adding `libSceDiscMap.sprx` back to `sys_modules` and still seeing same error:
![image](https://github.com/user-attachments/assets/f8ad64e1-6ce9-41b4-b1a0-4b2720c2647a)

**Comment by mscolari** [comment]
Update: Able to get to game loaded with this action and all sys_modules added: [https://github.com/shadps4-emu/shadPS4/actions/runs/10526470367](https://github.com/shadps4-emu/shadPS4/actions/runs/10526470367)
It runs until the first encounter with werewolf but game freezes once death animation is about to show.


https://github.com/user-attachments/assets/2f294b06-732e-45cc-b9bc-217676d8d4b2

**Comment by wahpedal** [comment]
I think that is the limitation of the emulator currently, since it's still on very early stage. the main idea here is just to be able to launch the game (mainly on bb-hacks? idk). and on some devices it will crash at certain point, mine crash when death and trying to teleport to another map. the solutions are using cheats for unlimited health and save files for accessing another map. 

and for anyone who has the same issues on the future, please read the documentary for launching Bloodborne while the emulator still on the early stage/WIP :
https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit

**Comment by Hermiten** [comment]
This issue can be close because it's fixed by this PR https://github.com/shadps4-emu/shadPS4/pull/637
