### ISSUE TITLE
[Aggregate issue] Unknown format in ConvertPixelFormat

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#553]
CUSA00246 - Backgammon Blitz
`Unknown format=3238395904`

**Comment by Emulator-Team-2** [comment]
- Cel Damage HD
```
[Debug] <Critical> image_info.cpp:ConvertPixelFormat:27: Unreachable code!
Unknown format=3238395904
```

Log:
[shad_log.zip](https://github.com/user-attachments/files/16735953/shad_log.zip)

**Comment by Hermiten** [comment]
I'm closing this one.
Please test the game on the last version, post it on the compat list (I cannot find any of these 2 games)  and if it's still present in 0.4, we will open a new one.
