### ISSUE TITLE
[Aggregate issue] Unknown mount mode in saveDataMount

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#554]
CUSA17983 - Five Nights at Freddy's: Sister Location
`Unknown mount mode = 58`

**Comment by Exhigh** [comment]
A log file would be helpful

**Comment by Xader726** [comment]
CUSA01019 - The Walking Dead: The Complete First Season
`Unknown mount mode = 30`
[TWDS1_shad_log.txt](https://github.com/user-attachments/files/16737796/TWDS1_shad_log.txt)

**Comment by gandalfthewhite19890404** [comment]
Reopen, please.
CUSA03528 - Deadpool
```
[Debug] <Critical> savedata.cpp:saveDataMount:535: Unreachable code!
Unknown mount mode = 20
```
