### ISSUE TITLE
ShadPS4 crashing on launch

### ISSUE THREAD

**Issue by Maxxxxxxx333333** [shadps4-emu/shadPS4#571]
so i tried to download 3 versions of shadps4 and it wont open on my screen and then  i tried to open it in win rar it did opened idk if its working yet but i want to found solution and how do i get bloodborne without ps

**Comment by mavethee** [comment]
And you won't find any, **shadPS4 requires you to own PS4**

**Comment by Hermiten** [comment]
Can be close, for sure.
This emulator need basic skill and you need to read the doc and maybe go on discord

**Comment by mavethee** [comment]
> Can be close, for sure. This emulator need basic skill and you need to read the doc and maybe go on discord

Would say the same about all thoose Bloodb*rne issues, caused by PR not main branch of the emulator. I swear this game will get me PTSD someday.
