### ISSUE TITLE
Odin Sphere Leifthrasir v1.00 (CUSA03873) crash

### ISSUE THREAD

**Issue by LinQinyan233** [shadps4-emu/shadPS4#574]
[shad_log.txt](https://github.com/user-attachments/files/16740382/shad_log.txt)

CPU: i7-12650H
Ram: 16Gb 3200Mhz 8+8
GPU: RTX 4050 Laptop GPU 6GB

**Comment by Hermiten** [comment]
Better to put it on compatibility list ?

**Comment by gorshco** [comment]
Submit the information here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/535

**Comment by Hermiten** [comment]
This issue can be close
