### ISSUE TITLE
Mac OS version seems to be far behind

### ISSUE THREAD

**Issue by ghostforest** [shadps4-emu/shadPS4#578]
The mac version of shad PS4 seems to be stuck with 2d games. Nothing of the more complicated stuff that the windows version runs, runs on mac.

Is this expected?

**Comment by mavethee** [comment]
There's couple things why:
1. MoltenVK doesn't exactly comply Vulkan 1.3 as original requirements are.
2. Rosetta 2 has some limitations, e.g Until Dawn trying to map to lower portion of user area that forbiden by Rosetta 2.
3. Code needs a lot of work to optimize it for macOS, some newer PRs may break things.

**Comment by raphaelthegreat** [comment]
Also to add none of the main developers in this project have a macbook to my knowledge. The port was an external contribution and maintained as such.

**Comment by mavethee** [comment]
Everyone is on squidbus' mercy with this project being on macOS basically 😆

**Comment by raphaelthegreat** [comment]
Haha indeed

**Comment by ghostforest** [comment]
Id like to offer my help but I feel somebody would need to tell me what to do. I'm on an M1 Max Mac. 
I can code but on projects like this and especially on gpu heavy stuff Id need some guidance.

**Comment by Hermiten** [comment]
Maybe we can add on the readme a warning for Mac user to mean that the mac version is less advanced but still tracked, so fewer games are usable and close this issue ?
