### ISSUE TITLE
[Reggresion] [macOS] Another World no longer boots using sys_modules

### ISSUE THREAD

**Issue by mavethee** [shadps4-emu/shadPS4#595]
![CleanShot 2024-08-26 at 10 29 22@2x](https://github.com/user-attachments/assets/965ed687-a6ca-4cdd-9dec-51e346f2ffe2)
Gets stuck on black screen and endlessly writes to log file.
[shad_log.txt](https://github.com/user-attachments/files/16746227/shad_log.txt)

**Comment by squidbus** [comment]
Do you know which change it stopped working in?

**Comment by mavethee** [comment]
> Do you know which change it stopped working in?

@squidbus No, but I have a screenshot which I've posted on discord as well, that it worked on https://github.com/shadps4-emu/shadPS4/commit/159be2c7f436a91ee85f8f58465974ca64a9425c.
So we could start from there 🤔 
Audio was awful, but it happening with RDR as well so it's not that game specific.
![image](https://github.com/user-attachments/assets/86556819-983b-48a0-8060-5986c7ea65a6)

**Comment by georgemoralis** [comment]
just tested it on latest main , it works on windows so maybe something to do with macOS version?

**Comment by mavethee** [comment]
> just tested it on latest main , it works on windows so maybe something to do with macOS version?

it's macOS issue, I figured, but not about macOS version, screenshot was made on latest macOS 15.1 beta and I'm still on the same build.
With each PR, things for macOS can break it seems and I guess we will have to keep an eye on that 🤷🏻‍♂️

**Comment by Hermiten** [comment]
Hello, you can also use the discord channel to report this, sometimes it can be fast to fix this for some devs.
Is it still an issue for you ?

**Comment by mavethee** [comment]
> Hello, you can also use the discord channel to report this, sometimes it can be fast to fix this for some devs. Is it still an issue for you ?

I did report this on discord if you didn't check 😅 GitHub issue at least leaves more traces.
Still black screen (probably not exactly latest tho but still)

![CleanShot 2024-10-04 at 16 19 32@2x](https://github.com/user-attachments/assets/a149988c-07f4-45d9-9c5e-34ae64886786)

Log file:
[shad_log.txt](https://github.com/user-attachments/files/17259972/shad_log.txt)

**Comment by ghost** [comment]
The game has broken sound. Besides that, gameplay works for me on MacOS.

**Comment by mavethee** [comment]
Well it's still broken for me, I remember it working 🤷🏻 
![CleanShot 2024-10-04 at 16 38 48@2x](https://github.com/user-attachments/assets/cd895c44-6739-458f-9987-d84a9972b45a)
Log file:
[shad_log.txt](https://github.com/user-attachments/files/17260223/shad_log.txt)

**Comment by ghost** [comment]
Ok, I can reproduced the black screen when using sys modules. Without sys modules it works ...besides broken sound.

**Comment by mavethee** [comment]
@Hermiten re-open, please.

**Comment by Hermiten** [comment]
Sure !

**Comment by Hermiten** [comment]
Lot of things change and you can also do a report on the compatibility list https://github.com/shadps4-emu/shadps4-game-compatibility for mac version.
Feel free if ou want to test on each version and if it's still a regression :)
