### ISSUE TITLE
[Aggregate Issue] sceNpCheckCallbackForLib:879, sceNetCtlCheckCallbackForNpToolkit:322

### ISSUE THREAD

**Issue by ElBread3** [shadps4-emu/shadPS4#604]
Tested on latest main build (v0.2.1 WIP ad83730), this Github issue aggregates games that spam these two stubbed calls repeatedly and prevent progress:

Patapon Remastered (1.01).
[pataponremasteredupdate_log.txt](https://github.com/user-attachments/files/16753589/pataponremasteredupdate_log.txt)

GPU: AMD RX 6600
Driver version: 24.7.1

**Comment by StevenMiller123** [comment]
Looking at these logs, the Patapon Remastered error appears to be related to these logs, which occur right before the check callback spam begins. 
```
[Kernel.Fs] <Info> file_system.cpp:sceKernelStat:301: (PARTIAL) path = /app0/texreplace-4x.pak
[Kernel.Pthread] <Error> file_system.cpp:posix_stat:329: posix_stat: error = -2147352574
[Tty] <Info> libkernel.cpp:ps4__write:210: WARNING: (PakFile) File 'host0:texreplace-4x.pak' does not exist
```
As for Locoroco Remastered, I can't tell if there's an actual issue. Based on the log, the game seems to reach a rendering loop, though there isn't much happening outside of that. If there is an actual issue, it's likely related to the lack of gs shader stage support.

**Comment by ElBread3** [comment]
Locoroco Remastered doesn't have a game-breaking issue with this in so much as exhibits the behavior of spamming the calls. This GitHub issue is helpful to find all the games that exhibit this behavior and why e.g. Quake 1 may do this for it's entirely different reason

**Comment by squidbus** [comment]
Similar problem in CUSA10155 (The Witch and the Hundred Knight 2) where it gets stuck on the loading screen spamming these two in a loop.

This may not actually be a problem with unimplemented NpToolkit functions though, it seems like it may be the threads are deadlocking and the network thread is left alive spinning.

**Comment by ElBread3** [comment]
Closing as these functions have been implemented
