### ISSUE TITLE
liverpool.cpp unreachable code crash

### ISSUE THREAD

**Issue by JunerJoker** [shadps4-emu/shadPS4#606]
when loading bloodborne it crashes with this error

![ApplicationFrameHost_a4EvJdgWKj](https://github.com/user-attachments/assets/2f862daf-2c45-491b-a742-8e9665af7d65)

here is my log
[shad_log.txt](https://github.com/user-attachments/files/16754553/shad_log.txt)

**Comment by SavillionPrime** [comment]
Temporal fix: Delete or move files inside roms "sfx" folder into another place.

**Comment by Hermiten** [comment]
Can you test again ?
This https://github.com/shadps4-emu/shadPS4/pull/637 will probably fix your problem

**Comment by GiftUngiven666** [comment]
I see the issue 637 has been merged, and also that's a fix for AMD cards. I have NVIDIA and got the same problem. Tried also temporal fix suggeste bt @SavillionPrime but to no avail.
