### ISSUE TITLE
Integrate CCache for increase repeat buildings on Linux and CI

### ISSUE THREAD

**Issue by GermanAizek** [shadps4-emu/shadPS4#619]
More info: https://ccache.dev/

**Comment by LeDragoX** [comment]
@GermanAizek I'm already working to fix that, expect it to come Soon™, literally with CCache. You'll be shocked for how fast it is.
Also, look at #542, they already talked about it.

**Comment by GermanAizek** [comment]
@LeDragoX fixed it on cmakelists https://github.com/shadps4-emu/shadPS4/pull/621. Is not affected actions CI.

**Comment by LeDragoX** [comment]
@GermanAizek I didn't knew how to make it work from CMakeLists, nice, all I could do was modifying the CI, does it benefit other OSes too?
If you want to look at my modifications, I got it here: https://github.com/LeDragoX/shadPS4/tree/cache-actions/.github/workflows

**Comment by Hermiten** [comment]
Fixed with this PR https://github.com/shadps4-emu/shadPS4/pull/985
