### ISSUE TITLE
Freeze every other launch: Rock Band 4 Boot Regression

### ISSUE THREAD

**Issue by jnackmclain** [shadps4-emu/shadPS4#630]
Please note I am working on a remote branch which has a couple of workarounds staged by Xezrunner in pr #499 to get the game fully booting.

last night I tried out rb4 on squidbus's memory pr branch #601 and it was working when i pulled those changes into our branch that has the xezrunner workarounds.

This morning i see its merged into main, so I merged main upstream into the same branch, and now the game boots but freezes after a few seconds at the esrb logo.

[shad_log.txt](https://github.com/user-attachments/files/16784955/shad_log.txt)

If there are any pointers on what commits i should be looking at to find the new bug, please let me know

if it is helpful this is our working branch. https://github.com/LlysiX/shadPS4/tree/test_upstream

**Comment by jnackmclain** [comment]
I have been looking into this further
Turns out right now it freezes every other game boot

i can reproduce all on vanilla game files
First boot, successful, boots until scene hang (correct)
Second boot, unsuccessful, freeze on esrb.
Third boot, successful.
Boots every other time

Each boot, my dual sense controler pulses stock blue, then turns a dim milky white with a hint of purple

I was not disconnecting or reconnecting my controller
https://cdn.discordapp.com/attachments/1258386683691274361/1278378030083080204/2024-08-28_10-33-18_1.mp4

**Comment by Hermiten** [comment]
I close it because we don't support custom branch.
You can also try the latest version because lot of fix was made.

And if it's still present, please open a Issue with a shadps4 branch
