### ISSUE TITLE
The last  bbhack version AMD crashing again

### ISSUE THREAD

**Issue by ChronoRPG** [shadps4-emu/shadPS4#648]
Greeting

With the last bbhack version ( c253fd8 ) AMD have a regression

Crashing the game when i try load the save or when i try a new game, on both case with AMD bloodborne crash.

I leave my log archive for investigate the cause.

[shad_log.txt](https://github.com/user-attachments/files/16803886/shad_log.txt)

**Comment by raphaelthegreat** [comment]
I cannot reproduce this problem on my AMD gpu. Can you enable validation option and send a new log? Make sure to install Vulkan SDK

**Comment by ChronoRPG** [comment]
Of crouse, this is the log, with Enable vulkan validation layers, and enable vulkan syncronization validation
[shad_log.txt](https://github.com/user-attachments/files/16803983/shad_log.txt)

**Comment by voguelike** [comment]
same here, i crash with this unhandled exception every time i continue or finish making a new character:
`[Debug] <Critical> liverpool.h:unhandled_exception:1100: Unreachable code!
Unhandled exception: vk::Device::createComputePipelineUnique: ErrorUnknown`

i tried all of the permutations i could think of; with and without gparams and libSceDiscMap, with and without sound and sfx, as well as with and without any patches/mods or external applications such as reshade.

i would send a log with vulkan validation layers enabled but it crashes instantly and leaves an empty log, so here is the regular one instead 😅
[shad_log.txt](https://github.com/user-attachments/files/16804003/shad_log.txt)

**Comment by raphaelthegreat** [comment]
I have pushed a commit that may fix the problem

**Comment by ChronoRPG** [comment]
Now it's worse 😅 I can't watch the first screen of bloodborne XDD

**Comment by raphaelthegreat** [comment]
Please post a log (always with reports so I can fix it)

**Comment by ChronoRPG** [comment]
Sorry, this the log with the new error 
[shad_log.txt](https://github.com/user-attachments/files/16805167/shad_log.txt)

**Comment by raphaelthegreat** [comment]
This looks like its crashing before any graphics part has been reached. Are you using sync logging?

**Comment by voguelike** [comment]
new build is throwing the same unhandled exception but this time before i even reach the main menu

here's the new log with validation layers enabled

[shad_log.txt](https://github.com/user-attachments/files/16805224/shad_log.txt)

**Comment by ChronoRPG** [comment]
This is the log with syncronization validation enable
[shad_log.txt](https://github.com/user-attachments/files/16805248/shad_log.txt)

**Comment by voguelike** [comment]
interesting, so the newest build now let's me attempt to load back into the game but it never gets to rendering any part of the game.
when i try to load into the game either from continuing or making a new character, i get the loading screen then during the loading screen a split second of audio makes it out then it fades into a black screen and eventually crashes without any critical errors.
[shad_log.txt](https://github.com/user-attachments/files/16805771/shad_log.txt)

**Comment by voguelike** [comment]
seems inconsistent too. i tried again without sound, and sfx and this time i got 
`[Debug] <Critical> vk_scheduler.cpp:SubmitExecution:202: Unreachable code!
Device lost during submit: vk::Queue::submit: ErrorDeviceLost`

i also tried without gparams and libSceDiscMap for posterity but i got the same crash
[shad_log.txt](https://github.com/user-attachments/files/16805893/shad_log.txt)

**Comment by voguelike** [comment]
i know these aren't bb-hack builds but i tried the last two main builds ( [6bf42aa](https://github.com/shadps4-emu/shadPS4/commit/6bf42aa9859c6af758190f23c08d05f1a96ad210) and [cf706f8](https://github.com/shadps4-emu/shadPS4/commit/cf706f8cc7fb2e1606182b676ac50510211ec88b) ) and i found that both of them crash if sfx are in the game. 

without sfx though, i can at least get into the game but i can only see the hud, the rest is either gray screen or black screen depending on if gparams and libSceDiscMap is in or not.

here's the log that shows the crash with sfx 
[sfx;enabled - shad_log.txt](https://github.com/user-attachments/files/16808044/sfx.enabled.-.shad_log.txt)

and here's the log where i can get in the game but can only see the hud with the rest being a gray/black
[shad_log.txt](https://github.com/user-attachments/files/16808047/shad_log.txt)

**Comment by ChronoRPG** [comment]
For me get fix the problem, now i can into the game very well, but when i into the game this going to 60 fps and then when touch the keyboard the fps down brutality, and is unplayable

i feel how if had  a desyncronisation betwen the video and the input keyboard.

**Comment by Drigtime** [comment]
It works for me, I can access in game, my specs are
* CPU : AMD Ryzen 5 5600
* GPU : AMD Radeon RX 6700 XT
  * Driver Version : 24.10.37.04-240823a-407010C-AMD-Software-Adrenalin-Edition
  * Vulkan API Version : 1.3.287
  * Vulkan Driver Version : 2.0.310

What I did was
* Applied the patchs (dont know if it really affect the out come)
  * Disabled chromatic aberration
  * Disable motion blur
* Removed the recommended files in **drawparam**
* Removed files in **sfx**
* Removed the recommended files in **sound**
* Did not include **libSceDiscMap**
* Applied the mod [Bloodborne FPS Boost (and other fixes)
](https://www.nexusmods.com/bloodborne/mods/27?tab=description)

**Comment by voguelike** [comment]
> It works for me, I can access in game, my specs are
> 
> * CPU : AMD Ryzen 5 5600
> * GPU : AMD Radeon RX 6700 XT
>   
>   * Driver Version : 24.10.37.04-240823a-407010C-AMD-Software-Adrenalin-Edition
>   * Vulkan API Version : 1.3.287
>   * Vulkan Driver Version : 2.0.310
> 
> What I did was
> 
> * Applied the patchs (dont know if it really affect the out come)
>   
>   * Disabled chromatic aberration
>   * Disable motion blur
> * Removed the recommended files in **drawparam**
> * Removed files in **sfx**
> * Removed the recommended files in **sound**
> * Did not include **libSceDiscMap**
> * Applied the mod [Bloodborne FPS Boost (and other fixes)
>   ](https://www.nexusmods.com/bloodborne/mods/27?tab=description)

are you using this exact build?
https://github.com/shadps4-emu/shadPS4/actions/runs/10621808609

**Comment by Drigtime** [comment]
> are you using this exact build? https://github.com/shadps4-emu/shadPS4/actions/runs/10621808609

Yes, I'm not saying that it never crash, but I would say 2 out of 3 time I could launch a new game or load a save.

[shad_log - worked.txt](https://github.com/user-attachments/files/16810302/shad_log.-.worked.txt)

**Comment by voguelike** [comment]
yes you are right. i started the installation from scratch to remove all confounding variables and i got it to work by removing **libSceDiscMap**, the recommended files in **drawparam** as well as installing the **bloodborne fps boost** mod and now i can get into the game. 

yesterday i was able to successfully play without crashing using [(main bb5)](https://github.com/kotn3l/shadPS4/actions/runs/10583347853) while keeping all **drawparam** files and the **libSceDiscMap** sys_module in place and now i'm unable to on this build. however, that is a fork of this repo so this kind of variation is to be expected.

**Comment by hgh32** [comment]
I also encountered a crash, but I am using an Intel GPU
`[Debug] <Critical> vk_compute_pipeline.cpp:operator():249: Assertion Failed!`
[shad_log.txt](https://github.com/user-attachments/files/16815639/shad_log.txt)

**Comment by Drigtime** [comment]
So I also did a fresh install, this time the only thing I did was to remove the **sfx**, I still have the **drawparam**, the **sound** and the **libSceDiscMap** and I could load a save.
But just moving the camera or making a few steps would crash the game.

[shad_log.txt](https://github.com/user-attachments/files/16816833/shad_log.txt)

**Comment by Hermiten** [comment]
The first issue is fixed, I'm closing it.
