### ISSUE TITLE
Crash after opening any game on AMD with no log

### ISSUE THREAD

**Issue by SHlSHlO** [shadps4-emu/shadPS4#653]
Hello dear shadPS4 team,

as the title says its crashing on after starting any game. I saw a few other issues like VK 1.3 is minimum but thats not the issue here. The emulator just closes instantly with no error and no log. Yes, there is no log, even not in "user/log", which is very weird but thankfully the console/log is always visible while the emulator is running and its quite interesting since there is also no error I would recognize. And i cant open the controller settings, nothing happens if I click on it.
shadPS4 error![image](https://github.com/user-attachments/assets/80be8bd0-80a6-495f-a32e-8ac1b9b79c84)

I tried the official release and this one https://github.com/shadps4-emu/shadPS4/actions/runs/10605355127 and both got the same issues.

My PC specs:

CPU: Ryzen 5 3600XT
RAM: 16GB DDR4 3600MHz
GPU: AMD Radeon Vega 64 (driver version 23.9.3, quite old but since then they stopped making new updates for older cards like mine but I had no issue with running new modern AAA games like Ghost of Tsushima or any UE5 game)
Windows: W11 23H2 22631.2361 (I used a custom made .iso to debloat windows and I never do updates since they dont do anything but I installed all drivers manually from my motherboards support page)
Sound card: Creative SoundBlaster Z and yes, I'm using a sound card for max sound fidelity and to push 600 Ohm headphones but I only mentioned this because at the end you never know if this is maybe an issue for the emulator.

And of course I also played many other PS3, PS2, Wii and Switch games on their respective emulators with zero issues and this in 4K30/60 fps.

And thanks for reading my issue and I'd appreciate any help on this.

**Comment by StevenMiller123** [comment]
Update your graphics driver, there are many newer versions for your GPU.

**Comment by Neysu** [comment]
Hey were you able to do anything i'm getting the same issue :|

**Comment by h00kd** [comment]
same issue right here :/

**Comment by henoch131415** [comment]
same after install windows 11

**Comment by DefaltBR** [comment]
AMD hardware doesn't seem to support a texture format that is used... D24_UNORM_S8_UINT #775

**Comment by Neysu** [comment]
> AMD hardware doesn't seem to support a texture format that is used... D24_UNORM_S8_UINT #775

hmm it's nice to know do you know if there is any hope for us AMD user ? (and it does seems weird knowing that console hardware on wich Bloodborn was released are using AMD based hardware or it's a probleme from the emulator)

**Comment by DefaltBR** [comment]
> hmm it's nice to know do you know if there is any hope for us AMD user ? (and it does seems weird knowing that console hardware on wich Bloodborn was released are using AMD based hardware or it's a probleme from the emulator)

I was looking through the issues here in GitHub and found some guys who made it work fine on AMD GPU... Apparently there are some files we can remove/patch in the game files for it to work (dvdroot_ps4>param>drawparam). However, I don't know which files =/

**Comment by 0xBA5E64** [comment]
Adding my own experience here as an AMD (Ryzen 9 7950X, RX 7900 XTX) Linux (Arch, KDE) user whose also trying to get BB running.

> Apparently there are some files we can remove/patch in the game files for it to work (dvdroot_ps4>param>drawparam). **However, I don't know which files =/**

@DefaltBR I believe this workaround is the same one mentioned in the widely circulated [ShadPS4 Bloodborne Quickstart](https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit)-document, which in the troubleshooting section ("Fix black/grey screen when loading into the game") instructs the user to:
> Move all files in `ShadPS4/games/CUSAXXXXX/dvdroot_ps4/param/drawparam` to a separate folder except these: `default.gparam.dcx` and `default_drawparam.gparambnd.dcx`.

Which, at least from my own experience changes nothing, running on my own build from the [AUR](https://aur.archlinux.org/packages/shadps4-git) on the latest mainline commit as of the time of writing (3a65052b8e28fb5cc2c94b2ac0c14e37e9d1b0de)

With MangoHUD set up on my system as well, I can see that the game window is indeed "rendering" at approximately 61-60 fps, even if nothing is showing up. When I try to close it, shadps4 freezes, and takes a good few seconds to close down.

Logs: [`shadps4.log`](https://github.com/user-attachments/files/16948237/shadps4.log)
