### ISSUE TITLE
game crashes along with emulator on bloodborne before posting any window

### ISSUE THREAD

**Issue by kxtaaa** [shadps4-emu/shadPS4#660]
specs
I3-12100F
RTX 3060TI
32G DDR4 RAM

no matter what i do, my game keeps crashing on launch along with the emulator. there is no error message being left, id like to imagine this is a hardware compatibility issue but honestly i hope im wrong 
![image](https://github.com/user-attachments/assets/371e5657-3b3d-458c-9f75-c2143515366f)
this is what i see before a crash

**Comment by Hermiten** [comment]
You can ask help on discord
There is not enough information on this issue, I close it
