### ISSUE TITLE
Fullscreen switching

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#661]
I encountered with weird bug with fullscreen switching by F11 button. Image just stucked, you can hear sound but frame is same like it was when I tried to switch to fullscreen.
Here is a video - https://youtu.be/_ejNDI65cCU
Tested with fullscreen = true, fullscreen works, but when you trying to switch to windowed mode - same thing, frame is freezing.
Can it be a NVIDIA bug? I guess it was tested before merge, but not with all hardware?

**Comment by yaya54840** [comment]
hello
same for me I have an AMD graphics card

**Comment by gandalfthewhite19890404** [comment]
Closed as solved now
