### ISSUE TITLE
Regression after PR551 (video_core: re-enable culling)

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#662]
https://github.com/shadps4-emu/shadPS4/commit/8192eaa668d6a1ba4b70dd3be01fbf6378ea136e cause graphics issues in some games, i.e. Worms W.M.D.

Before
![image](https://github.com/user-attachments/assets/61dc8508-b797-4ee2-8451-31239769d22d)

After
![image](https://github.com/user-attachments/assets/9a06455f-5fec-4c7a-9c97-034e3ccff689)

**Comment by Hermiten** [comment]
This is fixed by this PR https://github.com/shadps4-emu/shadPS4/pull/831
