### ISSUE TITLE
[Feature request] Intergrate ATRAC9 Codec

### ISSUE THREAD

**Issue by alexbogun** [shadps4-emu/shadPS4#664]
In the example of Bloodborne, the emulator can already play all sounds stored in .mp3 format (packed in .fsb) but cannot process .at9 files (ATRAC9). Maybe this library can help: https://github.com/Thealexbarney/LibAtrac9/tree/master

**Comment by bigol83** [comment]
Resident Evil Hd Remaster (CUSA01067) uses at9 too, for both fmvs audio and ingame cutscenes.

**Comment by alexbogun** [comment]
Interesting, so, at9 generally works, but not in Bloodborne. Maybe they are encrypted in BB? Any idea what could be different there?

**Comment by georgemoralis** [comment]
at9 is using ajm library to play them  , so adding it doesn't help , need to implemented ajm library too. Currently there is one dev working on this

**Comment by bigol83** [comment]
> Interesting, so, at9 generally works, but not in Bloodborne. Maybe they are encrypted in BB? Any idea what could be different there?

Nope, it doesn't work on Resident Evil either in shadps4 right now. I know it uses at9 for fmvs and cutscenes because in game files there are lots of at9 files that i decrypted with a tool to confirm they are the audio tracks of ingame events and fmvs.

**Comment by efigr** [comment]
> > Interesting, so, at9 generally works, but not in Bloodborne. Maybe they are encrypted in BB? Any idea what could be different there?
> 
> Nope, it doesn't work on Resident Evil either in shadps4 right now. I know it uses at9 for fmvs and cutscenes because in game files there are lots of at9 files that i decrypted with a tool to confirm they are the audio tracks of ingame events and fmvs.

Can confirm, Resident Evil 5 (CUSA04284) also uses at9 files.

**Comment by Hermiten** [comment]
I'm closing the issue because it's not planned. They have to implement AJM for this.
