### ISSUE TITLE
[CUSA03173] Bloodborne infinite health cheat doesn't work

### ISSUE THREAD

**Issue by TedMosly** [shadps4-emu/shadPS4#673]
[CUSA03173] Bloodborne " infinite health " cheat doesn't work, all other cheat work fine.

**Comment by DanielSvoboda** [comment]
Look what's written there!

We're not the ones doing this, so close this issue.

![image](https://github.com/user-attachments/assets/0026d8bf-f4d2-4f4e-81b6-7dd682738864)

**Comment by TedMosly** [comment]
No, because i tested infinite health on my ps4 and work. Also other cheats works fine on the emulator.

**Comment by DanielSvoboda** [comment]
If it works on your PS4 and not on the emulator, it could be several things, for example you may be using a modified build, but I sent you your .log file so I can check.

**Comment by TedMosly** [comment]
[shad_log.txt](https://github.com/user-attachments/files/16820826/shad_log.txt)

**Comment by DanielSvoboda** [comment]
It seems to be being applied correctly, I analyzed the applied cheats and what is in your log, the information is the same, now the reason why it is not working, I do not know, and since I cannot do tests, we just have to wait :)

**Comment by CrazyBloo** [comment]
I took a quick look at the health cheat and couldnt find a reason it wouldnt work compared to the other cheats. I will take a closer look in a few days once I finish libRtc. Worst case scenario I will just try to make a new infinite health cheat and add it to the shad ps4 cheat repo

**Comment by TedMosly** [comment]
So, thanks to @CrazyBloo \ Pino, he have fixed the god mode. Now work on the emulator: 

![image](https://github.com/user-attachments/assets/50928d3d-4da5-43ad-b6ea-88ce21fe508d)

I attach the fixed .json cheat for BB
[CUSA03173_01.09_shadPS4.json](https://github.com/user-attachments/files/16837011/CUSA03173_01.09_shadPS4.json)

**Comment by TedMosly** [comment]
Infinite Health Cheat now work after the fix.

**Comment by TedMosly** [comment]
I reopen the issue because this is a partial workaround, the grab attacks can still kill you

**Comment by CrazyBloo** [comment]
the cheat file still needs some work, not all of those addresses are necessary to be patched i was just throwing in a bunch i found from cheat engine, i will try to fix the grab attacks and cleanup the cheat file later, for now i am back to working on libRtc

**Comment by gmendezm** [comment]
> Infinite Health Cheat now work after the fix.

the unlimmited health works but you can't walk

**Comment by Hermiten** [comment]
This is not related to shadps4 but to the cheats so I close it
