### ISSUE TITLE
7900XT so much [Lib.Net] <Error>net.cpp:sceNetEpollCreate:552: (STUBBED) called

### ISSUE THREAD

**Issue by WalkFly** [shadps4-emu/shadPS4#676]
CPU: 13600KF
GPU: 
GPU DRIVER: 24.8.1

Crash after creating a character at the loading screen
thanks very much！

error：
[Lib.Net] <Error> net.cpp:sceNetPoolCreate:804: (DUMMY) name = ResolveDomainName size = 4096 flags = 0 
[Lib.Net] <Error> net.cpp:sceNetResolverCreate:865: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetResolverStartAton:880: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetResolverDestroy:870: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetPoolDestroy:809: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetEpollCreate:552: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetEpollControl:547: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetSetsockopt:945: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetGetsockopt:687: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetAccept:62: (STUBBED) called
[Lib.Net] <Error> net.cpp:sceNetGetsockname:682: (STUBBED) called

[shad_log.txt](https://github.com/user-attachments/files/16821150/shad_log.txt)

**Comment by WalkFly** [comment]
shadps4：v2.0.1 wip 6080066

**Comment by riverzhou** [comment]
Same problem.

**Comment by kusti420** [comment]
same thing when trying to run driveclub
