### ISSUE TITLE
[CUSA07010] Sonic Mania does not work on Linux

### ISSUE THREAD

**Issue by chaitan3** [shadps4-emu/shadPS4#682]
Using latest main branch, Sonic mania does not boot. I tested the same game on Windows and it works quite well. Below is the log on a self compiled build on Archlinux

[output.log](https://github.com/user-attachments/files/16822832/output.log)

**Comment by abouvier** [comment]
What did you change? Your git source tree is dirty.

**Comment by chaitan3** [comment]
Some submodules were not updated in git. After updating them here is the log
[shad_log.txt](https://github.com/user-attachments/files/16824509/shad_log.txt)

**Comment by chaitan3** [comment]
Running gdb gives me the following error (also tried the nightly appimage and have the same problem)

Thread 22 "GAME_MainThread" received signal SIGSEGV, Segmentation fault. 

Using the bb-hacks appimage for Bloodborne also has the same error message as above inside gdb

**Comment by Random06457** [comment]
I don't have any issue on linux (NixOS). The game does segfault but as long as I don't attach a debugger, it recovers from it just fine for me.

**Comment by h16033** [comment]
> I don't have any issue on linux (NixOS). The game does segfault but as long as I don't attach a debugger, it recovers from it just fine for me.

Wayland or x11

**Comment by chaitan3** [comment]
Wayland. I tried running shadps4 using gamescope inside wayland and shockingly it is working. Seems to be a wayland specific issue
