### ISSUE TITLE
[CUSA03173] Bloodborne freezes on death / warping

### ISSUE THREAD

**Issue by Julioevm** [shadps4-emu/shadPS4#687]
Hey there,

I've been following the development and testing different builds. The game gets in-game and as of current builds ([bb-hacks](https://github.com/shadps4-emu/shadPS4/actions/runs/10640128556)) also with this [build  ](https://github.com/rafael-57/bb-hacks-pino/actions/runs/10640780519)its quite playable. However, theres an issue that keeps happening consistently. Everytime I die, or try to warp to the hunters dream the loading screen freezes. It seems to be always in the same moment, with a list of '[Core.Linker] <Error> linker.cpp:InitTlsForThread:358: TLS user malloc called, using std::malloc' errors in the log. 

I have to kill the process, it doesn't really crash. And curiously, I can warp from hunters dream to the Yarnham after the hunter first goes to the hunters dream.

I have both AMD cpu and gpu: RX 6650 XT and Ryzen 7 7800X3D.

![image](https://github.com/user-attachments/assets/c4b67878-1b48-439b-b756-947d02020213)
![image](https://github.com/user-attachments/assets/5daa54ac-aa2c-4118-9e7d-663176c555fc)
Logs: 
[shad_log.txt](https://github.com/user-attachments/files/16824448/shad_log.txt)

**Comment by voguelike** [comment]
just here to corroborate the report. regardless build or permutations of mods, game files, and configurations, dying or warping causes the game to freeze until the process is manually aborted. 

i'm also running amd everything (5700x3d, 6750xt)

**Comment by jerseydevil1box1** [comment]
im also getting crash on warp but with AMD Ryzen 7 and NIVIDIA Geforce RTX 2060

**Comment by MaxStive** [comment]
I am also get this freeze but on AMD ryzen 7 and Nvidia Geforce RTX 3060ti, maybe, this freeze bound with Ryzen 7

**Comment by AnimatedG** [comment]
Same problem here with AMD ryzen 7 1700x + Gtx 1080ti

**Comment by ghost** [comment]
same happens for me on Ryzen 7 3060ti

**Comment by Ishikudeska** [comment]
anytime you warp/die it freezes and crashes. it's due to:
`[Debug] <Critical> liverpool.cpp:ProcessGraphics:180: Unreachable code! invalid PM4 type 0`
So it isn't your hardware. It's a code-based issue (someone please correct me if I'm wrong)

**Comment by Foul-Tarnished** [comment]
Use this build instead
https://github.com/rafael-57/bb-hacks-pino/actions/workflows/windows-qt.yml

**Comment by voguelike** [comment]
> Use this build instead https://github.com/rafael-57/bb-hacks-pino/actions/workflows/windows-qt.yml

this only helps if your issue is a crash. if you would pay attention to the title of this issue you would see that this is about a freeze on death/warp not a crash which that build unfortunately does not fix. at least not for me.

**Comment by Foul-Tarnished** [comment]
ah well this is a memory corruption or race condition or some more complex
issue.
Improving accuracy and fixing the emu in general should hopefuly solve this

**Comment by rafael-57** [comment]
I've collected log + call stack, I don't think it's much useful because I don't know where to put breakpoints for this
[bb_warp_hang.txt](https://github.com/user-attachments/files/16829396/bb_warp_hang.txt)

**Comment by vigor-c** [comment]
I also had the freeze on death and couldn't make it work with the bb-hacks build. But with this other one it works perfectly and I actually get more fps: https://github.com/kotn3l/shadPS4/actions/runs/10583347853.

**Comment by Julioevm** [comment]
> I also had the freeze on death and couldn't make it work with the bb-hacks build. But with this other one it works perfectly and I actually get more fps: https://github.com/kotn3l/shadPS4/actions/runs/10583347853.

And do you have the issue too with newer builds of that user? I have the issue with bb-8, maybe I can try again with bb-5 and check...

**Comment by vigor-c** [comment]
> > I also had the freeze on death and couldn't make it work with the bb-hacks build. But with this other one it works perfectly and I actually get more fps: https://github.com/kotn3l/shadPS4/actions/runs/10583347853.
> 
> And do you have the issue too with newer builds of that user? I have the issue with bb-8, maybe I can try again with bb-5 and check...

I just tried and it works fine with bb-8. Have you went through this guide: https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit ?

I've also seen that people suggest using this driver version:
https://www.amd.com/en/resources/support-articles/release-notes/RN-RAD-WIN-AFMF2-TECH-Preview.html

Another person had it working with the 24.5.1 version.

I also used this mod to add working sounds: https://www.nexusmods.com/bloodborne/mods/34

**Comment by Julioevm** [comment]
> > > I also had the freeze on death and couldn't make it work with the bb-hacks build. But with this other one it works perfectly and I actually get more fps: https://github.com/kotn3l/shadPS4/actions/runs/10583347853.
> > 
> > 
> > And do you have the issue too with newer builds of that user? I have the issue with bb-8, maybe I can try again with bb-5 and check...
> 
> I just tried and it works fine with bb-8. Have you went through this guide: https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit ?
> 
> I've also seen that people suggest using this driver version: https://www.amd.com/en/resources/support-articles/release-notes/RN-RAD-WIN-AFMF2-TECH-Preview.html
> 
> Another person had it working with the 24.5.1 version.
> 
> I also used this mod to add working sounds: https://www.nexusmods.com/bloodborne/mods/34

Yes I've tried that, except for those specific driver versions. Might be worth a shot. Thanks.

**Comment by adjonesey** [comment]
I caught this issue with a debugger attached today - it looks like a deadlock. The game spawns a number of threads while reloading a level (CSCloth among others) and they will randomly hang waiting for mutexes to unlock 

![image](https://github.com/user-attachments/assets/05d8ecd1-09e5-493b-a836-8d5bb784b734)

**Comment by Julioevm** [comment]
Finally not having issues on death or warph with this build: https://github.com/Foul-Tarnished/shadPS4/actions/runs/10753285567

**Comment by Foul-Tarnished** [comment]
Yep this build fully fix the random deadlock during loading screen

**Comment by adjonesey** [comment]
The workaround being used for this in hack builds forces reuse of the existing thread pool threads - it's not something we can merge into main. The root cause of the issue appears to be a missed cleanup when the threads are exiting.

**Comment by adjonesey** [comment]
This issue should now be resolved in main

**Comment by rafael-57** [comment]
can be safely closed, fixed some days ago by #855 
@raphaelthegreat
