### ISSUE TITLE
when start game system is going dead and emulator crashed 

### ISSUE THREAD

**Issue by Senorkashy470** [shadps4-emu/shadPS4#706]
when start game system is going dead and emulator crashed 
core i5 12400f
16g ram
rtx 3070 8g
but game when lunch (in game tips ) crashed emulator with this error
![Screenshot 2024-09-01 012608](https://github.com/user-attachments/assets/abfb3bde-a091-41e0-82ef-737e6f857ea4)

**Comment by Senorkashy470** [comment]
affter change some setting
![Uploading Screenshot 2024-09-01 154217.png…]()

**Comment by Senorkashy470** [comment]
affter change some setting

![Screenshot 2024-09-01 154217](https://github.com/user-attachments/assets/89ba875d-e68a-4f29-956f-9119ac8c4300)

**Comment by bastxness** [comment]
have you had any luck with the vector memory problem? I have the same thing rn also using a 3070

**Comment by Hermiten** [comment]
I close this one because we already have this error reported here https://github.com/shadps4-emu/shadPS4/issues/498
