### ISSUE TITLE
Incorrect command list sent with copyGPUBuffers

### ISSUE THREAD

**Issue by Ruahh** [shadps4-emu/shadPS4#707]
CUSA03745 - The Last Guardian (v1.00)
Crashing with opcode errors for implemented opcodes when `copyGPUBuffers = true` in config.

```
[Debug] <Critical> liverpool.cpp:ProcessGraphics:526: Unreachable code!
Unknown PM4 type 3 opcode 0x81 with count 33
```

And when `WriteConstRam` opcode is copied to ProcessGraphics, error switches to;
```
[Debug] <Critical> liverpool.cpp:ProcessGraphics:532: Unreachable code!
Unknown PM4 type 3 opcode 0x88 with count 1
```

Log for unedited build of main branch:
[shad_log.txt](https://github.com/user-attachments/files/16828900/shad_log.txt)

**Comment by polybiusproxy** [comment]
Possible bug with `Liverpool::CopyCmdBuffers`.
On \`The Last Guardian\`, by enabling the `copyGPUBuffers` option, the PM4 packets from the CCB get sent to the DCB instead, causing `Unknown PM4 type 3 opcode` unreachables to appear.

**Comment by Exhigh** [comment]
check if #876 fixes this reported issue.

**Comment by Hermiten** [comment]
No update since 3 weeks but seem's to be fixed as I can see on the log here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/326
