### ISSUE TITLE
when I click download patches nothing happens and I get a error when I click save 

### ISSUE THREAD

**Issue by noahs21fg** [shadps4-emu/shadPS4#709]
I have version 1.09 and sys modules [
![Cheats _ Patches 8_31_2024 10_28_12 PM](https://github.com/user-attachments/assets/2b60c94a-89aa-47a3-b1e2-6121669d96b9)
](url)

**Comment by DrShadow34** [comment]
![image](https://github.com/user-attachments/assets/6301c886-10e6-421d-b1b3-0c423fa4da6d)
On arch linux with current shadps4-git, version 0.2.0.r259.g101aeb92-1, download button works (files being downloaded), but saving isn't possible, cause no option being shown to chose from, so "no option chosen" dialog appears. 
It's looks like UI\folder scanning\parsing bug.

**Comment by JamesMaloney** [comment]
Happens on Windows 11 as well, version "shadps4-win64-qt-2024-09-02-889d8c8"  bb-hacks. Same as described above.

**Comment by DanielSvoboda** [comment]
The download on Linux was fixed today.
The save button is to save the choices of the downloaded patches, but you should note one very important thing, there are no patches for the specific version of the game, try updating this game, because there is no error happening now.

**Comment by JamesMaloney** [comment]
> The download on Linux was fixed today.
> 
> The save button is to save the choices of the downloaded patches, but you should note one very important thing, there are no patches for the specific version of the game, try updating this game, because there is no error happening now.

Sorry for the misunderstanding, the error was due to the game being 1.0 instead of latest version. You can close the ticket now

**Comment by DanielSvoboda** [comment]
@noahs21fg As I mentioned, the download on Linux has been fixed. You could test it by downloading the latest version and trying to download it again. If everything is ok, you can now close the issue.
