### ISSUE TITLE
[CUSA 02411]Kung Fu Panda: Showdown of Legendary Legends doesn't boot anymore (ShadPS4 0.2.0 official)

### ISSUE THREAD

**Issue by tomnic79** [shadps4-emu/shadPS4#711]
Hi everybody, I'm trying to play Kung Fu Panda: Showdown of Legendary Legends as it says it works in ShadPS4 0.1.1 WIP but I cannot get it even to boot with the official 0.2.0 release in Windows.

Vulkan version issues or a regression? I'm using a Ryzen 9 5950x with 64Gb of RAM and an nVidia RTX 3070 8Gb driver version 560.70

**Comment by Hermiten** [comment]
I'm closing this one. No log, no updates. I didn't find it on the game compatiblity so you can report here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues With the release 0.3
