### ISSUE TITLE
Bloodborn crashes after character creation with Critical vector_memoy error

### ISSUE THREAD

**Issue by LowH1t** [shadps4-emu/shadPS4#713]
CPU: Ryzen 5 5600X
RAM: 16gb
GPU: RX 6600 8gb

<img width="672" alt="Screenshot 2024-09-01 181112" src="https://github.com/user-attachments/assets/c92e5c31-7031-4900-874d-9e2e30a55102">

**Comment by mattmorganpdx** [comment]
I have the same issue with exactly the same log output.
CPU: 12th Gen Intel(R) Core(TM) i9-12900F, 2400 Mhz, 16 Core(s), 24 Logical Processor(s)
RAM: 32gb
GPU: NVIDIA GeForce RTX 3080 Ti

**Comment by Senorkashy470** [comment]
Me to
I have this issue 

Core i5 1240f
Rtx 3070
Ram16

**Comment by takeshineale128** [comment]
same here

intel core i5 10500
gtx 1660
16GB RAM

**Comment by kutulhu** [comment]
Same issue, Bloodborne 1.09. Sysfiles installed.

**Comment by LuisCasillas2710** [comment]
I have the same problem with:
Ryzen 5600x
RTX 4070
32GB RAM

**Comment by bitcrushxd** [comment]
same problem
Intel Core i7 9700K
GTX 1060
32GB RAM

**Comment by Jaswanth-Vardireddy** [comment]
I have the exact same problem. Why is this happening to so many people?

**Comment by Matteo842** [comment]
same here

8700x3D
3060Ti
64gb ram

**Comment by peperoni1996** [comment]
RX 6700XT
R5 3600
32GB RAM
same error.

**Comment by S1rra** [comment]
happens right after character creation

NVIDIA 2060 SUPER
intel i7-9700K
32GB RAM

**Comment by MatterRacc** [comment]
Accept character, get into loading screen and then crash

Suprim X 3070 Ti
Ryzen 7 3800X
64GB RAM

**Comment by LuisCasillas2710** [comment]
It already renders me with the latest version.
https://github.com/shadps4-emu/shadPS4/actions/runs/10672465509

**Comment by dante42lk** [comment]
Same
7840hs
RTX4060
32gb RAM

**Comment by AltairJr85** [comment]
Same here
12400f
RX 6700 XT 12GB
48GB RAM

**Comment by ziadrrr** [comment]
same here
4070 ti
i7 13700k
32gb ram

**Comment by Dhrazer** [comment]
Same here
R7 7700
1070Ti
32GB RAM

**Comment by RayZ3R0** [comment]
Same here

CPU: Ryzen 5 5600G
RAM: 16gb
GPU: RX 6600 8gb

**Comment by Dhrazer** [comment]
> Same here R7 7700 1070Ti 32GB RAM

Re: Managed to make it run with https://github.com/LeDragoX/shadPS4/actions/workflows/windows-qt.yml

**Comment by ziadrrr** [comment]
![image](https://github.com/user-attachments/assets/2fd29c4b-988b-4d79-90b9-fb94ef94ba86)
can confirm it is working i was able to go in game for the first time with @Dhrazer link but i am not sure it might be using in older build of the code as the sound partially working and not all patches available for some reason
