### ISSUE TITLE
[Linux AppImage] Cannot download patches "Failed to retrieve HTML page" error

### ISSUE THREAD

**Issue by Aftonstjarna** [shadps4-emu/shadPS4#715]
![Screenshot_20240901_123603](https://github.com/user-attachments/assets/76c12ee3-0b8f-4486-91d2-56cb41f3588a)
Using latest bb_hacks build #1998

**Comment by Aftonstjarna** [comment]
Patch downloader works with the download all button but not the per game one in the screenshot above. 
The bulk cheat downloader says it's successful but no cheats populate and the per game downloader fails to find all repos.

**Comment by DanielSvoboda** [comment]
i made some changes, and generated this action, when you can, could you test to see if you can download the patches on Linux, please. I haven't sent this to MAIN yet, it's in my repository to test first

https://github.com/DanielSvoboda/shadPS4/actions/runs/10656763675

**Comment by DanielSvoboda** [comment]
It's not just you, some other people who use Linux are having this problem, thanks for reporting, I'm working on a solution...

edit- this is the real mistake
![image](https://github.com/user-attachments/assets/ac8bd1eb-f511-4a20-89a5-a1738b8c3bd6)

**Comment by DanielSvoboda** [comment]
I believe it is necessary to include OpenSSL for Linux, but I don't understand much about it, maybe I have to change the CI, any help is welcome here.

**Comment by DanielSvoboda** [comment]
I made [PR 738](https://github.com/shadps4-emu/shadPS4/pull/738), tested it with the build generated by the github action and now it can download the Cheats and Patches.

**Comment by DrShadow34** [comment]
> I made [PR 738](https://github.com/shadps4-emu/shadPS4/pull/738), tested it with the build generated by the github action and now it can download the Cheats and Patches.

Tested it right now on my arch, behaves similar to native now: downloads fine, but then no new (or any) patches\options appearing, hence save button doesn't do anything (showing error message, that no option is selected). If I understand correctly - that a regression, cause I found a video tutorial on "how to setup emulator", where folder parsing after download works fine.

**Comment by DanielSvoboda** [comment]
The save button is to save the marked checkboxes, but first you need to download the Patches to be able to select them. And the patches are downloaded and used according to the serial + version, there may not be patches for the combination I mentioned, I didn't understand what you want to do with the 'save' button, to test if you are actually downloading something look in the 'user/patches' folder if there is something in there it is working.

**Comment by DrShadow34** [comment]
> The save button is to save the marked checkboxes, but first you need to download the Patches to be able to select them. And the patches are downloaded and used according to the serial + version, there may not be patches for the combination I mentioned, I didn't understand what you want to do with the 'save' button, to test if you are actually downloading something look in the 'user/patches' folder if there is something in there it is working.

Maybe screenshot will explain better:
![image](https://github.com/user-attachments/assets/20481d79-c18a-4f9f-bd51-48737375535d)
As you can see, download succesfull, we have files for needed game, that match their serial, but window to chose patch to apply still empty, hence we can't use Save button, cause we can't select anything. 

I see this behavior in both AppImage and AUR version on my Arch. Current build that I test is: 0.2.0.r259.g101aeb92-1[

According to another report](https://github.com/shadps4-emu/shadPS4/issues/709#issuecomment-2325099897), Windows 11 have same behavior. 

Okay, I figured it out, it was actually pretty simple. My app version detected as 1.00, while downloaded patches are for 1.09. I think it still a UI issue, that we doesn't get notified about mismatched app version for downloaded patches.

**Comment by Zadeerade** [comment]
I'm getting the same on Windows 10

Renaming AppVer from 01.09 to 01.00 worked for me

**Comment by DanielSvoboda** [comment]
@DrShadow34 I have to add a new text for translation, so I'll take the opportunity to put a better explanation, that some patches were made only for specific versions

**Comment by DanielSvoboda** [comment]
Okay, the download has been fixed. You can now close this issue.
I will make this improvement to the text later, to make it clearer.

**Comment by LazyClicks** [comment]
> Okay, the download has been fixed. You can now close this issue. I will make this improvement to the text later, to make it clearer.

im trying it rn with version 0.5.0 on windows 11 and im still getting that issue

**Comment by LazyClicks** [comment]
> > Okay, the download has been fixed. You can now close this issue. I will make this improvement to the text later, to make it clearer.
> 
> im trying it rn with version 0.5.0 on windows 11 and im still getting that issue

actually quite a weird thing happened, shadps4 from the website has the issue while the one from github doesn't for me

**Comment by DanielSvoboda** [comment]
> > > Okay, the download has been fixed. You can now close this issue. I will make this improvement to the text later, to make it clearer.
> > 
> > 
> > im trying it rn with version 0.5.0 on windows 11 and im still getting that issue
> 
> actually quite a weird thing happened, shadps4 from the website has the issue while the one from github doesn't for me

Are you sure it's the same error? Could you send a print? Which error are we talking about?
