### ISSUE TITLE
[Suggestion, Linux] Use XDG Desktop Portals for file pickers instead of the Qt file picker

### ISSUE THREAD

**Issue by retcinder** [shadps4-emu/shadPS4#718]
I've noticed whenever shadPS4 asks for a file from the user, it uses the Qt file picker which (imo) is not very nice to use and also looks out of place on my desktop.

The file picker from the portals are usually the underlying DE's file picker. For example, on KDE, it looks like this:
![image](https://github.com/user-attachments/assets/dce0c8d6-4757-483a-a6de-ff5de91805af)

**Comment by Ishikudeska** [comment]
Qt is what shadPS4 uses for GUI/file picker, so they'd have to completely redo that system to use XDG
