### ISSUE TITLE
Failed allocating buffer

### ISSUE THREAD

**Issue by Spiraxz** [shadps4-emu/shadPS4#721]
![Error](https://github.com/user-attachments/assets/2aa558ea-976b-49fb-aade-096ac3b8287c)

It crashed here at character selection screen
I have even allocated 8gb vram to vega 7 igpu
It worked well in intro scene but it crashed later at character selection screen

Specs :
16gb ram
vega 7 (8gb allocated)
amd ryzen 5 5500u
storage: 500gb ssd

**Comment by Blake64** [comment]
Hi, 
as you can see from the screenshot, the purple line says that you ran out of memory

follow the guide for bb: [bb guide](https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit)

extract of the guide:

RAM - Memory used by the Central Processing Unit (CPU)
At the moment, emulating BB is known to have severe memory leaks, meaning the game will inevitably crash. Thus it is recommended to have as much RAM and VRAM as possible. As long as other programs aren’t hogging up memory in the background, you might get away with using 16 GB, although 32 is recommended.
If you are running out of RAM, you can use a pagefile. Read about increasing your pagefile here: https://www.tomshardware.com/news/how-to-manage-virtual-memory-pagefile-windows-10,36929.html

VRAM - Memory used by the Graphics Processing Unit (GPU)
Some places in the game can suddenly use up a lot of VRAM, and can easily crash graphics cards with 8 Gigabytes of memory. Thus it is recommended to look at the ground if you notice a particular area is suddenly crashing your game, or to ensure your graphics card has plenty of memory, preferably at least 12 Gigabytes._

**Comment by Hermiten** [comment]
I close this one because we already have this error reported here https://github.com/shadps4-emu/shadPS4/issues/498
