### ISSUE TITLE
What is the actual minimum system requirements 

### ISSUE THREAD

**Issue by MadxXx2003** [shadps4-emu/shadPS4#725]
i was having crashes on my system if i do anything
so i tested different cpu architectures on the intel sde and it seems any system before broadwell just crashes if you try to do anything (trying to install a pkg or trying to run a game)
it's written in the requirements that it needs a quad core 6 threaded 2.5 ghz cpu
but what instruction set does it need I tried with hasswell but same issue 
same thing on the gpu side does it just require any vulkan 1.3 gpu or does it need some specific extensions to work
if it's helpful I am running a 1st gen xeon based on the westmare arch cpu (quad core 8 threads at 2.67 ghz) and an rx 480

**Comment by Aruto-san** [comment]
Same here on Xeon E5-2689 (Sandy Bridge), it has AVX but not AVX2. Tried SDE too, but no luck. Seems like nobody cares about processors this old anymore.

**Comment by polyneutron** [comment]
+, same on my i7 3770 (Ivy Bridge), sde didnt' help either. I'm not implying anything but does actual PS4 support avx2? Just curious, because I couldn't find a solid answer online, sadly.
Is it possible to build an avx (not avx2) compatible build of shadps4? Or create a patch for the current build, or something?

**Comment by polyneutron** [comment]
I don't want to sound impatient, but is it really that hard for emu devs to reply in a thread like this? You know, I'm not asking for 100% accurate list of supported hardware, even a short statement would do just fine.

**Comment by StevenMiller123** [comment]
It can be difficult for devs to spot real issues inbetween the flood of Bloodborne-related issues. The current requirements are a CPU with support for AVX2 instructions, and a modern GPU. Any GPU with 6+ GB of VRAM released in the last 8 years should work. Finally, you should have at least 16gb of ram.

**Comment by StevenMiller123** [comment]
Note that while these stated requirements differ from the ones stated on the readme, these are the ones frequently stated on the emulator's discord.

**Comment by polyneutron** [comment]
Thank you very much for the reply!
Are there any plans to support AVX (non-AVX2) capable CPUs some time in the future?

**Comment by StevenMiller123** [comment]
I don't think there are specific plans at the moment, but some of the ongoing work for ARM compatibility may make this change more feasible. I'm not too familiar with that area of code though, so I can't say for certain.

**Comment by polyneutron** [comment]
Roger that, thanks again! Good luck with further development!

**Comment by Hermiten** [comment]
You can have a look here: https://github.com/shadps4-emu/shadPS4/blob/main/documents/Quickstart/Quickstart.md
