### ISSUE TITLE
ShadPS4 instantly crashes without an Error Message

### ISSUE THREAD

**Issue by h00kd** [shadps4-emu/shadPS4#726]
I Just reinstalled Windows and tried to run BB again with the new patches but after I got everything set up the game and ShadPS4 instantly crash and I get no error message as you can see with the attachment. 
![image](https://github.com/user-attachments/assets/c8497971-687b-44d7-aef6-ddbfaa66b61a)

Was hoping anyone knew the issue or if I'm missing any piece of software necessary.

**Comment by pop555828** [comment]
I have the same problem here!!

**Comment by rmueller83** [comment]
Look into the Windows Even Viewer under "Windows Logs" / "Application".
For me it crashes in C:\WINDOWS\System32\ucrtbase.dll
My file has the version 10.0.22621.3593

**Comment by victorafs** [comment]
To solve this i delete/rename the user folder on the Shadps4 installation and the BB worked to me.
Before i tried a lot of versions of this program and no one worked for me.

**Comment by Hermiten** [comment]
duplicate https://github.com/shadps4-emu/shadPS4/issues/653

**Comment by GutsR27** [comment]
> To solve this i delete/rename the user folder on the Shadps4 installation and the BB worked to me. Before i tried a lot of versions of this program and no one worked for me.

sadly this solution did not work for me.. still closes without any error msg or anything.

**Comment by pop555828** [comment]
thnx I will try it
