### ISSUE TITLE
Emulator does not open

### ISSUE THREAD

**Issue by juliarscat** [shadps4-emu/shadPS4#730]
Hi all, I have as a problem as after game folder selection the emulator closes. I've tried downloading various QT versions, reinstalling C++ 2022, etc. It does not pass the command screen and immediately closes. Anyone could help here? Thanks for your time.

**Comment by juliarscat** [comment]
Nevermind, it was the graphics driver. Closing issue.

**Comment by JamallaBhanu** [comment]
> Nevermind, it was the graphics driver. Closing issue.

same for me can u tell me how to fix this problem
