### ISSUE TITLE
[Feature request] Add Visual C++ Redistributable check

### ISSUE THREAD

**Issue by alexbogun** [shadps4-emu/shadPS4#733]
Add a check whether VC++ redistributable is available on the system and if not give a message with a download link.

**Comment by polybiusproxy** [comment]
Closing as I don't believe this is possible, the emulator itself needs the VC++ runtime to operate, and if it's not installed, there's nothing we can do

**Comment by alexbogun** [comment]
@polybiusproxy: Plenty of programs check if VC++ is installed on the machine and if its not, display a message to a user. It is as simply as "try ... catch... " block in the beginning or just looking in the registry. But if you deem it not worth the hassle feel free to keep it closed
