### ISSUE TITLE
is steel crash aftter make charcter

### ISSUE THREAD

**Issue by Senorkashy470** [shadps4-emu/shadPS4#734]
is steel crash aftter make charcter
please fix this 
![Screenshot 2024-09-01 012608](https://github.com/user-attachments/assets/fd61b02f-e83f-40b5-bbf8-c8217a78ba57)
![Screenshot 2024-09-01 154217](https://github.com/user-attachments/assets/bf773046-aed9-4d37-a844-eb9e008df457)
![Screenshot 2024-09-02 144740](https://github.com/user-attachments/assets/b023bd57-7a3d-43e1-8924-25e962f1f0de)
![Screenshot 2024-09-02 144923](https://github.com/user-attachments/assets/bb089d30-40cd-481b-89af-62871f08109f)
 this all error i get

**Comment by Blake64** [comment]
Hi, 
as you can see "ErrorOutOfDeviceMemory" means that you ran out of RAM. 
follow the guide for bb: [bb guide](https://docs.google.com/document/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/edit) 

extract of the guide: 

RAM - Memory used by the Central Processing Unit (CPU)
At the moment, emulating BB is known to have severe memory leaks, meaning the game will inevitably crash. Thus it is recommended to have as much RAM and VRAM as possible. As long as other programs aren’t hogging up memory in the background, you might get away with using 16 GB, although 32 is recommended.
If you are running out of RAM, you can use a pagefile. Read about increasing your pagefile here: https://www.tomshardware.com/news/how-to-manage-virtual-memory-pagefile-windows-10,36929.html


VRAM - Memory used by the Graphics Processing Unit (GPU)
Some places in the game can suddenly use up a lot of VRAM, and can easily crash graphics cards with 8 Gigabytes of memory. Thus it is recommended to look at the ground if you notice a particular area is suddenly crashing your game, or to ensure your graphics card has plenty of memory, preferably at least 12 Gigabytes._

**Comment by Hermiten** [comment]
I close this one because we already have this error reported here https://github.com/shadps4-emu/shadPS4/issues/498
