### ISSUE TITLE
[macOS] Regression: Rosetta Error

### ISSUE THREAD

**Issue by shinra-electric** [shadps4-emu/shadPS4#735]
This is related to Issue #667. When that issue was fixed by PR #685 it exposed this issue. 

I opened this because I don't want to necropost on a closed issue. 

The following games will crash with a rosetta error. ~~It seems to have been introduced with PR #638.~~

Dead Cells - CUSA11253 (When entering the first level)
```
rosetta error: unexpectedly need to EmulateForward on a synchronous exception x86_rip=0x38670545502 arm_pc=0x481054039580 num_insts=3 inst_index=2 x86 instruction bytes: 0x5083236904201223365 0x11330223254244112
```

Dark Souls - CUSA08495 (When starting a new game)
```
rosetta error: unexpectedly need to EmulateForward on a synchronous exception x86_rip=0x38666814885 arm_pc=0x481062790024 num_insts=3 inst_index=2 x86 instruction bytes: 0x1296127535214623941 0x5192690247171377216
```

**Comment by rcaridade145** [comment]
https://github.com/golang/go/issues/42700 Golang seems to have it that issue also.

**Comment by squidbus** [comment]
This is not a regression from https://github.com/shadps4-emu/shadPS4/pull/638, I tried a build from the commit before and it has the same issue.

**Comment by squidbus** [comment]
As far as I can tell this starts with https://github.com/shadps4-emu/shadPS4/commit/cf706f8cc7fb2e1606182b676ac50510211ec88b

**Comment by squidbus** [comment]
Specifically, blocking texel buffers from stream buffer is causing this, possibly something to do with the exception handler logic for buffer tracking.

**Comment by squidbus** [comment]
I think this has stopped happening with some of the recent changes, could you check?

**Comment by shinra-electric** [comment]
It has stopped happening with Dead Cells, but it still happens with Dark Souls. 

It used to happen with the EU version of RDR (but not the US version, I'm told). But I'll have to reinstall that to check.

Edit: I tried out the EU version of RDR [CUSA36843] and it doesn't have the rosetta error anymore.

**Comment by squidbus** [comment]
This seems to be a bug in Rosetta 2 where store instructions that cross a page boundary don't fire page fault signals properly, causing problems with the buffer/texture caches. I have filed a feedback to Apple to try and get it fixed.

**Comment by Hermiten** [comment]
Do you have any feedback about that ?
Is it fixed here ?

**Comment by squidbus** [comment]
No, it is not fixed yet.

**Comment by Hermiten** [comment]
2 months since the last message, is it still revelant ?

**Comment by polybiusproxy** [comment]
I suppose so.

**Comment by shinra-electric** [comment]
Fixed for now, but these Rosetta errors tend to resurface. 
Closing....
