### ISSUE TITLE
Got An Error When Trying To Run ' Until Dawn ' 

### ISSUE THREAD

**Issue by Darkestangel69** [shadps4-emu/shadPS4#742]
I attached the log file, any help on this will be appreciated 

[shad_log.txt](https://github.com/user-attachments/files/16844004/shad_log.txt)

**Comment by DanielSvoboda** [comment]
It looks almost the same as what is done in this repository...
https://github.com/shadps4-emu/shadps4-game-compatibility

**Comment by Darkestangel69** [comment]
> It looks almost the same as what is done in this repository... https://github.com/shadps4-emu/shadps4-game-compatibility

Can you explain whats wrong?

**Comment by gorshco** [comment]
You should open/update an issue for the specific game in the https://github.com/shadps4-emu/shadps4-game-compatibility repo, and report your findings.

Edit:
There is an open issue for 'Until Dawn': https://github.com/shadps4-emu/shadps4-game-compatibility/issues/183

**Comment by Hermiten** [comment]
I'm closing it because it's a game report
