### ISSUE TITLE
No character visible at character creation screen & game crashes after intro cinematic

### ISSUE THREAD

**Issue by dante42lk** [shadps4-emu/shadPS4#752]
```
[Lib.Rtc] <Error> rtc.cpp:sceRtcGetCurrentClockLocalTime:80: (STUBBED) called
[Lib.Rtc] <Error> rtc.cpp:sceRtcGetTick:122: (STUBBED) called
[Lib.Rtc] <Error> rtc.cpp:sceRtcSetTick:191: (STUBBED) called
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondInit:661: name=NoName, result=0
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:79: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:389: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Render.Vulkan] <Info> vk_shader_cache.cpp:CompileModule:119: Compiling fs shader 0x2db65555
[Render.Vulkan] <Info> vk_shader_cache.cpp:CompileModule:119: Compiling vs shader 0x1635154c
[Debug] <Critical> vector_memory.cpp:operator():366: Assertion Failed!
Non immediate offset not supported
```

7840hs, 32gb ram, rtx 4060, (tried the integrated 780m, crashes with the same error)
Build version: shadps4-win64-qt-2024-09-03-3a41829

On the character creation screen the log is full of:

`[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:389: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)`

**Comment by Ishikudeska** [comment]
seems that `titled image: R32Sfloat` is our issue here

**Comment by gandalfthewhite19890404** [comment]
Close, pls

**Comment by dante42lk** [comment]
New releases now fail with a different message:
`[Lib.Pad] <Info> pad.cpp:scePadSetVibration:526: scePadSetVibration called handle = 1 data = 0 , 0
[Lib.Pad] <Info> pad.cpp:scePadSetVibration:526: scePadSetVibration called handle = 1 data = 0 , 0
[Lib.Rtc] <Error> rtc.cpp:sceRtcGetCurrentClockLocalTime:80: (STUBBED) called
[Lib.Rtc] <Error> rtc.cpp:sceRtcGetTick:122: (STUBBED) called
[Lib.Rtc] <Error> rtc.cpp:sceRtcSetTick:191: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:391: Unsupported tiled image: D32SfloatS8Uint (Depth_MacroTiled)
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:391: Unsupported tiled image: D32SfloatS8Uint (Depth_MacroTiled)`

**Comment by pavelbarabanov** [comment]
and why was it closed? I have the same problem(
