### ISSUE TITLE
Every time I open the emulator and try to run any game the emu crashes with no error messages 

### ISSUE THREAD

**Issue by pop555828** [shadps4-emu/shadPS4#754]
![Screenshot (58)](https://github.com/user-attachments/assets/7a536f96-5e34-46ae-b5e8-247a75703429)

**Comment by Valle9612** [comment]
Hi 
i had exactly the same error.
I fixed the problem reinstalling from scratch the Visual C++ Redistributable.
I'm not 100% sure but if you go to the Windows event viewer you should see in the report that the error is generated by the following module path: C:\Windows\SYSTEM32\MSVCP140.dll.
Maybe this will be usefull for other with the same issue.

**Comment by pop555828** [comment]
thnx it worked ...now I have this problem ......i installed all the patches
![Uploading Screenshot (59).png…]()

**Comment by Hermiten** [comment]
Closed because the first issue is completed
