### ISSUE TITLE
Shadps4 not working under wayland on arch linux

### ISSUE THREAD

**Issue by h16033** [shadps4-emu/shadPS4#758]
Hello everyone i have problem with shadps4 it’s didn’t want work on arch linux under wayland i have ryzen 3600 and rtx 2070super 32 ram but when log in with X11 its work what is the problem exactly??and I test it with cachyos and same problem

**Comment by chaitan3** [comment]
Can reproduce this on Nvidia 4070 Ti Super on KDE Wayland. Using gamescope inside wayland surprisingly works.

**Comment by enzi** [comment]
good thing you posted this because i thought it's just broken on my system. turns out it indeed does work when running with gamescope

**Comment by emuyia** [comment]
Doesn't seem to be working for me. I have a fedora 40 system with KDE wayland, Nvidia GTX 1080. Boots Bloodborne on X11 but not wayland - I get stuck on a black screen before reaching the main menu.

I tried launching with `gamescope --` and got the same result, but I don't know if I'm using that right. Same result on both the qt and sdl appimages and the cli executable.

**Comment by ImanolFotia** [comment]
Have you tried forcing XWayland?
`env -u WAYLAND_DISPLAY env XDG_SESSION_TYPE=x11 gamescope Shadps4-qt.AppImage`

**Comment by HermitsA** [comment]
Mainline builds have been broken on linux for a while.

**Comment by ImanolFotia** [comment]
The builds from this fork are working nicely, if you wanna run bloodborne
https://github.com/Foul-Tarnished/shadPS4

![Screenshot_20240906_025257](https://github.com/user-attachments/assets/89653c86-995a-459b-8742-bf19d5d95f21)

**Comment by luisnunmello** [comment]
> The builds from this fork are working nicely, if you wanna run bloodborne https://github.com/Foul-Tarnished/shadPS4
> 
> ![Screenshot_20240906_025257](https://private-user-images.githubusercontent.com/5194308/365049245-89653c86-995a-459b-8742-bf19d5d95f21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDQzNjIsIm5iZiI6MTcyNTYwNDA2MiwicGF0aCI6Ii81MTk0MzA4LzM2NTA0OTI0NS04OTY1M2M4Ni05OTVhLTQ1OWItODc0Mi1iZjE5ZDVkOTVmMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDYyNzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE5Yzg3MzEyNjAzMGE0MDhhZWNlNDBiOTc1MmRkMWE3NjJjNmY2YTg3MzFiYzMzYjZkMGRhNjYzNTQ0MTY4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c1AGDR895LdV7M5TUTrMTCkdinXggIRiqGHj1qhbWm4)

Yeah, that's because of a fix that was included in the past but not anymore in any other branch
![image](https://github.com/user-attachments/assets/d06c7e11-ddd3-46d9-8de4-4119cf320ca8)

Every branch i want to use with linux, i need to include this hack.
If you have problems running builds, i suggest building with this fix.

**Comment by ImanolFotia** [comment]
Nice!!
Thank you!

**Comment by emuyia** [comment]
> Have you tried forcing XWayland?
> env -u WAYLAND_DISPLAY env XDG_SESSION_TYPE=x11 gamescope Shadps4-qt.AppImage

This didn't work for me, same result.

> The builds from this fork are working nicely, if you wanna run bloodborne https://github.com/Foul-Tarnished/shadPS4

Can confirm this works for me, but only with gamescope:
```
gamescope ./Shadps4-qt.AppImage
```
For now I no longer have to switch to X11, thank you. I'll try building in future.

**Comment by chaitan3** [comment]
For folks who are looking for a patch they can apply on latest main branch to get Bloodborne running here it is:

```
diff --git a/src/core/libraries/kernel/thread_management.cpp b/src/core/libraries/kernel/thread_management.cpp
index 919afcb4..36574607 100644
--- a/src/core/libraries/kernel/thread_management.cpp
+++ b/src/core/libraries/kernel/thread_management.cpp
@@ -1065,7 +1065,16 @@ ScePthread PThreadPool::Create() {
         }
     }

+#ifdef _WIN64
     auto* ret = new PthreadInternal{};
+#else
+    // TODO: Linux specific hack
+    static u8* hint_address = reinterpret_cast<u8*>(0x7FFFFC000ULL);
+    auto* ret = reinterpret_cast<PthreadInternal*>(
+        mmap(hint_address, sizeof(PthreadInternal), PROT_READ | PROT_WRITE,
+             MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED, -1, 0));
+    hint_address += Common::AlignUp(sizeof(PthreadInternal), 4_KB);
+#endif
     ret->is_free = false;
     ret->is_detached = false;
     ret->is_almost_done = false;
```

**Comment by Caliel666** [comment]
is there any reason for this patch to not be implemented on main?

**Comment by ImanolFotia** [comment]
> is there any reason for this patch to not be implemented on main?

I think this is much of a hack to be included on main

**Comment by ngoquang2708** [comment]
Guys, please test this build
~~https://github.com/shadps4-emu/shadPS4/actions/runs/11127985710~~
~~https://github.com/shadps4-emu/shadPS4/actions/runs/11128877736~~
and report to https://github.com/shadps4-emu/shadPS4/pull/1184. Thanks.
