### ISSUE TITLE
Trying to install a game patch crashes the program

### ISSUE THREAD

**Issue by Eraea** [shadps4-emu/shadPS4#760]
Hi, I am trying to patch an PS Store exclusive game which was turned to a FPKG but its only on base version.
Scouring the web I was able to find a link for the only version patch the game had but when I try to apply this to the installed game it gets stuck in a not responding loop and if I interact with the window it crashes the program.
Then when I open the program again it says its on the new patch but I don't think any file was updated or extracted to the game folder

**Comment by Hermiten** [comment]
I close it because it's seem's that you try to patch a game with a program, we don't know which one and this is not followed up.
