### ISSUE TITLE
Possible Pr #575 Regression

### ISSUE THREAD

**Issue by hgh32** [shadps4-emu/shadPS4#765]
Bloodborne crashes on boot to grey screen:

`[Debug] <Critical> vk_compute_pipeline.cpp:operator():249: Assertion Failed!`

[shad_log.txt](https://github.com/user-attachments/files/16860226/shad_log.txt)

I think this may be a regression from f118dc7

On 833a366 the game reaches the character creation screen and then freezes:

`[Debug] <Critical> emit_spirv_context_get_set.cpp:EmitStoreBufferFormatF32xN:540: Unreachable code!
Invalid format for conversion: Format16_16_16_16`

[shad_log.txt](https://github.com/user-attachments/files/16860229/shad_log.txt)

**Comment by Hermiten** [comment]
I suggest you use the latest version and open a new ticket if necessary.

**Comment by hgh32** [comment]
> I suggest you use the latest version and open a new ticket if necessary.

This is a long standing unresolved issue, I'm pretty sure it's still there in the latest builds
This will trigger on devices using igpu, not just bloodborne
I've reported this to @raphaelthegreat
I'm not sure what you think, but I don't think there's any need to open a new issue

**Comment by Hermiten** [comment]
I Can open it again to track it

**Comment by Hermiten** [comment]
"I don't think this is relevant anymore, haven't seen this reported in 2 months"
I'm closing it, Thanks you
