### ISSUE TITLE
The game opens and gives me this screen ...I have installed all the patches

### ISSUE THREAD

**Issue by pop555828** [shadps4-emu/shadPS4#772]
![Screenshot (59)](https://github.com/user-attachments/assets/989a0e64-8f96-416e-b52a-1fbfeebc8c8d)

**Comment by vibudh007** [comment]
I have the same issue as well. Don't know how youtubers are getting it to work so well.

**Comment by Slug98** [comment]
Bandage fix: if you go to the where the game is installed and go to /ShadPS4/CUSA03173/dvdroot_ps4/param/drawparam

And delete every file except for "default.gparam.dcx" and "default_drawparam.parambnd.dcx" it will allow you to actually see.

Just make sure you make a backup of all the files before you delete them in case they implement a proper fix into the emulator later on.

**Comment by vibudh007** [comment]
@Slug98 That makes my game go black instead of white. I still can't see anything.

**Comment by Slug98** [comment]
@vibudh007 

Hmm, I was having that issue initially (black screen) after updating my shadps4 appimage it turned to white, that's when I learned that deleting the non default param files could actually let you see.

You could try changing the resolution to 1600x900 as that is what BB renders at on the ps4.

If you want to know how I learned about this it's from this youtube channel:

https://youtu.be/0DKfRoDwNzA?si=Maw0K8hFH_4mcGp9

I linked the specific video talking about your issue as well.

If you don't want to click the link you can search "Bloodborne PC had a big issue and I fixed it (ish)" It's a video by fromsoftserve
