### ISSUE TITLE
[Feature Request] Support for PlayLink Mobile App Integration

### ISSUE THREAD

**Issue by xGuTeK** [shadps4-emu/shadPS4#779]
Could you please add support for PlayLink games to allow playing via the PlayLink app on mobile devices?

I understand that it's not a priority at the moment, but it would be great if this feature could be supported in the future.

**Comment by Hermiten** [comment]
This is really not planned, I close it for now

**Comment by xrtxn** [comment]
I hope this will be reconsidered

**Comment by ElBread3** [comment]
Actually, if I recall correctly, libSceCompanion (the Playlink library) literally just opens a network and does some event management, will likely be trivial to add it once the net libraries are implemented.
