### ISSUE TITLE
[Feature Request] Hide cursor on idle

### ISSUE THREAD

**Issue by Foul-Tarnished** [shadps4-emu/shadPS4#786]
Hide mouse cursor when idle

**Comment by Hermiten** [comment]
Closed because little information and no follow-up

**Comment by Foul-Tarnished** [comment]
> Closed because little information and no follow-up

??? It's self explanatory...

The mouse cursor stay visible on the game window even when in fullscreen.

**Comment by polybiusproxy** [comment]
Fixed by https://github.com/shadps4-emu/shadPS4/pull/1211
