### ISSUE TITLE
Unable to install PKG on apple silicon

### ISSUE THREAD

**Issue by Rogeatic** [shadps4-emu/shadPS4#790]
I am unable to install my package in any recent builds, it all crashes when I try. Crash report is attached. It was Bloodborne of course...
[crash report M1 mac.txt](https://github.com/user-attachments/files/16884983/crash.report.M1.mac.txt)
Please tell me if I'm just an idiot and did something wrong.

**Comment by shinra-electric** [comment]
This should be fixed by #784

**Comment by mavethee** [comment]
Game is trying to install `game_data` on wrong dir, working on that with #784, but I'm screwed with uni, so my work is slow.

Workaround:
create `user` folder near executable.
move your data there.

It's not an issue with every game when it should affect any game, so thats even funnier.

**Comment by Rogeatic** [comment]
Thanks for the info, really impressive work you guys! Good luck with uni, I just finished recently.

**Comment by mavethee** [comment]
Forgot to mention, Bloodborne doesn't work so even if you will be able to install it or will be using `bb_hacks` branch.
It's calling for address range that is reserved on ARM Macs, if I'm up to date with the game news.

**Comment by mavethee** [comment]
Can be closed as of #809
