### ISSUE TITLE
Invalid device on startup

### ISSUE THREAD

**Issue by bdzerr** [shadps4-emu/shadPS4#793]
I have all perquisites, tried different builds and also building it myself and I must be missing something as i get the error below while trying to start the app,it happens after I select the install location for games,  could someone point out what I'm doing wrong?

ERROR:             vkDestroyFramebuffer: Invalid device [VUID-vkDestroyFramebuffer-device-parameter]

14900K
RTX 4090, Driver Ver: Latest 560.94

**Comment by bdzerr** [comment]
Further looking with event viewer shows the error in vulkan-1.dll, Ive tried reinstalling NV drivers, using the Vulkan installer standalone, neither has helped codes are:

Exception code: 0xc0000409
Fault offset: 0x00000000000b5345

**Comment by Hermiten** [comment]
I'm clsing it because little information and not followed up

**Comment by bdzerr** [comment]
Well the issue is still present, I was asking for help and gave every but of information i could what information is needed rather then closing it?

**Comment by Hermiten** [comment]
Maybe which platform and which version ?

**Comment by Devirex** [comment]
I had a similar issue with one layer blocking my device on windows. Run Powershell:

`$env:VK_LOADER_DEBUG="error,warn,layer"`
run software 

Output:
```
LAYER:             vkCreateInstance layer callstack setup to:
LAYER:                <Application>
LAYER:                  ||
LAYER:                <Loader>
LAYER:                  ||
LAYER:                VK_LAYER_NV_optimus
LAYER:                        Type: Implicit
LAYER:                            Disable Env Var:  DISABLE_LAYER_NV_OPTIMUS_1
LAYER:                        Manifest: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_ea7f458f0e49497d\nv-vk64.json
LAYER:                        Library:  C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_ea7f458f0e49497d\.\nvoglv64.dll
LAYER:                  ||
LAYER:                VK_LAYER_someotherapp_layer
LAYER:                        Type: Implicit
LAYER:                            Disable Env Var:  DISABLE_VK_LAYER_someapp_layer_1
LAYER:                        Manifest: D:\....
LAYER:                        Library:  D:\...
LAYER:                  ||
LAYER:                <Drivers>
ERROR: vkDestroyFramebuffer: Invalid device [VUID-vkDestroyFramebuffer-device-parameter]
app crash
```

I had to set the disable env var of the someotherapp layer to true '$env:DISABLE_VK_LAYER_someapp_layer_1="true"'  
running software again and issue was gone
