### ISSUE TITLE
Bloodborne. No 3d renderring happening (no character at the character creation screen, no world, but the game shows the interface).

### ISSUE THREAD

**Issue by dante42lk** [shadps4-emu/shadPS4#795]
`[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondInit:655: name=NoName, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondInit:655: name=NoName, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondInit:655: name=NoName, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondInit:655: name=NoName, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondInit:655: name=NoName, result=0
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:391: Unsupported tiled image: D32SfloatS8Uint (Depth_MacroTiled)
[Render.Vulkan] <Warning> vk_pipeline_cache.cpp:ShouldSkipShader:177: Skipped graphics shader hash 0x8e3f8dc4.
[Render.Vulkan] <Warning> vk_pipeline_cache.cpp:ShouldSkipShader:177: Skipped compute shader hash 0x4ca76892.
[Render.Vulkan] <Warning> vk_pipeline_cache.cpp:ShouldSkipShader:177: Skipped compute shader hash 0xa954e79d.
[Render.Vulkan] <Warning> vk_pipeline_cache.cpp:ShouldSkipShader:177: Skipped compute shader hash 0x2da7fe60.
[Lib.Pad] <Info> pad.cpp:scePadSetVibration:526: scePadSetVibration called handle = 1 data = 0 , 0
[Lib.Pad] <Info> pad.cpp:scePadSetVibration:526: scePadSetVibration called handle = 1 data = 0 , 0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadCondInit:655: name=NoName, result=0
[Lib.Rtc] <Error> rtc.cpp:sceRtcGetCurrentClockLocalTime:80: (STUBBED) called
[Lib.Rtc] <Error> rtc.cpp:sceRtcGetTick:122: (STUBBED) called
[Lib.Rtc] <Error> rtc.cpp:sceRtcSetTick:191: (STUBBED) called`

Rtx 4060 7840hs 32gb ram latest nvidia drivers 23h2 22631.4112

No character at the character creation screen, 3d visuals renderred at all, but the audio and interface are loading

**Comment by DanielSvoboda** [comment]
Just out of curiosity, what build are you using in this test?

**Comment by enzi** [comment]
bb-hacks branch?

**Comment by gandalfthewhite19890404** [comment]
Close issue, please

**Comment by dante42lk** [comment]
> Just out of curiosity, what build are you using in this test?

All latest builds from Actions fail, BB-hacks builds (i[ assume builds by this guy](https://github.com/rafael-57/shadps4-pino/actions) as the bb-hack branch is outdated and has no updates). Always the same rs32/d32s float unit error.

**Comment by DanielSvoboda** [comment]
So you are reporting a 'issue' from another repository here?
Please close this and open an issue there, as this doesn't make sense.
here is the shadPS4 repository, go to rafael-57's repository and report there

**Comment by dante42lk** [comment]
> So you are reporting a 'issue' from another repository here? Please close this and open an issue there, as this doesn't make sense. here is the shadPS4 repository, go to rafael-57's repository and report there

Are you serious? I answered multiple questions. One of them was about bb-hacks. Both the main branch and Raphael's branch fail with the same error. So the report is under main branch for that reason.

**Comment by DanielSvoboda** [comment]
I had understood that this error was happening with the code from the other repository. If it is giving an error in this repository, it makes sense to report it here then

**Comment by Hermiten** [comment]
I suggest you use the latest version and open a new ticket if necessary.

**Comment by M7MD25XWd** [comment]
i have the same problem of charcter do you have an answer
