### ISSUE TITLE
Debian 12: cannot compile with error: ‘contains’ is not a member of ‘std::ranges’

### ISSUE THREAD

**Issue by Fabxx** [shadps4-emu/shadPS4#799]
System info:

OS: Debian GNU/Linux 12 (bookworm) x86_64 
Kernel: 6.1.0-25-amd64 
CPU: Intel i7-10700 (16) @ 2.900GHz 
GPU: NVIDIA GeForce RTX 3060 
Memory: 15841MiB 

[error.txt](https://github.com/user-attachments/files/16898441/error.txt)

**Comment by retcinder** [comment]
This error implies Debian 12 does not (at least partially) support C++ 23 (which is the spec version that `std::ranges::contains` was added in) along with C++ 20 (`std::chrono::current_zone` was added in that spec version).

**Comment by Hermiten** [comment]
Hello, you can test it again ? Thanks you

**Comment by Ripod** [comment]
Hello, i have same exact error on debian 12 
System info:

Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-25-amd64 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4070 SUPER/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B550 AORUS ELITE V2
[error.txt](https://github.com/user-attachments/files/17237770/error.txt)
Tested on the latest master (commit 7e533ccf500ec0a847053aaf05e657e172f3f7de)

**Comment by qurious-pixel** [comment]
@Ripod @Fabxx your error message is missing what compiler and version you are using.
You need the `libstdc++` from gcc-13

See: https://github.com/shadps4-emu/shadPS4/issues/205#issuecomment-2178598400

**Comment by Ripod** [comment]
@qurious-pixel I am using clang 16 
Debian clang version 16.0.6 (15~deb12u1)
Also tried gcc version 12.2.0 
I tried and couldn't find the way to install newer C++ compiler on debian 12 because of system library dependencies

**Comment by Fabxx** [comment]
gcc 13 with full C++23 support won't be included until Debian Trixie is released.
