### ISSUE TITLE
[Debug] <Critical> vector_memory.cpp:operator():366: Assertion Failed!

### ISSUE THREAD

**Issue by SuperJogosDBZ** [shadps4-emu/shadPS4#801]
`[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:79: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:391: Unsupported tiled image: D32SfloatS8Uint (Depth_MacroTiled)
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:320: Compiling cs shader 0xd7003d5a 
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:320: Compiling cs shader 0xbaf640d5 
[Tty] <Info> libkernel.cpp:ps4__write:210: == Stall during rendering at flush 261
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:320: Compiling fs shader 0xb6e87124 
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:320: Compiling vs shader 0x8e3f8dc4 
[Debug] <Critical> vector_memory.cpp:operator():366: Assertion Failed!
Non immediate offset not supported
`

fix pls

**Comment by Jaswanth-Vardireddy** [comment]
I keep getting the same error too. Let me know if you have it fixed.

**Comment by fuhuan416** [comment]
With [squidbus:vk-format-feature](https://github.com/squidbus/shadPS4/tree/vk-format-feature) make character render correclty but i got same log with you.

**Comment by Mikiri7** [comment]
Same here, wich is your gpu?
I got an AMD Rx6600, and i think for the moment it's only happening with AMD gpu

**Comment by SuperJogosDBZ** [comment]
> Same here, wich is your gpu? I got an AMD Rx6600, and i think for the moment it's only happening with AMD gpu

1660 Super

**Comment by Mikiri7** [comment]
I download the last build and now i can run the game https://github.com/shadps4-emu/shadPS4/actions/runs/10746589695

**Comment by mamamoy** [comment]
i have some error when playing GOW III Remastered:
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:378: Compiling fs shader 0xccdebd80d1b8f55c (permutation)
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:88: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:378: Compiling vs shader 0xccdebd802401e5ac (permutation)
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:88: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:88: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:378: Compiling fs shader 0x29966d1be34790b4 
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:378: Compiling vs shader 0x29966d1b47a9adb1 
[Debug] <Critical> image.cpp:operator():236: Assertion Failed!

**Comment by Hermiten** [comment]
It's a common error, please check on the compatibily list for gow 3
