### ISSUE TITLE
vector_memory.cpp

### ISSUE THREAD

**Issue by Mikiri7** [shadps4-emu/shadPS4#807]
[Debug] <Critical> vector_memory.cpp:operator():366: Assertion Failed!
Non immediate offset not supported

Setup:
GPU: RX6600 8GB VRAM
CPU: i5 12400f
RAM: 16GB DDR4 3200MHz Dual Channel

**Comment by fuhuan416** [comment]
Duplicate with https://github.com/shadps4-emu/shadPS4/issues/801

**Comment by Mikiri7** [comment]
> Duplicate with #801

Oh, thank you!
i'll check
