### ISSUE TITLE
ShadPS4 crashes without an error message when installing a PKG

### ISSUE THREAD

**Issue by KubokPekla** [shadps4-emu/shadPS4#811]
I've tried a bunch of the newest builds in the Windows QT directory (under Actions) and every single one of them crashes to desktop nearly immediately before the installation progress window pops up whenever I try to install a PKG. I've attempted this with Bloodborne and I've also attempted it with PT, neither of them work so I don't think it's an issue with the PKG files themselves. I've checked the Windows Event Viewer which doesn't tell me much other than that the file can't be accessed for a bunch of different possible reasons, and I've checked all of them minus it being caused by storage drivers, but I'm having a hard time believing that that is the issue, though I could be wrong, I've never messed with my storage drivers. Drive health is fine, they're connected, I've tried different disks, I've tried running ShadPS4 on other disks, nothing seems to work and I'm always just left with an incomplete installation of about 11.6MB which of course doesn't function.

I'm on Windows 10, I've tried three different builds, the newest one being the most recent "game_data fixes" build, I have 16GB of RAM, none of my hard drives are too full, and that's about all of the relevant information I can think of.

Any help would be greatly appreciated, I really want to see how well this runs.

**Comment by mavethee** [comment]
PKG installation process isn't tracked in log for now.

**Comment by georgemoralis** [comment]
> PKG installation process isn't tracked in log for now.

smells like a work for someone

**Comment by Aruto-san** [comment]
What is your CPU model? I've the same issue and I've seen some posts suggesting it might be because of lack of AVX2 instructions support.

**Comment by Ishikudeska** [comment]
@KubokPekla could you post your log file here so we can see what's happening. (if there's even a log file)

**Comment by mavethee** [comment]
Again read above, PKG installation isn't logged.

**Comment by Ishikudeska** [comment]
Right, sorry. I'm looking into it right now.

**Comment by KubokPekla** [comment]
Yeah there is no log file. 

> What is your CPU model? I've the same issue and I've seen some posts suggesting it might be because of lack of AVX2 instructions support.

I'm running a rather ancient AMD FX 8350. It wouldn't really surprise me if that is the issue, but I couldn't help but be curious if it runs better than RPCS3 like others have said, and that actually runs okay if it weren't for the awful audio glitch in Demon's Souls.

Not a big deal at all if it's more of a "wait and see" kind of issue, I can deal with that.

**Comment by SinMxchine** [comment]
Run Shadps4 as Administrator.
That fixed it for me.

**Comment by KubokPekla** [comment]
> Run Shadps4 as Administrator. That fixed it for me.

Yeah I've already tried that a few times, still crashes. I just tried it on the latest build as well to be thorough but no dice.

**Comment by rmueller83** [comment]
Same problem here using the qt version rev 81f7c83 with Win11 trying to install CUSA01114. I have a i7-10700K CPU. Trying as admin does not help and in the Event Viewer I see a error in VCRUNTIME140.dll which has version 14.40.33810.0. But for me, other PKGs than this one work.

**Comment by bigol83** [comment]
I have the same issue. Windows 10. Generally trying several times the emulator manages to install the PKG without crashing

**Comment by rmueller83** [comment]
There are related issues like #692 so implementing PKG installation logging seems to be a good idea.

**Comment by Jorge9811** [comment]
same here stable or actions it always crashes a few seconds after i try to install a pkg,the game doesnt matter either they all crash the same

[GZ4UAPL3.webm](https://github.com/user-attachments/assets/57459168-c9c7-4183-b786-3ea71ff7073f)

**Comment by KubokPekla** [comment]
> same here stable or actions it always crashes a few seconds after i try to install a pkg,the game doesnt matter either they all crash the same
> GZ4UAPL3.webm

Yep, that's exactly the same issue I'm having. Though I haven't tried the stable build yet, I don't think I'm going to bother though as it doesn't work with the games I'm trying to emulate and yeah, probably will just do the same thing.

**Comment by XPacL** [comment]
Same. Please Hlp!

**Comment by EduardoMgit** [comment]
Same problem here, tried bloodborne and sonic mania, both crashes the same way. Tried to put the pkg in the Shadps4 folder, run as admin, nothing worked.
Is there any way to find the game 'already installed' and copy to the Shadps4 folder?

**Comment by EduardoMgit** [comment]
Same problem here, tried bloodborne and sonic mania, both crashes the same way. Tried to put the pkg in the Shadps4 folder, run as admin, nothing worked.

**Comment by Wurzelsepp1337** [comment]
Same here. It just dies and I also have an prehistoric AMD FX8350 : )

**Comment by KubokPekla** [comment]
> Same here. It just dies and I also have an prehistoric AMD FX8350 : )

Huh, that's making me wonder if maybe it's an issue with certain CPU's.

Anyway, I guess as a bit of an update, I've gone back and tried all of the older main builds, they all have the same issue, and I've also been trying newer, but also kind of semi-random builds from actions over the past three weeks and the issue seems to have been present from day one. I figured that I could possibly find a build that works and just copy and paste the unpacked files from version to version, but they all crash within a few seconds of trying to install the PKG. That _might_ be worth trying for other people, someone might be able to find an older build that works (and please post it if you find one lol), but I gave up because there are just so many to go through and it really seems like they all have the same problem, at least for me.

For the hell of it, here's the rest of my specs if anyone finds it relevant:

![specs](https://github.com/user-attachments/assets/9d6b6928-e6ed-41bc-9d2d-680e95d52f2b)

**Comment by AussiePlick** [comment]
I have had the above issue when installing larger PKG's. It usually happened when I was extracting the PKD's while opening and running other APPs on my win 10 OS. 
The easiest way is to use itemsFlow game manager on your jail broken PS4 to download the game to a external HD via USB; as this fully extracts and decrypts the game while downloading it to the HD, I have 32 gig RAM.
I hope this helps...

**Comment by EduardoMgit** [comment]
> I have had the above issue when installing larger PKG's. It usually happened when I was extracting the PKD's while opening and running other APPs on my win 10 OS. The easiest way is to use itemsFlow game manager on your jail broken PS4 to download the game to a external HD via USB; as this fully extracts and decrypts the game while downloading it to the HD, I have 32 gig RAM. I hope this helps...

I thought it could be because of the PKG size (I was trying Bloodborne) or corrupted file, but tried Sonic Mania (less than 200mb I guess) and just happen, it crashes

**Comment by handi216** [comment]
I have same error when try to install Bloodborne (CUSA01363) base game which is 26GB large. I am trying to run it with debugger but it will take very long time for learning dev.
It crash after about 10 MB file are written into the game folder. 
Anyone know if a few files written in the game folder means the decryption key for PFS is correct?

**Comment by OldePSN00b** [comment]
Same issue here. My Rig was built in 2016 so no problem with AVX2 instruction set if that's a problem.

**Comment by handi216** [comment]
I found my problem was because I directly exported the PKG files from my PS4 and did not convert the file from Official format to Fake format. After conversion to Fake format, the install pkg function is passed.
May be the install function should add a validation checking and alert user about the PKG has to be in Fake format.

**Comment by Inlength52** [comment]
> I found my problem was because I directly exported the PKG files from my PS4 and did not convert the file from Official format to Fake format. After conversion to Fake format, the install pkg function is passed. May be the install function should add a validation checking and alert user about the PKG has to be in Fake format.

used PS4PKGView and my bloodborne is really in PKG Fake Format, so i don't think that's it for everyone

**Comment by Foul-Tarnished** [comment]
> > Same here. It just dies and I also have an prehistoric AMD FX8350 : )
> 
> Huh, that's making me wonder if maybe it's an issue with certain CPU's.
> 
> Anyway, I guess as a bit of an update, I've gone back and tried all of the older main builds, they all have the same issue, and I've also been trying newer, but also kind of semi-random builds from actions over the past three weeks and the issue seems to have been present from day one. I figured that I could possibly find a build that works and just copy and paste the unpacked files from version to version, but they all crash within a few seconds of trying to install the PKG. That _might_ be worth trying for other people, someone might be able to find an older build that works (and please post it if you find one lol), but I gave up because there are just so many to go through and it really seems like they all have the same problem, at least for me.
> 
> For the hell of it, here's the rest of my specs if anyone finds it relevant:
> 
> ![specs](https://private-user-images.githubusercontent.com/170151360/370200818-9d6b6928-e6ed-41bc-9d2d-680e95d52f2b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjUzNTYsIm5iZiI6MTcyODMyNTA1NiwicGF0aCI6Ii8xNzAxNTEzNjAvMzcwMjAwODE4LTlkNmI2OTI4LWU2ZWQtNDFiYy05ZDJkLTY4MGU5NWQ1MmYyYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxODE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2Q5YWIzYjY1Y2EyOTU1MzE0NGY1MTg0YTg4ZTc5MjVkY2RhMjdlNjcxODVmNjNkYzIyYmY1NDU1OGNmYmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ieV2pqCS2oLXIkLyXai-iBqQzqAKHRv2U41HBxZlYDA)

A RTX 2060 on a 12yo old cpu with slow ass DDR3 ram is hilarious

**Comment by Inlength52** [comment]
aside from the CPU, the rest i think is normal, i don't think RAM Speed will matter that much

**Comment by renjeun** [comment]
same issue here using linux

**Comment by KubokPekla** [comment]
-snip- First part wasn't meant to be posted, didn't notice that it was still in the comment field when I logged back in.

> > > Same here. It just dies and I also have an prehistoric AMD FX8350 : )
> > 
> > 
> > Huh, that's making me wonder if maybe it's an issue with certain CPU's.
> > Anyway, I guess as a bit of an update, I've gone back and tried all of the older main builds, they all have the same issue, and I've also been trying newer, but also kind of semi-random builds from actions over the past three weeks and the issue seems to have been present from day one. I figured that I could possibly find a build that works and just copy and paste the unpacked files from version to version, but they all crash within a few seconds of trying to install the PKG. That _might_ be worth trying for other people, someone might be able to find an older build that works (and please post it if you find one lol), but I gave up because there are just so many to go through and it really seems like they all have the same problem, at least for me.
> > For the hell of it, here's the rest of my specs if anyone finds it relevant:
> > ![specs](https://private-user-images.githubusercontent.com/170151360/370200818-9d6b6928-e6ed-41bc-9d2d-680e95d52f2b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjUzNTYsIm5iZiI6MTcyODMyNTA1NiwicGF0aCI6Ii8xNzAxNTEzNjAvMzcwMjAwODE4LTlkNmI2OTI4LWU2ZWQtNDFiYy05ZDJkLTY4MGU5NWQ1MmYyYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxODE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2Q5YWIzYjY1Y2EyOTU1MzE0NGY1MTg0YTg4ZTc5MjVkY2RhMjdlNjcxODVmNjNkYzIyYmY1NDU1OGNmYmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ieV2pqCS2oLXIkLyXai-iBqQzqAKHRv2U41HBxZlYDA)
> 
> A RTX 2060 on a 12yo old cpu with slow ass DDR3 ram is hilarious This emu will never run on a CPU like that

Yeah yeah I know now, my broke ass' ancient PC definitely wasn't going to stop me from trying to figure out exactly what the issue was and trying to see if I could work around it though, I am nothing if not persistent when it comes to shit like this lol. 

Sure as hell would've been nice if it was stated somewhere clearly what the exact requirements for this are though, would've saved me a lot of time trying to figure out what the issue is and if I can work around it. Especially considering some of the contributors commented acting all confused, so I don't know how the hell I was supposed to know it wouldn't run without trying it first and figuring it out from there, especially considering I have like no issue running a lot of modern games on this thing, as well as PS3/360 emulators. It'd be in the contributor's best interests to have the system requirements and exactly what kind of PKG is needed written clearly somewhere, it'd cut down on a lot of needless issue reports.

**Comment by StevenMiller123** [comment]
@KubokPekla The requirements are an AVX2 CPU, 16gb of RAM, and a modern GPU. The AMD FX-8350 lacks AVX2 support, so you aren't going to be able to install PKGs or run games.

**Comment by KubokPekla** [comment]
> @KubokPekla The requirements are an AVX2 CPU, 16gb of RAM, and a modern GPU. The AMD FX-8350 lacks AVX2 support, so you aren't going to be able to install PKGs or run games.

Thank you, I am aware now though.

Also I noticed the updated quickstart guide, much better explanation, though if I overlooked something that was already written somewhere on the Github then I apologize. Also, you guys are doing just fine, I was mostly just kind of annoyed at the snarky comment I was replying to. I wish you the best of luck with this project, you guys are doing some great work.

Gonna go ahead and close this, fingers crossed I'm able to build a new PC soon lol.

**Comment by type0dev** [comment]
Ok, I believe you need gengp4 and fake pkg generator to create a fake package so you can install. I remember having to do this with pkg's to install on cfw on ps4.
a guide on converting backups
https://hackinformer.com/2018/04/06/how-to-backup-ps4-games

**Comment by saudghs1** [comment]
> شغّل Shadps4 كمسؤول. هذا حلّ المشكلة بالنسبة لي.

thxxxxxxxxxxxxxxxxxxxxx
