### ISSUE TITLE
Bloodborne crashes and closes at launch

### ISSUE THREAD

**Issue by Dictavios** [shadps4-emu/shadPS4#813]
Hi, Im having big trouble with making Bloodborne even boot. When launch the game, a bunch of stubb errors are displayed in red and the emu closes not reaching the games first screen.I'll share the log, please help. Last build i've tried was "win64-qt-2024-09-06-a48bfb0"

Specs are:
Rx6600
i5 10400f
16gb ram  
[shad_log.txt](https://github.com/user-attachments/files/16907176/shad_log.txt)

**Comment by Ishikudeska** [comment]
`[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt8ios_base4InitC1Ev (nid: sqWytnhYdEg) called, returning zero to 0x97003b3c3` Is at the end of the log.
Will look into this.

**Comment by StevenMiller123** [comment]
@Ishikudeska That error is caused by not adding sys_modules. That function is part of libSceLibcInternal.sprx

**Comment by Ishikudeska** [comment]
ok. Thank you. @StevenMiller123

**Comment by StevenMiller123** [comment]
@Dictavios It appears the sys_modules you are using are either encrypted or corrupted. Please redump your firmware libraries and retest.

**Comment by Dictavios** [comment]
Many thanks for the response, Im looking forward to fix it. Incredible work you are doing.

**Comment by camelfert** [comment]
Are sys_modules to blame for my and a few other folks in Discord crashes on boot? I was crashing at the same point @Dictavios was but managed to get a little further now to a new spot that I can't get past. 

10900k, RTX 3090, 32GB RAM, W11 Enterprise, NVIDIA driver 560.94

Event Viewer application log:

Faulting application name: shadPS4.exe, version: 0.0.0.0, time stamp: 0x66d9e2ec
Faulting module name: shadPS4.exe, version: 0.0.0.0, time stamp: 0x66d9e2ec
Exception code: 0xc0000005
Fault offset: 0x0000000000076604
Faulting process id: 0x0x1E80
Faulting application start time: 0x0x1DB007FD8412170
Faulting application path: D:\Emulation\shadPS4\shadPS4.exe
Faulting module path: D:\Emulation\shadPS4\shadPS4.exe
Report Id: 99c74118-8aed-478c-bdf8-fb2ce4b82483
Faulting package full name: 
Faulting package-relative application ID: 

[shad_log.txt](https://github.com/user-attachments/files/16911680/shad_log.txt)

**Comment by StevenMiller123** [comment]
@camelfert Your sys-modules are fine. I can't see any important error in the log though. Can you check if your logType is set to sync? It's an option you can set in the gui.

**Comment by camelfert** [comment]
> @camelfert Your sys-modules are fine. I can't see any important error in the log though. Can you check if your logType is set to sync? It's an option you can set in the gui.

Turns out I was able to finally fix this by redumping the game, but using an EU copy instead! After I did this, everything booted up finally as expected. Thanks for checking my logs and giving some insight!

**Comment by Ishikudeska** [comment]
ofc m8

**Comment by Dictavios** [comment]
I just managed to load it at version 1.00. The solution I used was based on @camelfert fix, redumped the game and then worked. But it leads to another issue when update to 01.09, which I opened an issue about.

**Comment by LucaNicosia** [comment]
Hello team. I see a similar issue: bloodborne is not starting and shadps4 crashes.

I have a Nvidia GE-Force 1650 (latest drivers), Windows 11, 16GB RAM, intel i7-16th_gen

[shad_log.txt](https://github.com/user-attachments/files/17034113/shad_log.txt)

Any suggestions?

**Comment by StevenMiller123** [comment]
> Hello team. I see a similar issue: bloodborne is not starting and shadps4 crashes.
> 
> I have a Nvidia GE-Force 1650 (latest drivers), Windows 11, 16GB RAM, intel i7-16th_gen
> 
> [shad_log.txt](https://github.com/user-attachments/files/17034113/shad_log.txt)
> 
> Any suggestions?

@LucaNicosia There is no 16th gen Intel processor, could you provide the full model number? Additionally, though I doubt it's related to this issue, a GTX 1650 lacks the VRAM needed to properly run Bloodborne. Lastly, is your log type set to sync? I don't see any important errors in your log, which with Bloodborne, seems to be an indicator of a bad game dump.

**Comment by gandalfthewhite19890404** [comment]
> Any suggestions?

Close this issue, like many other BB-related issues.

**Comment by Danygamer101** [comment]
@StevenMiller123 could you help me in dm maybe with getting these sys 11 modules without a ps4 for bloodborne pleasee ??

**Comment by StevenMiller123** [comment]
@Danygamer101 We do not endorse piracy. I cannot help you, and neither will any other shadPS4 contributor.
