### ISSUE TITLE
Bloodborne Crashes when I load into a save file

### ISSUE THREAD

**Issue by ksaOfficial** [shadps4-emu/shadPS4#818]
So here is my specs:

AMD Ryzen 7 5800X
RTX 4070 SUPER
32 GB of RAM
Windows 11 64 bit

and I may have found a critical bug:
[shad_log.txt](https://github.com/user-attachments/files/16912674/shad_log.txt)

**Comment by fuhuan416** [comment]
Duplicate with https://github.com/shadps4-emu/shadPS4/issues/801
