### ISSUE TITLE
Bloodborne - Gascoigne 2nd Phase Transform Crashes; Boss Kill Crashes

### ISSUE THREAD

**Issue by CrimsonVelka** [shadps4-emu/shadPS4#832]
CPU 5950X
GPU 4090

Gascoigne's transformation will crash the emulator. See log_1
Boss Kill crashes emulator. See log_2
Boss Kill crashed with Cleric Beast as well but progress was saved, progress did not save on Gascoigne kill after multiple repeats to reproduce crash.

Happens both out of the box both with and without patches active as well as hacks + patches active.
Work around is to turn camera away before the visual effects of transformation of boss defeat play out on screen. 
Easy to do on 2nd phase start, very hard to do on boss kill because its near instant

[shad_log_1.txt](https://github.com/user-attachments/files/16917940/shad_log_1.txt)
[shad_log_2.txt](https://github.com/user-attachments/files/16918013/shad_log_2.txt)

**Comment by ixiLod** [comment]
Same here

CPU i7 14700KF
GPU 3090

**Comment by ixiLod** [comment]
Update in case people are blocked.
It's necessary to remove sfx folder or apply intel fix available on NexusMod
