### ISSUE TITLE
Crash at loading Bloodborne 

### ISSUE THREAD

**Issue by Dictavios** [shadps4-emu/shadPS4#835]
For me, v.1.00 of the game works as I can reach gameplay. Problem is when update to 1.09, since it no longer launch the game anymore. Last thing I can read before it closes is a kernel warning regarding memory, in yellow letters. I'll share the log.
Specs are: 
Rx6600
i5 10400f
16gb ram
Tried all emu Winqt  builds from yesteday to now on   
[shad_log.txt](https://github.com/user-attachments/files/16918815/shad_log.txt)

**Comment by Dictavios** [comment]
[Kernel.Vmm] <Warning> memory_management.cpp:sceKernelGetDirectMemorySize:19: called
[Kernel.Vmm] <Info> memory_management.cpp:sceKernelAllocateDirectMemory:51: searchStart = 0x0, searchEnd = 0x120000000, len = 0x7400000, alignment = 0x200000, memoryType = 0x0, physAddrOut = 0x0
[Kernel.Vmm] <Info> memory_management.cpp:sceKernelMapDirectMemory:177: called, redirected to sceKernelMapNamedDirectMemory
[Kernel.Vmm] <Info> memory_management.cpp:sceKernelMapNamedDirectMemory:150: addr = 0x0, len = 0x7400000, prot = 0x3, flags = 0x0, directMemoryStart = 0x0, alignment = 0x200000

**Comment by dogoawesomeness256** [comment]
wait for the newest build of bb-hacks and also make  sure you downloaded the Bloodborne FPS Boost 1.0 which is apart of the Bloodborne Visual Tweaks mod pack on nexus

**Comment by dogoawesomeness256** [comment]
thank you fromsoftserve for making this mod your one of the most talented people pushing for bloodborne to be playable on pc

**Comment by Hermiten** [comment]
I suggest you use the latest version and open a new ticket if necessary.
