### ISSUE TITLE
Bloodborne crashes when installing or trying to start it

### ISSUE THREAD

**Issue by hotdog058** [shadps4-emu/shadPS4#836]
[shad_log.txt](https://github.com/user-attachments/files/16919475/shad_log.txt)
![изображение_2024-09-07_214819976](https://github.com/user-attachments/assets/36db7b3b-7497-4929-994e-4e764894714d)
Intel Xeon E5 2689
Nvidia 4060 8 gb
24 gb RAM
Win 10
Big wish to play Bloodborne : (

**Comment by dogoawesomeness256** [comment]
use bb-hacks if you want i can send a google drive of the build idk if thats allowed but there probably prepping for a new build with the new fix that fixes ram leakage

**Comment by hotdog058** [comment]
> use bb-hacks if you want i can send a google drive of the build idk if thats allowed but there probably prepping for a new build with the new fix that fixes ram leakage

Dude, it would be really cool if you could do this for me.

**Comment by Hermiten** [comment]
No more information and duplicate, I'm closing it
