### ISSUE TITLE
Bloodborne crashes when installing 1.09 pkg  update file

### ISSUE THREAD

**Issue by fighterxuyue** [shadps4-emu/shadPS4#839]
My Game id is CUSA03023 , when i try to update the game from 1.00 to 1.09 ,shads4 crashes :
HP9000-CUSA03023_00-BLOODBORNE0000AS-A0109-V0100.pkg

shadps4 version is shadps4-win64-qt-2024-09-07-8e3a39b

**Comment by fighterxuyue** [comment]
> My Game id is CUSA03023 , when i try to update the game from 1.00 to 1.09 ,shads4 crashes : HP9000-CUSA03023_00-BLOODBORNE0000AS-A0109-V0100.pkg
> 
> shadps4 version is shadps4-win64-qt-2024-09-07-8e3a39b

but the patch is already installed after creash , i think it's not a big problem

**Comment by Dictavios** [comment]
Hi, it happened the same to me but had to double check cause its not really properly installed. Tried a  second and even a third time to do it right. I think that it has to show the box dialog that say it has been correctly completed to take it done.

**Comment by Foul-Tarnished** [comment]
Same issue on BB goty EU

**Comment by ajtuttle99** [comment]
Same here, & the emulator instantly crashes when trying to start BB after

**Comment by Dictavios** [comment]
> Same here, & the emulator instantly crashes when trying to start BB after

Are you on AMD gpu?

**Comment by ajtuttle99** [comment]
> > Same here, & the emulator instantly crashes when trying to start BB after
> 
> Are you on AMD gpu?

Nvidia RTX 4070 & on the latest drivers (560.94)

**Comment by Hermiten** [comment]
Some fix was made with the patching system, can one of you try again?

**Comment by ajtuttle99** [comment]
> Some fix was made with the patching system, can one of you try again?

I can confirm on my end that everything is working now as of release V0.3.0

**Comment by fighterxuyue** [comment]
> My Game id is CUSA03023 , when i try to update the game from 1.00 to 1.09 ,shads4 crashes : HP9000-CUSA03023_00-BLOODBORNE0000AS-A0109-V0100.pkg
> 
> shadps4 version is shadps4-win64-qt-2024-09-07-8e3a39b

i may found the reason ,the pkg file is encryped , i can't find the passcode

**Comment by StevenMiller123** [comment]
@fighterxuyue Dump your patch off your PS4 properly. PKGs dumped through FTP, and PKGs downloaded from Sony servers are encrypted by default, with a passcode that no one should know.

**Comment by Joze53** [comment]
For those who are confused, the update file that you downloaded is encrypted and or broken, so you need to find another 1.09 update and hope it's a good one.
