### ISSUE TITLE
Bloodborne crashes shadPS4 on new game load or load game

### ISSUE THREAD

**Issue by AluminumHaste** [shadps4-emu/shadPS4#840]
I can get past intro video, and I can see the 3d character model in character creation.
Once I try to start the game it crashes on load screen.

PC
GPU: Radeon 7900XTX (latest drivers 24.8.1)
CPU: Intel 14700K
RAM: 32 GB 3600Mhz DDR4
HDD: XPG 480GB M.2 NVME

[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:391: Unsupported tiled image: D32SfloatS8Uint (Depth_MacroTiled)
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:320: Compiling fs shader 0x7cc2c044 
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:79: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:320: Compiling fs shader 0x2db65555 
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:320: Compiling vs shader 0x1635154c 
[Debug] <Critical> vector_memory.cpp:operator():366: Assertion Failed!
Non immediate offset not supported

[shad_log.txt](https://github.com/user-attachments/files/16920756/shad_log.txt)

I tried compiling in Visual Studio as well as using the artifcats.

**Comment by fighterxuyue** [comment]
> I can get past intro video, and I can see the 3d character model in character creation. Once I try to start the game it crashes on load screen.
> 
> PC GPU: Radeon 7900XTX (latest drivers 24.8.1) CPU: Intel 14700K RAM: 32 GB 3600Mhz DDR4 HDD: XPG 480GB M.2 NVME
> 
> [Render.Vulkan] tile_manager.cpp:TryDetile:391: Unsupported tiled image: D32SfloatS8Uint (Depth_MacroTiled) [Render.Vulkan] vk_pipeline_cache.cpp:CompileModule:320: Compiling fs shader 0x7cc2c044 [Render.Vulkan] vk_graphics_pipeline.cpp:GraphicsPipeline:79: Rectangle List primitive type is only supported for embedded VS [Render.Vulkan] vk_pipeline_cache.cpp:CompileModule:320: Compiling fs shader 0x2db65555 [Render.Vulkan] vk_pipeline_cache.cpp:CompileModule:320: Compiling vs shader 0x1635154c [Debug] vector_memory.cpp:operator():366: Assertion Failed! Non immediate offset not supported
> 
> [shad_log.txt](https://github.com/user-attachments/files/16920756/shad_log.txt)
> 
> I tried compiling in Visual Studio as well as using the artifcats.

i put the extra 9 firmeware files into the \user\sys_modules solved this problem ,may be works for you

**Comment by fighterxuyue** [comment]
> > I can get past intro video, and I can see the 3d character model in character creation. Once I try to start the game it crashes on load screen.
> > PC GPU: Radeon 7900XTX (latest drivers 24.8.1) CPU: Intel 14700K RAM: 32 GB 3600Mhz DDR4 HDD: XPG 480GB M.2 NVME
> > [Render.Vulkan] tile_manager.cpp:TryDetile:391: Unsupported tiled image: D32SfloatS8Uint (Depth_MacroTiled) [Render.Vulkan] vk_pipeline_cache.cpp:CompileModule:320: Compiling fs shader 0x7cc2c044 [Render.Vulkan] vk_graphics_pipeline.cpp:GraphicsPipeline:79: Rectangle List primitive type is only supported for embedded VS [Render.Vulkan] vk_pipeline_cache.cpp:CompileModule:320: Compiling fs shader 0x2db65555 [Render.Vulkan] vk_pipeline_cache.cpp:CompileModule:320: Compiling vs shader 0x1635154c [Debug] vector_memory.cpp:operator():366: Assertion Failed! Non immediate offset not supported
> > [shad_log.txt](https://github.com/user-attachments/files/16920756/shad_log.txt)
> > I tried compiling in Visual Studio as well as using the artifcats.
> 
> i put the extra 9 firmeware files into the \user\sys_modules solved this problem ,may be works for you

![Uploading 2024-09-08_151909.png…]()

**Comment by fighterxuyue** [comment]
> > I can get past intro video, and I can see the 3d character model in character creation. Once I try to start the game it crashes on load screen.
> > PC GPU: Radeon 7900XTX (latest drivers 24.8.1) CPU: Intel 14700K RAM: 32 GB 3600Mhz DDR4 HDD: XPG 480GB M.2 NVME
> > [Render.Vulkan] tile_manager.cpp:TryDetile:391: Unsupported tiled image: D32SfloatS8Uint (Depth_MacroTiled) [Render.Vulkan] vk_pipeline_cache.cpp:CompileModule:320: Compiling fs shader 0x7cc2c044 [Render.Vulkan] vk_graphics_pipeline.cpp:GraphicsPipeline:79: Rectangle List primitive type is only supported for embedded VS [Render.Vulkan] vk_pipeline_cache.cpp:CompileModule:320: Compiling fs shader 0x2db65555 [Render.Vulkan] vk_pipeline_cache.cpp:CompileModule:320: Compiling vs shader 0x1635154c [Debug] vector_memory.cpp:operator():366: Assertion Failed! Non immediate offset not supported
> > [shad_log.txt](https://github.com/user-attachments/files/16920756/shad_log.txt)
> > I tried compiling in Visual Studio as well as using the artifcats.
> 
> i put the extra 9 firmeware files into the \user\sys_modules solved this problem ,may be works for you

you also need to enable dumpShaders too.

**Comment by Dictavios** [comment]
If you're using msi afterburner try closing it, and then open the emu and load the game.

**Comment by Hermiten** [comment]
I suggest you use the latest version and open a new ticket if necessary.
