### ISSUE TITLE
Instant Crash Trying to Start Bloodborne

### ISSUE THREAD

**Issue by ajtuttle99** [shadps4-emu/shadPS4#847]
[shad_log.txt](https://github.com/user-attachments/files/16923725/shad_log.txt)

![image](https://github.com/user-attachments/assets/f44fa01f-ac0e-497a-9a74-934b35c6e3a0)

AMD Ryzen 7800X3D
32gb RAM
RTX 4070
Win 10

Trying to launch BB with the latest windows qt build (Windows-Qt #2447: Commit [9101bd7]) is resulting in the emulator instantly closing. Nothing is being written to the log file in "user\log\shad_log.txt". I've tried launching as admin, I've tried launching as admin in all available compatibility modes, I've disabled fullscreen optimizations, I've tried all "High DPI Scaling override" options, and in the emulator itself I've set my 4070 as the graphics device & set log type to sync. I've tried to launch BB V 1.0 & 1.09, and I've tried to launch 1.09 with the sys modules installed.

**Comment by Hermiten** [comment]
duplicate https://github.com/shadps4-emu/shadPS4/issues/653

**Comment by GutsR27** [comment]
having same issue did u manage to fix it?

**Comment by ajtuttle99** [comment]
> having same issue did u manage to fix it?

I've just been using [this build](https://github.com/shadps4-emu/shadPS4/actions/runs/11091793044) & haven't had these issues at all (there's some graphical issues, but it's whatever). No clue if anything newer works or not.
