### ISSUE TITLE
[Feature Request] Add an auto-updater to the ShadPS4 app

### ISSUE THREAD

**Issue by Pipi86** [shadps4-emu/shadPS4#848]
It would be very useful to have an auto-updater like the one RPCS3 uses, with the ability to manually or automatically update, show a changelog with all the changes since last time the app was updated, and restart it after update is downloaded and installed.

**Comment by Saoghal** [comment]
I'm writing here just to say I support this idea!

**Comment by DanielSvoboda** [comment]
I'm doing...

**Comment by Pipi86** [comment]
Closing this as it was resolved by #1006. Nice.

**Comment by DanielSvoboda** [comment]
Yes, finally ready 😄
now just wait for the new updates
