### ISSUE TITLE
Unable to reserve virtual adress space EVEN ON SONIC MANIA

### ISSUE THREAD

**Issue by mactonight37** [shadps4-emu/shadPS4#857]
```
[Loader] <Info> emulator.cpp:Emulator:52: Starting shadps4 emulator v0.2.1 WIP 
[Loader] <Info> emulator.cpp:Emulator:53: Revision 749fe92882ff2a03ae13e73c00fe9a1a8ac88f95
[Loader] <Info> emulator.cpp:Emulator:54: Branch main
[Loader] <Info> emulator.cpp:Emulator:55: Description 749fe92
[Config] <Info> emulator.cpp:Emulator:57: General isNeo: false
[Config] <Info> emulator.cpp:Emulator:58: GPU isNullGpu: false
[Config] <Info> emulator.cpp:Emulator:59: GPU shouldDumpShaders: true
[Config] <Info> emulator.cpp:Emulator:60: GPU shouldDumpPM4: false
[Config] <Info> emulator.cpp:Emulator:61: GPU vblankDivider: 1
[Config] <Info> emulator.cpp:Emulator:62: Vulkan gpuId: 0
[Config] <Info> emulator.cpp:Emulator:63: Vulkan vkValidation: false
[Config] <Info> emulator.cpp:Emulator:64: Vulkan vkValidationSync: false
[Config] <Info> emulator.cpp:Emulator:65: Vulkan vkValidationGpu: false
[Config] <Info> emulator.cpp:Emulator:66: Vulkan rdocEnable: false
[Config] <Info> emulator.cpp:Emulator:67: Vulkan rdocMarkersEnable: false
[Config] <Info> emulator.cpp:Emulator:68: Vulkan crashDiagnostics: false
[Debug] <Critical> address_space.cpp:operator():74: Assertion Failed!
Unable to reserve virtual address space!

```

i have over 12gbs of free ram and i get this error and an immediate app crash when i try to run any game including sonic mania

**Comment by Nathanielpd140** [comment]
same problem here havent found a fix yet.

**Comment by mactonight37** [comment]
> same problem here havent found a fix yet.

what are your specs, mine are w11, ryzen 5 5500, rx 6700 10gb with shadps4 supported amd driver which i couldnt recall the name but it was something like fsfa, 16gb ram.

**Comment by Nathanielpd140** [comment]
I5 6400, Gtx 1070, 24 gb of ram.
Someone else had the same issue and said they updated or reinstalled windows and it fixed it. Im going to try today

**Comment by mactonight37** [comment]
thanks, have you tried it

**Comment by Nathanielpd140** [comment]
I actually tried again yesterday and it just started working, im not completely sure how but I think because I had my computer fully turned off and then powered it on and immediately ran the emulator it was able to allocate the memory. Try turning off your pc fully like unplugged from the outlet and then immediately run emulator after turning back on, I think thats what did it for me but not 100% sure

**Comment by mactonight37** [comment]
Thanks, im gonna try and report, by the way did you have the issue again after the first try or is it consistent for now?

**Comment by mactonight37** [comment]
ive tried it and the issue persists

**Comment by Nathanielpd140** [comment]
Im not sure exactly why mine started working, it will most likely be fixed in the upcoming versions though.
