### ISSUE TITLE
bloodborne, region protection failed

### ISSUE THREAD

**Issue by shadps4ye** [shadps4-emu/shadPS4#863]
so, after pressing 'Continue' starts loading into the game, but after a second it freezes with an error. There screenshot
![Desktop Screenshot 2024 09 11 - 00 03 24 48](https://github.com/user-attachments/assets/5b4c3ba2-21fa-46a2-9ec9-50c9070ec91b)

[Debug] <Critical> page_manager.cpp:operator():47: Assertion Failed!
Region protection failed

**Comment by shadps4ye** [comment]
https://github.com/shadps4-emu/shadPS4/actions/runs/10786711138 on this build no errors

**Comment by jbckr20** [comment]
I am having the same issue with Bloodborne. When I press continue in the menu it causes a crash and has the same error. On older builds I can continue and boot into the game with no issue other than it crashes when i try to teleport to or from a lantern/hunters dream.

**Comment by Hermiten** [comment]
This is fixed, I close it
