### ISSUE TITLE
Region protection failed

### ISSUE THREAD

**Issue by Mikiri7** [shadps4-emu/shadPS4#866]
![imagen](https://github.com/user-attachments/assets/76d825c9-aa6d-4a3e-9b88-33e2462fdb55)
When i start the game this happen

**Comment by Ninomaker** [comment]
same issue recently

**Comment by Seppelbert** [comment]
I get the same Error with Bloodborne

**Comment by cvertee** [comment]
same with Bloodborne

**Comment by maurymoyano** [comment]
The same thing happens to me

**Comment by cptang2007** [comment]
same here

**Comment by rmueller83** [comment]
Duplicate of #863

**Comment by TagoSMD** [comment]
same

**Comment by psucien** [comment]
Fixed in the latest main, please check.

**Comment by Mikiri7** [comment]
> Fixed in the latest main, please check.

Thank you!
