### ISSUE TITLE
[macOS] Regression: Audio is terrible after PR 507 (SDL Audio Latency)

### ISSUE THREAD

**Issue by shinra-electric** [shadps4-emu/shadPS4#870]
At least the following games have terrible audio after PR #507:

Undertale - CUSA09415
Wonder Labyrinth - CUSA29366

(The number of affected titles are probably more, but I can't test many titles as there is a separate regression affecting a lot of previously working games at the moment).

**Comment by kh0nsu** [comment]
Try setting TARGET_LATENCY_MS to some larger value eg. 40ms, 60ms, or 100ms.

**Comment by shinra-electric** [comment]
> Try setting TARGET_LATENCY_MS to some larger value eg. 40ms, 60ms, or 100ms.

I don't have my Mac set up for building shadPS4 locally, so I can't try this out. Maybe someone else can give it a try.

**Comment by shinra-electric** [comment]
I'll close this because the PR was reverted.
