### ISSUE TITLE
Bloodborne crash on taking damage/enemy attack

### ISSUE THREAD

**Issue by Ducky229** [shadps4-emu/shadPS4#872]
Maybe it is because of effects, idk.

Steps to reproduce:

1. Run game
2. Start new or load game
3. Take damage

[shad_log.txt](https://github.com/user-attachments/files/16969561/shad_log.txt)

**Comment by Damiania626** [comment]
I’m having the same issue. Works fine until I attack an enemy or take damage

**Comment by Ducky229** [comment]
Try to rename sfx folder in game/dvd.(Something, i dont remember) folder. But this disables all point light source and indoors looks completly black

**Comment by Damiania626** [comment]
That was it. Soon as I changed the name to the SFX folder it worked

**Comment by Hermiten** [comment]
Duplicate here: https://github.com/shadps4-emu/shadPS4/issues/503
If you want to post update, you can on the other issue

**Comment by d3vv** [comment]
Fixed issue for Intel 14900K with sfx folder replace from 
https://www.nexusmods.com/bloodborne/mods/41?tab=files

**Comment by lordrustin** [comment]
its worked thx Ducky229
