### ISSUE TITLE
BloodBorne : Unplayable right after character creation

### ISSUE THREAD

**Issue by Sournois** [shadps4-emu/shadPS4#873]
Unplayable right after character creation, brightness bug, no sounds, game crashes after being killed by the game's first enemy.

shadPS4 version : shadps4-win64-qt-2024-09-11-8a76cd8 

https://gist.github.com/Sournois/24af22654540dad64afef2082c8b33b5#file-gistfile1-txt

CUSA03173 – EUR

Bloodborne.GOTY-CUSA03173-EUR-Game-PRELUDE.pkg
Bloodborne.GOTY-CUSA03173-EUR-v1.09-[1080p60fps].pkg
Bloodborne.GOTY-CUSA03173-EUR-DLC-PS4.pkg

**Comment by Hermiten** [comment]
Hacked version is not allowed
