### ISSUE TITLE
Links on wiki point at old repo location

### ISSUE THREAD

**Issue by kavika13** [shadps4-emu/shadPS4#883]
On this page:
https://github.com/shadps4-emu/shadPS4/wiki/

The link `[PS4 PKG](https://github.com/georgemoralis/shadPS4/wiki/PKG-Information)` points at the old wiki. Should be a trivial fix.

There's also several similar links that need changing in the table on:
https://github.com/shadps4-emu/shadPS4/wiki/PKG-Information

**Comment by Hermiten** [comment]
I add the label documentation and this is correct, the links on the wiki are outdated

**Comment by Hermiten** [comment]
We have updated he wiki. Thanks for this report
