### ISSUE TITLE
CUSA03173 Hangs on Black Screen 

### ISSUE THREAD

**Issue by corigne** [shadps4-emu/shadPS4#885]
System:
Linux 6.10.9-arch1-2
AMD Ryzen 7 3800X
NVIDIA GeForce RTX 2070 SUPER (nvidia 560.35.03)
32 GB of RAM

Build from commit 5e12303b06c1984a06c2ecbeec6983761c4b0c82
Also happens on commit 1b12138cda65d5f080800e6ceca43e0bc2bc516f

Hangs on black screen when game is started.

Log:
[shad_log.txt](https://github.com/user-attachments/files/16980006/shad_log.txt)

**Comment by StevenMiller123** [comment]
Please change your log type to sync, then send a new log.

**Comment by raphaelthegreat** [comment]
Known linux problem
