### ISSUE TITLE
CUSA00900 Memory Management Crash

### ISSUE THREAD

**Issue by corigne** [shadps4-emu/shadPS4#886]
System:
Linux 6.10.9-arch1-2
AMD Ryzen 7 3800X
NVIDIA GeForce RTX 2070 SUPER (nvidia 560.35.03)
32 GB of RAM

Commit: https://github.com/shadps4-emu/shadPS4/commit/1b12138cda65d5f080800e6ceca43e0bc2bc516f

Description: Crashes after reaching unreachable code.

Log: 
[shad_log.txt](https://github.com/user-attachments/files/16980200/shad_log.txt)

**Comment by StevenMiller123** [comment]
Your firmware libraries appear to be encrypted. Make sure you are decrypting the libraries when dumping them.
