### ISSUE TITLE
Emulator does not start

### ISSUE THREAD

**Issue by Kae1thas** [shadps4-emu/shadPS4#887]
After launching the emulator with the interface (qt), nothing else starts except the terminal.
Specs:
CPU: Ryzen 5 4600H
GPU: 1650ti(laptop)
![image](https://github.com/user-attachments/assets/f67c8148-38f9-40dd-92c4-a962171d75c0)

**Comment by StevenMiller123** [comment]
Try running shadPS4 in a different location, or running it as an administrator. Your issue might be because the emulator is trying to write in the Program Files (x86) folder, which requires administrator access on Windows.

**Comment by Kae1thas** [comment]
When starting the qt version of the emulator, nothing appears except the command line. I saw solutions to the problem by reinstalling Microsoft Visual Studio C++ Redistributable latest version, I did it and it didn't help, moving the emulator to the C system directory, but for me it is useless😔

**Comment by Kae1thas** [comment]
After updating the integrated AMD video card, the emulator started
