### ISSUE TITLE
Configuring .exe output in Visual Studio

### ISSUE THREAD

**Issue by fraxalotl** [shadps4-emu/shadPS4#889]
Hi,

I'm trying to compile `main` branch from source on Windows, in Visual Studio.

In the Documents/"Building shadPS4 for windows", step 4 of "Compiling with Visual Studio GUI" reads `Change the project to build to shadps4.exe`.

How exactly do i do that? I've googled around and not found a solution, and im not familiar with c++ or clang tbh.

Sorry for noob question, TIA!

**Comment by tGecko** [comment]
Hi,

you can change it here:

![image](https://github.com/user-attachments/assets/cbdff622-1a68-4cff-b96a-b28dfaec89af)

**Comment by fraxalotl** [comment]
@tGecko Thank you!!
