### ISSUE TITLE
Compilation Build error 'Subcommand failed'

### ISSUE THREAD

**Issue by fraxalotl** [shadps4-emu/shadPS4#890]
Building `main` from source on Windows 11,
I followed the Document "Building shadPS4 for Windows".

`Build All` fails, saying:

`[288/778] Building CXX object externals\glslang\glslang\CMakeFiles\glslang.dir\cmake_pch.cxx.obj`
`ninja: build stopped: subcommand failed.`

`Build All Failed`

Any help would be appreciated!

full output is attatched:

[Build All Log.txt](https://github.com/user-attachments/files/16984584/Build.All.Log.txt)

**Comment by fraxalotl** [comment]
`Build All` succeeds on latest commit, not sure what was preventing it before

I believe it was on [This commit's](https://github.com/shadps4-emu/shadPS4/actions/runs/10835381107) Source Code

**Comment by fraxalotl** [comment]
I believe it was on [This commit's](https://github.com/shadps4-emu/shadPS4/actions/runs/10835381107) Source Code

**Comment by StevenMiller123** [comment]
There are occasionally issues that appear for certain build methods. If this issue is resolved on current builds, then you should close this issue.

**Comment by fraxalotl** [comment]
> There are occasionally issues that appear for certain build methods. If this issue is resolved on current builds, then you should close this issue.

sure, thanks!
