### ISSUE TITLE
Emulator error: it doenst open after selecting where to install the games

### ISSUE THREAD

**Issue by loquito342** [shadps4-emu/shadPS4#891]
after selecting the folder to install, it suddenly closes and doenst open to the main menu of the emulator

**Comment by StevenMiller123** [comment]
Please provide your device's hardware specs.

**Comment by loquito342** [comment]
8gb ram
Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz
nvidia Geforce GTX 460

**Comment by StevenMiller123** [comment]
Your device falls below the currently accepted minimum requirements in almost every way, so this report is invalid. If you can replicate the issue on a newer device, please use that to report instead.

**Comment by loquito342** [comment]
Not only me had this problem, a Guy from a Youtube comment got the same
thing and his specs are way better then mine, here his comment:


He says he has an RTX 4060, 32gb ram and i5 13gen

Em sex, 13 de set de 2024 13:34, Stephen Miller ***@***.***>
escreveu:

**Comment by StevenMiller123** [comment]
@loquito342 Where is your shadPS4 game's folder located? There are several issues related to people selecting protected folders as their games folder. 

On another note, A random comment from Youtube isn't enough proof. We don't know what shadPS4 build they're using, what folder they're trying to install to, if they're being honest about device specs, etc. Too many unknowns. And even if I solve this issue, you won't be able to run a single game with those specs.

**Comment by loquito342** [comment]
the folder is in the same page of the main folder

**Comment by Hermiten** [comment]
No more information and news about this issue, I'm closing it. You can open a new one if needed with better information.
