### ISSUE TITLE
Unable to start any game via shadPS4

### ISSUE THREAD

**Issue by Retiw** [shadps4-emu/shadPS4#892]
![image](https://github.com/user-attachments/assets/8339e09e-a100-40b7-b5c5-6a286e6207c0)
No game window appears, immediately crash

**Comment by StevenMiller123** [comment]
Please provide your device's hardware information, especially the amount of RAM and the model of GPU you are using.

**Comment by Retiw** [comment]
> Please provide your device's hardware information, especially the amount of RAM and the model of GPU you are using.

GPU: Palit GeForce RTX 4060
RAM: 32GB DDR5
CPU: Intel Core I5-13400F
OS: Windows 10 x64

**Comment by Retiw** [comment]
> Please provide your device's hardware information, especially the amount of RAM and the model of GPU you are using.

Any updates?

**Comment by StevenMiller123** [comment]
I'll be honest, I don't know why this error is occuring for you. Your specs seem fine, but the error suggest the emulator is unable to reserve memory for the emulator to start. Are there any applications you are running that could interfere with other apps?

**Comment by StevenMiller123** [comment]
Either that, or maybe run a proper memory test to verify your hardware is working properly. Those are all the suggestions I have at the moment.

**Comment by Retiw** [comment]
> Either that, or maybe run a proper memory test to verify your hardware is working properly. Those are all the suggestions I have at the moment.

Could there be a problem here that I have 4 RAM modules? Like 4x 8GB ddr5?

**Comment by Retiw** [comment]
Issue closed. After reinstalling the new Windows, the error disappeared.

**Comment by Nathanielpd140** [comment]
I know this was closed but Im having the same issue. You said reinstalling windows fixed it? or was it a windows update that fixed it.

**Comment by mactonight37** [comment]
did anyone else find a solution other than reinstalling windows

**Comment by spectrex9** [comment]
The solution is to create a shortcut of the game and launch the game from the shortcut. In shadps4 you can right click the game and click on Create shortcut. It solved the issue for a lot of us!

**Comment by mactonight37** [comment]
Thanks but i cant try it now since ive reset my pc entirely and that solved
the issue.

9 Haz 2025 Pzt 13:16 tarihinde Vlad Andrei ***@***.***> şunu
yazdı:
