### ISSUE TITLE
Bloodborne [Windows] A strong glow. How to fix

### ISSUE THREAD

**Issue by TeJleny3o** [shadps4-emu/shadPS4#893]
A strong glow. How to fix
![blood](https://github.com/user-attachments/assets/550b7a19-d438-46ac-a613-f0b5c88c67c8)

**Comment by TeJleny3o** [comment]
[shad_log.txt](https://github.com/user-attachments/files/16985655/shad_log.txt)

**Comment by Purenuggetry** [comment]
Looks normal for the current WIP
