### ISSUE TITLE
mainwindow.ui should be replace with code

### ISSUE THREAD

**Issue by georgemoralis** [shadps4-emu/shadps4#9]
ui code is probably a mess , probably is better to rewrite in code

**Comment by perdo-nober-rs** [comment]
Why are 2 github repository?

**Comment by georgemoralis** [comment]
this one is a rewrite of shadps4 but not in the emu state of the other repo .  So until it is full merged we maintance both

**Comment by perdo-nober-rs** [comment]
Ok thank you

**Comment by georgemoralis** [comment]
this ticket is already fixed
