### ISSUE TITLE
Game crashes after character creation with ProcessGraphics:459 error

### ISSUE THREAD

**Issue by SaltCaramel** [shadps4-emu/shadPS4#900]
game crashes after character creation
Specs:
rtx 3070
ryzen 5 5600
ddr4 16gb 3200 ram
windows 11 pro
![ykL9TmDeJy](https://github.com/user-attachments/assets/2ef11dc5-8939-46f8-b89a-7f21d862b9d5)

**Comment by StevenMiller123** [comment]
You are running an old build of shadPS4, this issue is fixed in newer builds.

**Comment by SaltCaramel** [comment]
I downloaded it from the releases page, where can I get the latest build?

**Comment by StevenMiller123** [comment]
Download from the actions tab to get the more recent WIP builds.

**Comment by SaltCaramel** [comment]
thanks a lot! The game starts, but it seems to me that it runs worse than it should. 
is that so? (also i tried 3440x1440 resolution and it works similar to full hd)
![NVIDIA_Overlay_hiSIB1NxvV](https://github.com/user-attachments/assets/31482ce3-3cdf-4596-aa3b-eb5bb02ca636)

**Comment by StevenMiller123** [comment]
This is normal when running the current main builds. I believe some of the patches you can apply should make it run faster, but I've seen a bunch of recent posts from people having issues with the patches.

**Comment by SaltCaramel** [comment]
ok, thanks for help! i'll wait for new patch

**Comment by StevenMiller123** [comment]
This issue should probably be closed, as the reported issue is solved. If you run into any issues with user-made patches, make sure to report those on the patch repository instead of posting them here.
