### ISSUE TITLE
Cant boot bloodborne

### ISSUE THREAD

**Issue by Putic0** [shadps4-emu/shadPS4#901]
I patched my game to run better and added the sound mod, but now is stuck as a blackscreen and isnt booting 
![imagen_2024-09-13_162812417](https://github.com/user-attachments/assets/b88a818b-91dd-4367-bc09-ae78631d1ba1)
Console goes up to that point and then stops, any help?

**Comment by StevenMiller123** [comment]
If the issue came after modding your game or applying patches, then the issue isn't with shadPS4, it's with the modifications you've applied. You need to determine which of these caused the issue, then report the issue to the creators of whatever caused it.
