### ISSUE TITLE
Windows qt. Stop game and saves issue

### ISSUE THREAD

**Issue by Aionik8** [shadps4-emu/shadPS4#903]
The game stop button in the emulator does not work. To close the game, I press alt + f4. After that, the game cannot overwrite the saves.

**Comment by StevenMiller123** [comment]
This is normal behavior at the moment, the stop button hasn't been implemented yet. As for the saves issue, games should save just like they would on a PS4, so if the game you're playing isn't properly saving when it should, please provide a log.

**Comment by Aionik8** [comment]
[shad_log.txt](https://github.com/user-attachments/files/16998050/shad_log.txt)
Did you mean this log?

**Comment by Aionik8** [comment]
Just in case, I'll clarify that the problem only starts after I close the game at least once via alt+f4. Before that, the saves work as they should. Maybe there's another way to close the game so as not to break anything?

**Comment by Aionik8** [comment]
I tried with the latest version and now there is no problem
