### ISSUE TITLE
Crash without start

### ISSUE THREAD

**Issue by Mikiri7** [shadps4-emu/shadPS4#905]
When i try to play the game, emulator freezes on this and crashes ![image](https://github.com/user-attachments/assets/7b7c56a2-ac73-425e-93fc-ce42649e1efe)

**Comment by atakanbaba3161** [comment]
same happens to me with latest build

**Comment by Mikiri7** [comment]
Yes, from yesterday i can't access to game

**Comment by hollowscourge** [comment]
same bro
