### ISSUE TITLE
crashes when playing bloodborne CUSA0090 when getting attacked by the first enemy

### ISSUE THREAD

**Issue by zzzzzkk31** [shadps4-emu/shadPS4#908]
the last thing my cmd gives me before it crashes is this: [Render.Vulkan] <Warning> emit_spirv_context_get_set.cpp:Emit SetAttribute:214: Ignoring pos1 export. fix this please also my caracther emits light and the sound isnt working

**Comment by Aionik8** [comment]
Check that method:
https://github.com/shadps4-emu/shadPS4/issues/872
