### ISSUE TITLE
Game freezes after Rom fight, at cinematic that tp's you to Yahargul

### ISSUE THREAD

**Issue by LouderLimix** [shadps4-emu/shadPS4#914]
Whenever I get close to Pthumerian Queen and the cinematic is about to start, the game just stays like this forever
![aaa](https://github.com/user-attachments/assets/b1100ad8-032a-4d90-811e-70bfe38f0b5c)

I've tried everything, turning on and off some patches, restarting PC, restarting emulator, spamming X before cinematic begins, but nothing happens.

Im playing CUSA03173 version and the last thing the cmd shows when it gets frozen is this:

[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called

**Comment by StevenMiller123** [comment]
Please provide your log file. Your shadPS4 build may be out of date, as Bloodborne's teleport crashes should've been fixed by a recent update.

**Comment by IIshion** [comment]
![QQ截图20240919205046](https://github.com/user-attachments/assets/07f1b1f6-eba3-4d29-94af-7cba6e8e5200)
I met this issue too... this is the latest log when the emulator frozen. Can anyone help?

**Comment by IIshion** [comment]
> Please provide your log file. Your shadPS4 build may be out of date, as Bloodborne's teleport crashes should've been fixed by a recent update.

[shad_log.txt](https://github.com/user-attachments/files/17059476/shad_log.txt)

I met this issue too... this is the latest log when the emulator frozen. Can anyone help?

the emulator edition is v0.2.1 WIP

log file uploaded

**Comment by IIshion** [comment]
I don't know why it is fixed.... I successfully get into Yahar'gul without doing anything. 

The only thing I did was switch the log type from async to sync, don't know if it is the way to fix.

**Comment by knapman** [comment]
I just run into this crash, for me it worked after reloading, making no changes.

**Comment by IIshion** [comment]
> ###
> **[LouderLimix](/LouderLimix) ** commented [Sep 15, 2024](#issue-2526504539) •

Hey you can try turn off the FPS patch in the emulator

**Comment by BenLeonBB** [comment]
> > **[LouderLimix](/LouderLimix) ** commented [Sep 15, 2024](#issue-2526504539) •
> 
> Hey you can try turn off the FPS patch in the emulator

How do you turn off the FPS patch exactly? I've ran into the same issue as well and it only happens with Laurence's cutscene. Tried everything except what you mentioned and switching to sync.

**Comment by IIshion** [comment]
> > > **[LouderLimix](/LouderLimix) ** commented [Sep 15, 2024](#issue-2526504539) •
> > 
> > 
> > Hey you can try turn off the FPS patch in the emulator
> 
> How do you turn off the FPS patch exactly? I've ran into the same issue as well and it only happens with Laurence's cutscene. Tried everything except what you mentioned and switching to sync.

![QQ截图20240923000022](https://github.com/user-attachments/assets/8ee2f7f8-281b-4c16-9eb7-40993793d0ea)

Try cancel these two FPS options, the game will run at fast speed but for me it fixed the freeze.

**Comment by BenLeonBB** [comment]
> > > > **[LouderLimix](/LouderLimix) ** commented [Sep 15, 2024](#issue-2526504539) •
> > > 
> > > 
> > > Hey you can try turn off the FPS patch in the emulator
> > 
> > 
> > How do you turn off the FPS patch exactly? I've ran into the same issue as well and it only happens with Laurence's cutscene. Tried everything except what you mentioned and switching to sync.
> 
> ![QQ截图20240923000022](https://private-user-images.githubusercontent.com/106499038/369700817-8ee2f7f8-281b-4c16-9eb7-40993793d0ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMjE3NjEsIm5iZiI6MTcyNzAyMTQ2MSwicGF0aCI6Ii8xMDY0OTkwMzgvMzY5NzAwODE3LThlZTJmN2Y4LTI4MWItNGMxNi05ZWI3LTQwOTkzNzkzZDBlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxNjExMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjQ3ZGEwMDY3OGZmOGY3Y2ZjYmNhZmY1YmJkM2EwNDAxYjhlODAxOWE0ODQ2NTA1ZWM0YjljMzg5NTQyYWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UHtB67xBRBVYWKA_i_qu4fNrxxXrPfNtuLr42ttUqRc)
> 
> Try cancel these two FPS options, the game will run at fast speed but for me it fixed the freeze.

I tried it but it still softlocks Lawrence's cutscene for me. I did the 60 FPS patch by just copying and pasting it on the CUSA03173 folder. Is there any way to revert it or disable it so that I can remove it entirely?

**Comment by IIshion** [comment]
> > > > > **[LouderLimix](/LouderLimix) ** commented [Sep 15, 2024](#issue-2526504539) •
> > > > 
> > > > 
> > > > Hey you can try turn off the FPS patch in the emulator
> > > 
> > > 
> > > How do you turn off the FPS patch exactly? I've ran into the same issue as well and it only happens with Laurence's cutscene. Tried everything except what you mentioned and switching to sync.
> > 
> > 
> > ![QQ截图20240923000022](https://private-user-images.githubusercontent.com/106499038/369700817-8ee2f7f8-281b-4c16-9eb7-40993793d0ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMjE3NjEsIm5iZiI6MTcyNzAyMTQ2MSwicGF0aCI6Ii8xMDY0OTkwMzgvMzY5NzAwODE3LThlZTJmN2Y4LTI4MWItNGMxNi05ZWI3LTQwOTkzNzkzZDBlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxNjExMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjQ3ZGEwMDY3OGZmOGY3Y2ZjYmNhZmY1YmJkM2EwNDAxYjhlODAxOWE0ODQ2NTA1ZWM0YjljMzg5NTQyYWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UHtB67xBRBVYWKA_i_qu4fNrxxXrPfNtuLr42ttUqRc)
> > Try cancel these two FPS options, the game will run at fast speed but for me it fixed the freeze.
> 
> I tried it but it still softlocks Lawrence's cutscene for me. I did the 60 FPS patch by just copying and pasting it on the CUSA03173 folder. Is there any way to revert it or disable it so that I can remove it entirely?

You don't need to copy and past anything, simply untick the two options on the panel I  attached.

 If that doesn't work, I don't know how to fix......
