### ISSUE TITLE
CUSA00900 Error Out Of Device Memory

### ISSUE THREAD

**Issue by MajorMokoto** [shadps4-emu/shadPS4#921]
Game is crashing after about 5 min with out of device memory. I'm likely missing something I should have done to avoid this, but am stumped at this point. Unsure if this is a me problem, or a memory leak. I can watch task manager and memory usage is on a steady increase at all times once the game has loaded a map. Going to main menu does not reset memory used, just stops it from increasing. 

i7 13700k
RTX 3080 12gb
32gb ram
: Commit [9203e28](https://github.com/shadps4-emu/shadPS4/commit/9203e28b21eb82be60511436e5dbdf2e3bc6a306)
[shad_log.txt](https://github.com/user-attachments/files/17003910/shad_log.txt)

**Comment by StevenMiller123** [comment]
You should retest on the latest main builds, as the memory leaks in Bloodborne were fixed in recent builds.

**Comment by MajorMokoto** [comment]
> You should retest on the latest main builds, as the memory leaks in Bloodborne were fixed in recent builds.

Initial test appear to no longer have this leak. Thank you for the update!
