### ISSUE TITLE
Black screen of death, just hangs up on that

### ISSUE THREAD

**Issue by UsranaMotka** [shadps4-emu/shadPS4#924]
log file
 
[shad_log.txt](https://github.com/user-attachments/files/17004495/shad_log.txt)

**Comment by gandalfthewhite19890404** [comment]
Lol

**Comment by LNDF** [comment]
May be related to #860

**Comment by StevenMiller123** [comment]
@UsranaMotka The GTX 960 only has 2GB of VRAM, which is not enough to run demanding games in shadPS4.
