### ISSUE TITLE
Bloodborne with amd have slow motion with diegolix29 version

### ISSUE THREAD

**Issue by ChronoRPG** [shadps4-emu/shadPS4#925]
Greetings

I'm using the latest version of diegolix29. Here's a short video to help you understand. In certain areas, when I move the camera, the game starts to have a slow-motion effect. If you look at the game console, when I move the camera or move around, the following appears in yellow:

[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:391: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)

Video:
https://discord.com/channels/1080089157554155590/1274870927636824064/1284708295701041164

I’m attaching my log file; I hope it helps in resolving the issue

[shad_log.txt](https://github.com/user-attachments/files/17004530/shad_log.txt)

My PC specifications are: CPU AMD 5900X, GPU AMD 6700XT, and 32 GB of RAM

**Comment by 0xZ3n0x** [comment]
I also have the problem of slowing down in the game, but the error message you gave is constantly written on the screen, not only during slowdown moments. In moments of slowdown , the following error message is also printed on the screen.

[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:79: Rectangle List primitive type is only supported for embedded VS

I think this is related to the slow motion effect.

My PC specifications are: CPU AMD Ryzen 5 5600, GPU AMD RX 7600XT (24.20.11.01), and 16 GB of RAM

**Comment by polybiusproxy** [comment]
Forks are not officially supported.
