### ISSUE TITLE
always freezes after character creation! bloodborne

### ISSUE THREAD

**Issue by oldgamer2024** [shadps4-emu/shadPS4#927]
<img width="1408" alt="Снимок экрана 2024-09-15 в 5 57 33 PM" src="https://github.com/user-attachments/assets/bd642153-e0c0-492e-86ab-7c7fbe8dad59">
always freezes after character creation!
ryzen 8840u
32gb ram
onexplayer 2 pro

the same thing happens on my second console asus rog ally x!

**Comment by dbz400** [comment]
I got the same issue until I lower the GPU clock via MSI afterburner then no freeze anymore.

**Comment by oldgamer2024** [comment]
> I got the same issue until I lower the GPU clock via MSI afterburner then no freeze anymore.

write in detail - what and how did you do it?

**Comment by StevenMiller123** [comment]
@oldgamer2024 You need to provide a log file. Set the log type to sync, then run the game. Once it crashes, send the shad_log.txt from the user/logs folder.

**Comment by StevenMiller123** [comment]
@raven02 If the issue is fixed by lowering your GPU clock speed, then I suspect the issue you're running into is hardware related. Either way, please provide your hardware specs and log.

**Comment by Dhrazer** [comment]
Had the same problem, swapping in an older save where I got past character creation fixed it(the save is from an older BB hack build). There might be a problem specifically with the creation of save files or initializing a save/"character"

**Comment by polybiusproxy** [comment]
Closing, not enough information
