### ISSUE TITLE
.exe doesn't do anything

### ISSUE THREAD

**Issue by Encefaloraptor** [shadps4-emu/shadPS4#929]
After downloading the QT version I tried executing the .exe but it just starts a command prompt window and then either freezes or just crashes. Here are my specs just in case since I have seen that that can be an issue. ( It's a laptop)
GPU RTX 3050 Ti 4Gb
Processor AMD Ryzen 7 4800H 2.90 GHz
Installed RAM	16.0 GB (15.4 GB usable)

**Comment by Unikrime** [comment]
Same problem here, my config is r9 6900hx/rx6800s

**Comment by polybiusproxy** [comment]
Reinstall the VC++ redistributables: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Encefaloraptor** [comment]
> Reinstall the VC++ redistributables: https://aka.ms/vs/17/release/vc_redist.x64.exe

It still crashes

**Comment by Ruahh** [comment]
Ensure you have up to date AMD and Nvidia drivers. You may also need additional drivers provided by your laptop's OEM, but it's worth testing with just AMD Chipset drivers and Nvidia graphics drivers first.

**Comment by twoBitSoda** [comment]
Same issue here. Rig is RX 6900 XT and a Ryzen 3600. Visual Studio and VC++ redist reinstalled and up to date, same with driver software. Using Windows 11 with the shadps4-win64-qt version. Deleting user folder didn't work.

**Comment by redspirit** [comment]
Same issue 😢

**Comment by rawwager** [comment]
same stuff.

**Comment by rawwager** [comment]
but before everything was awesome.

**Comment by rarakrura** [comment]
Same, tried a week ago and today with newer builds. Updating drivers and vc++ doesn't help :(

**Comment by rawwager** [comment]
0.2.0 starts okay.

**Comment by rawwager** [comment]
i have fixed this issue.
Bios default settings works for me.

**Comment by redspirit** [comment]
It helped me: updating VC++ and updating the video driver to the latest version, and then REBOOTING
