### ISSUE TITLE
Bloodborne - Light Overexposure is Alleviated with Lowered Resolution 

### ISSUE THREAD

**Issue by anasteraceae** [shadps4-emu/shadPS4#938]
While taking screenshots for my lighting mod, I made the discovery that _reducing_ the resolution of Bloodborne using a patch fixes the issue with overexposed lights from sfx and world lighting. Unsure if this is helpful, but thought I'd note it in case it helps in any way with the emulator.

For reference, some screenshots:

Base PS4:
![HD_Base](https://github.com/user-attachments/assets/4d640aa2-403c-4163-af04-a6a5c275894e)

Emulated:
![Comp](https://github.com/user-attachments/assets/15baff38-08ae-45b3-a6cb-d036b7df44ff)

Also, as an addendum, when trying to fix this issue by reducing light intensity, a general modifier of 25-30x less bright at 720p was the closest I could get to retail Bloodborne.

**Comment by Foul-Tarnished** [comment]
This may interest @raphaelthegreat

**Comment by fl4kez** [comment]
actually where do you get the lower res patches from?

**Comment by Foul-Tarnished** [comment]
You can just edit the xml file whrre the patches are, there's an
hexadecimal value for the width and another for the height.

Le mer. 18 sept. 2024 à 13:41, hamsgbschbep ***@***.***> a
écrit :

**Comment by anasteraceae** [comment]
> actually where do you get the lower res patches from?

Here is the file for testing purposes (rename to .xml)
[Bloodborne.txt](https://github.com/user-attachments/files/17047120/Bloodborne.txt)

But to say I authored them is a stretch, you can just take one of the existing patches:

```
    <Metadata Title="Bloodborne" Name="Resolution Patch (144p)" Author="Aster" PatchVer="1.0" AppVer="01.09" AppElf="eboot.bin" isEnabled="true">
        <PatchList>
            <Line Type="bytes32" Address="0x055289f8" Value="0x00000100"/>
            <Line Type="bytes32" Address="0x055289fc" Value="0x00000090"/>
            <Line Type="bytes" Address="0x01a44c55" Value="b880070000"/>
            <Line Type="bytes" Address="0x01a44c5a" Value="90"/>
            <Line Type="bytes" Address="0x01a44c5b" Value="90"/>
            <Line Type="bytes" Address="0x01a44c5c" Value="90"/>
            <Line Type="bytes" Address="0x01a44c5d" Value="90"/>
            <Line Type="bytes" Address="0x01a44c5e" Value="c4e1fa2ac8"/>
            <Line Type="bytes" Address="0x01a44c63" Value="b838040000"/>
            <Line Type="bytes" Address="0x01a44c68" Value="90"/>
            <Line Type="bytes" Address="0x01a44c69" Value="90"/>
            <Line Type="bytes" Address="0x01a44c6a" Value="90"/>
            <Line Type="bytes" Address="0x01a44c6b" Value="90"/>
            <Line Type="bytes" Address="0x01a452c7" Value="b880070000"/>
            <Line Type="bytes" Address="0x01a452cc" Value="90"/>
            <Line Type="bytes" Address="0x01a452cd" Value="90"/>
            <Line Type="bytes" Address="0x01a452ce" Value="90"/>
            <Line Type="bytes" Address="0x01a452cf" Value="90"/>
            <Line Type="bytes" Address="0x01a452d0" Value="c4e1fa2ac8"/>
            <Line Type="bytes" Address="0x01a452d5" Value="b838040000"/>
            <Line Type="bytes" Address="0x01a452da" Value="90"/>
            <Line Type="bytes" Address="0x01a452db" Value="90"/>
            <Line Type="bytes" Address="0x01a452dc" Value="90"/>
            <Line Type="bytes" Address="0x01a452dd" Value="90"/>
        </PatchList>
    </Metadata>
```
And edit the first two bytes32's, the first being horizontal resolution, the second being vertical.
You will need to convert an int to byte32 to get the value you want.

**Comment by Hermiten** [comment]
Thanks about this, with this commit: https://github.com/shadps4-emu/shadPS4/pull/1146 the light is fixed :)
