### ISSUE TITLE
Out of device memory

### ISSUE THREAD

**Issue by Mikiri7** [shadps4-emu/shadPS4#946]
![image](https://github.com/user-attachments/assets/d8aa0f6e-a961-4d3d-9362-4b69b8b25da8)
Thank you for all the work, everything going fine, but from yesterday i got again this bug, i got 16GB RAM DDR4 3200MT/s, RX6600 and i512400f

**Comment by StevenMiller123** [comment]
This error indicates a lack of VRAM. I would suggest updating your graphics drivers, and making sure to disable any cheats or game patches. Duplicate of #921, #734, #721, #706, and #498. (Someone really needs to sort through the BB issue spam)

**Comment by Mikiri7** [comment]
> This error indicates a lack of VRAM. I would suggest updating your graphics drivers, and making sure to disable any cheats or game patches. Duplicate of #921, #734, #721, #706, and #498. (Someone really needs to sort through the BB issue spam)

Thank you! i'll close this issue
