### ISSUE TITLE
Is this graphical glitch normal at the current state of the emulator?

### ISSUE THREAD

**Issue by javsp** [shadps4-emu/shadPS4#950]
Bloodborne:
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/e65aa5db-df29-4872-9460-974cf284c182">

It happens randomly each X minutes (in both, modded and vanilla game) with native resolution and framerate. Only restarting the game/emulator fixes the glitch until the next time it appears.

I have a 7800X3D and a RTX 4090.

**Comment by Mikiri7** [comment]
Yes, it is, when this happen just go to main menu and back to play the game, this bug must go away

**Comment by raphaelthegreat** [comment]
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/968
