### ISSUE TITLE
Crash on character creation

### ISSUE THREAD

**Issue by Shamamo** [shadps4-emu/shadPS4#951]
Using shadps4-win64-qt-2024-09-16-9d7745c, the game crashes on character creation, with the following log 
[shad_log.txt](https://github.com/user-attachments/files/17020048/shad_log.txt)

CPU: Ryzen 5 3600
GPU: GTX 1070
Latest driver as of 16/09/2024 (561.09)

**Comment by StevenMiller123** [comment]
We don't provide support for forks. You need to create an issue report on the fork you downloaded from, or contact the maker of that build.

**Comment by Shamamo** [comment]
That is not a fork, it was the latest WIP build at the date of the post. Also I forgot to mention that I'm trying to boot Bloodborne

**Comment by igornakonechnyi** [comment]
same thing for me v0.2.1 WIP
AMD Ryzen 5 3600X
AMD Radeon RX 7800 XT
[shad_log.txt](https://github.com/user-attachments/files/17024899/shad_log.txt)

**Comment by Dhrazer** [comment]
Do you have an older save file where you got past character creation? Mine crashed with character creation too but ran fine after I swapped in an older save where I got to the hunter's dream already...

**Comment by Dhrazer** [comment]
Do you have an older save file where you got past character creation? Mine locked up with character creation too but ran fine after I swapped in an older save where I got to the hunter's dream already(from an older BB hack build)...

**Comment by igornakonechnyi** [comment]
Unfortunately, I have no saves. I just downloaded the emulator yesterday, created a character and got this trouble

**Comment by StevenMiller123** [comment]
> That is not a fork, it was the latest WIP build at the date of the post. Also I forgot to mention that I'm trying to boot Bloodborne

The log suggests otherwise. You probably accidentally downloaded someone else's main build, as those can show up when filtering for main, because some people like to make PR's based off their main builds.

**Comment by Hermiten** [comment]
Not the good branch, I'm closing it
And it seem's to be a memory problem at the end, I'm not a dev, but try the last version, there a is memory leak fix
