### ISSUE TITLE
Stuck in bloodborne main menu

### ISSUE THREAD

**Issue by vasyok991** [shadps4-emu/shadPS4#958]
after starting the game everything goes fine, but errors start to appear in the console, in the main menu you can switch between online/offline mode, but it won’t start
![изображение_2024-09-17_161336612](https://github.com/user-attachments/assets/18127243-53cd-4f2a-af27-e8d7c4af7aab)
![изображение_2024-09-17_161404080](https://github.com/user-attachments/assets/b354b35d-8ce3-4048-826d-2bf27f9a24b9)
no mods are installed, bloodborne version 1.09
![изображение_2024-09-17_161454636](https://github.com/user-attachments/assets/2edf69ab-e7af-4f42-abdb-68715f92b5a3)

**Comment by utkuoksuz** [comment]
Piracy is not allowed
