### ISSUE TITLE
Stuck in bloodborne main menu

### ISSUE THREAD

**Issue by vasyok991** [shadps4-emu/shadPS4#966]
after starting the game everything goes fine, but errors start to appear in the console, in the main menu you can switch between online/offline mode, but it won’t start
![image](https://github.com/user-attachments/assets/03b466f6-fc75-4c41-9fe0-13c17002b078)
![image](https://github.com/user-attachments/assets/7b7500ca-5a18-4286-98f0-50f5bfde42ea)
no mods are installed, bloodborne version 1.09

**Comment by raphaelthegreat** [comment]
Github is not meant for support questions, discord server might be able to help you

**Comment by lostessoxan** [comment]
бро, ты решил проблему?
