### ISSUE TITLE
Blank screen on startup

### ISSUE THREAD

**Issue by kaposztasajt** [shadps4-emu/shadPS4#972]
I tried Bloodborne and Rayman legends. Rayman has sound but screen is blank then crashes. Bloodborne doesnt do anything just blank screen unril i stop it. Logs attached
AMD 5600x
AMD 6700xt
32gb
Win11 pro

BB:
[shad_log.txt](https://github.com/user-attachments/files/17047133/shad_log.txt)

Rayman Legends:
[shad_log.txt](https://github.com/user-attachments/files/17047152/shad_log.txt)

**Comment by Hermiten** [comment]
Better to put this here or check if it exist: https://github.com/shadps4-emu/shadps4-game-compatibility/issues
