### ISSUE TITLE
WEIRD COLOR RIGHTS RX 5908GBVRAM

### ISSUE THREAD

**Issue by maturinno** [shadps4-emu/shadPS4#975]
![shadPS4 v0 2 1 WIP 92a44f4 _ CUSA00900 - Bloodborne _01 09_ 18_09_2024 0_08_20](https://github.com/user-attachments/assets/a1951b8d-519c-4a7a-bb59-2187c0c2db17)
![shadPS4 v0 2 1 WIP 2aab7e0 _ CUSA00900 - Bloodborne _01 09_ 18_09_2024 15_11_22](https://github.com/user-attachments/assets/a9470bfb-ac45-42b4-83ce-c3b30b8281b1)

Okay, so I'm running this on an RX590 8gbvram 16GBRAM Ryzen 7 2700.

Sometimes this happens sometimes it doesn't, I need some help. This looks quite specific. SFX FOLDER IS DISABLED. 

Any thoughts?

**Comment by raphaelthegreat** [comment]
You have not provided any log or details about your issue, seek support on the discord instead or provide additional information
