### ISSUE TITLE
Linux Bloodbourne Missing Geometery

### ISSUE THREAD

**Issue by mxli2025** [shadps4-emu/shadPS4#978]
![Screenshot from 2024-09-18 21-42-38](https://github.com/user-attachments/assets/2e78514d-99aa-4eb9-bbb3-07701d268248)

above is what it looks like on first load

below is after running around abit quitting to mainmenu and reloading

![Screenshot from 2024-09-18 21-58-54](https://github.com/user-attachments/assets/e5bb7711-024f-4172-ae74-259a7ae4d122)

Loading bug maybe ? as it can display it

LCD Deck
Mint 22
no mods

**Comment by gurrgur** [comment]
I have the same issue on Arch Linux / RX6700XT / RADV. I can also confirm that on second load most of the time, the geometry data loads properly.

I did two traces in Renderdoc (first with missing meshes and second with no missing meshes) and noticed that some vs input vertex buffers and index buffers are filled with zeros only on the trace with missing meshes.

My (uneducated) theory on this is that when the game loads in new assets from disk, due to some unknown reason (perhaps sync issue like missing fence / barrier?) the meshes are only partly loaded into GPU memory. On the second load, the data is already cashed in system memory so that the upload to GPU is quick enough to complete in time. Rdoc also shows, that a compute shader acesses these buffer objects before they are passed to the VS stage (which is part of a depth pass IIRC).

Also, I'd like to add that when moving from one area to another, the geometry disappears again. For example, load into central yarnham and climb the ladder. After some steps on the ladder, the screen will turn grey for a short amount of time and after that the meshes will be gone.

**Comment by gurrgur** [comment]
Oh and this is a RADV only issue. amdvlk has no missing meshes (though it has waaaaaaay worse perf).

And finally, sometimes it looks like some of the zero filled vertex buffers are instead filled with garbage data leading to flicker. Seems kind of random and apparently depends on timing.

**Comment by LNDF** [comment]
Same issue. Fedora 40 using RADV.

It might be nice to see what the validation layers print out.

**Comment by mxli2025** [comment]
issue #976 , seems to be similar. Windows on a nVidia card.

**Comment by grassponderer** [comment]
Same here. Arch, 6900XT using vulkan-radeon, tested on linux, linux-zen, and linux-cachyos, no difference.

When I tried amdvlk, got to the first loading screen before the area loads in, then shadps4 crashes. I don't know if it's helpful, but I noticed that I get the following error spammed repeatedly:
`[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:391: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)`
Don't have enough background as to whether or not this might point to the cause of the issue though.

**Comment by Hermiten** [comment]
Can you test with the last update ?
This commit https://github.com/shadps4-emu/shadPS4/pull/1146 can maybe fix somethings

**Comment by R1chterScale** [comment]
> Can you test with the last update ? This commit #1146 can maybe fix somethings

No dice

**Comment by HermitsA** [comment]
As a compromise, using the amdgpu-pro drivers fix this. You can have both the mesa and proprietary drivers on the same machine, defaulting to mesa normally, and enabled by using "progl [command]". You can also try the amdvlk drivers, altough performance was horrible last time i tested.

Tested on the 3 different vulkan implementations (RADV, AMDVLK, VULKAN-AMDGPU-PRO) on a 6700xt with archlinux

**Comment by Mast3rwaf1z** [comment]
I have the same issues, amdgpu-pro works, but the game stutters, i just tried running through nightmare of mensis with radv, no textures but the game is much more smooth with RADV.

**Comment by grassponderer** [comment]
Just a quick update, now it seems to work for me using this
[https://github.com/ngoquang2708/shadPS4/actions/runs/11869943285](url)
and AMDVLK. Seems to be related to #1193 since when using amdvlk these error don't get spammed.

**Comment by Malumen** [comment]
> Just a quick update, now it seems to work for me using this [https://github.com/ngoquang2708/shadPS4/actions/runs/11869943285](url) and AMDVLK. Seems to be related to #1193 since when using ***amdvlk*** these error don't get spammed.

how do we enable AMDvlk?

**Comment by grassponderer** [comment]
> how do we enable AMDvlk?

Assuming you use arch, the safest way without messing up everything else that uses vulkan-radeon is probably https://github.com/Frogging-Family/amdvlk-opt

**Comment by Channeira** [comment]
Did someone report the RADV specific issues to mesa already?

**Comment by dunestorm333** [comment]
![image](https://github.com/user-attachments/assets/2a07ef31-8272-417c-bb58-cc78011ef222)
Can confirm, this is still a problem on the latest shadPS4 build :(

Running Fedora 41 (Linux 6.11.10-300.fc41.x86_64)
Mesa 24.2.7

AMD 6800XT

**Comment by Mershl** [comment]
RADV users please give this build a test run https://github.com/diegolix29/shadPS4/actions/runs/12286290681
played through the intro + half of yharnam on an 7900XTX using RADV without seeing the issue, this is the first build I've tested that does not show the issue.

**Comment by dunestorm333** [comment]
You are my hero!
This build appears to have solved this issue for me:
![image](https://github.com/user-attachments/assets/221108bf-5351-47c4-8454-8c6db0adfa06)

**Comment by raphaelthegreat** [comment]
Issues on the main repo should be about main branch only, please test that

**Comment by Mast3rwaf1z** [comment]
> RADV users please give this build a test run https://github.com/diegolix29/shadPS4/actions/runs/12286290681 played through the intro + half of yharnam on an 7900XTX using RADV without seeing the issue, this is the first build I've tested that does not show the issue.

I've just done 2 layers of chalice dungeons on my main and most of old yharnam on my new character. no missing geometry using RADV on this build.
I'm running ryzen 5 3600x with a 6950XT. so it seems to work with rdna2 as well

**Comment by Missake212** [comment]
Does this still happen on latest main ?

**Comment by R1chterScale** [comment]
> Does this still happen on latest main ?

No, seems good now, might be interesting to bisect the change to report to the Mesa devs

**Comment by rharish101** [comment]
Can confirm that it's fixed for me on RADV (on a 7900 XTX), although I only tested this in Iosefka's clinic.
