### ISSUE TITLE
ARC770 graphics card Bloodborne crash

### ISSUE THREAD

**Issue by okaku123** [shadps4-emu/shadPS4#980]
ARC770 graphics card Bloodborne crashes when entering the 3D screen of the game, but works normally when creating a 2D character
[shad_log.txt](https://github.com/user-attachments/files/17053399/shad_log.txt)

**Comment by ouco1986** [comment]
Encountered the same problem

**Comment by hgh32** [comment]
https://github.com/shadps4-emu/shadPS4/issues/765
Basically can be determined to be a specific problem with intel gpu
https://github.com/shadps4-emu/shadPS4/blob/171e475f80158e4e539a5ba173db5761a3baf196/src/video_core/renderer_vulkan/vk_compute_pipeline.cpp#L190
Commenting out this line of code will allow it to continue running, but may cause some graphics issues

**Comment by ouco1986** [comment]
> #765 Basically can be determined to be a specific problem with intel gpu
> 
> https://github.com/shadps4-emu/shadPS4/blob/171e475f80158e4e539a5ba173db5761a3baf196/src/video_core/renderer_vulkan/vk_compute_pipeline.cpp#L190
> 
> Commenting out this line of code will allow it to continue running, but may cause some graphics issues

Thank you for your attempt. Can you release a program that allows us Intel graphics card users to test it

**Comment by Hermiten** [comment]
Cleaning bloodborne issue, please try again on lastest version, check if it's fixed for you and if not, please check if issue already exist on github before doing a new one.
