### ISSUE TITLE
CUSA00005 Resogun AMD GPU Black Screen And Full App Crash

### ISSUE THREAD

**Issue by DenizSAHIN570** [shadps4-emu/shadPS4#982]
RX6700XT
WIN 11

Black screen followed by full app crash.
[shad_log.txt](https://github.com/user-attachments/files/17053893/shad_log.txt)

**Comment by jrmedany** [comment]
real me too

**Comment by kaposztasajt** [comment]
Also 6700xt, also crashing. But in different games (havent tested this one yet)

**Comment by DenizSAHIN570** [comment]
I wonder if this is a game related or gpu related crash.

**Comment by Hermiten** [comment]
Thanks for the report
A more recent test has been done here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/73
If you have the same result, no need to open a new issue
