### ISSUE TITLE
Crashing on entering the character creation menu

### ISSUE THREAD

**Issue by Drag365** [shadps4-emu/shadPS4#988]
The game crashes when entering the character creation menu with the error: [Debug] <Critical> buffer.cpp:operator():90: Assertion Failed!
Failed allocating buffer with error ErrorOutOfDeviceMemory. This instantly fills up all video memory and RAM. The computer freezes for a couple of minutes. Ryzen 5 3500u, Vega 8, 12 gb RAM(10 Gb RAM, 2 Gb VRAM)

**Comment by leandropgg** [comment]
i have the same error, i have gtx 1050 2gb i7 7700 16gb ram

**Comment by cxrnersha** [comment]
u can try increasing the swap file size to 16GB and change the build of shadps4

i encountered this problem on newer builds, so I had to roll back to the old ones

**Comment by Drag365** [comment]
> u can try increasing the swap file size to 16GB and change the build of shadps4
> 
> i encountered this problem on newer builds, so I had to roll back to the old ones

I increased the swap file to 40 GB, but even this did not help, as soon as the video memory and RAM are full, an error is displayed and the computer freezes. Swap is not fully used. I will try to install earlier versions, but I tried versions within a week.

**Comment by LGDMF** [comment]
I'm using 0.3.0 version and it crashes as soon as i enter the character creation screen.

My PC:
RTX 3060 12GB 
16GB RAM DDR4
Ryzen 5 5600g
Windows 11
Installed on HDD

**Comment by alikh1342** [comment]
I have same problems
[shad_log.txt](https://github.com/user-attachments/files/17168507/shad_log.txt)

**Comment by C1rn0qwq** [comment]
same problem 
my laptop 3060 6gb i5 16gb
