### ISSUE TITLE
MACOS Sequoia game crash

### ISSUE THREAD

**Issue by lemkyahamed** [shadps4-emu/shadPS4#993]
I have installed Sleeping Dogs, game menu is usually but shadps4 crashes when I start the new game
<img width="993" alt="Screenshot 2024-09-20 at 9 39 25 AM" src="https://github.com/user-attachments/assets/a3495d35-e732-4048-ba6d-0655ca9c6a29">

**Comment by raphaelthegreat** [comment]
Not adequate information about the problem, feel free to reopen if you get a log and additional debug info
