### ISSUE TITLE
Crash on startup bloodborne 

### ISSUE THREAD

**Issue by Skateboardlegend** [shadps4-emu/shadPS4#997]
Hey I'm trying to start bloodborne it kinda works on 1.0.0 but when going in game crashes, when I update it to 1.0.9 it crashes on startup 

I get this error in the console
[Kernel.Vmm] <Warning> memory_management.cpp:sceKernelGetDirectMemorySize:17: called
[Kernel.Vmm] <Info> memory_management.cpp:sceKernelAllocateDirectMemory:48: searchStart = 0x0, searchEnd = 0x180000000, len = 0x7400000, alignment = 0x200000, memoryType = 0x0, physAddrOut = 0x0
[Kernel.Vmm] <Info> memory_management.cpp:sceKernelMapDirectMemory:165: called, redirected to sceKernelMapNamedDirectMemory
[Kernel.Vmm] <Info> memory_management.cpp:sceKernelMapNamedDirectMemory:138: addr = 0x0, len = 0x7400000, prot = 0x3, flags = 0x0, directMemoryStart = 0x0, alignment = 0x200000

And I attached the log file.

I have an AMD Ryzen 5 7600
and an AMD Radeon RX 7600XT
with 32 GB of ram
and I'm on Windows 11

[shad_log.txt](https://github.com/user-attachments/files/17073818/shad_log.txt)

**Comment by Toaster167** [comment]
me too but it just won't work on both versions

**Comment by Skateboardlegend** [comment]
i got a diffrent patch for 1.09 and now i can launch and play the game for some reason
